### ISSUE TITLE
Overlay hides line numbers

### ISSUE THREAD

**Issue by angrybacon** [minad/corfu#10]
I see you've mentioned the possibility of preferring another method than overlays in the README. This is just to give it another reason/motivation. I also realize that there are (too) many line-number solutions that exist and their internals might be different from one another, let me know if I can help testing out other alternatives to `display-line-numbers-mode`.

You can reproduce the issue with the following configuration, place point after `def` and call `completion-at-point`. 

```elisp
(progn
  (add-to-list 'load-path "~/.config/emacs/elpa/corfu-0.2")
  (require 'corfu)
  (corfu-mode)
  (setq tab-always-indent 'complete)
  (display-line-numbers-mode))

(def








 



;; End
```

![image](https://user-images.githubusercontent.com/5608624/115235025-fd3fc000-a119-11eb-870e-d1c79a1d6ab7.png)

**Comment by minad** [comment]
This sounds like an Emacs bug to me. But maybe multiline overlays are not supposed to work at all?

~~~ elisp
(defun bug ()
  (display-line-numbers-mode)
  (goto-char (point-min))
  (let ((ov (make-overlay (line-beginning-position)
                          (save-excursion (forward-line 4)
                                          (line-beginning-position)))))
    (overlay-put ov 'invisible t)
    (overlay-put ov 'before-string "line1\nline2\nline3\line3\nline4\n")))
~~~

**Comment by minad** [comment]
Okay, so it seems I misunderstood how display-line-numbers interact with the overlays. So it should indeed be fixed by putting overlays on each line separately.

**Comment by angrybacon** [comment]
> by putting overlays on each line separately

Do you mean one new overlay per line (and maintain a list of overlays as a result)? Could this have a significant impact on performance then?

**Comment by minad** [comment]
> Do you mean one new overlay per line (and maintain a list of overlays as a result)? Could this have a significant impact on performance then?

Yes, one overlay. No this will not have an impact for performance. But it seems a bit difficult to write this robustly. Overlays are really not good for popups.

**Comment by minad** [comment]
I decided to not spend more time on improving the overlay code. For me it works reasonably well except for some of the  scenarios mentioned here (https://github.com/minad/corfu/commit/fef837718bc138b2ad6844f588a6e51eefae5726).
