### ISSUE TITLE
Corfu-auto no longer appears when using multiple-cursors

### ISSUE THREAD

**Issue by daanturo** [minad/corfu#107]
When `multiple-cursors` is active, `corfu-auto` hasn't automatically appeared anymore since commit fef546f.

Since then, `corfu--auto-complete` also checks if `(point)` has changed, at the same time, MC works the fake cursors by moving the real cursor to those positions, therefore changing `point` after each `corfu--auto-post-command` triggered by MC, not to mention `tick`.

About the check that `corfu--auto-complete` uses:
```lisp
when (and (not completion-in-region-mode) (eq buf (current-buffer))
             (eq tick (buffer-chars-modified-tick)) (eq pt (point)))
```
Can you make it customizable, or split into a smaller function so that advising it to be more lenient is easier?

**Comment by minad** [comment]
@daanturo Good idea, please give it a try. You can advise the tick function.

**Comment by grolongo** [comment]
Sorry for bumping this issue, but I actually want to do the opposite, aka disable `corfu` when I'm using multiple cursors and typing. Is it possible to do that or do I need to manually disable `corfu-mode` for the time when I'm multiple cursors?

**Comment by minad** [comment]
@grolongo Yes, it is probably easiest to disable corfu temporarily while mc is active.

**Comment by grolongo** [comment]
just adding this for reference in case someone wants to disable corfu while using multiple-cursors too:

```elisp
(add-hook 'multiple-cursors-mode-enabled-hook (lambda () (corfu-mode -1)))
(add-hook 'multiple-cursors-mode-disabled-hook (lambda () (corfu-mode 1)))
```
