### ISSUE TITLE
corfu auto inserts on exact match

### ISSUE THREAD

**Issue by billop** [minad/corfu#108]
Version:
```
GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-01-02
```

The config used for testing corfu + lsp-mode.
```elisp
;;
;; Bootstrap straight.el
;;
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; alias straight-use-package to use-package
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
;; Enable auto-installing of packages declared by use-package
(setq use-package-always-ensure t)


(use-package flycheck)
(use-package yasnippet
  :init
  (yas-global-mode 1)
  )

(use-package corfu
  ;; tng config
  :custom
  (corfu-auto t)
  (corfu-cycle t)
  (corfu-preselect-first nil)
  (corfu-commit-predicate nil)
  :bind
  (:map corfu-map
        ("TAB" . corfu-next)
        ([tab] . corfu-next)
        ("S-TAB" . corfu-previous)
        ([backtab] . corfu-previous))
  :init
  (corfu-global-mode)
  )

(use-package orderless
  :custom
  (completion-styles '(orderless))
  )

(use-package cape)


(use-package lsp-mode
  :init
  (defun my/lsp-mode-setup-completion ()
    (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
          '(flex)))
  (setq-local completion-at-point-functions (list (cape-capf-buster #'lsp-completion-at-point)))
  :hook
  (
   ((mhtml-mode js-mode) . lsp)
   (lsp-completion-mode . my/lsp-mode-setup-completion)
   )
  :commands
  lsp
  :custom
  ;; use corfu
  (lsp-completion-provider :none)
  :config
  (setq lsp-enable-file-watchers nil)
  (setq lsp-log-io t)
  )
```

The config used for testing company + lsp-mode.
```elisp
;;
;; Bootstrap straight.el
;;
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; alias straight-use-package to use-package
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
;; Enable auto-installing of packages declared by use-package
(setq use-package-always-ensure t)


(use-package flycheck)
(use-package yasnippet
  :init
  (yas-global-mode 1)
  )

(use-package company
  :init
  (global-company-mode)
  )

(use-package lsp-mode
  :hook
  (
   ((mhtml-mode js-mode) . lsp)
   )
  :commands
  lsp
  :config
  (setq lsp-enable-file-watchers nil)
  (setq lsp-log-io t)
  )
```

To replicate:
```
mkdir whatever
touch whatever/index.html
emacs -q --load path_to_test_init.el whatever/index.html
```

Type:
```html
<body class
```

With corfu, this is automatically completed and turns into:
```html
<body class=""
```
https://gfycat.com/allperiodicbighorn

With company, no text is inserted, it simply shows the list of candidates with the sole candidate of `class`.
https://gfycat.com/medicalactualjaeger

This does not happen in corfu when there are multiple candidates available.

This does not happen in corfu with other language servers that I've tried when there is only one candidate available.
I've tried pyright, rust-analyzer, html-ls, css-ls, clangd, ts-ls, eslint, texlab, lua-language-server, json-ls.

With the help of @yyoncho it looks like deleting the following from corfu--update fixes this issue:
```elisp
     ;; 2) Single matching candidate and no further completion is possible
     ((and (not (equal str ""))
           (equal corfu--candidates (list str))
           (not (consp (completion-try-completion str table pred pt corfu--metadata))))
      (corfu--done str (if initializing 'exact 'finished)))
```

https://github.com/minad/corfu/blob/0b17ff6cfd526d1ec48ede9bf448f97910ecbc6e/corfu.el#L802

Callstack using corfu when lsp--expand-snippet is called:
```
Debugger entered--entering a function:
* lsp--expand-snippet(#("class=\"$1\"" 0 10 (fontified nil)) 7 17)
  lsp-completion--exit-fn("class" exact #f(compiled-function () #<bytecode 0x8d2e6c93c15911a>))
  apply(lsp-completion--exit-fn ("class" exact #f(compiled-function () #<bytecode 0x8d2e6c93c15911a>)))
  #f(compiled-function (&rest args-before) #<bytecode -0x1f9c767dddfd9a61>)("class" exact)
  corfu--done("class" exact)
  corfu--update()
  corfu--auto-complete((#<buffer index.html> 81 12))
  apply(corfu--auto-complete (#<buffer index.html> 81 12))
  timer-event-handler([t 25070 24381 213469 nil corfu--auto-complete ((#<buffer index.html> 81 12)) nil 476000 nil])
```

**Comment by billop** [comment]
@yyoncho suggests adding a flag to the `and` condition to control this behavior.

I personally think current behavior should not be default.

**Comment by minad** [comment]
Thanks for the report! Please give it a try.

**Comment by billop** [comment]
It seems like the issue remains.

**Comment by minad** [comment]
Okay, I see. You want to disable this auto insert feature on exact match completely, even if the popup is visible? This is not an bug, it is a feature.

**Comment by billop** [comment]
Yes I was hoping for a configuration option.

**Comment by minad** [comment]
So has the original bug been fixed for you?

**Comment by billop** [comment]
Autocompletion without popup is indeed fixed.

But I want to note that that was not my issue.

The auto insert feature on exact match has been very disruptive for me as it interrupts my typing.

Typing `<div class="` would result in `<div class="=""` for example.

**Comment by minad** [comment]
Yes, it may be disruptive, but you can also set `corfu-auto-delay` to a higher value? I am not against adding a configuration variable per se but I usually try to avoid to make everything configurable prematurely. I am rather looking for sane defaults and so far nobody complained about the auto insertion feature.

**Comment by billop** [comment]
But increasing `corfu-auto-delay` would make autocompletion slower in all contexts. That is not a reasonable solution for this issue.

What exactly is the benefit of current behavior? Because if it's not a snippet completion, an exact match would result in nothing happening anyways? I must be misunderstanding something.

**Comment by minad** [comment]
> But increasing corfu-auto-delay would make autocompletion slower in all contexts. That is not a reasonable solution for this issue.

It is reasonable since you have an issue where auto completion interferes with your typing, so it sets in too early. Note that the auto completion popup also interferes in other ways with its keybindings. Many people seem to try very aggressive auto completion settings (like delay=0), which can lead to slowdown, excessive gc runs and then wonder why auto completion creates issues.

> What exactly is the benefit of current behavior? Because if it's not a snippet completion, an exact match would result in nothing happening anyways? I must be misunderstanding something.

The exit-function is not only used by snippet expansion. For example pcomplete/eshell inserts a space, css-mode inserts `: |;` after entering an attribute. Corfu is acting semantically correct here. As soon as a completion session has started (popup is visible), the completion is supposed to be terminated with a call to the exit-function. Now Corfu interprets exactly matching candidates as selection, and this is a questionable default, therefore I opened #109.
