### ISSUE TITLE
Will corfu implement post completion actions?

### ISSUE THREAD

**Issue by s-kostyaev** [minad/corfu#11]
For example, lsp-mode + company-capf can fill snippets after completion by yasnippet. It's very useful feature.

**Comment by minad** [comment]
Yes, this feature should work. However it could be that Corfu does not invoke the `:exit-function` correctly. When I enter a prefix, press TAB, then select a candidate with RET, the `:exit-function` is called. This is where post command actions can happen. This works for example in eshell or css mode, as simple examples. But I have yet to try how lsp, maybe it handles some things differently?

**Comment by s-kostyaev** [comment]
I think @yyoncho can explain.

**Comment by yyoncho** [comment]
My wild guess is that text properties are stripped from the candidate? Other than that I need more info what is the actual behaviour and eventually a config+steps to reproduce the issue with

**Comment by minad** [comment]
@yyoncho Yes, that's a good guess. They are stripped. Is it according to the specification of `:exit-function` to retain the properties for the exit function call? I also strip the properties from the inserted string. Is this okay?

The relevant code is this:

~~~ elisp
(defun corfu--insert (status)
  "Insert current candidate, exit with STATUS if non-nil."
  (pcase-let* ((`(,beg ,end ,table ,pred) completion-in-region--data)
               (str (buffer-substring-no-properties beg end)))
    ;; Replace if candidate is selected or if current input is not valid completion.
    ;; For example str can be a valid path, e.g., ~/dir/.
    (when (or (>= corfu--index 0) (equal str "")
              (not (test-completion str table pred)))
      (setq str (concat (substring str 0 corfu--base)
                        (substring-no-properties
                         (nth (max 0 corfu--index) corfu--candidates))))
      (completion--replace beg end str))
    (if (not status)
        (setq corfu--index -1) ;; Reset selection, but continue completion.
      ;; XXX Is the :exit-function handling sufficient?
      (when-let (exit (plist-get corfu--extra-properties :exit-function))
        (funcall exit str status))
      (completion-in-region-mode -1))))
~~~

**Comment by yyoncho** [comment]
company-mode does not strip the text properties - without them, we cannot get the information about the item back.

**Comment by minad** [comment]
> without them, we cannot get the information about the item back.

You can keep the candidates around and look them up again via `member` or `assoc`. But if it is a common thing to retain the properties, then Corfu should do that too. Does default completion retain the properties when inserting?

**Comment by minad** [comment]
@yyoncho In Eglot the properties are restored by looking up the candidate in the `:exit-function`, since default completion does not provide the properties. See https://github.com/joaotavora/eglot/issues/148 and the following eglot code:

~~~ elisp
                  (or (get-text-property 0 'eglot--lsp-item proxy)
                      ;; When selecting from the *Completions*
                      ;; buffer, `proxy' won't have any properties.
                      ;; A lookup should fix that (github#148)
                      (get-text-property
                       0 'eglot--lsp-item
                       (cl-find proxy (funcall proxies) :test #'string=))))
~~~

This means the reliance on text properties is a bug in lsp-mode.

**Comment by yyoncho** [comment]
The labels are not unique so this is pretty much a workaround that does not work... We have a similar code in lsp-mode.

**Comment by minad** [comment]
> The labels are not unique so this is pretty much a workaround that does not work... We have a similar code in lsp-mode.

Yes, I know. This is the same problem with `completing-read` which strips properties. I made some proposals on emacs-devel to change this, this could also apply to completion-at-point. However, if you say that you have such code, why is it then a problem to strip the properties https://github.com/minad/corfu/issues/11#issuecomment-822523543.

**Comment by yyoncho** [comment]
> . However, if you say that you have such code, why is it then a problem to strip the properties [#11 (comment)](https://github.com/minad/corfu/issues/11#issuecomment-822523543).

It is hard to tell - the potential text properties issue was just a guess.

**Comment by s-kostyaev** [comment]
> @s-kostyaev You could give the following code a quick try. Just eval-defun and try again if yasnippet works now.
> 
> ```emacs-lisp
> (defun corfu--insert (status)
>   "Insert current candidate, exit with STATUS if non-nil."
>   (pcase-let* ((`(,beg ,end ,table ,pred) completion-in-region--data)
>                (str (buffer-substring-no-properties beg end)))
>     ;; Replace if candidate is selected or if current input is not valid completion.
>     ;; For example str can be a valid path, e.g., ~/dir/.
>     (when (or (>= corfu--index 0) (equal str "")
>               (not (test-completion str table pred)))
>       (setq str (concat (substring str 0 corfu--base)
>                          (nth (max 0 corfu--index) corfu--candidates))) ;; !!!!!!!! RETAIN PROPERTIES !!!!!!!
>       (completion--replace beg end str))
>     (if (not status)
>         (setq corfu--index -1) ;; Reset selection, but continue completion.
>       ;; XXX Is the :exit-function handling sufficient?
>       (when-let (exit (plist-get corfu--extra-properties :exit-function))
>         (funcall exit str status))
>       (completion-in-region-mode -1))))
> ```

Not working for me.

**Comment by s-kostyaev** [comment]
Testing recipe:
`emacs -Q`
```elisp
(package-initialize)
(yas-global-mode +1)
(setq tab-always-indent 'complete)
(corfu-mode +1)

(defun corfu--insert (status)
  "Insert current candidate, exit with STATUS if non-nil."
  (pcase-let* ((`(,beg ,end ,table ,pred) completion-in-region--data)
               (str (buffer-substring-no-properties beg end)))
    ;; Replace if candidate is selected or if current input is not valid completion.
    ;; For example str can be a valid path, e.g., ~/dir/.
    (when (or (>= corfu--index 0) (equal str "")
              (not (test-completion str table pred)))
      (setq str (concat (substring str 0 corfu--base)
                         (nth (max 0 corfu--index) corfu--candidates))) ;; !!!!!!!! RETAIN PROPERTIES !!!!!!!
      (completion--replace beg end str))
    (if (not status)
        (setq corfu--index -1) ;; Reset selection, but continue completion.
      ;; XXX Is the :exit-function handling sufficient?
      (when-let (exit (plist-get corfu--extra-properties :exit-function))
        (funcall exit str status))
      (completion-in-region-mode -1))))
```
Then open some file in lsp supported project with snippets support. `M-x` `lsp` `M-x` `company-mode` `M-x` `corfu` and try to complete by pressing `TAB`. Snippet expansions not works.

**Comment by minad** [comment]
@s-kostyaev Can you try to select using `RET` instead of `TAB`? `TAB` is bound to `corfu-complete` which is written as non-exiting completion. I should probably still invoke the exit function from there depending on if its the only completion.

**Comment by s-kostyaev** [comment]
> @s-kostyaev Can you try to select using `RET` instead of `TAB`? `TAB` is bound to `corfu-complete` which is written as non-exiting completion. I should probably still invoke the exit function from there depending on if its the only completion.

Exactly. I have tested it with single completion candidate. With multiple candidates it works fine. Will you fix it for single candidate?

**Comment by minad** [comment]
@s-kostyaev I cannot reproduce this. Can you please be more precise. You see three candidates. Then you press what? down/ret/tab? You see a single candidate. Then you press what? down/ret/tab? This all may all make a difference on the code paths.

**Comment by s-kostyaev** [comment]
I can't see single candidate in dropdown. It complete and insert candidate. And don't eval exit function.

**Comment by s-kostyaev** [comment]
I have print prefix that can be completed with one variant only, press `tab` and see this variant inserted, no dropdown or so.

**Comment by minad** [comment]
Thank you, this explains the issue.

**Comment by minad** [comment]
I pushed an improved fix. Please try it again.

**Comment by minad** [comment]
Ideally test all these scenarios, which should all work with expansion.

1. Direct single-candidate completion with prefix by just pressing TAB
2. Enter incomplete prefix, press TAB, select using up down, then RET
3. Enter incomplete prefix, press TAB, select using up down, then TAB
4. Enter incomplete prefix, press TAB, narrow further until you see a single candidate, then TAB
5. Enter incomplete prefix, press TAB, narrow further until you see a single candidate, then RET

**Comment by s-kostyaev** [comment]
> Ideally test all these scenarios, which should all work with expansion.
> 
>     1. Direct single-candidate completion with prefix by just pressing TAB

failed

>     2. Enter incomplete prefix, press TAB, select using up down, then RET

pass

>     3. Enter incomplete prefix, press TAB, select using up down, then TAB

failed

>     4. Enter incomplete prefix, press TAB, narrow further until you see a single candidate, then TAB

failed. client-side filtering is broken.

>     5. Enter incomplete prefix, press TAB, narrow further until you see a single candidate, then RET

failed. client-side filtering is broken.

**Comment by minad** [comment]
What does failed mean? No expansion? What is "client-side filtering is broken"?

**Comment by minad** [comment]
Btw, I just gave it another test after your disappointing test report. I used the following `corfu--done` function which prints the exit status.

~~~ elisp
(defun corfu--done (str status)
  "Call the `:exit-function' with STR and STATUS and exit completion."
  ;; XXX Is the :exit-function handling sufficient?
  (message "EXIT WITH str=%S status=%S" str status)
  (when-let (exit (plist-get corfu--extra-properties :exit-function))
    (funcall exit str status))
  (completion-in-region-mode -1))
~~~

In all cases 1.-5. I get the result

~~~
EXIT WITH str=... status=finished
~~~

This means that the exit function is indeed called correctly. If this is insufficient the problem lies elsewhere.

**Comment by s-kostyaev** [comment]
Failed means no expansion on `tab` press. "client-side filtering is broken" means that in `lsp` server return all completions for fuzzy completion on client side. And this filtering is not working with corfu. Doesn't matter what keys I press all candidates are still here.

**Comment by s-kostyaev** [comment]
Sorry, you get great job. I don't want to create disappointing reports. I will try to explain better.

**Comment by s-kostyaev** [comment]
For me it's ok what I need to press `ret` for completion. But in first case with direct single-candidate completion snippets are not expanded, only candidate inserted.

**Comment by s-kostyaev** [comment]
> Btw, I just gave it another test after your disappointing test report. I used the following `corfu--done` function which prints the exit status.
> 
> ```emacs-lisp
> (defun corfu--done (str status)
>   "Call the `:exit-function' with STR and STATUS and exit completion."
>   ;; XXX Is the :exit-function handling sufficient?
>   (message "EXIT WITH str=%S status=%S" str status)
>   (when-let (exit (plist-get corfu--extra-properties :exit-function))
>     (funcall exit str status))
>   (completion-in-region-mode -1))
> ```
> 
> In all cases 1.-5. I get the result
> 
> ```
> EXIT WITH str=... status=finished
> ```
> 
> This means that the exit function is indeed called correctly. If this is insufficient the problem may lie some where else.

I can't see message in case 1.
Maybe completion is provided without `corfu` in that case? How can I call it explicitly? `M-x` `corfu-complete` is failed with `Wrong type argument: number-or-marker-p, nil`

**Comment by minad** [comment]
> Maybe completion is provided without corfu in that case? 

Yes, it is provided by default completion. However the post command hook should then execute the `:exit-function`. `corfu--done` is also called in `corfu--update-display`. I think the approach I am using now is in principle correct. But maybe there are some edge cases I missed. And since you say that the filtering is not working means that something is changed with how the completion infrastructure works. I have to investigate this a bit more in detail at some point.
