### ISSUE TITLE
Enabling corfu-mode breaks order with `completion-cycle-threshold`

### ISSUE THREAD

**Issue by phikal** [minad/corfu#113]
Hi,

when `corfu-mode` is enabled in a buffer, and the configuration of `completion-cycle-threshold` applies so that options are cycled instead of completed, the order of candidates in a completion table are not respected the same way as they are when `corfu-mode` is disabled.

I have noticed this in rcirc, that sets `completion-cycle-threshold` to t, to complete user names and command by cycling.

Would it be possible to preserve the default behavior and ordering when cycling when corfu-mode shouldn't pop up.

**Comment by minad** [comment]
Originally Corfu was implemented differently. It reused `completion--in-region` (the default completion function) and only opened the popup in cases where the normal `*Completions*` buffer would open. Unfortunately this approach turned out to be a maintenance nightmare. I had to use many advices and hooks to adapt the behavior of the default completion function to work properly together with Corfu. For this reason I replaced the implementation of the `completion-in-region` function with a clean slate reimplementation, see https://github.com/minad/corfu/commit/d480b27465bf238cb596462f5d30bf32f74496dc and https://github.com/minad/corfu/commit/d480b27465bf238cb596462f5d30bf32f74496dc, which of course uses the sorting/filtering mechanism of Corfu.

Corfu relies for sorting on its `corfu-sort-function` or the `display-sort-function`, as specified by the completion metadata. The cycling of default completion relies on the `cycle-sort-function`, which could lead to a deviation in behavior here. Could you be more concrete here? How does the sort order differ, in which ways is the default sort order better? I don't intend to go back to reuse the default `completion--in-region` function due to the aforementioned maintenance issues, but we can discuss how the default sorting can be improved. In general the default sort function of both Vertico and Corfu replicates the sort function of the default completion system (by length and alphabetical).

**Comment by phikal** [comment]
Daniel Mendler ***@***.***> writes:

> Corfu relies for sorting on its `corfu-sort-function` or the
> `display-sort-function`, as specified by the completion metadata. The
> cycling of default completion relies on the `cycle-sort-function`,
> which could lead to a deviation in behavior here.

Maybe `cycle-sort-function' should be consulted as well, because
`rcirc-completion-at-point' sets it to identity, and this appears to not
be respected.  It seems to be that Corfu should either not respect
`completion-cycle-threshold' or should use `cycle-sort-function'.

> Could you be more concrete here? How does the sort order differ, in>
> which ways is the default sort order better?

rcirc completes user names in order of their last message (it makes
sense, because you probably want to reply to someone who just sent a
message, not someone who has been idling), while when coruf-mode is
enabled I cannot recognise a consistent order.

-- 
	Philip Kaludercic

**Comment by minad** [comment]
> Maybe `cycle-sort-function' should be consulted as well, because `rcirc-completion-at-point' sets it to identity, and this appears to not be respected.

Do you use a different order for cycling and display, `cyle-sort-function` vs `display-sort-function`? If you set both to identity there shouldn't be an issue. I consider using different cycle and display functions a misfeature and I consider the distinction a historical mistake. I've also not stumbled over many examples where different functions are used. Is there a good reason to not set both the display and cycle function to identity?

**Comment by phikal** [comment]
Daniel Mendler ***@***.***> writes:

>> Maybe `cycle-sort-function' should be consulted as well, because
> `rcirc-completion-at-point' sets it to identity, and this appears to
> not be respected.
>
> Do you use a different order for cycling and display,
> `cyle-sort-function` vs `display-sort-function`? If you set both to
> identity there shouldn't be an issue. I consider using different cycle
> and display functions a misfeature and I consider the distinction a
> historical mistake. I've also not stumbled over many examples where
> different functions are used. Is there a good reason to not set both
> the display and cycle function to identity?

I have tried this, and it doesn't fix the issue.  From my understanding
of the corfu-internals, redefining `corfu--sort-function' to

        (defun corfu--sort-function ()
          "Return the sorting function."
          (or (and (completion--cycle-threshold corfu--metadata)
                   (corfu--metadata-get 'cycle-sort-function))
              (corfu--metadata-get 'display-sort-function)
              corfu-sort-function))

should have the same effect, but this too doesn't preserve the order
(except for the "empty" completion, in which case all completions
accurately reflect the order of the last message sent out by each nick).

-- 
	Philip Kaludercic

**Comment by minad** [comment]
For now I pushed a fix which uses the `cycle-sort-function` for sorting. If you look at `corfu--recompute-candidates` there is a little more manipulation happening, e.g., prefix candidates are moved to the front, exact candidates are moved to the front, consecutive duplicate are deleted etc. Could this lead to the issue you are observing? I could also remove this special manipulation when cycling is active. However I wonder how this causes your issue. You may want to give this a check.

**Comment by phikal** [comment]
Daniel Mendler ***@***.***> writes:

> For now I pushed a fix which uses the `cycle-sort-function` for
> sorting. If you look at `corfu--recompute-candidates` there is a
> little more manipulation happening, e.g., prefix candidates are moved
> to the front, exact candidates are moved to the front, consecutive
> duplicate are deleted etc. Could this lead to the issue you are
> observing? I could also remove this special manipulation when cycling
> is active. However I wonder how this causes your issue. You may want
> to give this a check.

It does fix the main issue with ordering, but there still seem to be
issues caused by `corfu--move-prefix-candidates-to-front' when it comes
to case, if `completion-ignore-case' is enabled.

-- 
	Philip Kaludercic

**Comment by minad** [comment]
Unfortunately I had to revert ba649bfc1e5772d14b67058cf8491be1098d2b12 after having it tried for a little longer. It leads to very confusing behavior if the popup uses a different sorting function than the cycling. This is observable in particular if auto completion is also activated. As a way out I could use the `cycle-sort-function` consistently throughout Corfu. For some reason (which I don't recall), I made the choice to use the `display-sort-function` as sort function in Vertico/Corfu. But anyways, I suggest to not specify different cycle and sort functions. 

I modifed `corfu--move-prefix-candidates-to-front` such that it respects `completion-ignore-case`.

**Comment by phikal** [comment]
Daniel Mendler ***@***.***> writes:

> Unfortunately I had to revert ba649bfc1e5772d14b67058cf8491be1098d2b12
> after having it tried for a little longer. It leads to very confusing
> behavior if the popup uses a different sorting function than the
> cycling. This is observable in particular if auto completion is also
> activated.

That is understandable.  For now I have just disabled corfu-global-mode,
and added corfu-mode to prog-mode-hook instead, and that circumvents the
issue in my case.

> As a way out I could use the `cycle-sort-function`
> consistently throughout Corfu. For some reason (which I don't recall),
> I made the choice to use the `display-sort-function` as sort function
> in Vertico/Corfu. But anyways, I suggest to not specify different
> cycle and sort functions.

I can fix this for rcirc, it just seems like an issue that could pop up
elsewhere, at some other time.  As I said, rcirc always uses cycling
completion (as is the convention for IRC clients), so it seems
reasonable that `cycle-sort-function' should suffice.  I can imagine
others making the same "mistake" at some point.

> I modifed `corfu--move-prefix-candidates-to-front` such that it
> respects `completion-ignore-case`.

Great, thank you!

-- 
	Philip Kaludercic

**Comment by minad** [comment]
> I can fix this for rcirc, it just seems like an issue that could pop up
elsewhere, at some other time.  As I said, rcirc always uses cycling
completion (as is the convention for IRC clients), so it seems
reasonable that `cycle-sort-function' should suffice.  I can imagine
others making the same "mistake" at some point.

I doubt this. There is no point in using Corfu if you want to cycle only. Then you are effectively not using Corfu and should just use default completion. That's of course okay. Corfu is a local mode for a reason :)

I still recommend the corfu-global-mode. You can opt out via corfu-excluded-modes.
