### ISSUE TITLE
debugging latency

### ISSUE THREAD

**Issue by titaniumbones** [minad/corfu#115]
As I experiment with corfu, I am sometimes noticing significant latency while typing, which I imagine comes from running too many completion functions as once. In particular, while I am rapidly typing text I end up with off errors, so I'd like to fix it. Any suggestions on how I might debug my setup so I can find the root cause of the issue?  

Thank you!

**Comment by minad** [comment]
Start the profiler with `profiler-start`, let it run for a while when editing and then inspect the `profiler-report` afterwards. I suspect that the issues is your configuration and I suspect that you use a low value of `corfu-auto-delay` and a short `corfu-auto-prefix`. If one uses a low delay it will cause Corfu to always compute the candidates on every keypress which is expensive. It works better with a longer delay and longer prefix. Then auto completion does not add significant latencies. If nothing helps you can also consider disabling auto completion and use TAB completion to trigger Corfu. Manual trigger works really well from my experience and leads to an unobtrusive behavior, so maybe give that a try?

Regarding errors during completion I need more details. If you use the default capf provided by lsp/eglot/major mode it should be all fine. Furthermore you can combine the Capfs with some of my [Cape](https://github.com/minad/cape) functions which should also not lead to issues. In some cases you may not see a stack trace, then you have to set the `debug-on-error` variable and additionally execute:

~~~ elisp
(defun force-debug (func &rest args)
  (condition-case e
      (apply func args)
    ((debug error) (signal (car e) (cdr e)))))

(advice-add #'corfu--post-command :around #'force-debug)
~~~

Furthermore when debugging, try to start with a minimal configuration, only emacs -Q with Corfu. Then add your completion functions step by step. It could be that only a single problematic backend leads to these bad effects. I hope this helps.

**Comment by minad** [comment]
So what is the new finding here? That `cape-ispell` introduces latencies? It is simple - add completion functions one by one and then you will find if some are acceptable and some are not. Don't just activate all the completion functions right away. I don't see an issue here. Corfu is doing all it can to avoid inefficiencies, but if backends are slow, Corfu can do nothing about this.

**Comment by minad** [comment]
Note that in the Cape README, these functions are enabled by default:

~~~ elisp
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-tex)
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-keyword)
~~~

`cape-dict`, `cape-ispell` etc are not. You can invoke them on-demand with a keybinding.

**Comment by ronniedroid** [comment]
Ah I see, I thought maybe their is an issue with cape-ispell that could be fixed (then I guess this is not the appropriate place to file an issue for it)

Sorry for wasting your time.

**Comment by minad** [comment]
> Ah I see, I thought maybe their is an issue with cape-ispell that could be fixed (then I guess this is not the appropriate place to file an issue for it)

I doubt there is a possibility. `cape-ispell` shells out to aspell/ispell asking for matching words, so this is necessarily slow. It is still okay to use manually or when you have `corfu-auto=nil`.

**Comment by ronniedroid** [comment]
Still doesn't explain why it is trying to complete a single `<SPC>` char. Or `-<SPC>` when I have `corfu-auto-prefix` set to 3.

**Comment by minad** [comment]
> Still doesn't explain why it is trying to complete a single <SPC> char. Or -<SPC> when I have corfu-auto-prefix set to 3.

Interesting. Can you please be precise about this? Can you give me a minimal recipe, emacs -Q, corfu+cape only?

**Comment by ronniedroid** [comment]
here you go
launch emacs with `emacs -Q` and add the following

```lisp
(add-to-list 'load-path "/path/to/corfu")
(add-to-list 'load-path "/path/to/cape")

(load "corfu")
(load "cape")

(require 'corfu)
(setq corfu-cycle t)                
(setq corfu-auto t)                 
(setq corfu-quit-at-boundary t)     
(setq corfu-quit-no-match t)        
(setq corfu-echo-documentation nil)
(corfu-global-mode)

(require 'cape)
(add-to-list 'completion-at-point-functions #'cape-file)
(add-to-list 'completion-at-point-functions #'cape-dabbrev)
;;(add-to-list 'completion-at-point-functions #'cape-ispell) ; uncomment and evaluate this line and the problem should arise
```

**Comment by minad** [comment]
@ronniedroid Thank you! Indeed you are perfectly right. There was a subtle bug in Corfu regarding the prefix length checking, which only affected non-exclusive Capfs. Probably `cape-ispell` is the only Capf where you can observe this. Fix is on the way!

**Comment by ronniedroid** [comment]
I am glad I could help, thank you for such a great package.
