### ISSUE TITLE
post-completion actions revisited

### ISSUE THREAD

**Issue by titaniumbones** [minad/corfu#116]
I found an interesting discussion in #11 about post-completion actions, something I would also like to see myself in LSP, where I would hope to use TempEl or similar code scaffolding to automate writing e.g. function definitions.  However, though you say in https://github.com/minad/corfu/issues/11#issuecomment-945090127 that "post completion actions work properly", I don't see an explanation in the docs about how to achieve this. Is there a place in the code I should look to understand more?  

Thanks for your tireless maintainership of all these packages & pls let me know if issues are an inconvenient way to ask these questions.

**Comment by minad** [comment]
Post completion actions are implemented by the `:exit-function`. See for example `temple-complete` which expands the Tempel template after completion (https://github.com/minad/tempel/blob/17f3020b8ecd7fdd16b34aeb11c91a620ac42c3a/tempel.el#L531-L550).

**Comment by minad** [comment]
> Thanks for your tireless maintainership of all these packages & pls let me know if issues are an inconvenient way to ask these questions.

It is of course fine to ask such questions here as long as you are doing a bit of reading/searching yourself (which apparently you do, so it is alright). Generally I prefer to use the issue trackers for issues only to reduce the load, but these special questions regarding completion are welcome here. There are not many other places where one can ask (emacs-devel of course and maybe reddit if @oantolin reads your question ;).

Note that I usually close issues quickly which don't require actions from my side or changes to the packages. Feel free to continue the discussion anyways. Occasionally some contributors will chime in too!
