### ISSUE TITLE
rotate through completion functions?

### ISSUE THREAD

**Issue by titaniumbones** [minad/corfu#117]
I'm sorry to be a little confused and perhaps asking something everyone should already know. Is there a mechanism to rotate through completion-at-point-functions in corfu? Or will the first function with candidates always inhibit later completions from running? The manual says "When the command completion-at-point runs, it calls the functions in the list one by one, without any argument." but I'm not sure if that means completion-at-point actually allows overriding of individual functions.

**Comment by minad** [comment]
- A non-exclusive capf will inhibit later capfs from running if it returns candidates.
- An exclusive capf will inhibit later capfs even if the returned completion tables is empty, except if it explicitly opts out by returning nil. 
- You cannot rotate between Capfs, but you could write a command yourself which does that. My recommendation however is to bind separate completion commands separately, see for example https://github.com/minad/cape#configuration.
