### ISSUE TITLE
New approach for quitting on field boundary

### ISSUE THREAD

**Issue by minad** [minad/corfu#119]
OK, I have a corfu-auto + orderless setup that works very well for me.  Happy to put it on the wiki if it isn't too esoteric.  The idea is:

- Enable quit-on-boundary.
- Use a special unicode word-syntax character (in addition to space) for the orderless component separator.  "[ \u268b]" is my current choice (that char looks like `⚋`).  
- Bind `M-SPC` in corfu-map to insert this special character.
- Advise `corfu--post-command` to turn _off_ (via let-bind) `corfu-quit-at-boundary` _if the input contains this special separator character_. 

This works really well in practice.  All I have to do is remember to `M-SPC` instead of `SPC` with corfu _the first time only_ when I want to use multiple orderless filters.  And the default quit-on-boundary basically eliminates _all_ the false-positives, e.g. defining new variables, random words in strings or comments that my cape-ified dabbrev-enabled capf throws, etc.  But still lets you use full orderless power with regexps, etc. in buffer.  The only small drawback is the potential for unicode chars to persist in your buffer (if you `C-g` with a multi-component filter), hence my interest in a quick undo-and-quit, above. 

Thoughts?  Suggesting an advice is obviously not ideal for the wiki. Is there a predicate config option you are considering which might work instead for this `corfu--post-command` `:around` advice?

```elisp
  (defun my/corfu-disable-quit-with-orderless-advice (func)
    (let ((corfu-quit-at-boundary
	   (not (seq-contains (car corfu--input)
			      my/orderless-unicode-separator))))
      (funcall func)))
```

_Originally posted by @jdtsmith in https://github.com/minad/corfu/issues/109#issuecomment-1030686690_

**Comment by minad** [comment]
See discussion following in #109 https://github.com/minad/corfu/issues/109#issuecomment-1030688695

**Comment by jdtsmith** [comment]
Here's another nice unicode option (`#x00b7`, MIDDLE DOT):

<img width="163" alt="image" src="https://user-images.githubusercontent.com/93749/152661198-26b097a8-f374-486c-886b-2e434753a13d.png">

**Comment by minad** [comment]
Why not just use space? If we dynamically turn off the boundary check for M-SPC we can do that.

**Comment by jdtsmith** [comment]
OK, yeah, better; so just check the command keys?  We of course still want a normally-typed space to quit.

**Comment by minad** [comment]
Yes, sure. It would require you to configure two things: 1. The separator corfu-separator-char and 2. bind a new command corfu-insert-separator to a key of your choice.

**Comment by Cletip** [comment]
Hello !

I thought the workflow for using corfu effectively, and discovered (or just find one time again after someone else ?) something very nice (I think), with the following behaviour:
- type the word you want (not the whole word)
- corfu is displayed
- if you do your separator (recommanded : space), it inserts a separator for orderless
- if you press two time your separator, it inserts the current candidate
- if you do C-u separator, it leaves the word as it is, without completion, and inserts a space.

Here's the code that should normally work:

  ```
(setq corfu-separator 32)

  ;; highly recommanded to use corfu-separator with "32" (space)
    (define-key corfu-map (char-to-string corfu-separator)
      (lambda ()
	(interactive)
	(if current-prefix-arg
	    ;;we suppose that we want leave the word like that, so do a space
	    (progn 
	      (corfu-quit)
	      (insert " "))
	  (if (and (= (char-before) corfu-separator)
		   (or
		    (= (char-after) ?\s)
		    (= (char-after) ?\n)))
	      (progn
		(corfu-insert)
		(insert " "))
	    (corfu-insert-separator)))))
```

We can now type "spc" to insert a separator (and using orderless), and "spc spc" to insert the current candidate.

What do you think about this ?

**Comment by minad** [comment]
@Cletip Thanks, feel free to add your code to the Corfu wiki. I don't see much of a difference to the current approach:

- Insert the separator either with SPC or M-SPC
- Insert a space either with M-SPC or SPC
- Insert the candidate with RET

**Comment by Cletip** [comment]
Ok thanks
The problem was that I wanted the same key to insert the separator and insert the candidate, I feel that much more natural.

**Comment by minad** [comment]
> Ok thanks
> The problem was that I wanted the same key to insert the separator and
> insert the candidate, I feel that much more natural.

Sure, there is nothing wrong to use this in your user configuration.
Please also add it to the wiki for other users. To me it does not look
more natural, considering how Emacs usually works. Emacs uses many
different keys and keys with modifiers.
