### ISSUE TITLE
Small MacOS compile issue

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#123]
This isn't new, but on MacOS the compiler complains:

```elisp
Compiling file /Users/jdsmith/code/emacs/corfu/corfu.el at Mon Feb  7 14:55:05 2022
corfu.el:378:1:Warning: Unused lexical variable ‘x-gtk-resize-child-frames’
```

**Comment by minad** [comment]
Hmm, we could work around this with a macro. But to cite the [Emacs FAQ](https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Why-Emacs-on-Windows.html):

> 1.1 Why support GNU Emacs on Windows?
> It is not our goal to “help Windows users” by making text editing on Windows more convenient. We aim to replace proprietary software, not to enhance it. So why support GNU Emacs on Windows?
> We hope that the experience of using GNU Emacs on Windows will give programmers a taste of freedom, and that this will later inspire them to move to a free operating system such as GNU/Linux. That is the main valid reason to support free applications on nonfree operating systems. 

So it is okay if the compilation experience on non free operating systems is not as good. :laughing: 

(Seriously, I think this is a minor issue and I would just leave it as is. Hopefully the x-gtk hack goes away at some point in the future, as well as many of the other hacks which are needed to placate the buggy Emacs child frames.)

**Comment by jdtsmith** [comment]
Yes not a big deal just thought I'd mention in case the fix was easy (thanks, looks like it was!).

PS: Don't forget to bump the version for the obsolete.  Or do you prefer to sit with it a bit before pushing to elpa?

**Comment by minad** [comment]
Yes, I will let it sit for a month before the next ELPA release.
