### ISSUE TITLE
hitting esc/corfu-reset during completion does not recover the position of the point

### ISSUE THREAD

**Issue by ville-h** [minad/corfu#125]
Hitting esc/corfu-reset during completion does not recover the position of the point.
```
void fff_fff() {
}


int main() {
    ff // <-- place point here right after "ff" and activate completion
    return 0;
}
```
0) start as follows
![emacs_corfu_reset_0](https://user-images.githubusercontent.com/8824715/153722764-09eced18-552e-4c98-bdc5-30bd4722d60e.png)

1) hit tab to select a completion
![emacs_corfu_reset_1](https://user-images.githubusercontent.com/8824715/153722813-ed403209-4876-4d46-a021-63144a25a775.png)

2) hit esc to cancel selection
![emacs_corfu_reset_2](https://user-images.githubusercontent.com/8824715/153722854-34e4afab-9d05-43af-aead-88dfb15a1e8d.png)

The point is now before "ff" rather than after "ff" the position the point started at before activating completion.

**Comment by minad** [comment]
I cannot reproduce this in an Elisp buffer with emacs -Q with only `corfu-global-mode` activated. Maybe this is an issue of your configuration or the Lsp or Eglot backend?

**Comment by ville-h** [comment]
I also forgot to specify what version I am using. It's 0.18 from elpa.

**Comment by ville-h** [comment]
Here's perhaps something you might be able to better replicate. 
0) main.cxx:
```
int fff_fff() {
}


int main() {
  f // <-- place point here right after "f", hit tab twice and bang on esc.
    // 3 esc moves the point to before "f"
    // 3 more esc closes the completion box
    return 0;
}
```
1) emacs_clean_start_with_package.el:
```
(require 'package)


(setq debug-on-error t)
(setq no-byte-compile t)
(setq package-archives '(
    ("melpa" . "https://melpa.org/packages/")
    ("gnu" . "https://elpa.gnu.org/packages/")
))
(setq package-user-dir
    (expand-file-name (make-temp-name "__remove-remove-remove-elpa") user-emacs-directory)
)
(setq custom-file (expand-file-name "__remove-remove-remove-custom.el" package-user-dir))


(let*
    (
        (pkg-list
            '(
                 ;; add packages here:
                 corfu
                 lsp-mode
             )
        )
    )

    (package-initialize)
    (package-refresh-contents)

    (mapc
        (lambda (pkg)
            (unless (package-installed-p pkg)
                (package-install pkg))
            (require pkg)
        )
        pkg-list
    )

    (add-hook 'prog-mode-hook
        (lambda()
            ;; enable packages here:
            (corfu-global-mode 1)
            (setq tab-always-indent 'complete)
            ;; 2021-02-12 note: from https://github.com/minad/corfu/wiki
            (setq lsp-completion-provider :none)

            ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
            ;; 2021-02-12 note: for some reason this line seems to affect corfu behaviour
            (setq lsp-clients-clangd-args '("--header-insertion=never"))
            ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

            (lsp)
        )
    )

    (add-hook 'c++-mode-hook
        (lambda()
            (define-key c++-mode-map (kbd "<tab>") #'indent-for-tab-command)
        )
    )

    (add-hook 'kill-emacs-hook
        (lambda()
            (delete-directory package-user-dir t)
        )
    )
)


(provide 'emacs-clean-start-with-package)
```
2) Run:
```
emacs --quick --load ./emacs_clean_start_with_package.el ./main.cxx
```

**Comment by minad** [comment]
I am not using lsp-mode myself. Maybe the lsp-mode maintainers can be of help. The issue seems specific to lsp-mode since I don't see this with any of the other Capfs. @jdtsmith You probably observed this too?

**Comment by jdtsmith** [comment]
I haven't seen this with my lsp server, no.

**Comment by ville-h** [comment]
After recent update to corfu 0.19 the behaviour has changed. Now the point postion is not changed, but it takes 6 esc clicks to cancel out of the completion box. Also it's no longer dependent on `(setq lsp-clients-clangd-args '("--header-insertion=never"))`

**Comment by jdtsmith** [comment]
What happens with `C-g`?

**Comment by minad** [comment]
> Now the point postion is not changed, but it takes 6 esc clicks to cancel out of the completion box.

I recommend the configuration `(global-set-key [escape] #'keyboard-escape-quit)` such that you don't have to hammer ESC so many times.

**Comment by ville-h** [comment]
Yes in my real configuration I do have: `(define-key global-map (kbd "<escape>") #'keyboard-escape-quit)`. I was just reporting what happens in a clean environment using the script I provided.

**Comment by minad** [comment]
> Even with this binding, it takes two Escapes to get out of corfu. Would be useful to improve this.

No, this is intentional. You can replace `corfu-reset` with something else, if you want to quit faster. :)

**Comment by ville-h** [comment]
Not sure if i should post here or open a new issue, but there are still some problems:
```
#include "iostream"

int main()
{
  st // <- place point after "st"
  return 0;
}
```
1. place point after "st"
2. hit tab
3. hit tab
4. hit esc

The point is now before "st". I would have expected the point to be after "st".

**Comment by minad** [comment]
@ville-h I don't consider this as an issue of Corfu since it is lsp-mode specific. I don't use lsp-mode currently so I am unable to debug it. Furthermore since the issue seems to occur only when aborting completion it is a rare scenario. You can unbind `corfu-abort` in the `corfu-map` if this command makes problems for you.
