### ISSUE TITLE
(wrong-type-argument consp "...") on custom Emmet completion

### ISSUE THREAD

**Issue by vmsp** [minad/corfu#129]
I'm trying to implement a CAPF completion function for `emmet-mode` to make it work nicely with Corfu.

I ended up this, which works fine when using Emacs' default completion-at-point

``` elisp
(use-package emmet-mode
  :commands (emmet-find-left-bound emmet-transform emmet-reposition-cursor)
  :hook (web-mode . vsp/emmet-setup-capf)
  :init
  (defun vsp/emmet-expand ()
    (list (emmet-find-left-bound) (point)
          (lambda (str pred action) (emmet-transform str))
          :exclusive 'no
          :exit-function (lambda (str status)
                           (emmet-reposition-cursor str))))

  (defun vsp/emmet-setup-capf ()
    (add-hook 'completion-at-point-functions 'vsp/emmet-expand 0 'local)))
```

As soon as I turn on Corfu, like so

``` elisp
(use-package corfu
  :hook (prog-mode . corfu-mode))
```

I get the following error -- with debug turned on -- when trying to expand `.asd` to `<div class="asd"></div>`

``` elisp
Debugger entered--Lisp error: (wrong-type-argument consp "<div class=\"asd\"></div>")
  completion-hilit-commonality("<div class=\"asd\"></div>" 4 0)
  completion-basic-all-completions(".asd" (closure (t) (str pred action) (emmet-transform str)) nil 4)
  #f(compiled-function (style) #<bytecode 0x1fe52851965d>)(basic)
  completion--some(#f(compiled-function (style) #<bytecode 0x1fe52851965d>) (basic substring flex))
  completion--nth-completion(2 ".asd" (closure (t) (str pred action) (emmet-transform str)) nil 4 (metadata))
  completion-all-completions(".asd" (closure (t) (str pred action) (emmet-transform str)) nil 4 (metadata))
  apply(completion-all-completions (".asd" (closure (t) (str pred action) (emmet-transform str)) nil 4 (metadata)))
  corfu--all-completions(".asd" (closure (t) (str pred action) (emmet-transform str)) nil 4 (metadata))
  corfu--recompute-candidates(".asd" 4 (closure (t) (str pred action) (emmet-transform str)) nil)
  corfu--in-region(#<marker at 4 in app.html.erb> 8 (closure (t) (str pred action) (emmet-transform str)) nil)
  completion-in-region(#<marker at 4 in app.html.erb> 8 (closure (t) (str pred action) (emmet-transform str)) nil)
  completion-at-point()
  indent-for-tab-command(nil)
  funcall-interactively(indent-for-tab-command nil)
  #<subr call-interactively>(indent-for-tab-command nil nil)
  apply(#<subr call-interactively> indent-for-tab-command (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> indent-for-tab-command nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (indent-for-tab-command nil nil))
  call-interactively(indent-for-tab-command nil nil)
  command-execute(indent-for-tab-command)
```

**Comment by minad** [comment]
The completion table you used here doesn't look correct:

~~~ elisp
(lambda (str pred action) (emmet-transform str))
~~~

See Cape for many examples: https://github.com/minad/cape. See also https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html for the documentation of completion table. Note in particular the use of `complete-with-action` in the Cape completion tables. I hope this helps.

**Comment by minad** [comment]
To give you two quick examples:

~~~ elisp
;; Basic example
(defun example-capf ()
  (let ((bounds (or (bounds-of-thing-at-point 'word) (cons (point) (point)))))
    (list (car bounds) (cdr bounds)
          '("capffirst" "capfsecond" "capfthird" "capffourth"))))

;; Programmed completion table, see complete-with-action
(defun example-capf ()
  (let ((bounds (or (bounds-of-thing-at-point 'word) (cons (point) (point)))))
    (list (car bounds) (cdr bounds)
          (lambda (str pred action)
            (complete-with-action action
                                  '("capffirst" "capfsecond" "capfthird" "capffourth")
                                  str pred)))))


(setq completion-at-point-functions '(example-capf))
(global-set-key (kbd "C-c p") #'completion-at-point)
~~~

**Comment by minad** [comment]
I assume that you want to simply expand the emmet input instead of offering completion? The closest example I have is `tempel-expand` which also does that. It expands a template if the key you are completing matches exactly.

See https://github.com/minad/tempel/blob/5242ebb37fbf14f60c8eecf4461091ee22389912/tempel.el#L544-L561

**Comment by vmsp** [comment]
I had been looking at the exact function you mention in Templ to try an write that but, unfortunately, my elisp-foo is not up to par!

If I'm not mistaken, you were suggesting that the completion table must be a list-ish type, right?. Reading the docs it says that `collection` must be 

> ... in a form suitable for passing as the second argument to try-completion.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-in-Buffers.html

And taking a look at `try-completion`, it says that

> You can also use a function as collection. Then the function is solely responsible for performing completion; try-completion returns whatever this function returns.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Completion.html

So -- again, not an expert -- but it does seem like my code should work.

Anyway, I ended up with an alternative implementation. I think using it like this is discouraged but it's working fine, with Corfu.

``` elisp
(add-hook 'completion-at-point-functions (lambda () (emmet-expand-line nil) 0 'local)
```

**Comment by minad** [comment]
No, you have to pass the list to `complete-with-action` instead of returning it directly from the lambda. If you look at your code, there is something missing:

~~~ elisp
(lambda (str pred action) (emmet-transform str))
~~~

Why do we have the pred and action parameters? The bytecode compiler should warn you about the unused arguments. 

> Anyway, I ended up with an alternative implementation. I think using it like this is discouraged but it's working fine, with Corfu.

Yes, that works fine for now. But it will may break auto completion and expand when you don't expect it. Needless to say that I don't recommend using the obsolete API. This API usage is more than discouraged actually. It could very well happen that I break it.
