### ISSUE TITLE
Completions list left gutter

### ISSUE THREAD

**Issue by muffinmad** [minad/corfu#13]
Hi! Thanks for the cool package! ;)

Is it possible to display the completion candidates right below the text without left "padding"? Right now they are one character to the right of the text:

<img width="236" alt="Знімок екрана 2021-04-21 о 10 18 38" src="https://user-images.githubusercontent.com/2702727/115513534-d6090000-a28b-11eb-9f93-d0b3083811d3.png">

**Comment by minad** [comment]
Thanks, I toyed around with this here (https://github.com/minad/corfu/tree/customizable-border). The downside is that we lose the fancy border then. Given that the display code is brittle right now I am not sure if I want to add such a configuration or any display configurations for the popup at all. At least I will wait a bit to see if this feature is requested more often.

**Comment by manuel-uberti** [comment]
I am not sure this is related, but completion candidates are displayed in a weird position in `M-x shell`:

![Screenshot from 2021-04-26 10-10-01](https://user-images.githubusercontent.com/8199224/116050301-9a00e100-a677-11eb-8f96-800aa7f5706c.png)

**Comment by minad** [comment]
@manuel-uberti This is interesting. I haven't seen this before. I will give it a try.

**Comment by manuel-uberti** [comment]
It's easy to reproduce from `emacs -Q` as well. I am on GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.18, cairo version 1.16.0) of 2021-04-26, commit `50f29f6a282b7426377be5fb54322fc5b5a487fc`, with `--with-native-compilation` enabled.

**Comment by minad** [comment]
I think it is better to keep the border. We could move the popup one character to the left to fix the alignment, but then it would not work at the line beginning. I think a better solution for more flexible visuals should use posframe/child-frames. However my experiences with child-frames have been mixed. Maybe this changes when pgtk lands in Emacs.

Closing as wontfix.
