### ISSUE TITLE
corfu auto calling capf repeatedly

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#130]
Now that I am for the first time exercising the code path of completion-in-region-mode-predicate (thanks to the new magic separator), I have discovered the hard way that corfu calls back frequently into the CAPF during auto-completion, in its post-command-hook.  This seems quite dangerous and/or expensive for CAPF's which require "setup" to return a completion table.  In some ways this is even worse than company's behavior of dumping the table on new input.  Since the CAPF must decide if it can complete there, _and_ build and return a table/table function, I am hoping there may be a lighter-weight approach to decide when to quit corfu.  Ideally the CAPF would be called once at the start of (auto-)completion

At minimum, there is no need to conceive of a quit or re-consult the expensive CAPF if the input is unchanged (e.g. on arrow keys).

**Comment by minad** [comment]
> This seems quite dangerous and/or expensive for CAPF's which require "setup" to return a completion table.

By definition of the API, Capfs should not perform dangerous or expensive setups.

> At minimum, there is no need to conceive of a quit or re-consult the expensive CAPF if the input is unchanged (e.g. on arrow keys).

Fixed in https://github.com/minad/corfu/commit/1c646584c3b99480906bf2ec7c4f2440fc4d8800.

**Comment by minad** [comment]
But I must say that the design of the predicate is not good. It would be better if the completion table comes with an `:alive-predicate` which could be called repeatedly, instead of calling the capf again. Such addition/api extension may be a good idea.

**Comment by jdtsmith** [comment]
Good idea with a continuation commands. It helps. Honestly, I knew the answer before I wrote, since I had seen this comment from the capfs docs: "NOTE: These functions should be cheap to run since they’re sometimes run from ‘post-command-hook’.".  But I agree, it would make more sense for it to be decomposed into "can you complete here" and "what are the completions here" functions.  I'll work on my CAPF to cache the table more thoroughly.

But there is one interesting side-effect of this quit predicate — by invoking the CAPF in post-command, it behaves more like company.  Why?  Unless I'm missing something, the CAPF does not and cannot know it was called "in the middle" of a completion vs. via a new completion session.  So whatever re-contacting the server/etc. it must do initially to gather completions, it will now do after each command (but only _before_ the special separator character).   

I can even convince myself that such a setup is good — recontact the LSP server, company-style, for a fresh set of completions _while in the first component_.  But then, with further orderless components, that's just pure filtering, so don't bother. Some people I bet would even prefer this behavior.  But IMO,  it's strange for it to be arrived at through the back door, in such a hidden and non-configurable way.  And it means the now obsolete quit-on-boundary was in fact doing something quite strange: deciding how often your completion backend was getting contacted.

**Comment by minad** [comment]
So there is at least one difference in contrast to starting auto completion. When checking the predicate, we check on every key press, while auto completion at least has a delay. However if we also add a delay/throttle to check the predicate we will end up with "No match" popups again. We could add our own heuristics, e.g., not checking the predicate when the prefix consists only of letters. But I would rather not add something like this. Ideally backends just take care of this themselves and ensure that the capf setup is fast enough.

**Comment by jdtsmith** [comment]
I agree that a timer isn't ideal.  I do wish there were an explicit separation of concerns between "check if you can complete here" and "build a table that can provide completions here".  It's a bit fussy, but not too terrible to cache for future calls and invalidate only if anything has changed.  But really they are quite distinct operations.  

When you have to perform expensive candidate lookup, contacting a server or process, you're left wondering when to do so:

1. As soon as the CAPF is called?  No, bad idea, it can happen in PCHs.
2. Invalidating cache when the CAPF gets called, then contacting server/process "on demand" in the table function, during the first non-trivial call?  No, the CAPF can be called _even when nothing has changed_.
3. Invalidate the cache only if "things have changed" from the last call to CAPF, otherwise returning a saved table?  Essential, if PCH calls to the CAPF are possible.  
4.  In the table function, when the probe string differs from its initial value?  Maybe, for updating ongoing completion, e.g. when you delete from `foo` to `fo`.

**Comment by minad** [comment]
> I agree that a timer isn't ideal. I do wish there were an explicit separation of concerns between "check if you can complete here" and "build a table that can provide completions here". It's a bit fussy, but not too terrible to cache for future calls and invalidate only if anything has changed. But really they are quite distinct operations.

I don't see the point. If you want this distinction, implement it in your table. If the table is called for the first time, perform the initialization. Note that the predicate only calls the Capf but not the table. So in other words, we already have the distinction.

> When you have to perform expensive candidate lookup, contacting a server or process, you're left wondering when to do so:

The answer is easy. Always do it in the table. Your answer (4) is correct. The remaining question is how to make the capf setup fast enough, ideally by avoiding communication with the server.

**Comment by jdtsmith** [comment]
> I don't see the point. 

The point is that CAPF results must always be valid, including a collection/table, start/end, special plist elements, etc. This is because a CAPF never knows _why_ it is being called (unlike a table function).  So you have to carry this baggage around (and cache it to avoid poor performance) even when a UI like corfu simply wants to know "is this still a valid completion point?".  But yes, you can hack around this without too much fuss.

**Comment by minad** [comment]
But if you always initialize your Capf tables lazily there is no problem? I really fail to see the point. The only question is if you can quickly determine if completion is possible at a point. 

I think your problem is that you want to do heavy work when actual completion is demanded and only do light work (heuristic?) for the predicate checking. But even for this use case, there is a solution. You can use a nonexclusive completion table. Always only do the heuristic when returning the table. Then as soon as the table is called do the heavy work. If the heuristic was a false positive, then bail out with zero candidates. The next Capf will take over.

**Comment by jdtsmith** [comment]
> only do the heuristic in the Capf before returning the (not yet initialized) table

Yes I'm doing that exactly.  The issue is when to decide you will soon have more heavy work (i.e. when to dump the cache).  If the CAPF was only called on corfu auto, that's the perfect time to drop the cache and (lazily) recompute candidates.  If the CAPF can be called whenever, even for checking if at a valid spot, you must check to see what's changed, if anything, in buffer.  Probably this design, even if more convoluted, is more UI-proof anyway.
