### ISSUE TITLE
Initial and secondary delay for `corfu-echo-documentation`

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#131]
I noticed two small issues with `corfu-echo-documentation`:

1. Because of the logic `(or (eq corfu-echo-documentation t) corfu--echo-message)`, once a single candidate has had its documentation shown (usually the first), all further candidates have their docs shown immediately, without a time delay.  
2. The `:company-docsig` function may be expensive, e.g. contacting the server/process to learn the documentation.  In the present design, this function is called on every `corfu--update`.

Ideally, the `corfu-echo-documentation` timer would apply to all candidates, and the function would be called "just in time" to avoid unnecessary server contact.   That way you could scroll rapidly through a list of candidates without concern, pausing to see the docs for one, if interested.

**Comment by minad** [comment]
I had it like this before but didn't like it. But I am okay with a PR which adds this behavior. Currently `corfu-echo-documentation` is a float, just make it a pair of floats instead, the first for the initial delay, the second for the following delays.

**Comment by minad** [comment]
Discussion continues in #132.
