### ISSUE TITLE
Long signatures break the popup

### ISSUE THREAD

**Issue by deifactor** [minad/corfu#135]
![image](https://user-images.githubusercontent.com/30192992/155656250-661902a2-8d1d-493a-9b5a-6967b7cdc07f.png)

As you can see, the type signatures just march off the right-hand side of the screen, and that prevents any *other* type signatures from being viewed. Trimming it off is probably the only reasonable thing to do.

(Unrelated, but with the `tsls` language server, the signatures don't show up at all until I `M-h` them. They show up immediately with the `rust-analyzer` language server. Not sure what the difference here is.)

**Comment by minad** [comment]
Thank you for the report! Please let me know if the issue is fixed for you. In case you want to prevent the popup from growing so large adjust `corfu-max-width`.

**Comment by deifactor** [comment]
Yep, issue's fixed. Thanks for the quick turnaround!
