### ISSUE TITLE
How to make corfu + orderless work well with eglot + clangd

### ISSUE THREAD

**Issue by Eason0210** [minad/corfu#136]
Hi @minad 

I use `corfu `（latest commit）with `eglot `+ `clangd` backend, when the candidates include a space between signatures, `M-SPACE `will consider the space instead of the orderless separator.

When I input "cou", the candidates is as expected:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/47546452/155830159-f8a3c1cb-2d86-46fe-b576-d2e0f2f28ee4.png">

But when I press `M-SPACE`, the candidate will change as below:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/47546452/155830200-99d8b0b7-7f1e-4024-b61f-998b1a766b46.png">

Maybe the problem can be solved by customize orderless, but I don't know how to set it, do you have any suggestions?

Steps to reproduce:

1. install `corfu`, `orderless`, `eglot`, `yasnippet`, ` yasnippet-snippets`, [clangd](https://clangd.llvm.org/installation)
2. referred configurations:
```
(use-package corfu
  :demand t
  :custom
  (corfu-auto t)
  :init
  (corfu-global-mode))

(use-package orderless
  :demand t
  :config
  (setq completion-styles '(orderless partial-completion)
        completion-category-defaults nil
        completion-category-overrides '((file (styles . (partial-completion))))))

(use-package yasnippet
  :diminish yas-minor-mode
  :hook (prog-mode . yas-minor-mode)
  :config
  (yas-reload-all))

(use-package yasnippet-snippets
  :defer t
  :after yasnippet)

(use-package eglot
  :defer t
  :config
  (setq read-process-output-max (* 1024 1024))
  (push :documentHighlightProvider eglot-ignored-server-capabilities))

```
3. open a cpp file `test.cpp`
4.  `M-x eglot`
5. iput codes as pictures above

Emacs version and platform: 
```
In GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin21.3.0, NS appkit-2113.30 Version 12.2.1 (Build 21D62))
 of 2022-02-21 built on MacBook
Repository revision: 69c3ae29692e031296ef0ef4f56808dba4c6c27d
Repository branch: master
Windowing system distributor 'Apple', version 10.3.2113
System Description:  macOS 12.2.1

Configured using:
 'configure --with-native-compilation --with-xwidgets'

```

**Comment by minad** [comment]
I assume the problem is that Eglot overwrites the completion style. Orderless is not used here.

See https://github.com/joaotavora/eglot/blob/bd6a1cccfe9c0f724772f846d1f4a9300f40f88f/eglot.el#L321-L323
