### ISSUE TITLE
Missing `corfu-quit-at-boundary` = `nil` functionality with new `corfu-insert-separator`

### ISSUE THREAD

**Issue by krisbalintona** [minad/corfu#139]
This issue was brought up in [this Reddit thread](https://www.reddit.com/r/emacs/comments/t38kkh/comment/hytmcpg/?utm_source=share&utm_medium=web2x&context=3). It regards the deprecation of `corfu-quit-at-boundary`, particularly its `nil` behavior.

That's fair. Can you open an issue at corfu on this? Minad and I discussed whether to more fully emulate the old corfu-quit-at-boundary = nil approach. These are better defaults for people who use corfu-auto (which seems to be most).

I personally invoke `corfu` manually, that is, I have `corfu-auto` set to `nil`. This means that, although the move to `corfu-insert-separator` is helpful for those who set this to `t`, which may be most, it can be a regression in functionality for users in my situation.

The reason is the following: `orderless` dispatchers whose predicates are symbols such as `,` forces `corfu` to quit if used with the first component.  For instance, I have the following `orderless` dispatcher (written by Protesilaos):
```
  (defun orderless--strict-*-initialism (component &optional anchored)
    "Match a COMPONENT as a strict initialism, optionally ANCHORED.
The characters in COMPONENT must occur in the candidate in that
order at the beginning of subsequent words comprised of letters.
Only non-letters can be in between the words that start with the
initials.

If ANCHORED is `start' require that the first initial appear in
the first word of the candidate.  If ANCHORED is `both' require
that the first and last initials appear in the first and last
words of the candidate, respectively."
    (orderless--separated-by
     '(seq (zero-or-more alpha) word-end (zero-or-more (not alpha)))
     (cl-loop for char across component collect `(seq word-start ,char))
     (when anchored '(seq (group buffer-start) (zero-or-more (not alpha))))
     (when (eq anchored 'both)
       '(seq (zero-or-more alpha) word-end (zero-or-more (not alpha)) eol))))

  (defun orderless-strict-initialism (component)
    "Match a COMPONENT as a strict initialism.
This means the characters in COMPONENT must occur in the
candidate in that order at the beginning of subsequent words
comprised of letters.  Only non-letters can be in between the
words that start with the initials."
    (orderless--strict-*-initialism component))
  
  (defun prot-orderless-strict-initialism-dispatcher (pattern _index _total)
    "Leading initialism  dispatcher using the comma suffix.
It matches PATTERN _INDEX and _TOTAL according to how Orderless
parses its input."
    (when (string-suffix-p "," pattern)
      `(orderless-strict-initialism . ,(substring pattern 0 -1))))
```
If I try to use this dispatcher with the first `orderless` component, `corfu` will quit. The only way to work around this is to insert `corfu-separator` first then go back and add the dispatcher character. Here is [a demonstrative GIF](https://gfycat.com/elementaryunrulybarnowl). Notice how, near the end, I have to move the point backward after inserting a space (my `corfu-separator`).

**Comment by minad** [comment]
Thanks! @jdtsmith already opened #138 and corfu-quit-at-boundary has been added back. See #138 for more details - the completion prefix is a bit special due to how the capf determines if it can complete at the given point.

**Comment by jdtsmith** [comment]
Thanks @krisbalintona.  I got a bit ahead of you, but would be good if you can test the restored quit-at-boundary behavior and make sure it works as you'd anticipate.

**Comment by krisbalintona** [comment]
> Thanks @krisbalintona. I got a bit ahead of you, but would be good if you can test the restored quit-at-boundary behavior and make sure it works as you'd anticipate.

Yes! It works exactly as intended while still incorporating the user-side benefits of a `corfu-auto` = `t` workflow.
