### ISSUE TITLE
Corfu exits if there are no longer any matches, this is not typo-friendly

### ISSUE THREAD

**Issue by oantolin** [minad/corfu#14]
If you are in a Corfu session and type something that causes no candidates to match any more you get kicked out of the session. I'd prefer a little more tolerance, since I often make typos. Note that minibuffer completion is much more forgiving.

**Comment by minad** [comment]
Yes, I am aware. See [Caveats](https://github.com/minad/corfu#caveats) "Completion is terminated if there are no matches. Add optional confirmation?" and the [branch "confirmation"](https://github.com/minad/corfu/tree/confirmation).

**Comment by minad** [comment]
The downside of adding confirmation is that it will prevent you from just typing away. So I am unsure of this. Usually you argue against confirmation :wink:

**Comment by oantolin** [comment]
I don't argue against confirmation! I even have some actions like deleting a buffer or deleting a file require confirmation by default in Embark, and I keep that default in my personal configuration. I like that I need to press RET when I'm done in the minibuffer and wouldn't call it "confirmation".

**Comment by minad** [comment]
I just updated the "confirmation" branch and rebased it on top of the main branch. You may want to give it another try.

**Comment by oantolin** [comment]
> You may want to give it another try.

I'll try it, but it will be my first try of that branch, not "another try".

**Comment by minad** [comment]
I meant "another try" relative to your current try of the main branch.

**Comment by oantolin** [comment]
Works great, thanks! You even made the default value `"(No match)"`! I thought you were going to add the variable but make the default be `nil`.

**Comment by minad** [comment]
Yes, I actually like this too. Your comment just made me push it over the edge :smile:

**Comment by jdtsmith** [comment]
I like typo forgiveness, and it's essential for regexps (which won't match until complete), but with orderless this leaves "no match" hanging all the time; see #42.
