### ISSUE TITLE
Performance is bad when typing in magit commit buffer

### ISSUE THREAD

**Issue by zilongshanren** [minad/corfu#140]
Here is a screenshot:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/785541/156560934-8b2dbbd3-8aa9-4b31-a68c-8a2d270d1940.png">

when switching to company-mode and the company-backend is also dabbrev which feels more smooth.

**Comment by minad** [comment]
Try cape-dabbrev-check-other-buffers=nil. This is not a Corfu issue. But one could try to implement a more efficient Dabbrev backend in Cape.

**Comment by zilongshanren** [comment]
Thanks, after changing auto delay to a larger value, the problem is solved.
