### ISSUE TITLE
No separator between the candidate string and its annotation

### ISSUE THREAD

**Issue by galeo** [minad/corfu#143]
As shown in the screenshot below, there is no separator between the candidate string and annotation. Should a space be added to separate the two parts as shown in the second screenshot? 

![157842721-1ed50f2d-09ba-46c0-a2fb-42b3d8d79695](https://user-images.githubusercontent.com/1025559/157842973-639443b7-c837-4dbe-813c-67a59721cabf.png)

![Screen Shot 2022-03-11 at 5 52 32 PM](https://user-images.githubusercontent.com/1025559/157843999-1fbf08d0-5de7-41b7-a337-10f6e99da8a6.png)

**Comment by minad** [comment]
Which annotation function is this? The default completion UI also doesn't add a separator. The annotation functions usually add separators themselves.

**Comment by galeo** [comment]
> Which annotation function is this?

No annotation function is used. This is the default display. 



> The annotation functions usually add separators themselves.

I will learn more about this.

Thanks.

**Comment by minad** [comment]
If there are annotations then an annotation function is used here. Is this python?

**Comment by galeo** [comment]
> Is this python?

Yes. This completion backend is [company-jedi](https://github.com/emacsorphanage/company-jedi) which is used as a Capf via `cape-company-to-capf`.

> If there are annotations then an annotation function is used here.

Yes. Its annotation function returns the annotation string directly without adding a prefix space. Should this case be handled in the completion frontend?

**Comment by minad** [comment]
No the annotation function itself should add a space.
