### ISSUE TITLE
corfu-auto but always show menu when single-suggestion?

### ISSUE THREAD

**Issue by unhammer** [minad/corfu#144]
In company-mode, if I wait for the auto delay and there's a single suggestion it just shows that suggestion without actually using it until I hit tab, so I can safely keep typing if I e.g. don't notice it before I've typed a few more chars:
![bilde](https://user-images.githubusercontent.com/56868/158975780-ea63a01a-49b4-4b7e-9fae-743f59b2629b.png)

Is there a way to do this with corfu-auto? I don't care if the suggestion shows below or to the right of the word, it's just that the current corfu-auto leads me to type things like "REMOVEOV" (where the middle chars were inserted by corfu).

**Comment by minad** [comment]
Corfu doesn't auto insert like you describe. Maybe your version is outdated?

**Comment by unhammer** [comment]
Oh, I was using dabbrev-completion as completion-at-point-function but I see there is a separate package "cape" which defines dabbrev stuff, I guess I should've used that. That seems to not do this, so I'll close this :)

**Comment by minad** [comment]
You can use the `dabbrev-completion` *command* with Corfu, but not as completion-at-point-*function*. It is not a valid Capf. 

~~~
dabbrev-completion --[dabbrev completion table]--> completion-in-region --> Corfu

completion-at-point
   |
   |--> calls each of the completion-at-point-functions until success
   |
   `---[completion table from successful completion-at-point-function]--> completion-in-region --> Corfu
~~~

**Comment by unhammer** [comment]
OK, thank you for the explanation =D
