### ISSUE TITLE
Corfu-narrow: Kind-Narrowing

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#147]
Got the idea from a post requesting this for company. It would be interesting to make it possible to narrow candidates by kind using a key binding or even with a small prompt. So like consult-narrow, with user-configured setup, wrapping (or setting) the predicate.  I would definitely use this to switch the display of functions vs. variables, for example.

**Comment by minad** [comment]
Doesn't sound like a bad idea. It is quite easy to implement this by adjusting the completion predicate. However I see a number of practical problems:

* company-kind is defined by the backend, the set of kinds seems seems unrestricted.
* There are too many possible kinds.
* I doubt that the feature is very useful. It is nice to have for exploration, but I doubt it would pull its weight.

I don't want to blow up Corfu with more such features. The main feature of Corfu is that it is simple, easy to configure, easy to add to a configuration. I'd rather like to move out certain features, e.g., `corfu-show-location` and `corfu-show-documentation`. We could added narrowing as an extension. For now I added your proposal to the extension wishlish (#103). 

Anyway we don't have to take the lead here. The situation is like this: Company is defining its extensions the way it wants it and even adds them to core. I don't think Corfu will take off any time soon. If you look at the gh code search, company-mode is very widely used while nearly nobody uses corfu-mode.
