### ISSUE TITLE
Completion overlay and folded outline headings (including Org)

### ISSUE THREAD

**Issue by gusbrs** [minad/corfu#15]
Hi @minad, this is a follow-up on an exchange at Reddit.  Since you fixed everything I even mentioned there, I took it upon myself to bring you something else.  ;-)

It seems the completion overlays of `corfu` and outline folded headings (including Org's) are a little at each other's elbows.  I collected a couple of cases, for Org and outline-minor.

In the case of Org mode, if the completion popup stretches over a folded header, it is revealed.

This is the situation immediately before calling `completion-at-point`:

![Screenshot from 2021-04-27 16-43-39](https://user-images.githubusercontent.com/19410606/116304672-34951900-a779-11eb-8adb-73bbe301fac5.png)

Calling `completion-at-point` results in:

![Screenshot from 2021-04-27 16-44-07](https://user-images.githubusercontent.com/19410606/116304628-29da8400-a779-11eb-848b-e9f33da02445.png)

For `outline-minor-mode` the previous folded heading is also revealed but, additionally the folded header breaks `corfu`'s popup alignment.

This is the situation immediately before calling `completion-at-point`:

![Screenshot from 2021-04-27 16-51-12](https://user-images.githubusercontent.com/19410606/116304610-21824900-a779-11eb-9088-d018fd22665c.png)

Calling `completion-at-point` results in:

![Screenshot from 2021-04-27 16-51-44](https://user-images.githubusercontent.com/19410606/116304596-1c24fe80-a779-11eb-9f8c-572dc5d9446f.png)

And, again, thanks for the great package!

**Comment by minad** [comment]
Yes, invisible lines are not handled well by the overlay popup. There is also #10. I think I've somehow given up on overlays by now. I don't think it is possible to implement a really robust solution with overlays (this issue and #10 can be fixed for sure, but it is all a hassle). I think I will try to implement a solution based on child-frames. As a consequence Corfu will not work on the terminal.

**Comment by jaor** [comment]
On Tue, Apr 27 2021, Daniel Mendler wrote:

> Yes, invisible lines are not handled well by the overlay popup. There
> is also #10. I think I've somehow given up on overlays by now. I don't
> think it is possible to implement a really robust solution with
> overlays (this issue and #10 can be fixed for sure, but it is all a
> hassle).

Just out of curiousity: do you know what does company use for its
pop-ups?  They seem to be quite robust and free from this kind of
problems (which i've also noticed using corfu daily).  I assume they're
not child-frames, since they work too in the terminal, if i'm not
mistaken.

**Comment by gusbrs** [comment]
Another benchmark of interest here might be `ivy-overlay`. And there is a lot of similarity of purpose between it and `corfu`. I don't mean by it that its looks are good, quite the contrary.  But for some reason, abo-abo took a sort of steamroller solution and the overlay from `ivy-overlay` is made to open full whole lines, instead of being placed over the buffer's content.  I bet we are seeing some of these reasons in these reports.

**Comment by minad** [comment]
Yes, Company uses its own overlay-based implementation and it works around all those issues. This is all possible, but it is a hassle and honestly I am a bit tired of messing with overlays for popups. This is simply a broken way of solving the problem. The proper solution would be to handle this in the display engine directly. There should not be a problem to reserve a rectangular text area and display some text there. Basically there should be a 'rectangle properties for overlays.

**Comment by minad** [comment]
I decided to not spend more time on improving the overlay code. For me it works reasonably well except for some of the  scenarios mentioned here (https://github.com/minad/corfu/commit/fef837718bc138b2ad6844f588a6e51eefae5726).

**Comment by gusbrs** [comment]
I understand. Thanks for the stab at it. And, as I've said you, I'll be watching with interest how `corfu` evolves.
