### ISSUE TITLE
Annotations are not aligned correctly for variable pitch faces

### ISSUE THREAD

**Issue by minad** [minad/corfu#150]
See https://github.com/minad/corfu/issues/148#issuecomment-1081837377

![image](https://user-images.githubusercontent.com/50754/160619441-7afc2cec-5c49-4561-95a7-d51774d4153c.png)

**Comment by jdtsmith** [comment]
Interestingly the kind-icon SVGs are all the same width by design, but "text" based icons are indeed also not aligned using variable width fonts:

![image](https://user-images.githubusercontent.com/93749/160635487-537655c6-f927-4993-87d8-17ed5d4cef42.png)

You can also see the candidate and in-buffer text are not precisely aligned, since the width of "two characters" for the icons are not matched to 2 chars in the buffer. 

The Emacs facility for measuring the pixel-precise display width of a piece of text is fairly heavy (requiring an actual window with the text displayed in it).  I had some early prototypes working but concluded it wasn't worth it.  One simple possibility is to just give up on right-alignment of the suffix when the face is variable pitch.

**Comment by minad** [comment]
> The Emacs facility for measuring the pixel-precise display width of a piece of text is fairly heavy (requiring an actual window with the text displayed in it). I had some early prototypes working but concluded it wasn't worth it.

Yes, but I expect that the situation will improve. In Emacs 29 the new vtable (variable pitch table) package was introduced which also has to measure pixel width of each table cell. We can use the approach from there. If it turns out that this leads to performance issues we may even see changes in the rendering infrastructure which help in making these measurements cheaper. 

> One simple possibility is to just give up on right-alignment of the suffix when the face is variable pitch.

This would be my current suggestion for everyone hitting this issue. Just don't use right alignment if the font in the popup has variable pitch.

**Comment by Dima-369** [comment]
For me this works to align annotations in variable pitch fonts in Emacs 29:

I modify the `(setq suffix (propertize suffix 'face 'corfu-annotations))` statement as seen below:

```emacs-lisp
(defun dima-corfu--affixate (cands)
  "Annotate CANDS with annotation function.

Patches:
- align annotations via :display-to"
  (setq cands
        (if-let (aff (or (corfu--metadata-get 'affixation-function)
                         (plist-get corfu--extra :affixation-function)))
            (cl-loop for cand in cands collect (list cand "" ""))
          (if-let (ann (or (corfu--metadata-get 'annotation-function)
                           (plist-get corfu--extra :annotation-function)))
              (cl-loop for cand in cands collect
                       (let ((suffix (or (funcall ann cand) "")))
                         ;; The default completion UI adds the
                         ;; `completions-annotations' face if no other faces are
                         ;; present. We use a custom `corfu-annotations' face to
                         ;; allow further styling which fits better for popups.
                         (unless (text-property-not-all 0 (length suffix) 'face nil suffix)
                           (setq suffix
                                 (propertize
                                  (concat
                                   (propertize " " 'display
                                               `(space :align-to
                                                  (- right
                                                     ,(/ (string-pixel-width suffix)
                                                         (frame-char-width)
                                                         1.0))))
                                   suffix)
                                  'face 'corfu-annotations)))
                         (list cand "" suffix)))
            (cl-loop for cand in cands collect (list cand "" "")))))
  (let* ((dep (plist-get corfu--extra :company-deprecated))
         (completion-extra-properties corfu--extra)
         (mf (run-hook-with-args-until-success 'corfu-margin-formatters corfu--metadata)))
    (cl-loop for x in cands for (c . _) = x do
             (when mf
               (setf (cadr x) (funcall mf c)))
             (when (and dep (funcall dep c))
               (setcar x (setq c (substring c)))
               (add-face-text-property 0 (length c) 'corfu-deprecated 'append c)))
    (cons mf cands)))

(advice-add #'corfu--affixate :override #'dima-corfu--affixate)
```

![image](https://user-images.githubusercontent.com/15002298/181207220-6cb7e8e0-304b-4765-b096-f89b880adc49.png)

![image](https://user-images.githubusercontent.com/15002298/181207248-b275cc5e-0ad0-4c6f-bf2e-7d0d1f1ce134.png)

I took this from https://github.com/seagle0128/doom-modeline/commit/1d400aa88372962be6dad80182c244df3fe6e00b and https://github.com/seagle0128/doom-modeline/commit/2ff72d794d6a7ed4c5c5ac8b0b314704424150bd.

The last commit adds the `string-pixel-width` function for older Emacs versions.

It's slower, of course, but it's really nice to be able to align the annotation.

**Comment by minad** [comment]
I don't plan to add pixel-based alignment soon. It does not seem to be a commonly requested feature and I consider the slowdown problematic. I tried to port back `string-pixel-width` via the Compat package, but this led to problems in multiple packages including the aforementioned doom-modeline.
