### ISSUE TITLE
corfu-insert behaviour when no selection

### ISSUE THREAD

**Issue by jsy1001** [minad/corfu#152]
I've noticed that `corfu-insert` (bound to RET by default) always inserts the first candidate, even when no candidate is selected (e.g. if `corfu-preselect-first` is nil). Is this the intended behaviour? If yes, I'm confused about the purpose of the `corfu-preselect-first` setting -- what is gained by setting it to nil?

The context for my question is that I'm trying to prevent corfu from inserting candidates when I'm typing lists. This obviously involves typing RET at the end of each list item, and I don't want to insert a candidate unless I've manually selected one. The solutions I've thought of are to disable `corfu-auto` (but then I wouldn't know if there were completions available) or to rebind `corfu-insert` to a different key.

Thanks in advance for your help.

**Comment by minad** [comment]
The behavior was there mostly for backward compatibility. Let's try the simpler behavior now, where RET just quits if no candidate is selected. Feedback on the behavior is welcome. But it is hard to find a behavior which fits anyone. By simplifying the behavior we at least make the whole thing easier to understand and more hackable.

**Comment by jsy1001** [comment]
Thank you. That was amazingly fast work!
