### ISSUE TITLE
How to display menu instead of auto-complete single candidate ?

### ISSUE THREAD

**Issue by IrrenWirr** [minad/corfu#155]
Rationale:
I use corfu with manual and orderless completion and do a lot of exploratory completion (typing words and trying completion with the hope of finding something interesting). But it gets annoying to have to delete the completion of a `long-odd-name-used-by-a-candidate-I-won't-use' when I only wanted to check the completions of `odd' in case something useful turns up)

Question:
How do I get the completion menu instead of the default behavior (that inserts the match without asking) when only one candidate for completion is available ?

**Comment by minad** [comment]
First you probably want to set `completion-cycle-threshold=nil` to ensure that no cycling happens. The behavior to complete single candidates is implemented in `corfu--in-region`, see:

https://github.com/minad/corfu/blob/193233fb54287a72ae9b825e0dc8cde4d88135cf/corfu.el#L1091-L1097

There is no way to turn this off currently. One could add an option to make this tunable but I am hesitant to add customization options for all kinds of special behaviors. I think turning off completion of single candidates won't be often requested. Therefore it is better if you take the `corfu--in-region` function, patch it to your liking and add the patched function to your Emacs configuration.

**Comment by IrrenWirr** [comment]
The decisive code was just a few lines above. 

https://github.com/minad/corfu/blob/193233fb54287a72ae9b825e0dc8cde4d88135cf/corfu.el#L1088-L1089

For posterity, my patch was :

```elisp
(el-patch-let (($complete
                (unless (equal str newstr)
                  (completion--replace beg end (concat newstr))))
               ($goto (goto-char (+ beg newpt))))
  (el-patch-remove $complete
                   $goto)
  (el-patch-add (if (= total 1)
                    (corfu--setup)
                  (progn $complete
                         $goto))))
```

**Comment by minad** [comment]
Nice, that's the first time I see el-patch in action! :+1:
