### ISSUE TITLE
Corfu in LSP mode ignores suffix

### ISSUE THREAD

**Issue by zhenhua-wang** [minad/corfu#156]
When completing in the middle of a text in LSP mode, Corfu would only consider the text preceding the cursor. 

<img width="298" alt="Screen Shot 2022-04-19 at 4 28 55 PM" src="https://user-images.githubusercontent.com/11971417/164104971-fd74d33a-a5fb-4f9f-a892-b8eed4ec3bbb.png">

As a result, if I do corfu-insert, I would get duplicate text (In this case, I will get "num_interationsinterations" instead of "num_interations"). Do you happen to know what cause this problem? Thanks.

PS. I've tested with the same language server ([python-lsp-server](https://github.com/python-lsp/python-lsp-server)), Corfu works normally in Eglot.

**Comment by minad** [comment]
This behavior depends probably on the lsp-mode backend which only considers the input up to `(point)`. See https://github.com/emacs-lsp/lsp-mode/blob/b2a2e1aea502b4d07028606a91b1afd12ec22a8b/lsp-completion.el#L501-L503 where the end boundary of the symbol is set to `(point)`. Please ask on the lsp-mode issue tracker about this. 

(See also https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-mode for details regarding the lsp-mode configuration. You may want to tweak the completion styles, e.g., try Orderless to tune the filtering behavior.)
