### ISSUE TITLE
[Question] integration with flyspell-correct

### ISSUE THREAD

**Issue by david-vicente** [minad/corfu#158]
Hi.
I don't know if this is should be a corfu issue or cape issue (or a flyspell-correct one...) but is it possible to use corfu as a frontend for flyspell-correct?

Thanks!

**Comment by minad** [comment]
No, this is not possible. Typo correction and completion are quite different.

**Comment by eflanigan00** [comment]
@minad I would like to re-evaluate this request.

https://github.com/d12frosted/flyspell-correct/issues/113

flyspell-correct provides the list of potential corrections. Corfu would display those in the popup completion framework. I don't know the details of the code but I would love to see this. That way I can completely ditch the popup package use 100% use cofu :)

**Comment by eflanigan00** [comment]
@minad also happy to provide a 1 time sponsorship if you are able to solve this.
