### ISSUE TITLE
"C-n/C-p" bindings and eshell

### ISSUE THREAD

**Issue by gusbrs** [minad/corfu#16]
This has a simple description, and is a matter of thinking it over.

`corfu` covers the bindings of `C-n` and `C-p` by remapping them in `corfu-map`, respectively to `next-line` and `previous-line` (plus the arrow keys).  It makes plenty sense, of course.

However, `eshell` binds something else there, namely `eshell-next-input` and `eshell-previous-input` (I'm not sure if this binding requires module `esh-hist` to be enabled or not, it is a common module though and is enabled by default).  This means `C-n`/`C-p` won't give expected results in `eshell`: instead of navigating through candidates we end up leaving the completion session and, on top of that, `eshell` replaces current input completely by the next/previous element from history.

I'm not sure if binding directly `C-n` and `C-p` is to be considered too intrusive.  But this is the current situation for these bindings in `eshell`.

**Comment by minad** [comment]
Thanks for the reports! Yes, I consider binding `C-n` and `C-p` too intrusive, but you can easily bind the keys yourself in `vertico-map`. Closing as wontfix.
