### ISSUE TITLE
Bug: part of the completion popup is blocked

### ISSUE THREAD

**Issue by drshapeless** [minad/corfu#161]
I am using corfu with eglot and gopls. The machine is using Artix Linux, Emacs version 29.0.50.

Part of the popup is blocked by mysterious overlay, when I input more characters or choose other candidates using C-n to refresh the completion popup, it returns to normal.

I was using EXWM, but I have tested with other WM, the issue persists. I have eliminated all other factors by using emacs -Q and only loaded corfu, eglot and go, the same thing occurred.

Here's my corfu config.
```
(leaf corfu
  :require t
  :config
  (setq corfu-auto t
        corfu-quit-no-match 'separator
        corfu-auto-prefix 1
        corfu-auto-delay 0
        corfu-min-width 80
        corfu-max-width corfu-min-width
        corfu-count 14
        corfu-scroll-margin 4
        corfu-cycle nil
        corfu-preselect-first t
        corfu-echo-documentation t)
  (global-corfu-mode))

;; Corfu for eglot.
(setq completion-category-overrides '((eglot (styles orderless))))

(load "extensions/corfu-history")
(corfu-history-mode)
(add-to-list 'savehist-additional-variables 'corfu-history)
```
eglot
```
(leaf eglot
  :require t
  :hook
  ((c-mode-hook c++-mode-hook objc-mode-hook swift-mode-hook python-mode-hook js-mode-hook go-mode-hook sql-mode-hook dart-mode-hook) . eglot-ensure)
  (eglot-ensure . flymake)
  :bind
  (:eglot-mode-map
   ("C-c e r" . eglot-reconnect)
   ("C-c e f" . eglot-code-action-quickfix))
  :config
  ;; The automatic header insertion by clangd is cancer.
  (add-to-list 'eglot-server-programs
               '(c-mode . ("clangd" "--header-insertion=never")))
  (add-to-list 'eglot-server-programs
               '(c++-mode . ("clangd" "--header-insertion=never")))
  (add-to-list 'eglot-server-programs
               '(swift-mode . ("sourcekit-lsp")))
  (add-to-list 'eglot-server-programs
               '(sql-mode . ("sqls")))
  (add-to-list 'eglot-server-programs
               '(dart-mode . ("dart" "language-server"))))

(setq js-indent-level 2)
(setq compile-command "make")

;; Find the nearest parent go.mod as the project root.
(require 'project)

(defun project-find-go-module (dir)
  (when-let ((root (locate-dominating-file dir "go.mod")))
    (cons 'go-module root)))

(cl-defmethod project-root ((project (head go-module)))
  (cdr project))

(add-hook 'project-find-functions #'project-find-go-module)

;; gopls config.
(setq-default eglot-workspace-configuration
              '((:gopls .
                        ((staticcheck . t)
                         (matcher . "CaseSensitive")))))

(defun eglot-format-buffer-on-save ()
  (add-hook 'before-save-hook #'eglot-format-buffer -10 t))
(add-hook 'go-mode-hook #'eglot-format-buffer-on-save)
```
Here are some photos. I cannot use any screenshot application, because corfu will returns to normal if I press any key, sorry for my low quality iPhone image.
![IMG_1003](https://user-images.githubusercontent.com/66210497/166204087-b4e89103-999b-40b8-8397-14f56f247774.jpg)
![IMG_1004](https://user-images.githubusercontent.com/66210497/166204101-0f9c1af2-af15-4055-971c-4b16773fdc32.jpg)

**Comment by minad** [comment]
Is this pgtk? The bug you observed here is a child frame redisplay bug. There is nothing I can do about this in Corfu. It happens only very very rarely on my setup.

If you manage to create a reproducible configuration with emacs -Q then you can submit the bug report upstream via report-emacs-bug. But for this you have to cut down your configuration more. Do you see this with Corfu only on emacs -Q in an elisp mode buffer (scratch for example). Do you see this on Emacs 28? Emacs 29 doesn't exist, your current version information is meaningless. Furthermore it may depend on your GUI backend (X, pgtk, gtk, mltif, lucid, windows, haiku, ...).

**Comment by drshapeless** [comment]
I am using x11, gtk and the latest emacs.
This situation does not happen except in gopls. It is fine with elisp and other lsp, e.g. clangd, pyright. 

Thank you for your reply. The issue was solved by switching to an earlier version of Emacs.
