### ISSUE TITLE
How to prevent trigger corfu popup when  the input is number

### ISSUE THREAD

**Issue by Eason0210** [minad/corfu#162]
Hi minad,

When I just input number, will get a candidate as the picture below, it is a little annoying.
is it possible to prevent it to trigger auto complete when the input is start with number?

<img width="983" alt="image" src="https://user-images.githubusercontent.com/47546452/166215144-cc825e13-77eb-46da-a111-eaa83f6d4d72.png">

my config:

```emacs-lisp
(use-package corfu
  :demand t
  :custom
  (corfu-auto t)
  (corfu-min-width 80)
  (corfu-max-width corfu-min-width)
  (corfu-auto-delay 0.1)
  :bind (:map corfu-map
              ([tab] . smarter-tab-to-complete)
              ("TAB" . smarter-tab-to-complete)
              ("C-d" . corfu-info-documentation)
              ("M-." . corfu-info-location))
  :init
  (global-corfu-mode))

(use-package orderless
  :demand t
  :config
  (setq completion-styles '(orderless basic)
        completion-category-overrides '((file (styles basic partial-completion)))))
```

Environment:
macOS 12.3.1 
Emacs 29.0.50
corfu: https://github.com/minad/corfu/commit/71adaf1
https://github.com/oantolin/orderless/commit/75eeae2

**Comment by minad** [comment]
You could try a modified completion style which backs out for number-only input. You can write wrappers around orderless-try-completion and orderless-all-completions. But the underlying issue is that use-package generates these ugly symbol names here.

**Comment by Eason0210** [comment]
>  But the underlying issue is that use-package generates these ugly symbol names here.

👍  Thanks for your advice.  
These warning variables can be suppressed by the following setting, now everything works well 😄   :
```emacs-lisp
  (setq use-package-expand-minimally t)
```
