### ISSUE TITLE
corfu-auto takes too long to appear in some contexts

### ISSUE THREAD

**Issue by tgolsson** [minad/corfu#163]
Hello!

Recently I noticed that corfu sometimes takes significant amount of time to appear - over a second. Explicitly summoning corfu with tab is close to instant. It seems to be dependent on what I write. 

If I'm in my `init.el`, for example right before the first line of my config below; and write `*`, it'll suggest `:bind*`, `:bind-keymap*` and `:EXPORT_HUGO_SECTION*` instantly. This seems like dabbrev suggestions. If I write `(corf)` it'll suggest a bunch of `corfu` functions after a couple of seconds. 

Unfortunately I cannot tell when exactly this issue started occuring, as I still use company-mode for my daily driver modes due to familiarity. 

I'm using the following configuration:

```elisp
(use-package corfu
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-auto-delay 0.0)
  (corfu-auto-prefix 1)
  (corfu-commit-predicate nil)
  (corfu-quit-at-boundary t)
  (corfu-quit-no-match t)
  (corfu-echo-documentation t)

  :hook ((emacs-lisp-mode . corfu-mode)
         (shell-mode . corfu-mode)
         (eshell-mode . corfu-mode)))
```

**Comment by minad** [comment]
Can you provide a minimal recipe which I can try to reproduce with emacs -Q? Can you try to reduce the amount of adjustments to Corfu customization variables to narrow down the issue? Do it step by step. Note that the corfu-auto-delay=0 setting puts high load on the completion backend and the garbage collector. Furthermore the combination with a minimal prefix length of 1 generates many candidates. Therefore you probably observe garbage collector pauses or it takes a long time to generate the candidates. The behavior you observe is likely not a bug but a consequence of these inefficient configuration settings.

**Comment by tgolsson** [comment]
Hello @minad!

Per your suggestion I did change the settings to a delay of 0.3 and a minimal prefix length of 3 and it has no impact for the `(corf|` case. I *can* reproduce the ineffieciency if I input an number. For example; if I write `(corfu-auto-prefix |)` typing a 2 will stutter the editor but immediately display valid candidates. That's still much faster than the first case.

I went with the -Q route and narrowed it down to this setup:

```

**Comment by minad** [comment]
Okay, then I guess we solved the issue. I recommend to not use flyspell-prog-mode and flyspell in general since it seems to be very inefficient. The time taken by flyspell is unfortunately not available for other features like Corfu.

**Comment by tgolsson** [comment]
Yeah; it's a shame but I guess I have to sacrifice it. I'm curious whether it'd be possible to implement something like Auto-Complete has to advice the flyspell post-command hook: [ac-flyspell-workaround](https://github.com/auto-complete/auto-complete/blob/57cb8f2ee32dff17ea1b4431fe5920272aa38d72/auto-complete.el#L1928).

**Comment by minad** [comment]
I won't implement workarounds in Corfu but you can put something in your config.
