### ISSUE TITLE
Example of async backend?

### ISSUE THREAD

**Issue by aaronjensen** [minad/corfu#164]
Hi, I'm looking into moving over to corfu from company. 

The primary backend I use is this: https://github.com/aaronjensen/company-rg/blob/master/company-rg.el which just uses `rg` to search for matching completions. It's an async backend. It appears to work with `cape-company-to-capf`, which is great, but I was looking to port it to a `capf`. 

Do you by chance have any simple examples of async completion functions? 

I could reverse engineer and simplify `cape-company-to-capf`, but I'd prefer to start with something more rudimentary that doesn't have the rest of the complexity of handling all company backends built in to it. 

Thanks!

**Comment by minad** [comment]
Corfu interrupts backends with while-no-input. If your backend is interruptible you don't have to do anything special. You have to ensure only that no internal state is corrupted by the interrupts. See also cape-capf-noninterruptible.

There is no advantage of asynchronous capfs or company backends as long as you don't execute them in parallel. See company--multi-backend-adapter and the documentation in the Cape project cape-super-capf, cape-company-to-capf.

On the Cape issue tracker there was a discussion about an async Capf API. I wrote a prototype wrapper which transformed an asynchronous non-interruptible capf to a synchronous interruptible capf.

However for your rg backend I would just make sure that it is interruptible. What does your backend do precisely? Does this answer help?
