### ISSUE TITLE
Corfu and evil repeat

### ISSUE THREAD

**Issue by aaronjensen** [minad/corfu#168]
Hi, I don't know if you use evil or not or if you'd prefer I close this and open the issue on Evil, but I've noticed that evil-repeat (the `.` key) does not work with corfu auto completion (I use a tab'n'go style).

Specifically, if I do something like this:

```
foo
foo
foo
```

Point on first foo, `cw`, `ba` tab to select bar, go down to `foo` and hit `.`, only `ba` will be included. 

In company, this was first reported here: https://github.com/company-mode/company-mode/issues/15
And addressed with: https://github.com/emacs-evil/evil/blob/master/evil-integration.el#L212-L230

I can't make it work with corfu with any combination of evil repeat specifications.

cc @tomdl89 in case has any ideas or would like me to move this to evil's repo.

Thanks all.

![CleanShot 2022-05-14 at 00 08 11](https://user-images.githubusercontent.com/8588/168410176-ad4485cc-2366-4968-85c1-07991d3de831.gif)

**Comment by minad** [comment]
I don't use evil, mainly because I am not fond of having two layered sets of keybindings and because of all these integration issues. But I am not religious about modal or non-modal bindings ;)

I opened
https://github.com/emacs-evil/evil-collection/issues/552 at some point. Hopefully the issue can be fixed there. I am not familiar with the inner workings of evil, therefore I suggest you move the issue to the evil or evil-collection tracker.

**Comment by aaronjensen** [comment]
Thank you, much appreciated.

**Comment by aaronjensen** [comment]
@minad could you say a little bit about how corfu works? When I do `corfu-next`, how is the buffer updated with the next candidate?

**Comment by minad** [comment]
There is no update, it is just an overlay. The update happens in the very end.

**Comment by aaronjensen** [comment]
Ah, what causes the update at the very end? In the case of tab and go is it a precmd on whatever I use to do something else?

**Comment by minad** [comment]
corfu-insert inserts the selected candidate.

**Comment by aaronjensen** [comment]
For tab-n-go `corfu-insert` is never invoked, but `corfu--insert` is.

 I think that this is the secret:

https://github.com/company-mode/company-mode/blob/master/company-tng.el#L123-L127

Company unreads the command that would exit company and changes the command to `company-complete-selection`. I can play with doing the same.

**Comment by minad** [comment]
Right, for tabngo insertion happens in the pre-command-hook.
