### ISSUE TITLE
Complete common part of candidates

### ISSUE THREAD

**Issue by bertulli** [minad/corfu#170]
Hi!

First of all, thank you for your work. I am setting up vertico and Corfu, and I like them both.
However, there's something I miss from Company, that is the possibility to complete the common part of the candidates (`company-complete-common`). With vertico it's easy, there's `minibuffer-complete` (which is not part of vertico, but alas). I couldn't find in docstrings if it's possible to do the same also for Corfu. Is there a function to do so? Or should I define a custom function, taking inspiration from Company? Fwiw, I can submit a PR if it works.

Thank you for your time

**Comment by minad** [comment]
Thanks! If you set corfu-preselect-first=nil and use the basic completion style then corfu-complete will complete the common part. As soon as you select a candidate, common prefix completion does not make much sense anymore in my opinion. Does this solve your question?

**Comment by minad** [comment]
The answer lies in the code of `corfu-complete`:

https://github.com/minad/corfu/blob/1481b67871e6ab8b143017de2fd8151cd65f24e7/corfu.el#L990-L1009

Please read that function.

In principle I am open to changes in behavior. But it is not easy to make those without affecting the overall behavior. So any kind of proposal which changes the behavior must be well-thought out and take all the configuration variables into account, such that we get somewhat reasonable interactions between the features.

**Comment by bertulli** [comment]
Thanks, you gave me a lot to work on. I managed to write a custom function:
```emacs-lisp
(defun corfu-custom-try-complete ()
  "Try to complete current input as much as possible"
  (interactive)
  (pcase-let ((`(,beg ,end ,table ,pred) completion-in-region--data))
      ;; Try to complete the current input string
      (let* ((pt (max 0 (- (point) beg)))
             (str (buffer-substring-no-properties beg end))
             (metadata (completion-metadata (substring str 0 pt) table pred)))
        (pcase (completion-try-completion str table pred pt metadata)
          ('t
           (goto-char end)
           (corfu--done str 'finished))
          (`(,newstr . ,newpt)
           (unless (equal str newstr)
             ;; bug#55205: completion--replace removes properties!
             (completion--replace beg end (concat newstr)))
           (goto-char (+ beg newpt))
           ;; Exit with status 'finished if input is a valid match
           ;; and no further completion is possible.
           (when (and (test-completion newstr table pred)
                      (not (consp (completion-try-completion
                                   newstr table pred newpt
                                   (completion-metadata newstr table pred)))))
             (corfu--done newstr 'finished)))))))

(define-key corfu-map (kbd "TAB") #'corfu-custom-try-complete)
(define-key corfu-map (kbd "<tab>") #'corfu-custom-try-complete)
```
I only take `corfu-complete`, removed the `if` condition and the then branch, so to keep only the "complete-common" part. It worked in my `*scratch*` buffer, but not in other ones. Then I added it in my `init.el`, restarted Emacs, and now it doesn't work in any buffer. I don't know why.
Anyway, you were super kind! Thanks a lot! 👍

**Comment by liuyinz** [comment]
@bertulli , I have a simpler one
```elisp

  (defun corfu-complete-common-or-next ()
    "Complete common prefix or go to next candidate."
    (interactive)
    (if (= corfu--total 1)
        (progn
          (corfu--goto 1)
          (corfu-insert))
      (let* ((str (car corfu--input))
             (pt (cdr corfu--input))
             (common (try-completion str corfu--candidates)))
        (if (and (stringp common)
                 (not (string= str common)))
            (insert (substring common pt))
          (corfu-next)))))
  (put 'corfu-complete-common-or-next 'completion-predicate #'ignore)

```

**Comment by bertulli** [comment]
Thanks! Yes, your solution better leverages the Corfu variables, so I think it should be preferable. Actually, my function doesn't cycle the completions, but since your code is very clean it's just a matter of commenting/uncommenting the call to `(corfu-next)`!

There's just one thing I don't get it. Do you mind explaining what the second to last line (`(put ...)`) does? I'm sorry, but I'm still learning Elisp and I haven't encountered propnames.

**Comment by liuyinz** [comment]
https://github.com/minad/corfu/blob/a1638df651872acb9a8df0c97704bf321e85735a/corfu.el#L1277-L1281
Hiding `corfu-complete-common-or-next` from the M-x commandline so that you would not call it accidentally from minibuffer.

for the `with-` problem, maybe it's your emacs version or some personal setting problem. I could complete to `with-` at once.

Printing str and common's values to helping debug. Such as

```elisp
      (let* ((str (car corfu--input))
             (pt (cdr corfu--input))
             (common (try-completion str corfu--candidates)))

         (message "str: %s, common: %s" str common)

        (if (and (stringp common)
                 (not (string= str common)))
            (insert (substring common pt))
          (corfu-next)))))
```

**Comment by TxGVNN** [comment]
Thank you guys, I'm looking for this feature when migrate from company to corfu.
But I see the `corfu-complete-common-or-next` doesn't work with file completion.
So I try to copy some code from `corfu-complete` to mix with `corfu-complete-common-or-next` and it works. 
I actually don't understand too much how it works. You can see I use 2 common variable to see which var is longer. 

```emacs-lisp
(defun corfu-complete-common-or-next ()
    "Complete common prefix or go to next candidate."
    (interactive)
    (if (= corfu--total 1)
        (progn
          (corfu--goto 1)
          (corfu-insert))
      (let* ((str (car corfu--input))
             (pt (cdr corfu--input)))
        (pcase-let ((`(,beg ,end ,table ,pred) completion-in-region--data))
          (let* ((metadata (completion-metadata (substring str 0 pt) table pred))
                 (common (car (completion-try-completion str table pred pt metadata)))
                 (common2 (try-completion str corfu--candidates)))
            (message "DEBUG: common=%s, common2=%s, metadata=%s" common common2 metadata)
            (if (> (length common2) (length common))
                (setq common common2))
            (if (and (stringp common)
                     (not (string= str common)))
                (insert (substring common pt))))))))
```

**Comment by liuyinz** [comment]
It really doesn't work for filepath completion after I tested, maybe I will fix it when i'm not busy a few days later.
