### ISSUE TITLE
Configuration of `corfu-indexed-mode`

### ISSUE THREAD

**Issue by allenryb** [minad/corfu#172]
After I enable `corfu-indexed-mode`, the indexes show in the left of child frame. 
May I ask how to quick choose the candidate by these indexes?

In `company-mode`, I can use Meta key with numbers. 

Sorry for this junior question. 
But I can't find any solution after searching google.

**Comment by minad** [comment]
The indexed mode uses numeric prefix arguments, e.g., C-0 RET or C-1 TAB.
