### ISSUE TITLE
LSP: corfu displays only one candidate for overloaded methods

### ISSUE THREAD

**Issue by oqwo** [minad/corfu#173]
Hello, 

First things first, thank you for this wonderful package. I really like how it manages to stay focused on completion and emacs integration.

I'm using eglot + JDTLS and corfu, and sometimes there are missing candidates. Today, I realized that when there are several overloaded candidate methods, only one of them is proposed.

Looking at `corfu--recompute-candidates`, I noticed a suspicious (?) call to `delete-consecutive-dups`
Without this call, overloaded methods do get displayed. 

There is probably a reason for deleting dups, but if this issue is really a bug, at least it may be a starting point for further investigations.

Thanks again!

**Comment by oqwo** [comment]
Sorry, I didn't mentionned it but I did cross check against the default completion UI and company. Both propose all the overloaded candidates.

**Comment by minad** [comment]
* ://github.com/emacs-mirror/emacs/blob/5f6e64a316adc6cd6ea140453718160643c6cd93/lisp/minibuffer.el#L1559
* https://github.com/emacs-mirror/emacs/blob/5f6e64a316adc6cd6ea140453718160643c6cd93/lisp/minibuffer.el#L2041

**Comment by minad** [comment]
Why do you want to see duplicates anyway? To see the function signatures of the overloaded methods? Why does it make a difference for you when completing? Since the strings are equal the end result will be equal.

**Comment by minad** [comment]
Also company deletes duplicates: https://github.com/company-mode/company-mode/blob/783287526a791590bea4f9a23992c2bfebdb4c8d/company.el#L1491

However it turns out that it only deletes them when the annotations are different! This is quite inefficient!

**Comment by oqwo** [comment]
Thanks for your time and your explanations.

There is no doubt you know a lot more about the emacs internals than I do (I don't). I can just provide a screenshot of what happens on my side with emacs 28.1 without any customization + eglot master when I press C-M-i :

![image](https://user-images.githubusercontent.com/86486877/170124502-80888395-cd4f-4477-843f-0c7672adfd65.png)

Otherwise, you're right about me thinking that showing the signature of overloaded methods could be a plus. When working on some code base with poor/non-existent documentation, seeing the signature up-front can provide very useful hints. 
Moreover, while I don't care, eglot provide candidate signature expansion through yasnippet. You must select the appropriate candidate first, though

But maybe all of this is out the scope corfu targets?

In this case, while using corfu + eglot, the fact that only one candidate _with its signature_ is displayed is puzzling the first time you stumble upon it (where are the others?). I'd rather have no signature at all:

![image](https://user-images.githubusercontent.com/86486877/170125032-fa265fb7-8eb7-4c43-ba42-e6cd962dd4cf.png)

Is there a way to customize corfu in order to discard all the data associated with the candidate? Or do you consider this need should be addessed by LPS clients like eglot?

Well, it seems I got you irritated whereas it wasn't my intention. I should just have started this (non)issue by sticking to the description of my problem and provide more context. Sorry again

**Comment by minad** [comment]
There is no need to be sorry. You just found the issue that duplicate candidates in Emacs completions are not well defined at all. And I don't know how to resolve it. Either way (deleting or not deleting) is wrong in some sense. The way Company treats duplicate deletion is not acceptable in my opinion (checking strings, annotations and kinds). We could replace delete-consecutive-dups with a function which only delete consecutive dups if they are equal including properties. Would that work for your use case with duplicates and snippet expansion?

**Comment by minad** [comment]
But then the main problem is this - as soon as you have duplicates the strings are not unique anymore with respect to equal. When the string is inserted into the buffer the text properties are lost and the string uses its identity.

Therefore the only logical conclusion is this:

- Backends should not return duplicate candidates if they want to meaningfully distinguish them
- Frontends do not have to delete duplicates since backends

**Comment by oqwo** [comment]
Well, it's strange, the default completion seems to work (eglot + JDTLS), 

Otherwise, I kind of get your point. If I understand:

- clangd provides completion the right way when there are duplicate candidates:

```
[server-reply] (id:14) Wed May 25 10:01:52 2022:
(:id 14 :jsonrpc "2.0" :result
     (:isIncomplete :json-false :items
		    [(:detail "[2 overloads]" :filterText "overload" :insertText "overload($0)" :insertTextFormat 2 :kind 3 :label " overload(…)" :score 1.0087924003601074 :sortText "407edfe4overload" :textEdit
			      (:newText "overload($0)" :range
					(:end
					 (:character 6 :line 4)
					 :start
					 (:character 2 :line 4))))]))
```

- Whereas JDTLS seems to be in the wrong:

```
[server-reply] (id:5) Wed May 25 10:12:11 2022:
(:jsonrpc "2.0" :id 5 :result
	  (:isIncomplete :json-false :items
			 [(:label "overload(int i) : void" :kind 2 :detail "Test.overload(int i) : void" :sortText "999999035" :insertText "overload" :insertTextFormat 2 :textEdit
				  (:range
				   (:start
				    (:line 5 :character 12)
				    :end
				    (:line 5 :character 16))
				   :newText "overload(${1:i});")
				  :data
				  (:decl_signature "LTest;" :signature "(I)V" :name "overload" :pid "0" :rid "0" :uri "file:///home/oqwo/Temp/TEST/Test.java"))
			  (:label "overload() : void" :kind 2 :detail "Test.overload() : void" :sortText "999999035" :insertText "overload" :insertTextFormat 2 :textEdit
				  (:range
				   (:start
				    (:line 5 :character 12)
				    :end
				    (:line 5 :character 16))
				   :newText "overload();")
				  :data
				  (:decl_signature "LTest;" :signature "()V" :name "overload" :pid "1" :rid "0" :uri "file:///home/oqwo/Temp/TEST/Test.java"))]))
```

That kind of unfortunate, because all the data is there. However, I understand the issue shouldn't be pushed on corfu

**Comment by Artawower** [comment]
Tell me please, is there workaround or solution for this problem? I can't complete function which defined in different packages, sometime it's very annoying, sorry for ping (i checked linked issues, but didn't find solution)
