### ISSUE TITLE
Best way to modify completion-style on the fly?

### ISSUE THREAD

**Issue by jojojames** [minad/corfu#177]
I have something like this for company.

```
(defun j-company-capf-with-og-completion-styles (f &rest args)
  "Set `completion-styles' to be the default Emacs `completion-styles'
while `company-capf' runs."
  (let ((completion-styles
         (if (or (length< company-prefix
                          (if (and
                               (fboundp 'native-comp-available-p)
                               (native-comp-available-p))
                              3
                            3)))
             '(basic partial-completion emacs22)
           '(fussy basic))))
    (apply f args)))

(advice-add 'company-capf :around 'j-company-capf-with-og-completion-styles)

```

To trigger a different completion-style dependent on the length of the current prefix. What would be the best approach to replicate this functionality? Thanks!

**Comment by minad** [comment]
You could try to bind completion-styles around corfu--update. But there are also scattered calls to completion-try-completion so this is unlikely to work well.

The assumption of Corfu or the default completion style machinery is that the completion style can be changed depending on the completion category and not depending on the UI.

But it may be necessary to support a mechanism to override this locally in Corfu.

I am considering two options:

- Set the completion style buffer locally in the buffer you are completing in.
- Bind the completion styles variables explicitly in Corfu at various places.

Using buffer local variables doesn't sound like a bad approach in my opinion and it should already work well. The only downside is that your dynamic switcher wouldn't work. But a better approach would be to define a combined completion style for this case anyway which switches based on the STRING argument. See https://github.com/oantolin/orderless/issues/111#issuecomment-1098763842 for an example orderless+basic which mixes two styles. You could do the same and select one or the other based on the length of STRING.

**Comment by jojojames** [comment]
Just realized that advice above is really "switching" off of two things, the prefix length and the completion context (e.g. we're doing in buffer completion with company). I don't really want to delay fuzzy matching for minibuffer completion but only for inbuffer completion. I'm guessing the completion-style can easily switch based off the length of STR but what would you recommend for hooking off the context of the completion?

**Comment by minad** [comment]
By context do you mean buffer? If you set the completion-styles only locally in the buffer you are completing in it will be used only there. The minibuffer will still use the global default value of completion-styles.

You can add a hook to the corfu-mode-hook where you do setq-local completion-styles...

**Comment by jojojames** [comment]
I see, that will work for me, thanks!
