### ISSUE TITLE
Question: Is there a way to hook into when the currently selected candidate changes?

### ISSUE THREAD

**Issue by anonimitoraf** [minad/corfu#179]
(I don't see a "discussion tab" for this repo hence why I'm raising an "Issue")

Use case: I want to execute the [completionItem/resolve](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem_resolve) whenever the currently selected (i.e. completion isn't finalized yet) candidate is changed

Thanks!

**Comment by minad** [comment]
You could try to advise `corfu--insert`, see https://github.com/minad/corfu/blob/8b9d37413639a1c92f0c74f1230bddbe45e79c59/corfu.el#L1015. Another alternative would be to install your own `post-command-hook` where you check `corfu--candidates` and `corfu--index`. Does this answer help you?
