### ISSUE TITLE
corfu map being overridden by local keymap

### ISSUE THREAD

**Issue by JonatanSahar** [minad/corfu#180]
Hi,
I have C-j and C-k bound in corfu-map to move up and down the candidate list. I also have the same binding in insert mode (using evil..) to move between lines. When I try to move between candidates in the completion popup I get the wrong functionality…

I have this in my config, but it doesn’t seem to do the job:

  (advice-add 'corfu--setup :after 'evil-normalize-keymaps)
  (advice-add 'corfu--teardown :after 'evil-normalize-keymaps)
  (evil-make-overriding-map corfu-map)

Any ideas would be appreciated :)

**Comment by minad** [comment]
I am using Emacs in holy mode as was taught by St. Ignucius ;) Therefore I am not really able to help you with that. There have been a few evil issues before on this tracker, maybe you can find a solution there.

evil-collection also supports Corfu. The maintainer of evil-collection @jojojames recently started to experiment with Corfu, so you can probably get some help there. There were even some recent Corfu-related commits: https://github.com/emacs-evil/evil-collection/commit/e1bbf13194e06c435cd3328b2b431c9c46fbbf40

**Comment by JonatanSahar** [comment]
Thanks! I'll check it out.
