### ISSUE TITLE
Can I get all lsp completions with eglot and corfu?

### ISSUE THREAD

**Issue by ParetoOptimalDev** [minad/corfu#181]
I followed [Configuring corfu for eglot](https://github.com/minad/corfu/wiki#configuring-corfu-for-eglot) and it's a pretty nice result with haskell-language-server:

![2022-05-30_11-14](https://user-images.githubusercontent.com/93023868/171030298-60b9e9d7-a2d9-4909-8305-dc533c572d7e.png)

However (and I almost missed it) it seems not all candidates for the `Data.Vector` module are there.

<details>
<summary>Full list of identifiers I'd expect from Data.Vector for reference</summary>

```
(Data.Vector.!) :: Data.Vector.Vector a -> Int -> a
(Data.Vector.!?) :: Data.Vector.Vector a -> Int -> Maybe a
(Data.Vector.++) ::
(Data.Vector.//) ::
type Data.Vector.Vector :: * -> *
data Data.Vector.Vector a
Data.Vector.accum ::
Data.Vector.accumulate ::
Data.Vector.accumulate_ ::
Data.Vector.all :: (a -> Bool) -> Data.Vector.Vector a -> Bool
Data.Vector.and :: Data.Vector.Vector Bool -> Bool
Data.Vector.any :: (a -> Bool) -> Data.Vector.Vector a -> Bool
Data.Vector.backpermute ::
Data.Vector.break ::
Data.Vector.catMaybes ::
Data.Vector.cmpBy ::
Data.Vector.concat ::
Data.Vector.concatMap ::
Data.Vector.cons ::
Data.Vector.constructN ::
Data.Vector.constructrN ::
Data.Vector.copy ::
Data.Vector.create ::
Data.Vector.createT ::
Data.Vector.drop ::
Data.Vector.dropWhile ::
Data.Vector.elem :: Eq a => a -> Data.Vector.Vector a -> Bool
Data.Vector.elemIndex ::
Data.Vector.elemIndices ::
Data.Vector.empty :: Data.Vector.Vector a
Data.Vector.enumFromN :: Num a => a -> Int -> Data.Vector.Vector a
Data.Vector.enumFromStepN ::
Data.Vector.enumFromThenTo ::
Data.Vector.enumFromTo :: Enum a => a -> a -> Data.Vector.Vector a
Data.Vector.eqBy ::
Data.Vector.filter ::
Data.Vector.filterM ::
Data.Vector.find :: (a -> Bool) -> Data.Vector.Vector a -> Maybe a
Data.Vector.findIndex ::
Data.Vector.findIndices ::
Data.Vector.fold1M ::
Data.Vector.fold1M' ::
Data.Vector.fold1M'_ ::
Data.Vector.fold1M_ ::
Data.Vector.foldM ::
Data.Vector.foldM' ::
Data.Vector.foldM'_ ::
Data.Vector.foldM_ ::
Data.Vector.foldMap ::
Data.Vector.foldMap' ::
Data.Vector.foldl ::
Data.Vector.foldl' ::
Data.Vector.foldl1 :: (a -> a -> a) -> Data.Vector.Vector a -> a
Data.Vector.foldl1' :: (a -> a -> a) -> Data.Vector.Vector a -> a
Data.Vector.foldr ::
Data.Vector.foldr' ::
Data.Vector.foldr1 :: (a -> a -> a) -> Data.Vector.Vector a -> a
Data.Vector.foldr1' :: (a -> a -> a) -> Data.Vector.Vector a -> a
Data.Vector.forM ::
Data.Vector.forM_ ::
Data.Vector.force :: Data.Vector.Vector a -> Data.Vector.Vector a
Data.Vector.freeze ::
Data.Vector.fromArray ::
Data.Vector.fromList :: [a] -> Data.Vector.Vector a
Data.Vector.fromListN :: Int -> [a] -> Data.Vector.Vector a
Data.Vector.generate :: Int -> (Int -> a) -> Data.Vector.Vector a
Data.Vector.generateM ::
Data.Vector.head :: Data.Vector.Vector a -> a
Data.Vector.headM :: Monad m => Data.Vector.Vector a -> m a
Data.Vector.ifilter ::
Data.Vector.ifoldM ::
Data.Vector.ifoldM' ::
Data.Vector.ifoldM'_ ::
Data.Vector.ifoldM_ ::
Data.Vector.ifoldl ::
Data.Vector.ifoldl' ::
Data.Vector.ifoldr ::
Data.Vector.ifoldr' ::
Data.Vector.iforM ::
Data.Vector.iforM_ ::
Data.Vector.imap ::
Data.Vector.imapM ::
Data.Vector.imapM_ ::
Data.Vector.imapMaybe ::
Data.Vector.imapMaybeM ::
Data.Vector.indexM :: Monad m => Data.Vector.Vector a -> Int -> m a
Data.Vector.indexed ::
Data.Vector.init :: Data.Vector.Vector a -> Data.Vector.Vector a
Data.Vector.iscanl ::
Data.Vector.iscanl' ::
Data.Vector.iscanr ::
Data.Vector.iscanr' ::
Data.Vector.iterateN ::
Data.Vector.iterateNM ::
Data.Vector.izipWith ::
Data.Vector.izipWith3 ::
Data.Vector.izipWith4 ::
Data.Vector.izipWith5 ::
Data.Vector.izipWith6 ::
Data.Vector.izipWithM ::
Data.Vector.izipWithM_ ::
Data.Vector.last :: Data.Vector.Vector a -> a
Data.Vector.lastM :: Monad m => Data.Vector.Vector a -> m a
Data.Vector.length :: Data.Vector.Vector a -> Int
Data.Vector.map ::
Data.Vector.mapM ::
Data.Vector.mapM_ ::
Data.Vector.mapMaybe ::
Data.Vector.mapMaybeM ::
Data.Vector.maxIndex :: Ord a => Data.Vector.Vector a -> Int
Data.Vector.maxIndexBy ::
Data.Vector.maximum :: Ord a => Data.Vector.Vector a -> a
Data.Vector.maximumBy ::
Data.Vector.minIndex :: Ord a => Data.Vector.Vector a -> Int
Data.Vector.minIndexBy ::
Data.Vector.minimum :: Ord a => Data.Vector.Vector a -> a
Data.Vector.minimumBy ::
Data.Vector.modify ::
Data.Vector.notElem :: Eq a => a -> Data.Vector.Vector a -> Bool
Data.Vector.null :: Data.Vector.Vector a -> Bool
Data.Vector.or :: Data.Vector.Vector Bool -> Bool
Data.Vector.partition ::
Data.Vector.partitionWith ::
Data.Vector.postscanl ::
Data.Vector.postscanl' ::
Data.Vector.postscanr ::
Data.Vector.postscanr' ::
Data.Vector.prescanl ::
Data.Vector.prescanl' ::
Data.Vector.prescanr ::
Data.Vector.prescanr' ::
Data.Vector.product :: Num a => Data.Vector.Vector a -> a
Data.Vector.replicate :: Int -> a -> Data.Vector.Vector a
Data.Vector.replicateM ::
Data.Vector.reverse :: Data.Vector.Vector a -> Data.Vector.Vector a
Data.Vector.scanl ::
Data.Vector.scanl' ::
Data.Vector.scanl1 ::
Data.Vector.scanl1' ::
Data.Vector.scanr ::
Data.Vector.scanr' ::
Data.Vector.scanr1 ::
Data.Vector.scanr1' ::
Data.Vector.sequence ::
Data.Vector.sequence_ ::
Data.Vector.singleton :: a -> Data.Vector.Vector a
Data.Vector.slice ::
Data.Vector.snoc ::
Data.Vector.span ::
Data.Vector.splitAt ::
Data.Vector.sum :: Num a => Data.Vector.Vector a -> a
Data.Vector.tail :: Data.Vector.Vector a -> Data.Vector.Vector a
Data.Vector.take ::
Data.Vector.takeWhile ::
Data.Vector.thaw ::
Data.Vector.toArray ::
Data.Vector.toList :: Data.Vector.Vector a -> [a]
Data.Vector.uncons ::
Data.Vector.unfoldr ::
Data.Vector.unfoldrExactN ::
Data.Vector.unfoldrExactNM ::
Data.Vector.unfoldrM ::
Data.Vector.unfoldrN ::
Data.Vector.unfoldrNM ::
Data.Vector.uniq ::
Data.Vector.unsafeAccum ::
Data.Vector.unsafeAccumulate ::
Data.Vector.unsafeAccumulate_ ::
Data.Vector.unsafeBackpermute ::
Data.Vector.unsafeCopy ::
Data.Vector.unsafeDrop ::
Data.Vector.unsafeFreeze ::
Data.Vector.unsafeHead :: Data.Vector.Vector a -> a
Data.Vector.unsafeHeadM :: Monad m => Data.Vector.Vector a -> m a
Data.Vector.unsafeIndex :: Data.Vector.Vector a -> Int -> a
Data.Vector.unsafeIndexM ::
Data.Vector.unsafeInit ::
Data.Vector.unsafeLast :: Data.Vector.Vector a -> a
Data.Vector.unsafeLastM :: Monad m => Data.Vector.Vector a -> m a
Data.Vector.unsafeSlice ::
Data.Vector.unsafeTail ::
Data.Vector.unsafeTake ::
Data.Vector.unsafeThaw ::
Data.Vector.unsafeUpd ::
Data.Vector.unsafeUpdate ::
Data.Vector.unsafeUpdate_ ::
Data.Vector.unsnoc ::
Data.Vector.unstablePartition ::
Data.Vector.unzip ::
Data.Vector.unzip3 ::
Data.Vector.unzip4 ::
Data.Vector.unzip5 ::
Data.Vector.unzip6 ::
Data.Vector.update ::
Data.Vector.update_ ::
Data.Vector.zip ::
Data.Vector.zip3 ::
Data.Vector.zip4 ::
Data.Vector.zip5 ::
Data.Vector.zip6 ::
Data.Vector.zipWith ::
Data.Vector.zipWith3 ::
Data.Vector.zipWith4 ::
Data.Vector.zipWith5 ::
Data.Vector.zipWith6 ::
Data.Vector.zipWithM ::
Data.Vector.zipWithM_ ::
type role Data.Vector.MVector nominal representational
type Data.Vector.MVector :: * -> * -> *
data Data.Vector.MVector s a
Data.Vector.convert ::
```
</details>

Say I wanted `Data.Vector.accumulate_`, it seems that I have to first type not `V.` or `Data.Vector.` as I'd expect but also the proper first `corfu-auto-prefix` (default of 3) of what I want which here is not just `V.a` but `V.acc` before getting a list of candidates:

![2022-05-30_11-15](https://user-images.githubusercontent.com/93023868/171030832-8db21ad7-b7af-4229-999b-1503141a5bbb.png)

This would be find for my use case of "functions I know that I want help completing" but not for the "I know a piece of the function name but not necessarily anything else and want corfu and orderless to help discover it" use case.

Maybe this is a technical limitation of what happens when `.` is encountered? Or maybe (hopefully) there is a configurable length I can adjust that might give me all identifiers?

Related to that "help discover it use-case" I expected typing something like `umu _` to bring up `V.accumulate`... ah wait... that works kind of:

![2022-05-30_11-24](https://user-images.githubusercontent.com/93023868/171031363-becc7993-601f-4aa6-82f3-7259a0b01322.png)

The completion itself works, but isn't "qualified import aware". I'm guessing maybe this is a limitation of the language server? End result is I select the completion and then have to do a code action to fix it.

Another thing I thought would work is using orderless to search the annotations in keeping with the "everything is text philosphy" of emacs. So I expected `umu`:

![2022-05-30_11-25](https://user-images.githubusercontent.com/93023868/171031633-31a7ce7c-264a-4d30-a088-518dce6452f6.png)

When changed to `umu Vec` to match the annotation text and limit to the first two.

I realize there are some technical challenges and lots of discussion and hard work has went into this lsp support. So firstly, thanks for that :heart_eyes: 

Secondly, I tried to read through the existing discussions to understand if I could figure out my own solution but it wasn't clear to me:

- If it was possible
- If you think all or any of the things I'm trying to do should exist in corfu
- There was some simple way to adapt the lsp-mode examples (that may do this or some of this) to eglot

And it seemed best to create an issue and see what others have to say. Thanks for your time!

**Comment by minad** [comment]
You could try wrapping the eglot capf with `cape-capf-buster`:

~~~ elisp
(setq-local completion-at-point-functions
            (list (cape-capf-buster #'the-eglot-capf 'equal)))
~~~

See https://github.com/minad/cape#capf-buster---cache-busting for more details. Downside is that it will make completion slower. I hope this helps.

**Comment by minad** [comment]
Btw, @jdtsmith what do you use currently? lsp-mode or eglot?

**Comment by arkhan** [comment]
Hello @minad and @jdtsmith, I currently use eglot+corfu+cape and I have it like this in case it is of your interest:

``` emacs-lisp
(setup (:pkg (cape
              :host github
              :repo "minad/cape"))
  (:global "C-c p p" completion-at-point
           "C-c p d" dabbrev-completion
           "C-c p t" complete-tag
           "C-c p f" cape-file
           "C-c p k" cape-keyword
           "C-c p a" cape-abbrev
           "C-c p s" cape-ispell
           "C-c p w" cape-dict)
  (:option cape-dabbrev-check-other-buffers nil)
  (:load-after eglot
    (:with-hook eglot-managed-mode-hook
      (:hook (lambda ()
               (setq-local completion-at-point-functions (list
                                                          (cape-capf-buster
                                                           (cape-super-capf
                                                            (cape-company-to-capf #'company-yankpad)
                                                            #'eglot-completion-at-point
                                                            #'cape-ispell
                                                            #'cape-file
                                                            #'cape-dabbrev))))))))

  (add-to-list 'completion-at-point-functions (cape-capf-buster
                                               (cape-super-capf
                                                (cape-company-to-capf #'company-yankpad)
                                                #'cape-ispell
                                                #'cape-file
                                                #'cape-dabbrev))))
```

![image](https://user-images.githubusercontent.com/3141865/171033893-1a929ffe-37ba-47e2-b202-d8c4fb3dea63.png)

**Comment by minad** [comment]
@arkhan Looks like a quite sophisticated setup. You use a cache buster but you didn't specify `equal` as argument. Do you observe missing candidates? I think @ParetoOptimalDev's problem is that the lsp server is not asked often enough for new candidates and therefore we miss candidates here. If we figure out a solution which works in all cases we should also document the cache buster in the Corfu wiki.

**Comment by ParetoOptimalDev** [comment]
I also think this might be related to joaotavora/eglot#733.

**Comment by minad** [comment]
@ParetoOptimalDev I am not sure what your actual issue is in your setup, but the problem can be two fold.

- Candidates can get missing due to completion style filtering. You can try an alternative completion style in that case like `flex`. Or you could even write a completion style which does not filter at all (passthrough). If this is the issue it would be related to the issue 733 you mentioned.
- The lsp server doesn't deliver all candidates. lsp servers often limit the amount of returned candidates. In this case we have to ensure that the lsp server is asked more often. You can use the `cape-capf-buster` for that. For example if you use Company instead of Corfu, you will probably not observe the issue since Company does not cache the returned completion tables in the same way as Corfu.

**Comment by ParetoOptimalDev** [comment]
> I think @ParetoOptimalDev's problem is that the lsp server is not asked often enough for new candidates and therefore we miss candidates here. If we figure out a solution which works in all cases we should also document the cache buster in the Corfu wiki.

Yes, I've been reading eglot's completion-at-point and I believe the above closed PR is related by @jdtsmith. I'll have to try [their patch](https://github.com/joaotavora/eglot/pull/733/files#diff-d6c5a55ddb4dd8dca075c4e0d48c851460ead14c77f333c66b02ccc7d1c2aff0R2361).

**Comment by minad** [comment]
> Yes, I've been reading eglot's completion-at-point and I believe this is the case and the above closed PR is related by @jdtsmith. I'll have to try their patch.

I don't think this is the solution. Eglot uses `all-completions` correctly.

https://github.com/joaotavora/eglot/blob/aa50b4bb9e52d15472c7a4f9c6101506dfa4f8b4/eglot.el#L2592-L2600

The problem is rather the caching issue I mentioned in https://github.com/minad/corfu/issues/181#issuecomment-1141354413.

**Comment by ParetoOptimalDev** [comment]
> The problem is rather the caching issue I mentioned in https://github.com/minad/corfu/issues/181#issuecomment-1141354413.

I tried the solutions you listed, even all at once. I think the problem is that [Haskell language server defaults to 40 completions at once](https://github.com/haskell/haskell-language-server/blob/310e6a4683c40dc5d93ffaf12c45144dc8e079a4/hls-plugin-api/src/Ide/Plugin/Config.hs#L65).

**Comment by minad** [comment]
Yes exactly. The LSP server returns only a small set of candidates. If you use a short prefix this will not restrict the set of candidates sufficiently. The cape-capf-buster is needed to rerequest the candidates again if you add more input, if you make the filter prefix longer.

However nothing of this will help if you want to use Orderless-style completion. In order for this to work one has to increase the number of returned candidates.

**Comment by ParetoOptimalDev** [comment]
Success! Thanks for the help.

For my case of "use corfu to avoid looking up function names in documentation" a few hundred should be more than enough. I'll watch out for performance issues.

For future reference (I'll also add to wiki) here is how I configured the server using eglot:

```
(setq-default eglot-workspace-configuration
      '((haskell
	 (maxCompletions . 200))))
```

But you can use a `.dir-locals.el` (though I coudln't get it to work) something like:


```
((haskell-mode
  . ((eglot-workspace-configuration
      . ((:haskell . ((:maxCompletions 1))))))))
```

**Comment by jdtsmith** [comment]
I use eglot again.  That all-completions patch did get merged in btw (though the predicate function isn't correctly forwarded).  

Here's how I think about it:  the lsp server decides to provide "whatever candidates it wants" based on the buffer.  Some servers are quite conservative, and use prefix-matching.  Some are quite wild, and match pretty much anything.   If you are not getting "all the completions", check your Eglot events buffer to see if the server is even sending them.  If not, probably not much to be done unless there are server configs.  If it the server is sending them but the initial corfu popup doesn't display them, your completion style is trimming them out.  

I personally use the somewhat fancy orderless style below.  It works like this:

- When you have a new table (e.g. corfu just popped up) pass through _all_ results.  
- If you edit the input string, switch to flex in the first orderless component. 
- For other components, use normal orderless style. 

That seems to be the best compromise, as it leads to the least mismatch between say `some_th[lsp server consulted]ing` and `some_thing[lsp server consulted]`, but still allows you to have full super-fast orderless filtering.  I also use cape-capf-buster to get it to re-query the server during one completion session if the initial input is altered.  

```elisp
(defun my/orderless-dispatch-passthrough-first ()
    "Return a function for orderless dispatch.
Lets all matches through for 1st component, unless it has
changed, in which case flex is used."
    (let (last-table initial-pattern)
      (lambda (pattern index _total)
	(if-let (((eq index 0))
		 (table (caddr completion-in-region--data)))
	    (cond
	     ;; new table of results: save pattern and let all matches through
	     ((not (eq table last-table))
	      (setq last-table table
		    initial-pattern pattern)
	      "")			; empty string = all results
	     ;; Unchanged initial component pattern: let all matches through
	     ((and initial-pattern
		   (string-equal pattern initial-pattern))
	      "")
	     ;; Pattern has changed: fall back on flex matching for first
	     (t 'orderless-flex))))))

  (defun my/eglot-finalize ()
    (setf (alist-get 'styles
		     (alist-get 'eglot completion-category-defaults))
	  '(orderless))
    (make-local-variable 'orderless-style-dispatchers)
    (cl-pushnew (my/orderless-dispatch-passthrough-first)
		orderless-style-dispatchers)
    (setq-local completion-at-point-functions
		(cl-nsubst (cape-capf-buster #'eglot-completion-at-point)
			   'eglot-completion-at-point
			   completion-at-point-functions)))
```

adding the latter to `eglot-managed-mode-hook`.

**Comment by ParetoOptimalDev** [comment]
Still looking over @jdtsmith's config, but I added my findings above [to the wiki](https://github.com/minad/corfu/wiki#requesting-more-completions-from-your-lsp-server-with-eglot-workspace-configuration) since it's the simplest fix to address my current issue that others might also encounter.

**Comment by minad** [comment]
@jdtsmith Haha I like the crazy amount of flexibility of Orderless. But I'm most cases the simpler configuration as described in the Corfu wiki should do.

**Comment by Eason0210** [comment]
@ParetoOptimalDev  Thanks for add this to the wiki. I have the same issue.

And I can make it works with `.dir-locals.el` as below:

``` emacs-lisp
((haskell-mode
  . ((eglot-workspace-configuration
      . ((:haskell . (:maxCompletions 200)))))))
```
