### ISSUE TITLE
shell-mode + pcmpl-args: misaligned annotations

### ISSUE THREAD

**Issue by manuel-uberti** [minad/corfu#182]
First the relevant screenshot:

![Screenshot from 2022-05-31 08-28-46](https://user-images.githubusercontent.com/8199224/171107162-deb40f58-3aa1-4ede-a9f1-0b31678acb0f.png)
Then the recipe:

- emacs -Q
- M-x package-initialize
- `(setq tab-always-indent 'complete)`
- `(global-corfu-mode)`
- `(require 'pcmpl-args)`
- M-x shell
- `cd` into a Git-versioned directory
- `git che` <kbd>TAB</kbd>

Finally some details about my system:

- Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-05-31
- `emacs-repository-version`: 75bf80e2b136903525a54d6c53d69571e7b1332e
- Corfu: `corfu-0.25.0.20220525.211119`
- pcmpl-args: `pcmpl-args-0.1.3.0.20220510.145627`

**Comment by minad** [comment]
See https://github.com/JonWaltman/pcmpl-args.el/issues/20.
