### ISSUE TITLE
Don't show popup when buffer is read only

### ISSUE THREAD

**Issue by AkibAzmain** [minad/corfu#185]

**Comment by minad** [comment]
Corfu already barfs on read only buffers. What else do you mean?

**Comment by minad** [comment]
https://github.com/minad/corfu/blob/8b9d37413639a1c92f0c74f1230bddbe45e79c59/corfu.el#L1096

**Comment by AkibAzmain** [comment]
I mean automatic popup with `corfu-auto` set to `t`.

**Comment by minad** [comment]
And how can that happen? The auto popup is only triggered on self-insert-commands.

**Comment by minad** [comment]
Is this just about speeding up the pch and avoiding unnecessary work or is there an actual scenario where we trigger auto completion unintentionally?

**Comment by AkibAzmain** [comment]
> And how can that happen? The auto popup is only triggered on self-insert-commands.

Yes, its triggered by `self-insert-command`, even when that fails saying the buffer is read only.

**Comment by AkibAzmain** [comment]
The problem is mostly fixed, but doesn't take text properties into account (`barf-if-buffer-read-only` also ignores some text properties that `self-insert-command` checks).  Anyway, its good enough to use.  Thanks.

**Comment by minad** [comment]
Yes, I know. We could do a little bit better, but I consider Corfu and self-insert-commands in read-only buffers already as an edge case. I never triggered the Corfu popup in a read-only buffer accidentally, so I think we are mostly covered now.
