### ISSUE TITLE
Corfu doesn't complete correctly when used with lsp-mode and clangd

### ISSUE THREAD

**Issue by Ice-Cube69** [minad/corfu#187]
Corfu is not completing correctly, for example:
![image](https://user-images.githubusercontent.com/47600778/172188103-d2a9df5b-97ae-45d9-a5d9-9b36a1ecc909.png)
Same when using company:
![image](https://user-images.githubusercontent.com/47600778/172188257-c4ea4693-7a72-46be-9672-6216a40a6f21.png)

Relevant corfu config:
https://gitlab.com/binarydigitz01/dotfiles/-/blob/master/min-emacs-config/.config/emacs/emacs-init.org#L185

I am also using orderless, that might be interfering, but I'm not sure.

**Comment by minad** [comment]
Duplicate #176. Your lsp-mode package is probably outdated. Please upgrade everything to the newest version before reporting issues.

**Comment by Ice-Cube69** [comment]
I have upgraded all my packages, but I believe the issue still persists:
[https://imgur.com/a/FdykaUg](url)
Ignore the freeze, I believe that is a lsp mode issue

**Comment by minad** [comment]
@Ice-Cube69 The issue #196 should be gone. If your issue is unrelated, you can ask on the Lsp tracker about that, since it is an issue of the Lsp backend. Also please provide a minimal configuration for emacs -Q which can be used to reproduce the issue.

**Comment by Ice-Cube69** [comment]
Here's a minimal configuration:
```lisp
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(package-refresh-contents)

(unless (package-installed-p 'use-package)
   (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

(use-package corfu)
(global-corfu-mode)
(use-package lsp-mode)

(add-hook #'c++-mode-hook #'lsp)

(setq tab-always-indent 'complete)
```
