### ISSUE TITLE
Maybe a Performance Issue

### ISSUE THREAD

**Issue by drcxd** [minad/corfu#188]
Hi,

After switching to Corfu from Company, I frequently find that after I type several characters, Emacs will halt for more than 5 seconds. I can't type, can't move the cursor, can't do anything. During the halt, I could only `C-g` cancelling out the ongoing action, which I guess is related to completion, then the halt terminates immediately. If I just wait, then after the halt, the characters I typed during the halt will be displayed. The halt seldom happens after the completion list shows, but there are some cases. I am using auto completion.

This happens quite randomly. I tried to find some pattern but with no luck. I tried to switch between Corfu and Company back and forth and I can confirm that, in my environment, when using Corfu, the long halt frequently occurs, while using Company, there is no obvious (more than 1 second) halt. 

Any idea what is going on?

I am working on a project based on Unreal Engine, but I also confirmed that this situation happens when working on only the engine code.

**Comment by minad** [comment]
I don't know. It is with highly likelihood a misconfiguration on your side. You can try to collect a profile to check if there are some obvious performance bottlenecks. Generally Corfu shouldn't be slower than Company, usually it is slightly faster, since Corfu has some additional optimizations. But of course a problematic configuration could negate all kinds of potential advantages. In order to tell you more I need your minimal configurations of Company and Corfu.

**Comment by drcxd** [comment]
Here is the report generated by emacs built-in profiler. I executed `profiler-start`. The I kept typing in the buffer until the halt happened. Basically, I was copying some code in the same buffer. After the halt happened, I executed `profiler-stop` and `profiler-report`.

```
         731  80% - corfu--post-command
         730  80%  - corfu--update
         726  80%   - corfu--update-candidates
         723  79%    - corfu--recompute-candidates
         723  79%     - corfu--all-completions
         723  79%      - completion-all-completions
         723  79%       - apply
         723  79%        + #<compiled -0x187e8d863e1757aa>
           3   0%      redisplay
           3   0%     redisplay
           1   0%   - corfu--candidates-popup
           1   0%      corfu--popup-show
           1   0%  - corfu-quit
           1   0%   + completion-in-region-mode
         116  12% + ...
          29   3% + redisplay_internal (C function)
          17   1% - timer-event-handler
          17   1%  - apply
          17   1%   - corfu--auto-complete
          17   1%    - corfu--update
           5   0%     + corfu--update-candidates
           5   0%     + corfu-quit
           4   0%     + corfu--candidates-popup
           3   0%       redisplay
          12   1% - command-execute
          12   1%  - funcall-interactively
           8   0%   - corfu-insert
           8   0%    - corfu--insert
           8   0%     - corfu--done
           8   0%      + #<compiled -0x7aa2ac626036bae>
           4   0%   - self-insert-command
           2   0%    - tree-sitter--after-change
           2   0%       tree-sitter--do-parse
           1   0%   evil--jump-hook
```

My Corfu configuration:

```
(require-package 'corfu)
(global-corfu-mode)
(setq corfu-auto t
      corfu-cycle nil
      corfu-quit-at-boundary nil
      corfu-quit-no-match t
      corfu-preview-current nil)

(defun corfu-enable-in-minibuffer ()
  "Enable Corfu in the minibuffer if `completion-at-point' is bound."
  (when (where-is-internal #'completion-at-point (list (current-local-map)))
    (corfu-mode 1)))
(add-hook 'minibuffer-setup-hook #'corfu-enable-in-minibuffer)

(provide 'init-corfu)
```

```
(require-package 'corfu)
(require-package 'lsp-mode)

;; corfu completion setup
(setq lsp-completion-provider :none)
(defun corfu-lsp-setup ()
  (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
        '(orderless)))
(add-hook 'lsp-completion-mode-hook #'corfu-lsp-setup)

(provide 'init-corfu-lsp)
```

My Company configuration
```
(require-package 'company)
(add-hook 'after-init-hook 'global-company-mode)
(setq company-transformers '(company-sort-prefer-same-case-prefix))
(provide 'init-company)
```

I only enable Corfu or Company one at a time.

**Comment by BohongHuang** [comment]
The same issue occurs when I'm using lsp-mode and corfu recently, but everything works fine if I replace lsp-mode with eglot or corfu with company.

**Comment by minad** [comment]
Please report this on the lsp-mode issue tracker. It seems that completion just hangs in the lsp-mode backend.

**Comment by minad** [comment]
It could be that the lsp completion doesn't handle interrupts from Corfu gracefully and hangs up for that reason. In that case you could wrap the capf with `cape-capf-noninterruptible` from my Cape package.

**Comment by drcxd** [comment]
> It could be that the lsp-mode completion doesn't handle interrupts from Corfu gracefully and hangs up for that reason. In that case you could wrap the capf with `cape-capf-noninterruptible` from my Cape package.

How could I do that? Can you share some code? Yeah, I am an elisp idiot. I can only write something like `add-hook` or `setq`, this is out of my reach and I tried.

**Comment by minad** [comment]
This may do it:

~~~ elisp
(advice-add #'lsp-completion-at-point :around '#cape-wrap-noninterruptible)
~~~

However it would be much better if the lsp capf could be improved such that it is more robust and handles interrupts gracefully.

**Comment by drcxd** [comment]
> This may do it:
> 
> ```emacs-lisp
> (advice-add #'lsp-completion-at-point :around '#cape-wrap-noninterruptible)
> ```
> 
> However it would be much better if the lsp capf could be improved such that it is more robust and handles interrupts gracefully.

I tried
```
(setq lsp-completion-provider :none)
(defun corfu-lsp-setup ()
  (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
        '(orderless)))
(add-hook 'lsp-completion-mode-hook #'corfu-lsp-setup)

(advice-add #'lsp-completion-at-point :around '#cape-wrap-noninterruptible)
```
Emacs reported an error:
```
Invalid read syntax: #, 1, 0
```
If I put the advice-add statement in the setup function, the same error is reported.

**Comment by minad** [comment]
Just a typo. I corrected the comment above.

**Comment by minad** [comment]
@drcxd Do you still observe the issue with the advice mentioned in https://github.com/minad/corfu/issues/188#issuecomment-1148658471? If not, this would be an indication that the lsp-mode capf does not handle interrupts well.

**Comment by drcxd** [comment]
Since applying the advice, I have not observed the issue yet.

**Comment by meliache** [comment]
Question: Is this possibly a symptom of https://github.com/emacs-lsp/lsp-mode/issues/3607, as @c-alpha asked [here](https://github.com/emacs-lsp/lsp-mode/issues/3555#issuecomment-1195738369)? Then, it might worth trying the new patch provided by Minad [under the above issue](https://github.com/emacs-lsp/lsp-mode/issues/3607#issuecomment-1207211734). 

The queestion is whether I will still have to advice the patched `lsp-completion-at-point` with `cape-wrap-noninterruptible`, I hope (and expect) not, but let's see...

**Comment by justinbarclay** [comment]
I am running into this with JavaScript. Mainly, I noticed that this happens with JSX syntax `<, /` are the biggest offenders, but if I fat finger a `.` this also happens.

I'm trying out cape-wrap-non-interruptible, and it seems to resolve the situation. I only discovered this post this morning, so I haven't tested it thoroughly. Thanks for pointing out the work around @minad 😊

**Comment by minad** [comment]
@meliache @justinbarclay wrap-noninterruptible is still needed for lsp, even with my patch. Unfortunately the lsp-capf is broken in multiple ways. As an alternative you may want to try eglot.

**Comment by minad** [comment]
@justinbarclay Good to know that the Capf has been fixed. Now the issue is that the Capf must be interruptible, which I believe it is not currently. This means its state should not get corrupted when interrupts occur at arbitrary points. After interruption the Capf (and the returned completion table) should stay intact, such that it can be called again.
