### ISSUE TITLE
Default candidate

### ISSUE THREAD

**Issue by astoff** [minad/corfu#19]
After activating the Corfu popup and optionally typing some letters, `RET` and `C-n RET` do the same thing. This seems a bit inefficient, since `C-n RET` could as well select the second candidate.

Also — and perhaps this is silly, but still — the lack of a "current candidate" right after the popup is created urges me to press `C-n RET` instead of just `RET` to select the first one...

**Comment by minad** [comment]
> After activating the Corfu popup and optionally typing some letters, RET and C-n RET do the same thing. This seems a bit inefficient, since C-n RET could as well select the second candidate.

Maybe. I want to keep the current behavior. But it is easy enough to bind a custom command to `C-n` which skips the first candidate. Try to train your muscle memory ;)

> Also — and perhaps this is silly, but still — the lack of a "current candidate" right after the popup is created urges me to press C-n RET instead of just RET to select the first one...

This is hard to change. As soon as a candidate is selected, it will be shown as overlay over the input text. I am not sure I want to add another state where the current candidate is selected, but the prompt is still active. Note that when a candidate is selected and you enter something the completion is immediately quit.

**Comment by astoff** [comment]
Ah, I see: this is different from the minibuffer stuff in that you don't need to press RET to exit. Then indeed these ideas here don't make sense.

**Comment by minad** [comment]
Yes, the exiting criteria are relatively complicated. This aspect of completion in region is more complicated than for minibuffer completion. I tried to make it such that it will still feel reasonably natural for Selectrum or Vertico users.

https://github.com/minad/corfu/blob/3b58559a5fde194994d9a333ff8f048a3ca73398/corfu.el#L472-L511

https://github.com/minad/corfu/blob/3b58559a5fde194994d9a333ff8f048a3ca73398/corfu.el#L519-L524

https://github.com/minad/corfu/blob/3b58559a5fde194994d9a333ff8f048a3ca73398/corfu.el#L513-L516
