### ISSUE TITLE
Can I use cape backends when lsp-mode backend provide no completion?

### ISSUE THREAD

**Issue by drcxd** [minad/corfu#192]
```
(setq lsp-completion-provider :none)
```
I assume this disable all capfs for lsp-mode completion.

What I want is that I could use other capfs as alternative when lsp-mode does not provide any completion candidates. For example, when I am typing `./` in a comment block, I could get completion candidates from `cape-file`, when I am typing `Get` in a comment block, I could get completion candidates from `cape-dabbrev`. 

My desired behavior is working out of the box in `elisp-mode`. Could the same be done for `lsp-mode`?

**Comment by minad** [comment]
See https://github.com/emacs-lsp/lsp-mode/pull/3525.
