### ISSUE TITLE
`$1` comes whenever i enter completion

### ISSUE THREAD

**Issue by sofeepokhrel** [minad/corfu#194]
Hello ,

I'm using eglot with corfu . But i'm having problem in completion. Though completion shows  and i can enter and put the completed value. 
But at middle from nowhere it also adds `$1` 

For example

This is completing the completion
![image](https://user-images.githubusercontent.com/103311708/174364401-5703b907-6ab9-40dc-a918-2cc0949bc135.png)

and pressing enter this is result 
![image](https://user-images.githubusercontent.com/103311708/174366425-ea6ef94a-e023-42e1-91ba-fe8b910893c5.png)

This `$1` is added into `SignupComponent` in import. 
This not only applies to js but also all other languages and  internal completion.

how to solve it?

Thank you.

**Comment by minad** [comment]
The dollars are added by the :exit-function of the backend, in this case Eglot. This is out of control of Corfu. The issue may be fixed by installing yasnippet, see for example https://elixirforum.com/t/how-is-snippet-expansion-code-completion-supposed-to-work-in-emacs-with-eglot-elixir-ls/19685/5.
