### ISSUE TITLE
Corfu integration with evil-ex

### ISSUE THREAD

**Issue by adolfocorreia** [minad/corfu#195]
I have tried using Corfu in the minibuffer (using the `corfu-enable-in-minibuffer` function suggested in the README file) but it does not integrate well with evil-ex. For instance, after typing ':w' and 'TAB', Corfu correctly displays available evil-ex commands as expected. But after typing ':e ' (or ':edit ') and 'TAB', Corfu still displays commands and not the available files as expected.

Are there any tips or code snippets on how to integrate Corfu and evil-ex? Unfortunately I was not able to find any.

What I managed to find out is that in evil-ex.el (https://github.com/emacs-evil/evil/blob/master/evil-ex.el) there are different completion functions for commands (`evil-ex-command-completion-at-point`), files (`evil-ex-file-or-shell-command-completion-at-point`) and arguments (`evil-ex-argument-completion-at-point`) which AFAIU are used according to the context at point to provide the default context-aware evil-ex completion functionality. More generally, evil-ex offers the concept of argument handlers (`evil-ex-define-argument-type`) which I guess could be used to better integrate with Corfu.

Alternatively, it might be interesting to integrate evil-ex completion with Vertico (since we are on the minibuffer), but I was not able to find anything on that front either.

**Comment by minad** [comment]
My experience with Evil is quite limited. The Evil completion functions you mentioned should work with Corfu in principle. I suggest to open an issue on the Evil issue tracker if there are issues with the functions. Backend issues are usually not issues of Corfu itself. 

As for Evil integration of Vertico/Corfu, this is out of scope of these projects, but you may want to look into evil-collection which comes with some support. Furthermore Doom Emacs is considering to provide a Corfu module as far as I understand, so it is likely that the Evil integration will get improved over time, when more people start to use the Evil/Corfu/Vertico package combination.

**Comment by minad** [comment]
I forgot to mention - if you want to complete using Vertico in the minibuffer you can use consult-completion-in-region from the Consult package. This is documented in the Vertico and Consult README.
