### ISSUE TITLE
Current approach for chaining dot completions

### ISSUE THREAD

**Issue by ashlineldridge** [minad/corfu#196]
Hello, I'm trying to figure out the currently recommended approach for chaining dot completions as described in #95.

To describe what I'm trying to achieve, consider the following Rust code:

```rust
let aa = "AA".to_owned();
let aaa = "AAA".to_owned();
```

On the next line following the definition of `aaa`, if I type "aa" corfu will show me two completion candidates ("aa" and "aaa") as expected and by default (since `corfu-preselect-first` is enabled) "aa" will be selected.

At this point, I'd like to be able to type "." and have the corfu pop-up switch to showing the completions for the methods/properties of the `aa` variable. Instead, the corfu pop-up quits and I need to press TAB to show the completions.

What is the currently recommended approach for achieving the above completion workflow?

I understand that one approach used to be to advise the `corfu--post-command` function and dynamically set `corfu-quit-on-boundary` as described in #119. Is this approach still viable given the changes described [here](https://github.com/minad/corfu/issues/109#issuecomment-1037267402)? I have tried this approach using the latest version of corfu (0.25 at time of writing) and couldn't get it to work. In the discussion following the linked comment, I see mentions of advising `corfu--pre-command-hook` but I lack the understanding of corfu's internals to know what this advice should do exactly.

Any pointers would be appreciated.

**Comment by minad** [comment]
Chaining completions with dots is not supported currently. One approach would be to implement this in the backends itself. Alternatively we could try to automatically restart completion when appropriate. I don't recall our conclusions from prior issues, but this issue needs more design work.

**Comment by minad** [comment]
Actually I think that chaining completions with dot should just work. As soon as you hit dot the selected candidate is inserted and then auto completion should restart completion. Maybe the only problem is then the auto delay? One possibility would be to temporarily turn off the delay directly after one completion step. If auto completion fails, reenable the delay.

**Comment by ashlineldridge** [comment]
I currently already have:

```elisp
:custom
(corfu-auto t)
(corfu-auto-prefix 0)
(corfu-auto-delay 0)
```

To summarize the behavior I'm seeing:

| Step | Keys Pressed | What Happens                              |
|------|--------------|-------------------------------------------|
|    1 | `aa`         | corfu pop-up displayed with "aa" selected |
|    2 | `.`          | corfu pop-up quits                        |

But no pop-up shows me the completion candidates for aa's methods/properties unless I now press tab (completion does not appear to be restarted as you mention).

If, however, I press enter to select "aa" then subsequently pressing "." produces the desired behavior as below.

| Step | Keys Pressed | What Happens                                |
|------|--------------|---------------------------------------------|
|    1 | `aa`         | corfu pop-up displayed with "aa" selected   |
|    2 | `<enter>`    | corfu pop-up quits                          |
|    3 | `.`          | corfu pop-up displayed showing aa's methods |

**Comment by ashlineldridge** [comment]
My guess was that the `.` character was not being treated specially - the corfu pop-up quits because `corfu-quit-no-match` is not nil and there is no match for `aa.`. At this point it seems too late for whatever auto-complete event is (or should be) generated by pressing the `.`.

My config is below:

```elisp
(use-package corfu
  :straight '(corfu-mode :host github :repo "minad/corfu")
  :bind
  (:map corfu-map
        ("S-SPC" . corfu-insert-separator))
  :init
  (global-corfu-mode)
  :custom
  (corfu-auto t)
  (corfu-auto-prefix 1)
  (corfu-auto-delay 0)
  (corfu-excluded-modes '(org-mode)))
```

**Comment by ashlineldridge** [comment]
Works great now! 🙇🏼

**Comment by Ghosty141** [comment]
I think I'm currently experiencing the same/a similar issue. I don't use corfu-auto and invoke it manually whenever I need it. I use quit-at-boundary nil to use corfu together with orderless. What I now want is that corfu only quits when entering a separator of choice like a dot.

My usecase:
```
auto foo_bar = FooBar{};
fo<invoke corfu>
```

**Comment by Ghosty141** [comment]
I'm still having this issue. 

```
FooBar buf;
FooBar buffer;
<invoke corfu>
```

When I now type buf. it doesn't quit but interpret the dot as an orderless wildcard. I'm aware that using quit-at-boundary nil does that but I'd like to have a seperator that still "overwrites" that behavior. If I set quit-at-boundary to "." it doesn't handle the space separated search with orderless anymore.
