### ISSUE TITLE
Make corfu completion-in-region optional?

### ISSUE THREAD

**Issue by Inc0n** [minad/corfu#198]
I prefer to use consult-completion-in-region instead, which is what my completion-in-region-function is assigned to.

However, corfu overwrites this whenever it is activated.

This means currently my work around would be to `defalias` on `corfu--in-region-1`, which is hacky IMO. 

Would there be a better approach for this?

**Comment by minad** [comment]
It should be sufficient to kill the `completion-in-region-function` local variable after enabling Corfu:

~~~ elisp
(setq-default completion-in-region-function 'consult-completion-in-region)
(add-hook 'corfu-mode-hook (lambda () (kill-local-variable 'completion-in-region-function)))
~~~
