### ISSUE TITLE
Snippet not expanded for single completion.

### ISSUE THREAD

**Issue by mobid** [minad/corfu#199]
In java-mode with LSP, corfu works just fine, only exception is completing when there is only one possible completion. In this case, corfu insert completion with signature, eg.:
```
someFunction(boolean argument, String otherArgument) : Boolean<cursor-is-here>
```

Is there any fix to expand snippet in this case?

**Comment by minad** [comment]
Please list your precise steps to reproduce this and specify your Corfu and Lsp-mode configuration. It should be possible to fix this by adjusting some Corfu configuration options.

**Comment by mobid** [comment]
Here is the minimal config. I ran it with `emacs -Q --load config.el`
```
;;; config.el
(package-initialize)
(require 'use-package)

(use-package lsp-mode
  :ensure t)

(use-package yasnippet
  :ensure t
  :config
  (yas-global-mode +1))

(use-package corfu
  :ensure t
  :config
  (global-corfu-mode +1))
```

After visiting java file run `lsp` and try to complete method which has single match.
I trigger completion with `C-M-i` `complete-symbol` or `completion-at-point`. I don't user corfu-auto.
eg: `someFuncti<C-M-i>` -> `someFunction(boolean argument, String otherArgument) : Boolean`

I don't know if corfu has any function here. Can be snippet expanded in this case?

**Comment by minad** [comment]
Okay, I see the problem now. In `corfu--in-region-1` we check if the completed string can be completed further and only exit immediately if this is not possible.

https://github.com/minad/corfu/blob/4f70a0d5829efbdc28f2e8cc20eabcd0fd657ef0/corfu.el#L1140-L1145

Unfortunately the `lsp-completion-at-point` function provided by lsp-mode is not implemented correctly. In particular the actions `try-completion` and `test-completion` are wrong. See https://github.com/emacs-lsp/lsp-mode/blob/3fa645c0397b8f438f2db2dd288b899ba330d410/lsp-completion.el#L523-L530. In our case here, `lsp-completion-at-point` returns the `probe` or the first element from the list of candidates, while it should return `t` instead.

For comparison, this is the correct Eglot implementation: https://github.com/joaotavora/eglot/blob/bd970be047aba4513c2970b9ff2d842f0472cb0e/eglot.el#L2590-L2594

**Comment by minad** [comment]
I opened https://github.com/emacs-lsp/lsp-mode/issues/3607 on the lsp-mode tracker.
