### ISSUE TITLE
Support annotation-function

### ISSUE THREAD

**Issue by bbuccianti** [minad/corfu#2]
Hi there!

It's possible to use marginalia annotations with corfu?

Would be awesome!

**Comment by bbuccianti** [comment]
Sorry! I've just read the annotation section on readme :smile:

**Comment by astoff** [comment]
This does seem to be a feature many people would use.

**Comment by minad** [comment]
How would that look like? Show the annotations in the popup or in the echo area? I consider showing the info in the echo area, this is what company does for its `company-docsig` function. But the situation is chaotic, there is `annotation-function`, `affixation-function`, `company-docsig` and `company-kind` now.

* Prefixes: affixation-prefix (short string), company-kind (returns vscode icon name?)
* Suffixes: annotation-suffix, affixation-suffix, company-docsig

**Comment by minad** [comment]
@astoff In your digest gif, this is company mode + lsp or elglot? Are these annotations in the gif?

**Comment by astoff** [comment]
The GIF uses Company and Eglot. And this requires no special setup to work.

I wasn't aware of these different kinds of extra information. I just though it would be nice to see the same annotation one gets in the vanilla `*Completions*` buffer; I wouldn't care about an icon.

**Comment by minad** [comment]
It is the ~annotation-function~ then. The `*Completions*` buffer only supports the ~annotation-function~.

https://github.com/joaotavora/eglot/blob/fc221c8b8af33363a6a8d1e07950dc01555f6c9b/eglot.el#L2235-L2248

**Comment by minad** [comment]
Fixed by https://github.com/minad/corfu/commit/30126c45dbfa030b5b8a57d8923c243a441e8ea7

**Comment by bbuccianti** [comment]
This started to happen after 30126c4

![broken corfu](https://p.buccianti.dev/corfu.png)

**Comment by minad** [comment]
No, this is when your code contains tabs. Corfu refuses to work for people who indent using tabs :-P 

Seriously, the popup formatting is still brittle unfortunately and needs improvements.

**Comment by bbuccianti** [comment]
Oh! I can see that!

Maybe I could just use spaces instead of tabs. 

Thanks!

**Comment by bbuccianti** [comment]
I've found that setting indent-tabs-mode to nil was a way of avoiding that wrong alignment. Thanks!

**Comment by danielpza** [comment]
setting indent-tabs-mode doesn't do it for me, do I have to switch from tabs to spaces?

![image](https://user-images.githubusercontent.com/17787042/115090534-1dd20500-9ee3-11eb-97fd-e0fae10abeff.png)

**Comment by minad** [comment]
I have pushed a fix. Tabs should work now.

**Comment by danielpza** [comment]
Confirming it works now, Thanks.

**Comment by astoff** [comment]
I see a little bug right now, where selecting a candidate with the arrow keys makes the annotation appear in the buffer preview as well:
![image](https://user-images.githubusercontent.com/6500902/115102761-69b99400-9f4d-11eb-9d68-ee84efb84652.png)

I also wanted to mention that while I like the annotations in the above screenshot (completions from Digestif), some other backends return far less interesting annotations. So maybe displaying them should be configurable, since that's how you seem to prefer it.

**Comment by minad** [comment]
For me annotations are mostly fine. I am only critical regarding Marginalia annotations which are not a good fit here, since they take up a lot of space and are supposed to be shown in large buffers.
