### ISSUE TITLE
question about `corfu-auto`

### ISSUE THREAD

**Issue by liuyinz** [minad/corfu#201]
If I use `consult-completion-in-region` in terminal, I must call `completion-at-point` mannually every time when need completion.
The var `corfu-auto` is only for childframe, right?
What I should do if I want to popup minibuffer automatically when I input prefix of enough length ? Or it isn't designed by this way?

**Comment by minad** [comment]
This is not possible. It is not such a good idea since you don't want that the focus moves automatically from the buffer to the minibuffer. This will be inconvenient and confusing. You can try to implement this yourself based on Corfu, but it is probably a waste of time.
