### ISSUE TITLE
`corfu-complete` via TAB doesn't insert and close the popup in LSP mode (it works in elisp and other non LSP powered modes)

### ISSUE THREAD

**Issue by kwojcik-blockether** [minad/corfu#202]
![image](https://user-images.githubusercontent.com/14275210/178225870-543fe6e5-f20a-4bd5-a9bd-9eaf4e6f8a16.png)

**Comment by minad** [comment]
Duplicate #199. The problem is that lsp-mode does not implement a correct completion table. See the lsp-mode issue https://github.com/emacs-lsp/lsp-mode/issues/3607.
