### ISSUE TITLE
Corfu inserts extra tabs when editing quoted text in eshell

### ISSUE THREAD

**Issue by ryantking** [minad/corfu#204]
I am getting strange behavior with `corfu` in `eshell`. Whenever I insert text inside quotes (including the opening quote) with the setting `corfu-auto` enabled, a tab character is also inserted after the desired character.

Here is what typing `ls "$H` looks like. `-!-` represents the point and each line represents the next key press.

```
~ $ -!-
~ $ l-!-
~ $ ls-!-
~ $ ls -!-
~ $ ls "        -!-
~ $ ls "        $       -!-
~ $ ls "        $       H       -!-
```

Emacs info:

```emacs-lisp
: GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)
```

Test config:

```emacs-lisp
(package-install 'corfu)
(require 'corfu)
(setq corfu-auto t)
(global-corfu-mode 1)
```

**Comment by minad** [comment]
See https://github.com/minad/corfu#completing-in-the-eshell-or-shell. These are upstream bugs which are hopefully fixed in Emacs 29. In Emacs 28 you need Cape.
