### ISSUE TITLE
pdb autocompletion does not work

### ISSUE THREAD

**Issue by jgarte** [minad/corfu#207]
[pdb](https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/gud.el#L1822) autocompletion does not work

wdyt

**Comment by minad** [comment]
See #157. The last time I looked at gdb it didn't provide a valid capf. Please narrow the problems down and report it upstream.

Corfu auto completion has higher requirements than default completion with regards to Capf correctness since it calls them much more aggressively.

We could also try to sanitize the Capf somehow ala pcomplete/eshell with Cape wrappers. But I am not sure if this would work too for gud.

**Comment by jgarte** [comment]
I read #157 but it didn't seem conclusive what the fix was for it.

**Comment by minad** [comment]
There is no fix. The Capf is broken - it is not a Corfu issue.

**Comment by jgarte** [comment]
Thanks for clarifying

**Comment by jgarte** [comment]
@minad 

could this help the situation? https://github.com/muffinmad/emacs-pdb-capf

**Comment by muffinmad** [comment]
@jgarte There are no need to hook up emacs-pdb-capf with corfu in some special way. Just
```elisp
(global-corfu-mode)
```
And then use `pdb-capf` in some buffer:
```elisp
(add-hook 'completion-at-point-functions 'pdb-capf nil t)
```

**Comment by jgarte** [comment]
@muffinmad What key did you press to trigger the completion? I have my corfu set to auto but that seems not to work.

**Comment by muffinmad** [comment]
@jgarte It's `M-<tab>`

You need to setup completion functions in needed mode hooks. So, in case you want `pdb-capf` to work in `gud` mode, your config may look like this:
```elisp
(global-corfu-mode)
(setq corfu-history-mode t
      corfu-auto t
      corfu-quit-no-match t)
(add-hook 'pdb-mode-hook
          (lambda ()
            (add-hook 'completion-at-point-functions
                      'pdb-capf nil t)))
```

Then, after `M-x pdb`, pdb completions should work.

**Comment by jgarte** [comment]
@muffinmad 

Do you happen to know the function that is bound to `M-<tab>`? That is shadowed by my desktop environment (xfce).

BTW, The completion works for me know but `.` methods don't complete correctly when  executing `completion-at-point` via `M-x`.

**Comment by jgarte** [comment]
![image](https://user-images.githubusercontent.com/47760695/182722477-a8b01769-ad27-46b9-aa79-0776ae9439ee.png)

**Comment by muffinmad** [comment]
> Do you happen to know the function that is bound to `M-<tab>`? That is shadowed by my desktop environment (xfce).

```
C-M-i (translated from M-<tab>) runs the command complete-symbol
(found in global-map), which is an interactive byte-compiled Lisp
function in ‘bindings.el’.
```

BTW, you can type `M-<tab>` by pressing `<ESC>` and then `<tab>`

> BTW, The completion works for me know but `.` methods don't complete correctly when executing `completion-at-point` via `M-x`.
> 
> I had eglot enabled with `pylsp` in below screenshot.

Eglot has nothing to do with pdb completions. Eglot is responsible for completions in `python-mode` buffer. Completions need to be set up properly in debugger buffer itself.

**Comment by jgarte** [comment]
> 

@muffinmad 

hmmm, `complete-symbol` tries to complete only filenames in the currect directory instead of python object attributes.

Any thoughts on how I could debug this further?

Any suggestions for other configs/versions of software I'm running that I should share?

**Comment by muffinmad** [comment]
Here are the steps I follow to make completions works as expected in `emacs -Q`:
1. `M-x package-initialize`
2. `M-: (add-hook 'pdb-mode-hook (lambda () (add-hook 'completion-at-point-functions 'pdb-capf nil t)))`
3. `M-x global-corfu-mode`
4. `M-x pdb` `python -m pdb test.py`
5. In pdb buffer type `foo = 'bar'`
6. In pdb buffer type `foo.`
7. `M-x complete-symbol`
The result:
<img width="595" alt="Screenshot 2022-08-07 at 23 41 48" src="https://user-images.githubusercontent.com/2702727/183310424-8056b261-5ca5-4d05-8149-f1cf7ba69451.png">

**Comment by jgarte** [comment]
@muffinmad 

What exact version of emacs are you running?

I'm on `GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)`

**Comment by muffinmad** [comment]
@jgarte

I'm using `GNU Emacs 29.0.50 (build 2, x86_64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.5 (Build 21G72)) of 2022-08-02`

But the steps above works for me also on `GNU Emacs 28.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2022-05-11`

**Comment by jgarte** [comment]
Here's my full config:
```
(require 'org-modern) 
(global-org-modern-mode)

(require 'recentf) 
(recentf-mode)

(scroll-bar-mode 0)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)
   (emacs-lisp . t)
   (scheme . t)
   (org . t)
   (C . t)
   (sql . t)))

(setq org-src-fontify-natively t)
(setq org-confirm-babel-evaluate nil)

(setq evil-want-keybinding nil)
(setq evil-search-module 'evil-search)
(require 'evil) 
(evil-mode)
(setq evil-move-cursor-back nil) ; like vis
(evil-set-undo-system 'undo-redo)

(require 'evil-collection) 
(evil-collection-init)

(when (display-graphic-p)
  (fset 'evil-visual-update-x-selection 'ignore))

(require 'tempel)
(setq tempel-file (expand-file-name "~/snippets"))

(require 'vertico) 
(vertico-mode)

(require 'marginalia) 
(marginalia-mode)

(require 'orderless) 
(setq completion-styles '(orderless))

(require 'terminal-here)
(setq terminal-here-linux-terminal-command 'kitty)

(add-to-list 'load-path "~/emacs-pdb-capf/")
(require 'pdb-capf)
(add-to-list 'completion-at-point-functions #'pdb-capf)
(add-hook 'completion-at-point-functions 'pdb-capf nil t)
(add-hook 'pdb-mode-hook
          (lambda ()
            (add-hook 'completion-at-point-functions
                      'pdb-capf nil t)))

(require 'corfu)
(global-corfu-mode)
(setq corfu-history-mode t
      corfu-auto t
      corfu-quit-no-match t)

```

**Comment by jgarte** [comment]
@muffinmad 

Should I remove that duplicate `add-hook` code?

**Comment by muffinmad** [comment]
@jgarte 

I think so. Instead of
```elisp
(add-to-list 'completion-at-point-functions #'pdb-capf)
(add-hook 'completion-at-point-functions 'pdb-capf nil t)
(add-hook 'pdb-mode-hook
          (lambda ()
            (add-hook 'completion-at-point-functions
                      'pdb-capf nil t)))
```
you can keep only
```elisp
(add-hook 'pdb-mode-hook
          (lambda ()
            (add-hook 'completion-at-point-functions
                      'pdb-capf nil t)))
```

**Comment by jgarte** [comment]
@muffinmad This is what I get as completion for a string object:

![image](https://user-images.githubusercontent.com/47760695/184465410-086abcfa-0be4-42fb-8c34-9720d2e618a4.png)

**Comment by muffinmad** [comment]
@jgarte Can you please provide the steps to reproduce such behavior starting from `emacs -Q`?
