### ISSUE TITLE
Is there a way to let corfu handle auto-complete-mode completions?

### ISSUE THREAD

**Issue by atanasj** [minad/corfu#208]
Firstly, thanks for such a great package... together with the other packages (e.g., `consult`, `embark` etc.) this has really improved my user experience. 

I have a package that I used that was developed to use `auto-complete` for completion. Is there a  way to get `corfu` (maybe with `cape`?) to handle this instead? I really don't know where to start… Here is my current config for the package in question: 

```elisp
(use-package! mplus-mode
  :load-path "./mplus-mode"
  :init
  (require 'mplus-mode)
  (add-hook 'mplus-mode-hook #'visual-line-mode)
  (add-hook 'mplus-mode-hook #'display-line-numbers-mode)

  ;; (add-hook 'mplus-mode-hook #'auto-fill-mode)
  ;; config setup as per repo instructions
  (setq auto-mode-alist (cons '("\\.inp" . mplus-mode) auto-mode-alist))
  (add-hook 'mplus-mode-hook
            (lambda ()
              (require 'auto-complete-config)
              (add-to-list 'ac-dictionary-directories "~/.emacs.d/es-ac-dict")
              (setq-default ac-sources '(ac-source-abbrev
                                         ac-source-dictionary
                                         ac-source-words-in-same-mode-buffers))
              (add-to-list 'ac-modes 'mplus-mode)
              (add-hook 'mplus-hook (lambda () (auto-complete-mode 1))))
            )
  ;; NOTE place holder until I learn how to add modes to pro-mode, etc.
  (add-hook 'mplus-mode-hook #'hl-todo-mode)
  :hook
  (mplus-mode . auto-complete-mode)
```

I am using `doom` Emacs. Please let me know if you need any more info about my request… Other useful info below:

```sh
ProductName:	macOS
ProductVersion:	11.6.8
BuildVersion:	20G730
GNU Emacs 28.1
```

**Comment by minad** [comment]
Thanks! I am not familiar with mplus-mode, but it seems that you just use the generic abbrev, dabbrev and dict ac-sources. You can remove ac and use the corresponding Cape Capfs instead.

**Comment by atanasj** [comment]
Yes, it's a package for working with `Mplus` scripts… A statistical program. Thanks for that, I'll give it a go.
