### ISSUE TITLE
`corfu-quit-no-match` doesn't seem to work for some LSP backends

### ISSUE THREAD

**Issue by anonimitoraf** [minad/corfu#213]
Thanks heaps for this awesome package! Been using it as my daily driver for a while now.

The only issue I've noticed is that for some LSPs, corfu doesn't automatically close despite not having a match

e.g. `css`

https://user-images.githubusercontent.com/15933322/183249616-21bf50a7-094f-4cf8-a6a5-a5d279d216ae.mov

[Here's my config](https://github.com/anonimitoraf/doom.d/blob/master/config-sections/experimental.org#corfu-and-co)

What are the prerequisites for a "backend" (is this the right term) for `corfu` to quit on no match?

**Comment by minad** [comment]
This is an lsp-mode issue, see https://github.com/emacs-lsp/lsp-mode/issues/3607.

Duplicate #199, #202

**Comment by anonimitoraf** [comment]
Oh wow, thanks for the quick reply! And I see, sorry for raising a duplicate issue (I searched around for `quit-no-match` issues but didn't find any).

Also, thanks the LSP patch!

**Comment by minad** [comment]
I hope the patch works well for you. If you find time you could also cross check the patch against default completion and Company and comment on the lsp-mode tracker. Hopefully this convinces the lsp-mode maintainers that the issue can be fixed without regressions.

**Comment by anonimitoraf** [comment]
Yep I don't mind doing that :)

I've tried out your patch, the behaviour seems to not have changed.


https://user-images.githubusercontent.com/15933322/183251125-823f5ab8-5694-43a4-adcd-7e1da3ef72a3.mov

Here, I'm printing out the 3 args
```
       (lambda (probe pred action)
         (message "probe = %s | pred = %s | action = %s" probe pred action)
         (if (eq action 'metadata)
             '(metadata (category . lsp-capf)
                        (display-sort-function . identity)
                        (cycle-sort-function . identity))
           (complete-with-action action (funcall candidates) probe pred)))
```

**Comment by minad** [comment]
See the lsp-mode configuration in the wiki: https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-mode. You have to make sure that you configure the completion style correctly for the lsp-capf completion category.

**Comment by anonimitoraf** [comment]
Ah sweet, thanks! This works for me: https://github.com/minad/corfu/wiki#basic-example-configuration-with-orderless

I'll try it out with `company` shortly

**Comment by minad** [comment]
Thanks. Please try my patched lsp-completion-at-point function in three configurations:

1. Orderless/Flex config from the wiki
2. ootb Company configuration
3. ootb configuration with default completion

Hopefully everything works well. If my patch gets added to lsp-mode, the lsp-mode+Corfu setup should get quite a bit simpler. A bit in the future we could then ask the lsp-mode maintainers to also builtin some kind of Corfu configuration, similar to what is offered for Company.

**Comment by anonimitoraf** [comment]
> ootb configuration with default completion

Sorry, what do you mean by default completion?

> Hopefully everything works well. If my patch gets added to lsp-mode, the lsp-mode+Corfu setup should get quite a bit simpler. A bit in the future we could then ask the lsp-mode maintainers to also builtin some kind of Corfu configuration, similar to what is offered for Company.

Yep, I see what you mean. That'd be nice

**Comment by minad** [comment]
> Sorry, what do you mean by default completion?

No company-mode, no corfu-mode. Just the default `*Completions*` buffer which comes up when pressing TAB. 

You may be more familiar with `*Completions*` in the context of minibuffer completion. If you disable `vertico-mode` you will get the `*Completions*` buffer when pressing TAB in an M-x minibuffer.

**Comment by anonimitoraf** [comment]
Weirdly, I get candidates for default completion for CSS and Typescript, but not for Clojure.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/15933322/183253711-1407cf32-eb37-46b0-a780-c34512f04a41.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/15933322/183253739-152bb5fc-a446-40b5-925d-b05e4a93bded.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/15933322/183253702-f638d357-e3d0-46ad-95bc-84557865d0a3.png">

**Comment by anonimitoraf** [comment]
Ah whoops, I had forgotten to disable vertico. With vertico disabled, I get candidates
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/15933322/183253971-3f1e9981-4a32-4d2d-bc12-43053c470a00.png">

But that's a bit weird nonetheless?

**Comment by minad** [comment]
If you don't disable Vertico you probably use consult-completion-in-region which transfers the in-buffer completion to the minibuffer. There are many options for completions in buffers.

* Default `*Completions*`
* Vertico+consult-completion-in-region
* Corfu
* Company

**Comment by anonimitoraf** [comment]
Hmm, does that explain the difference between CSS/Typescript yielding candidates vs Clojure no candidates?

**Comment by minad** [comment]
No, I don't know what is wrong with Clojure. But as I understood, Corfu and Company work with Clojure? Then there is no point in digging much deeper here. We have to wait now for some movement on the lsp-mode side.

**Comment by anonimitoraf** [comment]
Yep, company and corfu work with Clojure
