### ISSUE TITLE
'corfu-preview-current' with 'corfu-preselect-first' doesn't preview first

### ISSUE THREAD

**Issue by david-vicente** [minad/corfu#215]
It feels a bit odd that the first entry is treated differently from the rest with regards to previewing.

Here `random` is not previewed next to the prompt
![image](https://user-images.githubusercontent.com/57544666/183540959-b5bd25d1-b7ea-4f9c-93fd-8a5fd416dc83.png)

but `arange` is previewed
![image](https://user-images.githubusercontent.com/57544666/183541088-6bd6f59e-4957-49fe-a57a-62e3f4659eee.png)

For example in Vscode every completion entry is previewed
![image](https://user-images.githubusercontent.com/57544666/183540907-5b320c31-c333-4fce-a964-92afaed3e93d.png)

Is this intended?

Thanks

**Comment by minad** [comment]
This is intended. We cannot preview the a candidate without overwriting the prompt. The vscode preview is less general and only works since the candidate matches the prefix. Corfu also supports non-prefix completion styles like substring, flex and orderless.
