### ISSUE TITLE
Auto-completion in the minibuffer: prevent from completing in password prompt

### ISSUE THREAD

**Issue by kenranunderscore** [minad/corfu#217]
I'm loving `corfu` so far, but the only little gripe I have with it is that when enabling auto-completion in the minibuffer as per the readme, it shows completion even when entering my SSH key passphrase :smile:
I bet there's an easy way to circumvent this, maybe just by extending the predicate for when to enable it, but I'm a bit at a loss as I don't know how the minibuffer works, and how to find out whether "a password prompt is being shown".

Thank you very much for any input, and for another great plugin!

**Comment by minad** [comment]
Yes, it should be possible to detect a password prompt and extend the predicate. Unfortunately I don't know how to do this exactly. I didn't have this problem so far thanks to ssh-agent. If you figure it out please let me know. Read the source ;)

**Comment by minad** [comment]
You could for example check the hooks, see https://github.com/emacs-mirror/emacs/blob/b4879603fd8f9c8e82e30c5fbb65fa63d8166ee4/lisp/subr.el#L3115. I am not sure if there is a better way.

**Comment by kenranunderscore** [comment]
Thanks. I went with this hacky way, as it worked first try, and I'm content :smile: 

```elisp
(defun corfu-enable-always-in-minibuffer ()
  "Enable Corfu in the minibuffer if Vertico/Mct are not active."
  (unless (or (bound-and-true-p vertico--input)
              (equal (current-local-map)
                     read-passwd-map))
    (setq-local corfu-auto t)
    (corfu-mode 1)))
```
