### ISSUE TITLE
How to check that corfu's popup is active?

### ISSUE THREAD

**Issue by cordelia04m** [minad/corfu#218]
Right now, when using SLIME's REPL, pressing RET will call `slime-repl-return`. I want to use RET to call `corfu-complete` too. 

This is the code I come up with
```
(defun complete-in-slime ()
  (interactive)
  (if corfu-popup-is-active? ;; <-- this is the function in question
      (slime-repl-return)
    (corfu-complete)))
```

**Comment by minad** [comment]
You can use the variable completion-in-region-mode for the check.

**Comment by cordelia04m** [comment]
Thank you.
