### ISSUE TITLE
Disable centaur tabs in child frame

### ISSUE THREAD

**Issue by lccambiaghi** [minad/corfu#22]
Hi, is there an easy way to disable `centaur-tabs` in the child frames created by `corfu`?

Attached you can find a screenshot.

<img width="1544" alt="Screenshot 2021-05-17 at 23 04 06" src="https://user-images.githubusercontent.com/15185927/118556660-70157880-b764-11eb-9d17-b43f6420edee.png">

**Comment by minad** [comment]
Unfortunately I have no experience with tabs. There are tab-bar-mode, tab-line-mode, centaur tabs, maybe more? Maybe the centaur developers can give some hints which setting is needed.

Child frame parameters:

https://github.com/minad/corfu/blob/02a2cbbaa52f1663705a39e5710bc39e1c76c700/corfu.el#L190

Buffer parameters:

https://github.com/minad/corfu/blob/02a2cbbaa52f1663705a39e5710bc39e1c76c700/corfu.el#L231

**Comment by protesilaos** [comment]
Hello @minad!  I have had this problem on Emacs 28 with the `tab-bar-mode`.  There is a new `tab-bar-format` variable.  I am not sure if you should add it directly or, generally, if you consider Emacs 28.  Just thought I would let you know about it.

[ I am too lazy to do the whole PR thing, so I prepared a patch instead.  Feel welcome to just commit yourself. ]

```patch
From 61efacd5075a5dee2f9fce406b6931b050eb46ac Mon Sep 17 00:00:00 2001
Message-Id: <61efacd5075a5dee2f9fce406b6931b050eb46ac.1627670790.git.info@protesilaos.com>
From: Protesilaos Stavrou <info@protesilaos.com>
Date: Fri, 30 Jul 2021 21:46:20 +0300
Subject: [PATCH] Hide tab-bar from Corfu child frame

This is the same problem as in issue #22, only it applies to the
tab-bar-mode.

The tab-bar-format comes with Emacs version 28.
---
 corfu.el | 1 +
 1 file changed, 1 insertion(+)

diff --git a/corfu.el b/corfu.el
index 3529608..b94afa1 100644
--- a/corfu.el
+++ b/corfu.el
@@ -254,6 +254,7 @@ (defvar corfu--frame-parameters
 (defvar corfu--buffer-parameters
   '((mode-line-format . nil)
     (header-line-format . nil)
+    (tab-bar-format . nil)
     (tab-line-format . nil)
     (frame-title-format . "")
     (truncate-lines . t)
-- 
2.32.0
```
