### ISSUE TITLE
Fast orderless completion style example wrong(?)

### ISSUE THREAD

**Issue by Walheimat** [minad/corfu#220]
I was looking into `orderless` and was following the README and noticed that Emacs complained about an unused `let` binding.

The example (https://github.com/minad/corfu#auto-completion):

```elisp
(orderless-define-completion-style orderless-fast
  ;; Should probably be `orderless-style-dispatchers', `orderless-dispatch' is a function.
  (orderless-dispatch '(orderless-fast-dispatch))
  (orderless-matching-styles '(orderless-literal orderless-regexp)))
```

This is so minor that I didn't want to open a PR just for it, but I think this is wrong.

**Comment by minad** [comment]
That's right. I don't really recommend that approach anymore. Instead it is better to define a limited basic completion style. But the optimization is hardly worth it. One shouldn't use these overly aggressive auto completion settings anyway.

~~~ elisp
(defun basic-limited-all-completions (string table pred point)
  (when (length< string 4)
    (completion-emacs21-all-completions string table pred point)))

(defun basic-limited-try-completion (string table pred point)
  (when (length< string 4)
    (completion-emacs21-try-completion string table pred point)))

(add-to-list 'completion-styles-alist
             '(basic-limited
               basic-limited-try-completion
               basic-limited-all-completions
               "Limited basic completion."))
~~~
