### ISSUE TITLE
childframe disappear while mouse cursor meets it

### ISSUE THREAD

**Issue by Loutine** [minad/corfu#221]
# emacs version:
 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
# description: 
This issue only happened on emacs 29 , corfu worked well on emacs 28. The childframe of candidates will suddenly disappear if the mouse cursor meets it, as the gif shows below:
![Peek 2022-08-22 12-56](https://user-images.githubusercontent.com/33801505/185842730-75deec93-4c30-49fe-afc6-dc6e0c20342a.gif)

my configuration for cape and corfu
``` emacs-lisp
(use-package corfu
	     ;; Optional customizations
	     :custom
	     (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
	     (corfu-auto t)                 ;; Enable auto completion
	     (corfu-auto-prefix 1)
	     (corfu-preselect-first t)    ;; Disable candidate preselection
	     :bind
	     (:map corfu-map
		   ("TAB" . corfu-next)
		   ([tab] . corfu-next)
		   ("S-TAB" . corfu-previous)
		   ([backtab] . corfu-previous))
	     :init
	     (global-corfu-mode))


(use-package cape
	     :after corfu
	     ;; Bind dedicated completion commands
	     ;; Alternative prefix keys: C-c p, M-p, M-+, ...
	     :bind (("C-c p p" . completion-at-point) ;; capf
		    ("C-c p t" . complete-tag)        ;; etags
		    ("C-c p d" . cape-dabbrev)        ;; or dabbrev-completion
		    ("C-c p h" . cape-history)
		    ("C-c p f" . cape-file)
		    ("C-c p k" . cape-keyword)
		    ("C-c p s" . cape-symbol)
		    ("C-c p a" . cape-abbrev)
		    ("C-c p i" . cape-ispell)
		    ("C-c p l" . cape-line)
		    ("C-c p w" . cape-dict)
		    ("C-c p \\" . cape-tex)
		    ("C-c p _" . cape-tex)
		    ("C-c p ^" . cape-tex)
		    ("C-c p &" . cape-sgml)
		    ("C-c p r" . cape-rfc1345))
	     :init
	     (add-to-list 'completion-at-point-functions #'cape-dabbrev)
	     (add-to-list 'completion-at-point-functions #'cape-file)
	     )


```

**Comment by minad** [comment]
Thanks. Since this is a regression caused by 29 it needs some investigation on what causes this. There have been many upstream changes recently regarding the UI, so it is hard to tell if this is intentional or not. I will investigate this when Emacs 29 is closer to release. It could as well be that the behavior turns back to normal in the meantime.

**Comment by danielpza** [comment]
I'm still encountering this issue on emacs 29.4, did you ever find a solution or workaround this issue?
