### ISSUE TITLE
Preview single candidates similar to company

### ISSUE THREAD

**Issue by elken** [minad/corfu#222]
Kinda related to https://github.com/minad/corfu/issues/215 but I thought it should be a new issue.

Similar to [company](https://company-mode.github.io/manual/Frontends.html#Preview-Frontends), what would be required in order to add this behaviour to Corfu?

Specifically the ability to preview a single candidate inline with a customizable face(s)
![image](https://user-images.githubusercontent.com/2872862/185904274-8b1b7708-61da-4ba9-b0ce-86704fc02a70.png)
![image](https://user-images.githubusercontent.com/2872862/185904392-934fc1e0-2dd4-46c9-a68e-a879812d2727.png)

If this already exists and I've missed something feel free to tell me I'm an idiot and close this! :D

**Comment by minad** [comment]
Duplicate #215 and #211. Feel free to implement this if you are interested and propose a PR. I don't think it is a particularly useful feature, especially if you use more flexible completion styles.

**Comment by elken** [comment]
I agree on the not useful front, but someone asked for it earlier.

I may look into it, but maybe not. Have other things to look into for when I start looking at adding this as a doom module soon ™️ .

**Comment by minad** [comment]
You are not the first to ask. The difficulty is to find a design which fits nicely with what we have right now. I hope there will be some good feedback from Doom since you have a full blown Company configuration.

We could preview the first candidate in the style of Company if it matches the prefix. Otherwise we could display something like `input<candidate>` for non-prefix matches. Given such preview one could even decide to not show the popup for unique candidates or only if you are scrolling down (`corfu--index>0`).

**Comment by elken** [comment]
Lots of people are pretty excited about Corfu, so I would like to think I could provide a good enough experience! :D 

I think it's only truly useful when you have a single candidate and even then behind `corfu-preview-single-candidate` or something. If true and we have 1 candidate, display the inline preview rather than invoking the frame.

As you say, with orderless in the mix trying to handle that for every kind of candidate would be too tricky.

**Comment by minad** [comment]
> As you say, with orderless in the mix trying to handle that for every kind of candidate would be too tricky.

Well, as I mentioned we could simply display `complicated-input|<the full candidate>` via the overlay, where | is the cursor. Not sure if this looks good for in-buffer completion, bit it would be similar to Ido or vertico-unobtrusive/flat in the minibuffer.
