### ISSUE TITLE
How do I use corfu-indexed-mode?

### ISSUE THREAD

**Issue by ackerleytng** [minad/corfu#223]
I started the mode using `(corfu-indexed-mode)` and the numbers appeared next to the completion suggestions. Do I have to add further config to use the suggestions? After a brief look at the code, I couldn't figure out what keystrokes to use to choose and apply the suggestions.

**Comment by jiacai2050** [comment]
Hi, I wonder how to bind this behavior to `M-<number>` like company?

**Comment by lxsameer** [comment]
It might be late but for future reference. An easy way to do this is:

```emacs-lisp
(dotimes (i 10)
(define-key corfu-mode-map
                  (kbd (format "M-%s" i))
                  (kbd (format "C-%s <tab>" i)))
```

**Comment by minad** [comment]
@lxsameer Using keyboard macros for this is actually a great approach! Maybe it makes sense to upstream a small utility function to Corfu and Vertico, which does this.

**Comment by lxsameer** [comment]
@minad absolutely. I'll make a PR later.

**Comment by cands** [comment]
Great solution, thanks! Does not seem to work for M-0 binding though (M-1 to M-9 work), any tips regarding this?
