### ISSUE TITLE
corfu-show-documentation not working?

### ISSUE THREAD

**Issue by mrpatrick** [minad/corfu#226]
Hi - I've recently migrated from company to corfu + cape - everything works great exempt I'm having an issue showing documentation when I execute C-h over an option

<img width="1001" alt="Screen Shot 2022-08-29 at 1 37 02 PM" src="https://user-images.githubusercontent.com/599497/187297115-5c3e0b83-8a27-4389-beb6-bf6aaf0801fc.png">

error: `Autoloading file /Users/mrpatrick/.emacs.d/elpa/corfu-0.26/corfu.elc failed to define function corfu-show-documentation`

I tried searching existing issues but couldn't find any similar errors which leads me to believe it's an issue with my setup/config/lack of knowledge.

Here is the related config:

```lisp
 (use-package corfu
   :custom
   ;; Works with `indent-for-tab-command'. Make sure tab doesn't indent when you
   ;; want to perform completion
   (tab-always-indent 'complete)
   (completion-cycle-threshold t)      ; Always show candidates in menu

   ;;(corfu-auto nil)
   (corfu-auto-prefix 0)
   (corfu-auto-delay .2)

   ;; new
   (corfu-quit-at-boundary t)
   (corfu-auto t)
   (corfu-cycle nil)

   ;; (corfu-min-width 80)
   ;; (corfu-max-width corfu-min-width)     ; Always have the same width
   (corfu-count 14)
   ;;(corfu-scroll-margin 4)


   (corfu-echo-documentation t)        ; Already use corfu-doc
   (corfu-separator ?\s)                 ; Necessary for use with orderless
   (corfu-quit-no-match 'separator)

   (corfu-preview-current 'insert)       ; Preview current candidate?
   (corfu-preselect-first t)             ; Preselect first candidate?

   ;(corfu-cycle t)
   ;; Optionally use TAB for cycling, default is `corfu-complete'.
   :bind (:map corfu-map
                   ("<escape>". corfu-quit)
                   ("<return>" . corfu-insert)
                   ("C-h" . corfu-show-documentation)
                   ("M-l" . 'corfu-show-location)
                   ("TAB" . corfu-next)
                   ([tab] . corfu-next)
                   ("S-TAB" . corfu-previous)
                   ([backtab] . corfu-previous))
   :init
   (global-corfu-mode))
```
I've also tried also setting `corfu-echo-documentation` to `nil` and adding corfu-doc hook like below but same result

```lisp
 ;;(add-hook 'corfu-mode-hook #'corfu-doc-mode)
 ;; (define-key corfu-map (kbd "C-h") #'corfu-doc-toggle)
```

Any advise would great appreciated.  Thanks!

**Comment by minad** [comment]
The command has been renamed a while ago:

https://github.com/minad/corfu/blob/42f777680ee50fa1328326c7be0c045e9c3ccb69/corfu.el#L244
