### ISSUE TITLE
Prevent auto from coming up when exact match exists

### ISSUE THREAD

**Issue by goldfita** [minad/corfu#228]
This is possibly a feature request. I tried playing with a number of the customizations and also briefly looking at the code, and I didn't see a way to do what I want. I like having auto completion on. But I don't want it to pop up when I know exactly what I want. Usually what happens is I'm at the end of a line or I've just edited some part of a line, and I've typed in a symbol or statement. Then just as I'm going for the enter or arrow keys, auto complete comes up, and I select something I don't want or I have to hit enter twice.

Is there a customization or hook so that you can prevent auto complete from coming up when you have an exact match, but there are also longer matches? Most of the time, when I know what I want, I type it fast enough that I never see the auto complete child frame. When I don't know what I want and it happens that I've typed in an exact match that is a prefix of what I want, I would prefer to manually invoke auto. I realize this is probably a somewhat unusual preference, so if you don't want to go this route, I'll understand.

**Comment by minad** [comment]
There are these possible solutions for your issue:

1. Use a large value for the delay, e.g., `corfu-auto-delay=0.5`. Then the popup won't come up so often accidentally. You probably use a much smaller delay?
2. You could write a custom completion style:

~~~ elisp
(defun substring-nonexact-all-completions (string table pred point)
  (let* ((results (completion-substring-all-completions string table pred point))
         (last (last results))
         (base (and last (cdr last))))
    (when results
      (setcdr last nil)
      (message "%S" string)
      (unless (member string results)
        (setcdr last base)
        results))))

(add-to-list 'completion-styles-alist
             '(substring-nonexact
               completion-substring-try-completion
               substring-nonexact-all-completions
               "Substring completion, but no exact matches."))
~~~

Then compare the completion behavior for these two completion styles:

~~~ elisp
(setq completion-styles '(substring-nonexact))
(setq completion-styles '(substring))
~~~

**Comment by goldfita** [comment]
1. I'm already using delay 0.5. I tend to stop briefly when I get to the end of a statement, function, or variable.
2. I've already set this to nil. I still end up having to hit return twice. I'm not sure what you mean about the arrow keys. When the popup comes up, if I hit down arrow, it will select the first item in the list. Maybe it's the way I have it configured?
3. OK. I would like to try to understand this custom completion style. I will report back when I've had a chance to investigate. Thanks!

**Comment by minad** [comment]
Regarding 2 - you are right that it doesn't make a big difference for corfu-preselect-first=nil. You still have to press RET twice.

**Comment by goldfita** [comment]
3. This almost does what I want. I made the following small change because I don't want the popup going up and down once it's already come up.

`(when (or (bound-and-true-p corfu--input) (not (member string results)))`

For the benefit of my future self or anyone else who stumbles across this thread, completion styles is not part of corfu, it's [core emacs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-Variables.html#Completion-Variables). You can find the relevant code in [minibuffer.el](https://github.com/emacs-mirror/emacs/blob/master/lisp/minibuffer.el). Also, the funny business with nulling out the end of results and then restoring it is, I beleive, because completion-substring-all-completions does not return a proper list.

**Comment by goldfita** [comment]
So I've noticed a couple more issues. The first is that I don't want this behavior in the minibuffer. That's easy enough to fix with the minibufferp predicate. The next issue is that by modifying completion-styles, I changed the behavior I had before. I don't really know at this point how I want it to work, but it should preserve the existing behavior while changing only nonexact completions. You can't just modify the first completion function in the list because emacs will just try the next one if it fails. I think the solution is to walk the list, wrapping this solution around each existing completion function.

```
(setq completion-styles-alist
      (mapcar
       (lambda (completion-style)
         (let* ((completions-symbol-string (symbol-name (nth 2 completion-style)))
                (completions-symbol-prefix-string
                 (progn
                   (string-match  "\\(.+\\)-all" completions-symbol-string)
                   (match-string 1 completions-symbol-string))))
           (list (car completion-style)
                 (nth 1 completion-style)
                 (lambda (string table pred point)
                   (let* ((completion-func (intern-soft (concat completions-symbol-prefix-string "-all-completions")))
                          (results (funcall completion-func string table pred point))
                          (end (last results))
                          (base (cdr end)))
                     (when results
                       (setcdr end nil)
                       (when (or (minibufferp)
                                 (bound-and-true-p corfu--input)
                                 (not (member string results)))
                         (setcdr end base)
                         results))))
                 (nth 3 completion-style))))
       completion-styles-alist))
(global-corfu-mode))
```
It would probably be better if I created named functions for each nonexact function and then appended them to the list, rather than modify the existing list, but this seems to work.

**Comment by minad** [comment]
> It would probably be better if I created named functions for each nonexact function and then appended them to the list, rather than modify the existing list.

Yes, it would be better if you define named functions and register them once in the alist. Then you only have to modify the completion-styles.
