### ISSUE TITLE
Auto completions: How to get completitions as you in type?

### ISSUE THREAD

**Issue by apoorv569** [minad/corfu#23]
I have been using `Doom Emacs` for quite a while, recently I decided to make my own configuration with the help of `SystemCrafters` videos on `YouTube`. Everything seems to be working fine with `corfu`, but when I'm in a programming buffer, say `C++` mode buffer, I am used to get completions as you type from `Doom Emacs` which I think used `company-mode` for completions, I could be wrong though. I'm wondering if something similar could be achieved using `corfu`.

Also when I do bring up `corfu` manually, when I select a item I want to select for completion, the popup for `corfu` does not close, I have to press `ESC` couple of time or `C-g` to close it. Is this behavior normal, if so how can I change it so it closes as soon as I press `RET` to select the highlighted item.

**Comment by minad** [comment]
There is no automatic completion popup in Corfu as of now. This feature may be added at some point. 

Regarding the exiting behavior, this sounds as if something is broken in your setup. Can you reproduce this problem in a minimal configuration with only a minimal number of packages? It is necessary to narrow down the package or configuration which causes this.

**Comment by apoorv569** [comment]
> There is no automatic completion popup in Corfu as of now. This feature may be added at some point.
> 
> Regarding the exiting behavior, this sounds as if something is broken in your setup. Can you reproduce this problem in a minimal configuration with only a minimal number of packages? It is necessary to narrow down the package or configuration which causes this.

Hi, I did as you suggested, tried removing some packages to see if works. And it did indeed work, but I'm not able to pinpoint the exact package that may or may not be causing this. Though I noticed this output in the `minibuffer` about `YASnippet` when I press `RET` to select the highlighted item.
![Peek 2021-05-28 20-34](https://user-images.githubusercontent.com/53279454/120004933-df8e3200-bfc6-11eb-9bce-87f860dd1be2.gif)

Don't know why `centaur-tabs` show up in `corfu` buffer. I did add this to the `centaur-tab` configuration.
```
    :hook
    (corfu-mode . centaur-tabs-local-mode)
 ```

But anyways, here is my `corfu` configuration
```
  (use-package corfu
    :straight '(corfu :host github
                      :repo "minad/corfu")
    ;; Optionally use these keybindings for cycling, default is `corfu-complete'.
    :bind (:map corfu-map
           ("C-j" . corfu-next)
           ("C-k" . corfu-previous)
           ("C-f" . corfu-insert))
  
    ;; You may want to enable Corfu only for certain modes.
    :hook ((prog-mode . corfu-mode)
           (lsp-mode . corfu-mode)
           (shell-mode . corfu-mode)
           (eshell-mode . corfu-mode))
  
    :config
  
    ;; Recommended: Enable Corfu globally.
    ;; This is recommended since dabbrev can be used globally (M-/).
    (corfu-global-mode)
  
    ;; Optionally enable cycling for `corfu-next' and `corfu-previous'.
    (setq corfu-cycle t)
  )
```

**Comment by minad** [comment]
See #22 regarding Centaur.

**Comment by minad** [comment]
I have a prototype for auto completion in the branch auto: https://github.com/minad/corfu/tree/auto

**Comment by jaor** [comment]
oh, this is great.  i've been using it for an hour now, and it's working
flawlessly so far.  thanks!

**Comment by minad** [comment]
@jaor This feature still needs a bit of polishing before it could be added to the main branch. In particular one should consider how the different configuration settings interact.

* If the variable `corfu-no-match` is set to a string, completion is not terminated if there is no match. In that case the string is shown in the popup instead.
* Similarly, if the variable `corfu-flexible-filter` is non-nil, completion is not terminated when inserting a field terminating character, e.g., a space. This allows orderless matching but may lead to an undesired interaction with auto completion, in case one continues to type even after the popup opened. I just added this configuration variable to the auto branch and I should probably find a better name for this setting.

There was the discussion to implement a different variant, where auto completion only opens an inactive popup which does not bind any keys. Only after the user presses TAB, the popup would be activated, enabling up/down keys. Such a popup may be less intrusive in case it opened unexpectedly, but it will also be less convenient.

What are your thoughts about this?

**Comment by jaor** [comment]
On Fri, Jun 25 2021, Daniel Mendler wrote:

> What are your thoughts about this?

for me, pressing TAB is something so frequent that it barely registers
at the conscious level.  so, when i'm looking at a corfu pop-up, i'm
rarely aware of whether it was summoned by a TAB or not, and therefore i
prefer that there is no distinction in behaviour between both cases.

as a consequence, i also find it quite natural not to quit on space, the
default value of corfu-flexible-filter, and honouring corfu-no-match in
auto mode too. (i use orderless, and really appreciate corfu's
compatibility with it.)

a thing that i would appreciate is a more streamlined way of excluding
modes from corfu-auto.  for instance, i want it everywhere except in
eshell mode.

if i'm reading the code correctly, to accomplish that right now one
needs to setq-local corfu-auto to nil before corfu-mode is activated,
which is a bit tricky if one uses global-corfu-mode.  my solution is to
add eshell-mode to corfu-excluded-modes, and then in eshell-mode-hook
first set corfu-auto, then call corfu-mode.  not a big problem (and i
can even define a macro and reuse it for a list of modes), but a
corfu-auto-excluded-modes would be nicer.

(finally, as a sidenote: i think that if i wanted a non-interactive
display of completion candidates, i'd prefer it in the minibuffer, or
perhaps in an little special buffer attached to the one i'm in: that'd
made me immediately aware that i'm in a different context and not able
to navigate the list of completions immediately... more like an eldoc
thing... come to think of it, i bet there's a way to define an eldoc
function to do just that, independently of corfu.)

**Comment by minad** [comment]
@jaor Thank you for your thoughts.

> ...and therefore i prefer that there is no distinction in behaviour between both cases.

Agree, I also prefer coherence.

> if i'm reading the code correctly, to accomplish that right now one
needs to setq-local corfu-auto to nil before corfu-mode is activated,
which is a bit tricky if one uses global-corfu-mode.  my solution is to
add eshell-mode to corfu-excluded-modes, and then in eshell-mode-hook
first set corfu-auto, then call corfu-mode.  not a big problem (and i
can even define a macro and reuse it for a list of modes), but a
corfu-auto-excluded-modes would be nicer.

Yes, that's correct. 

The solution you are proposing with `corfu-auto-excluded-modes` does not seem like a natural addition to me. The local `corfu-mode` itself is not doing mode-specific decisions. This happens only in `corfu-global-mode`, which accesses `corfu-excluded-modes`. Similarly one could add a `corfu-auto-mode`, `corfu-global-auto-mode` and `corfu-auto-excluded-modes`. I've considered this, but this seems less convenient for the user overall. So as you say, if one wants to use different settings depending on the mode (any settings, not only corfu-auto), one should probably not use `corfu-global-mode` (or use `corfu-excluded-modes`) and adjust buffer local settings. There is no need for another ad-hoc mechanism on top for this, which only works for a few special variables.

**Comment by jaor** [comment]
On Fri, Jun 25 2021, Daniel Mendler wrote:

> The solution you are proposing with corfu-auto-excluded-modes does not
> seem like a natural addition to me. The local corfu-mode itself is not
> doing mode-specific decisions. This happens only in corfu-global-mode,
> which accesses corfu-excluded-modes.  Similarly one could add a
> corfu-auto-mode, corfu-global-auto-mode and
> corfu-auto-excluded-modes. I've considered this, but this seems less
> convenient for the user overall. So as you say, if one wants to use
> different settings depending on the mode (any settings, not only
> corfu-auto), one should probably not use corfu-global-mode (or use
> corfu-excluded-modes) and adjust buffer local settings. There is no
> need for another ad-hoc mechanism on top for this, which only works
> for a few special variables.

fair enough!
