### ISSUE TITLE
corfu doesn't work with typescript-language-server

### ISSUE THREAD

**Issue by jgarte** [minad/corfu#230]
Hi,

corfu doesn't work with typescript-language-server and eglot for some reason. I tested with company-mode/eglot and completions work fine.

@minad Any suggestions for how to debug this?

**Comment by minad** [comment]
I cannot help you since it is a backend issue. I don't even know what you mean by "it doesn't work". Did it delete your disk and reboot your computer? I assume there are some logs which you could look at. Furthermore you can try to monitor the internal Corfu state and try to follow the control flow in Corfu.

**Comment by minad** [comment]
Thanks, @manuel-uberti! This is likely a configuration issue in @jgarte's setup.

**Comment by jgarte** [comment]
> FTR, everything works fine for me in a basic JS file.
> 
> ![Screenshot from 2022-09-19 07-50-42](https://user-images.githubusercontent.com/8199224/190956621-c01fa116-83a6-483c-947d-39bfa7e6684e.png)
> 
> I just installed `typescript-language-server`, visited a `/tmp/Test.js` buffer, and hit `M-x eglot`

Hi @manuel-uberti 

Did that work for you without any additional configuration of corfu following this guide[guide](https://github.com/minad/corfu/wiki/Home/1bafa3a183ba2c960ff3f6c74cb5bbb963b22108#configuring-corfu-for-eglot)? What emacs version where you using when you tested that?

**Comment by jgarte** [comment]
Hi @manuel-uberti 

What configs do you have set from the wiki?

Just these?

```lisp

(setq completion-category-overrides '((eglot (styles orderless))))


(with-eval-after-load 'eglot
   (setq completion-category-defaults nil))
   ```

**Comment by jgarte** [comment]
Just adding my emacs version as notes for now:

GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)

**Comment by jgarte** [comment]
@manuel-uberti 

Completion seems to also not work for me with 

GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo

**Comment by jgarte** [comment]
Here's my relevant config:

```lisp
(use 'orderless) 
(setq completion-styles '(orderless))

(use 'corfu) 
(global-corfu-mode)
(setq-local corfu-auto t
            corfu-auto-delay 0
            corfu-auto-prefix 0)

(setq completion-category-overrides '((eglot (styles orderless))))
(with-eval-after-load 'eglot
   (setq completion-category-defaults nil))
```
