### ISSUE TITLE
is there a way to bind M-num to insert the selected candidate immediately in corfu-indexed-mode

### ISSUE THREAD

**Issue by ustcpxy** [minad/corfu#231]
Hi

when the corfu-indexed-mode enabled, the the index number is able to display as the candidate's prefix.
if I want to pick the third candidate, I have to type C-3 <tab> or M-3 <tab>.
although it works, it's not the most efficient.

is there a way to bind M-num to insert the selected candidate immediately?

**Comment by minad** [comment]
No this is not possible currently. We could add it as an additional/optional feature to vertico-indexed. If you are interested in this feature feel free to open a PR.

**Comment by okamsn** [comment]
This is what I'm doing in my own config with `corfu-indexed-start` set to 1. You could change this to use `cl-loop`, etc.

``` elisp
;; Bind C-num and M-num for convenience.
(loopy-iter
  (with (map corfu-map))
  (numbering i :from 1 :to 9)
  (let ((idx i))
    (define-key map (kbd (format "M-%d" i))
      (lambda () (interactive)
        (let ((current-prefix-arg idx))
          (call-interactively #'corfu-insert))))
    (define-key map (kbd (format "C-%d" i))
      (lambda () (interactive)
        (let ((current-prefix-arg idx))
          (call-interactively #'corfu-complete))))))

```

**Comment by unhammer** [comment]
Maybe this could be included in corfu-indexed-mode, possibly as a an optional `(defun corfu-indexed-setup-immediate-keys () …)`  that can be put in `use-package corfu-indexed :config`?

**Comment by minad** [comment]
@unhammer I think it is easier to use kmacros, see https://github.com/minad/corfu/issues/223#issuecomment-2085418643.

**Comment by unhammer** [comment]
Neat trick! It drops the M→insert, C→complete nuance, but I don't consider that big loss. But is it a danger that it assumes `corfu-complete` is always bound to tab?
