### ISSUE TITLE
unclear how to use corfu-history-mode

### ISSUE THREAD

**Issue by sobafuchs** [minad/corfu#238]
I want to start out by thanking you immensely for your work on `corfu`. It's truly awesome work. Now, getting to my issue, and maybe I misunderstood [the documentation](https://github.com/minad/corfu#extensions), but it states:

> The extensions are installed together with Corfu if you pull the package from ELPA. The extensions are inactive by default and can be enabled manually if desired. Furthermore it is possible to install all of the files separately, both corfu.el and the corfu-*.el extensions. 

I'm now trying to configure `corfu` with `corfu-history-mode` with `use-package` and I'm not clear on what the recommended approach is:

```emacs-lisp
(use-package corfu
  :custom
  (corfu-cycle t) ; Allows cycling through candidates
  (corfu-auto t) ; Enable auto-completion
  :init
  (global-corfu-mode)
  :config
  (corfu-history-mode)
  (savehist-mode)
  (add-to-list 'savehist-additional-variables 'corfu-history))
```

This triggers an error:

```
⛔ Error (use-package): corfu/:config: Symbol’s function definition is void: corfu-history-mode
```

I also tried setting `corfu-history-mode t` in `:custom` in the `use-package` block, that also does not seem to work. In that case nothing errors obviously but `corfu-history-mode` never gets turned on. Finally I ended up copying the `corfu-history.el` file into my emacs folder and running `(require 'corfu-history)` in the `:config` block of `use-package`. This finally works but I'm probably doing something wrong, correct? This seems like the wrong way to include `corfu-history-mode` given that the file is already included with `corfu` when being installed from elpa. 

If this is however the intended behavior and we are expected to literally copy-paste the file, then I would propose improving the documentation surrounding this (and I'd be happy to make that PR). At the moment the docs suggest IMO that one does *not* have to copy the files since they are already bundled with elpa. The comments in `corfu-history.el` also make it seem like you just need to invoke `(corfu-history-mode)`.

**Comment by minad** [comment]
Thanks! Your issue sounds like an installation issue since corfu-history-mode should be available as autoload. It works if you perform the following steps.

1. Start emacs -Q
2. Install corfu from ELPA via package-install
3. M-x global-corfu-mode
4. M-x corfu-history-mode

Does this help? Do you use another package manager like straight/borg? These may create problems if they pull the package directly from the repository, since corfu-history.el lives in the subdirectory extensions/.

**Comment by sobafuchs** [comment]
ahhh you're right. I do use `straight.el` Do i need to configure an extra `:load-path` for this?

**Comment by minad** [comment]
Yes, you can adjust the load-path or maybe instruct straight to move the files during installation. I don't know precisely how to do this since I don't use straight, but you can surely find the information in the straight docs.
