### ISSUE TITLE
Question: How to get completion without prefix?

### ISSUE THREAD

**Issue by mekeor** [minad/corfu#239]
How can I get completion without having written any character yet, i.e. with zero prefix? Is there a keybinding (or a function) that I can call in order to trigger Corfu even though I have not written any characters yet?

In my particular situation, I'm editing a YAML-file with GNU Emacs, yaml-mode, Corfu and Eglot (using yaml-language-server and a JSON schema). E.g. in VSCodium, I can use C-SPC to trigger completion without any prefix/query. How can I configure Corfu to behave similarly?

PS: Thank you very much for Corfu!

**Comment by mekeor** [comment]
You can use `completion-at-point`!

**Comment by mekeor** [comment]
I just also tried `(setq tab-always-indent 'complete)` but it didn't work well. I guess, because it decides to change the indentation instead of completing.

I also wonder if it's possible to trigger completion automatically after pressing `RET`. I guess, I could just bind `RET` to a custom function.

**Comment by minad** [comment]
@sethidden 

> As a side note, I was wondering why does pressing TAB not open the popup, but cycles instead (in my test case there were like 2 completions sent by the langserver).

This setting is not really *described* in the readme. Never blindly copy configurations without understanding every single line and its implications! ;)

But anyway, I've commented that out now in the README, since I don't recommend cycling as a default. I try to keep the README settings close to my configuration.

https://github.com/minad/corfu/commit/35cd5a0f3cba89766072e3e933d1fe2ee02f2289

**Comment by minad** [comment]
@sethidden 

> I've had some luck with evaluating (setq indent-line-function 'indent-relative-first-indent-point) in yaml-ts-mode - that seems to trigger completion-at-point (not corfu) when pressing TAB.

Do you think we should recommend indent-relative-first-indent-point in text modes if we can reliably set this up only in text modes? Note that there is always M-TAB to trigger completion and many people also use auto completion.
