### ISSUE TITLE
Cannot use with evil: compltion-in-region--data is always nil

### ISSUE THREAD

**Issue by thiderman** [minad/corfu#24]
Hai,

Whenever I run `corfu-complete`, I get get an error because `completion-in-region--data` is `nil`. This makes the `pcase-let*` fail, specifically when setting `(pt (max 0 (- (point) beg)))` since `beg` is `nil`. This fails on things that can cycle things with `dabbrev-expand`, like `corfu-`.

I'm using [evil-mode](https://github.com/emacs-evil/evil) and [general.el](https://github.com/noctuid/general.el). I'm using the example configuration of `corfu` from the README, with the addition of the following in the `:config` block.

```lisp
(general-define-key
 :states 'insert
 "TAB" #'corfu-complete)
```

I understand that it is completely possible that it's my using both of the above mentioned packages that's causing this error, but it feels like it might be something else.

What could I be missing or doing wrong?

**Comment by minad** [comment]
> What could I be missing or doing wrong?

`corfu-complete` is not supposed to be bound to TAB. Bind `completion-at-point` to TAB instead or `(setq tab-always-indent 'complete)`. Then enable `corfu-mode`. You can use the example configuration from the README.

**Comment by thiderman** [comment]
Hah, I felt I was probably doing something fundamentally wrong. Thanks for the pointer, and a general thanks for the many interesting packages you're the author for! :blush:

**Comment by minad** [comment]
Thanks :)
