### ISSUE TITLE
[Question] How to make corfu behave like (setq completion-auto-help t) 

### ISSUE THREAD

**Issue by BooAA** [minad/corfu#241]
Sorry if this request may sounds strange, but how can I configure corfu to not display the menu and just complete the common portion if available. I want to make the menu to be displayed only when there are no common parts to be completed. E.g. just as the behaviors described in the Emacs doc for setting `completion-auto-help` to t.

 ```text
completion-auto-help is a variable defined in ‘minibuffer.el’.

Its value is t

Non-nil means automatically provide help for invalid completion input.
If the value is t, the *Completions* buffer is displayed whenever completion is requested but cannot be done.
...
```
Whenever there are common portion, just complete it and hide the already displayed menu (if this is the first time completion got trigger, than just don't show the menu). Is this possible in corfu? Thanks.

**Comment by minad** [comment]
This feature is not supported and currently not planned, but would be an easy addition to `corfu--in-region`. I would accept a PR which adds this feature.

(If the popup is already displayed, the popup shouldn't be hidden again as you proposed.)
