### ISSUE TITLE
Usability of the corfu-indexed-mode

### ISSUE THREAD

**Issue by jumper047** [minad/corfu#242]
Company-mode has functionality similar to corfu's indexed mode, but while in corfu I need to press "M-3 RET" to select third candidate, in company candidate will be selected and inserted with only "M-3", without additional enter press. Is it possible to implement in corfu same behavior as in company?

**Comment by minad** [comment]
Sure, I'd welcome a PR which adds this (and also to vertico-indexed). Duplicate #231.

**Comment by jumper047** [comment]
Sorry, I should check existing issues first:( Thank you for pointing out to issue, seems like it's contains workaround!
