### ISSUE TITLE
corfu-map and yas-keymap conflicts

### ISSUE THREAD

**Issue by drcxd** [minad/corfu#244]
Hi, I have found that when expanding a snippet and when the completion list has poped up, TAB always execute the command defined in yas-keymap rather than the command defined in corfu-map?

Is that possible to make corfu-map have higher priority even when expanding a snippet?

**Comment by minad** [comment]
No, this issue should be fixed in yasnippet. Yasnippet uses an unconventional aggressive technique via a special keybinding (extended menu item) to grab the TAB key. But you can probably configure it differently.

**Comment by Eason0210** [comment]
@drcxd This can be fixed by customize the variable `yas-keymap-disable-hook`

I use the TAB-and-Go style Corfu key binding, and this configuration fix for me:
```
(use-package yasnippet
  :diminish yas-minor-mode
  :custom (yas-keymap-disable-hook
           (lambda () (and (frame-live-p corfu--frame)
                           (frame-visible-p corfu--frame))))
  :hook (after-init . yas-global-mode))
```

**Comment by drcxd** [comment]
Eason Huang ***@***.***> writes:

> @drcxd This can be fixed by customize the variable yas-keymap-disable-hook
>
> I use the TAB-and-Go style Corfu key binding, and this configuration fix for me:
>
> (use-package yasnippet
>   :diminish yas-minor-mode
>   :custom (yas-keymap-disable-hook
>            (lambda () (and (frame-live-p corfu--frame)
>                            (frame-visible-p corfu--frame))))
>   :hook (after-init . yas-global-mode))
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

Thanks for your advice.

I have already switched to package Tempel for code snippets. It seems
that yasnippet is not actively maintained. Its last update happended on
Jun 4, 2020.

**Comment by Eason0210** [comment]
> It seems that yasnippet is not actively maintained. Its last update happended on
Jun 4, 2020.

Yes, your are right. The recent maintainer (João Távora) is looking for a new maitainer for YASnippet. And He said YASnippet is stable enough. Meanwhle Eglot also depends on YASnippet to expand snippets, that's why I am using YASnippet.
