### ISSUE TITLE
No autocomplete in the minibuffer

### ISSUE THREAD

**Issue by salutis** [minad/corfu#245]
I enabled Corfu in the mini-buffer with `(add-hook 'minibuffer-setup-hook #'corfu-mode)` and everything works, except for autocomplete.  I have `corfu-auto` set to `t`, and Corfu autocompletes everywhere, but not in the mini-buffer.  Any ideas? 

P.S. I verified that `corfu-auto` equals `t` in the mini-buffer (via `M-:`).

**Comment by minad** [comment]
It works in my setup on Emacs 28 for `M-:` if I add the following to the `minibuffer-setup-hook`:

~~~ elisp
(defun +corfu-enable-in-minibuffer ()
  "Enable Corfu completion in the minibuffer, e.g., `eval-expression'."
  (when (where-is-internal #'completion-at-point (list (current-local-map)))
    (setq-local corfu-auto t)
    (corfu-mode 1)))
~~~

Please investigate further and create a minimal reproducible configuration based on emacs -Q.

**Comment by salutis** [comment]
> Please investigate further and create a minimal reproducible configuration based on emacs -Q.

I apologize for a shitty bug report.

# Repro steps

1. `emacs -Q`
2. Open `corfu.el`
3. `M-x eval-buffer RET`
4. `M-: (setq corfu-auto t) RET`
5. `M-: (add-hook 'minibuffer-setup-hook #'corfu-mode)`
6. `M-x cor`

# Expected

Corfu frame shows automatically after 0.2 seconds per `corfu-auto-delay`.

# Actual

No Corfu frame shows.

# Notes

- Corfu shows after typing TAB, but not automatically.
- Per Corfu docs, I also tried:

5. `(add-hook 'minibuffer-setup-hook (lambda () (setq-local corfu-auto t) (corfu-mode)))`


# Configuration

- Emacs 29, commit `f46e3b82bc`
- Corfu from `main`, commit `037978e`

**Comment by minad** [comment]
Maybe it is Mac or Emacs 29 specific regression? I will try Emacs 29 in a few months when the release date comes closer.

**Comment by terlar** [comment]
For whatever it is worth I have tried this with Emacs 29 (on Linux though) and it is working. I used the configuration suggested by @minad.

**Comment by salutis** [comment]
Based on all of the above, it seems that we have a Mac-specific bug here.
