### ISSUE TITLE
delete-consecutive-dups doesn't play well with lsp's quick fix completions

### ISSUE THREAD

**Issue by cwhatley** [minad/corfu#246]
https://github.com/minad/corfu/blob/0d0b2c9fd97103eacc892ca79c5597f770fdee85/corfu.el#L643

When using a language like python under LSP mode, you can have multiple completion options leading to the same string insertion yet they have different quick-fix side effects.

E.g., "Count" has among its valid completions returned by the language server a completion string of "Counter" with three different quick-fix options for importing Counter from the "collections", "typings", and "typing_collections" packages. When delete-consecutive-dups is used in this way, it only shows whatever the lang server provided first. Whether you accept the completion or not, you end up with some manual cleanup that could be avoided if deleting dups was optional.

![image](https://user-images.githubusercontent.com/573757/202249332-201492a4-9afa-4b31-b83f-c42a0d72606e.png)

Seems like that isn't the full story though and that there are downstream assumptions of uniqueness. Tried redefining corfu--recompute without the deletion of dups, but if I choose the third "Counter" option, it always does the first action unless I move the selection past the one I want and go back.

This is something that I snag on a few times a day with Python.

**Comment by minad** [comment]
Thanks for the report. The uniqueness assumption is baked into the Emacs definition of the completion mechanism. For example the function completion-all-sorted-completions deletes duplicates. 

Ideally this should be fixed in lsp-mode, for example by adding unique suffixes, e.g. Counter(1), Counter(2), ...

There has already been a discussion of this in duplicate issue #173.

**Comment by minad** [comment]
You can test the duplicate deletion of the default completion UI. Start Emacs 28 with emacs -Q and execute the following code in the scratch buffer:

~~~ elisp
;; Test completing-read
(let ((minibuffer-allow-text-properties t))
  (completing-read "Duplicates: "
                   (list (propertize "candidate1" 'face 'error)
                         (propertize "candidate1" 'face 'warning)
                         (propertize "candidate1" 'face 'success)
                         (propertize "candidate2" 'face 'error)
                         (propertize "candidate2" 'face 'warning)
                         (propertize "candidate2" 'face 'success)
                         (propertize "candidate3" 'face 'error)
                         (propertize "candidate3" 'face 'warning)
                         (propertize "candidate3" 'face 'success)
                         (propertize "candidate4" 'face 'error)
                         (propertize "candidate4" 'face 'warning)
                         (propertize "candidate4" 'face 'success))))

;; Test TAB completion
(setq tab-always-indent 'complete
      completion-at-point-functions
      (list
       (lambda ()
	 (when-let (bounds (bounds-of-thing-at-point 'symbol))
	   (list (car bounds) (cdr bounds)
		 (list (propertize "candidate1" 'face 'error)
		       (propertize "candidate1" 'face 'warning)
		       (propertize "candidate1" 'face 'success)
		       (propertize "candidate2" 'face 'error)
		       (propertize "candidate2" 'face 'warning)
		       (propertize "candidate2" 'face 'success)
		       (propertize "candidate3" 'face 'error)
		       (propertize "candidate3" 'face 'warning)
		       (propertize "candidate3" 'face 'success)
		       (propertize "candidate4" 'face 'error)
		       (propertize "candidate4" 'face 'warning)
		       (propertize "candidate4" 'face 'success)))))))
~~~

**Comment by minad** [comment]
However something odd is going on if we specify an annotation-function which returns different annotations for the candidates. Then the default completion UI will indeed display the duplicate candidates

~~~ elisp
;; Test completing-read
(let ((minibuffer-allow-text-properties t)
      (completion-extra-properties
       (list :annotation-function (lambda (cand) (format "%S" (get-text-property 0 'face cand))))))
  (completing-read "Duplicates: "
                   (list (propertize "candidate1" 'face 'error)
                         (propertize "candidate1" 'face 'warning)
                         (propertize "candidate1" 'face 'success)
                         (propertize "candidate2" 'face 'error)
                         (propertize "candidate2" 'face 'warning)
                         (propertize "candidate2" 'face 'success)
                         (propertize "candidate3" 'face 'error)
                         (propertize "candidate3" 'face 'warning)
                         (propertize "candidate3" 'face 'success)
                         (propertize "candidate4" 'face 'error)
                         (propertize "candidate4" 'face 'warning)
                         (propertize "candidate4" 'face 'success))))

;; Test TAB completion
(setq tab-always-indent 'complete
      completion-at-point-functions
      (list
       (lambda ()
	 (when-let (bounds (bounds-of-thing-at-point 'symbol))
	   (list (car bounds) (cdr bounds)
		 (list (propertize "candidate1" 'face 'error)
		       (propertize "candidate1" 'face 'warning)
		       (propertize "candidate1" 'face 'success)
		       (propertize "candidate2" 'face 'error)
		       (propertize "candidate2" 'face 'warning)
		       (propertize "candidate2" 'face 'success)
		       (propertize "candidate3" 'face 'error)
		       (propertize "candidate3" 'face 'warning)
		       (propertize "candidate3" 'face 'success)
		       (propertize "candidate4" 'face 'error)
		       (propertize "candidate4" 'face 'warning)
		       (propertize "candidate4" 'face 'success))
		 :annotation-function (lambda (cand) (format "%S" (get-text-property 0 'face cand))))))))
~~~

I think lsp-mode makes use of this ill-defined behavior. Note that you can still not get back a propertized candidate from completing-read. I suspect that this is an implementation mistake in the default completion implementation.

**Comment by cwhatley** [comment]
I'm seeing that if you have an exit function for completing read, then the properties are available there, but I'm not seeing it work for completion-at-point. Too bad. I guess my solution is just to turn off corfu in LSP and use company there.

```
(let ((minibuffer-allow-text-properties t)
      (completion-extra-properties
       (list :annotation-function (lambda (cand) (format "%S" (get-text-property 0 'desc cand)))
	     :exit-function (lambda (cand status) (message "%S" (get-text-property 0 'desc cand)))
	     )))
  (completing-read "Duplicates: "
                   (list (propertize "candidate1" 'desc 'error)
                         (propertize "candidate1" 'desc 'warning)
                         (propertize "candidate1" 'desc 'success)
                         (propertize "candidate2" 'desc 'error)
                         (propertize "candidate2" 'desc 'warning)
                         (propertize "candidate2" 'desc 'success)
                         (propertize "candidate3" 'desc 'error)
                         (propertize "candidate3" 'desc 'warning)
                         (propertize "candidate3" 'desc 'success)
                         (propertize "candidate4" 'desc 'error)
                         (propertize "candidate4" 'desc 'warning)
                         (propertize "candidate4" 'desc 'success))))
```

**Comment by minad** [comment]
As I wrote, this should be fixed in Lsp. Lsp should not rely on the text properties being available. Furthermore it should not rely on duplicates. I could relax Corfu to pass properties to the :exit-function and not delete duplicates as long as they differ in their properties, but then we end up with a patch work of incompatible completion UIs.
