### ISSUE TITLE
wrong height of child frame when using tab-line-mode

### ISSUE THREAD

**Issue by ilupin** [minad/corfu#25]
tab-line-mode disabled:

![image](https://user-images.githubusercontent.com/5555871/120953162-04c93000-c77f-11eb-85ed-c4a447ae765b.png)

tab-line-mode enabled:

![image](https://user-images.githubusercontent.com/5555871/120953090-e6fbcb00-c77e-11eb-83a4-8b899de66151.png)

**Comment by minad** [comment]
Yes, I can confirm this.
