### ISSUE TITLE
Regression: the doc popup is positioned incorrectly when on the left with NS port Emacs

### ISSUE THREAD

**Issue by galeo** [minad/corfu#250]
@minad I see that you removed the code during refactoring that handles the [Emacs bug #58627](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=58627) described in galeo/corfu-doc#23. Now the problem reappears on NS port Emacs 28.2. I have explained the problem [here](https://github.com/minad/corfu/pull/178#issuecomment-1308144349). Do you have any special considerations? Thanks.

**Comment by minad** [comment]
I prefer to wait if Emacs 29 fixes the issue before maintaining workarounds. I also wonder - when do we get negative offsets? Usually this shouldn't happen if you use a maximized Emacs frame?

**Comment by galeo** [comment]
It's fixed now. Thanks.

> I also wonder - when do we get negative offsets? Usually this shouldn't happen if you use a maximized Emacs frame?

This problem occurs regardless of whether NS port Emacs is maximized or not. When I first calculated the left position I found it easier to use negative offsets. For the display within the frame and in order to solve this problem, the current calculation method seems to be better.
