### ISSUE TITLE
corfu-quick-jump: Symbol’s function definition is void: corfu--echo-cancel

### ISSUE THREAD

**Issue by galeo** [minad/corfu#252]
> BREAKING: Extract the corfu-echo extension from corfu.el. In order to see echo messages, enable corfu-echo-mode. You probably want to enable either corfu-echo-mode or corfu-popupinfo-mode.

Since `corfu-echo` has been extracted, I think this line should be removed:
https://github.com/minad/corfu/blob/aab6f7e34d7a65f060ba196cf1b1c62d6ceb9e43/extensions/corfu-quick.el#L127

Otherwise, using `corfu-quick` directly will result in an error.

**Comment by minad** [comment]
Thanks!
