### ISSUE TITLE
corfu-popupinfo cuts of documentation in lsp-mode

### ISSUE THREAD

**Issue by stevemolitor** [minad/corfu#255]
The new `corfu-popupinfo` extension cuts off documentation in `lsp-mode` (at least). 

![](https://cdn.zappy.app/3413ae5f04119a9bac16fa7ba304174e.png)

In the `add-corfu-doc` branch, commit 718e9c4, it looks like this:

![](https://cdn.zappy.app/a5082428affa36f2190995fde49031ed.png)

Note that in the first example the documentation gets cut off - "Subscribes component ". In the older code in the second example it does not get cut off - "Subscribes component to updates of the given state."

I did not see documentation get cut off in emacs-lisp mode - everything looked good there. But I do see it get cut off in lsp-mode. I have not tried other modes.

Also note that the formatting of the text is better in the older commit (although the placement on the right hand side is nicer in the new code.)

I am using ns emacs 29.0.50.

**Comment by minad** [comment]
I believe this should be fixed in Corfu 0.33. Please check.

**Comment by Eason0210** [comment]
Now the issue has been fix with Eglot. Thanks @minad

**Comment by stevemolitor** [comment]
It is inconsistent when I set  `corfu-popupinfo-direction` to `horizontal`. Sometimes I see this (bad):

![](https://cdn.zappy.app/caa5acabe63a396e5f96832bd5c404dd.png)

Sometimes as I complete or start completion over it works (good):

![](https://cdn.zappy.app/5490fbdfd97041925a3c3e80d478117d.png)

So far at least it _does_ seem to work consistently when I set `corfu-popupinfo-direction` to `vertical`:

![](https://cdn.zappy.app/914d97d2e53eb0291ea9a4315da963a8.png)

I am using commit b9727c5.

**Comment by minad** [comment]
@stevemolitor The bad look should only occur if the popup doesn't fit. But maybe the size computation of the text is also not correct. I will fix this in case I observe it again in my
