### ISSUE TITLE
corfu-popupinfo behaves a bit weirdly when the newly switched candidates have no documentation

### ISSUE THREAD

**Issue by galeo** [minad/corfu#258]
I usually set the value of `corfu-popupinfo-delay` to a relatively small value, such as `0.1`. To reduce flickering, I set `corfu-popupinfo-hide` to `nil`. Under this setting, when the switched next few candidates that have no documentation, the doc popup will always display first and then quickly hide, and the displayed content will always be the documentation of the old candidate which has documentation. corfu-popupinfo did not update the recorded candidate during this operation. This makes it look like a bug.

**Comment by minad** [comment]
@galeo If you have a fix, please create a PR. We could for example not hide the candidate if corfu-popup-hide is nil or alternatively replace the popup content with "No documentation available". I close this since I think the current default behavior is okay.

**Comment by galeo** [comment]
> If you have a fix, please create a PR. We could for example not hide the candidate if corfu-popup-hide is nil or alternatively replace the popup content with "No documentation available". I close this since I think the current default behavior is okay.

I'll dig into it when I have time.

**Comment by minad** [comment]
@galeo If you find time, you may also want to take a look at the various TODOs I put into the code. For example the direction left/right isn't fixed correctly. Maybe you have some ideas?

**Comment by galeo** [comment]
> If you find time, you may also want to take a look at the various TODOs I put into the code. For example the direction left/right isn't fixed correctly. Maybe you have some ideas?

One thing I can think of quickly is not good is that if a certain doc popup is very small, once the left/right direction is fixed, if another candidate's documentation is very long, it will cause it to appear in a very narrow area. I'll take a look then, might this weekend.

**Comment by minad** [comment]
Thanks. If there isn't enough space it won't look good, but I find the jumping popup very annoying. In a perfect implementation there would probably be some threshold to determine if the direction should stay fixed. Otherwise the direction would be unfixed. But that's obviously a complication.

Regarding this issue, would it suffice to reset the corfu-popupinfo--candidate here?

https://github.com/minad/corfu/blob/6c098ba9c96d43a0f93d53ebf582693fdf47bfcf/extensions/corfu-popupinfo.el#L374

If yes we can fix this quickly. Feel free to create a PR for a quick merge.

**Comment by minad** [comment]
Thinking about this again, it may be better to check if the popup is still visible.

Here:

https://github.com/minad/corfu/blob/6c098ba9c96d43a0f93d53ebf582693fdf47bfcf/extensions/corfu-popupinfo.el#L476

And here:

https://github.com/minad/corfu/blob/6c098ba9c96d43a0f93d53ebf582693fdf47bfcf/extensions/corfu-popupinfo.el#L481

**Comment by galeo** [comment]
> If there isn't enough space it won't look good, but I find the jumping popup very annoying. In a perfect implementation there would probably be some threshold to determine if the direction should stay fixed. Otherwise the direction would be unfixed. But that's obviously a complication.

Just glanced at the code, I see you have added a lot of `always-` options. Because it is limited to display the popup within the frame, it is not ideal to fix the direction in many cases. Most likely the documentation popup will be small or cut off, especially when the frame is not maximized or the candidate item is very long.

From my personal habits, I think the jumping popup is acceptable, at least horizontally. The offset of the doc popup relative to the candidate will not be very large, it can reduce the situation described above that the popup size is very small. A lot of designs I've observed do this kind of adaptation, like context menus.

Well, I'll think about it sometime later. Thanks.

**Comment by minad** [comment]
I find left/right jumps unacceptable if there is still sufficient space for a popup but not enough to show the full documentation text (smaller than corfu-popupinfo--size). I agree with you that the always options are not perfect, but we should get them for free, if we implement the direction fixing correctly.
