### ISSUE TITLE
"No match" messages

### ISSUE THREAD

**Issue by haji-ali** [minad/corfu#262]
I have `corfu-quit-no-match` set to `separator` with `corfu-auto` set to `t` and `corfu-separator` set to 32. I also have `corfu-line` in `completion-at-point-functions`.

I am noticing what I think is the wrong behavior where if I input some text which doesn't have a match nothing shows up *until* I press space wherein "No Match" shows up and doesn't quit until I press `C-g`.

Reading the documentation of `corfu-quit-no-match`, I thought "No Match" would show up when there are no matches and then disappear when I press the separator (spacebar).

As an aside, can I configure "No Match" to not block movement keys? In other words, if "No Match" shows up, I want `corfu-map` to not be activated and movement keys should move the point as usual and quit corfu.

**Comment by minad** [comment]
Try to set corfu-quit-no-match to nil.

**Comment by haji-ali** [comment]
Yes, this is much better which I will stick to. But does this mean the behavior with `corfu` quitting on separator is intentional?

Is there a way to configure corfu keys to quit corfu when there's no match? Maybe remove `corfu-map` from `completion-in-region-mode` when there's no match and add it when there are matches?

**Comment by minad** [comment]
The current behavior is intentional. Please take a look at the README. Iirc it is all described there.

> Is there a way to configure corfu keys to quit corfu when there's no match? 

Of course. In order to do that set `corfu-quit-no-match` to t.

**Comment by minad** [comment]
> But does this mean the behavior with corfu quitting on separator is intentional?

If you don't want to quit on separator you can obviously do this:

~~~ elisp
(define-key corfu-map " " #'corfu-insert-separator)
~~~
