### ISSUE TITLE
Do `corfu-popupinfo` interactive functions need autoload tags?

### ISSUE THREAD

**Issue by gcv** [minad/corfu#265]
`corfu-popupinfo-toggle` and the other `(interactive)` functions don't automatically do `(require 'corfu-popupinfo)`. I think..? I want to only enable manual documentation display, and I'm trying to do it like this:

```
(use-package corfu
  :bind
  (:map corfu-map
        ("M-d" . corfu-popupinfo-toggle))

  :init
  (global-corfu-mode 1)
  (setq tab-always-indent 'complete)
  )
```

I think `corfu-popupinfo-toggle` needs an `autoload` tag for that to work.

**Comment by minad** [comment]
I've considered it. But then I decided to rather provide an extra keymap corfu-popupinfo-mode for simplicity. You have to load the extension by enabling corfu-popupinfo-mode. Of course you can delay via use-package/autoload I'm your config.
