### ISSUE TITLE
Document how to load extensions with use-package

### ISSUE THREAD

**Issue by titaniumbones** [minad/corfu#274]
I'm having a little trouble figuring out the proper way to load extensions when using use-package. From what I can tell, the `extensions` directory is not added to `load-path` on package installation. So far this is what I'm doing, but it depends on quelpa and is quite hackish: 

```lisp
(use-package corfu
  :ensure t 
  :quelpa ((corfu :fetcher github :repo "minad/corfu") :upgrade t)
  :load-path "quelpa/build/corfu/extensions"
  ;; Optional customizations
  :init 
   (require 'corfu-popupinfo)
   (setq corfu-popupinfo-delay 0.2)
   (corfu-popupinfo-mode)
  :config
  (global-corfu-mode)
  )
```

Is there a better option? Thanks.

**Comment by minad** [comment]
I am not familiar with Quelpa, but it seems reasonable to adjust the load-path. Installation via Straight requires a similar modification. Does Quelpa ensure that all the *.el files are compiled? That's important.

Generally I recommend to install my packages via package.el from ELPA(-devel), depending on your stability preferences. I don't want to add documentation for alternative package managers to the README. There are too many (Quelpa/Straight/Elpaca/Borg/...). All the necessary information should be available in the respective manuals.
