### ISSUE TITLE
corfu-popupinfo: clicking on a doc link transfers corfu to new window

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#277]
Let corfu-popupinfo bring up docs for, e.g. `seq-find`.  Mouse-1 on `in the __sequence__ group`.  Corfu + popupinfo are transferred to the popped-to buffer's window.   Ideally this would just work, leaving corfu where it is.

**Comment by minad** [comment]
Duplicate of #112. Corfu should just close in such scenarios.
