### ISSUE TITLE
corfu-popupinfo: stops working after the first doc shown

### ISSUE THREAD

**Issue by d9d6ka** [minad/corfu#278]
Hi! Glad to see `corfu-doc-mode` included into `corfu`!

I've bumped into an issue: after the documentation is shown for the first time `corfu-popupinfo` starts throwing the following error

> Error running timer ‘corfu-popupinfo--show’: (wrong-type-argument listp corfu-popupinfo)

Interestingly, with some manipulations with [ESC] key I can make it work but for a single time only.

Screencapture included:
![Анимация](https://user-images.githubusercontent.com/29946047/207930677-6ce8c400-69d7-4799-a710-b5962a65a25f.gif)

I use Emacs 28.2 on Windows 11. Emacs is installed via Scoop.

The config snippet for `corfu` is further. I use `setup.el` instead of `use-package`. Packages are installed via `straight`.
```elisp
(setup (:straight (corfu :files (:defaults "extensions/*")
                             :includes (corfu-popupinfo))
                      kind-icon
                      popon
                      corfu-terminal
                      (corfu-doc-terminal
                       :type git
                       :repo "https://codeberg.org/akib/emacs-corfu-doc-terminal.git"))
        (:option corfu-auto nil
                 corfu-cycle t
                 corfu-preselect-first nil
                 corfu-preview-current 'insert
                 tab-always-indent 'complete
                 kind-icon-default-face 'corfu-default)
        (:bind-into corfu-map
            "TAB" corfu-next
            [tab] corfu-next
            "S-TAB" corfu-previous
            [backtab] corfu-previous)
        (global-corfu-mode)
        (corfu-popupinfo-mode)
        (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter)
        (add-to-list 'completion-at-point-functions #'cape-file t)
        (unless (display-graphic-p)
            (corfu-terminal-mode t)
            (corfu-doc-terminal-mode t)))
```

**Comment by minad** [comment]
I don't see this in my configuration. Please try to reproduce the issue with emacs -Q and create a minimal recipe.

**Comment by d9d6ka** [comment]
I've tried my config snippet without extra packages, the error is still there.

Unfortunately, I didn't manage to reproduce the error with emacs -Q because for some reason emacs consumed all of my 32GB RAM while building straight.el...

**Comment by minad** [comment]
Try a setup without straight.

**Comment by d9d6ka** [comment]
Ok, I wiped `.emacs.d` and installed only straigt, setup and corfu. And there is no problem!

Will search for settings causing errors.

**Comment by minad** [comment]
The issue must be resolved on the side of dimmer.
