### ISSUE TITLE
broken regexp in corfu-popupinfo.el

### ISSUE THREAD

**Issue by mattiase** [minad/corfu#279]
You may want to take another look at the regexp
```
                  "[\\s-\n]*\\[back\\][\\s-\n]*"
```
which probably doesn't work the way intended. The `[\\s-\n]` subexpressions denotes a set which includes the literal backslash character and the range from `s` to newline, or 115 to 10, but since that range starts higher than it ends it includes no characters at all. In other words, `[\\s-\n]` matches a backslash and nothing else.

Emacs regexps are often hard to write and read; you may want to try `rx`. The `relint` package also helps finding regexp mistakes (it found this one).

**Comment by minad** [comment]
Thanks. I don't like rx since I find it too verbose. Also I am accustomed to the short regexp syntax, since I wrote quite a bit of Perl a while back. But Emacs regexps are uglier and I particularly dislike the syntax classes, which were also used incorrectly here.
