### ISSUE TITLE
corfu-popupinfo: min-width and height not respected

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#281]
I noticed that corfu-popup-info-min-width and min-height now do not enforce a minimum size for the popup, instead just checking if such a size would fit on one side or another.

**Comment by minad** [comment]
That's intentional.

**Comment by jdtsmith** [comment]
The issue is that sometimes the first few lines of a doc has a calling syntax with arguments _one per line_, so the popup-window is _very_ narrow.  One solution might be to size it based on line width of the full doc, instead of the first lines shown.

**Comment by jdtsmith** [comment]
I still wish for a real min-width/height.  Here's an example:

![image](https://user-images.githubusercontent.com/93749/216832816-70872f9d-9523-4337-afa0-bed3e3783a6f.png)

Scrolling this down to read is painful.  And then just next door, much better:

![image](https://user-images.githubusercontent.com/93749/216832931-2a47de9f-6852-44bb-9837-93ce96cb95de.png)

Yes, these docsigs from the same package are formatted differently, but right now popupinfo width depends sensitively on what the docstring author happened to put in the first few lines.  So perhaps it would also work to infer the width from the full doc returned, not just its first displayed lines.

**Comment by minad** [comment]
1. We cannot do much about the formatting, see:

https://github.com/minad/corfu/blob/f02cf6d616dab982ffae3af350e0c945b3602469/extensions/corfu-popupinfo.el#L347

2. But we could take more text into account by not specifying max-height here:

https://github.com/minad/corfu/blob/f02cf6d616dab982ffae3af350e0c945b3602469/extensions/corfu-popupinfo.el#L243

Could you experiment a bit and potentially propose a patch?

**Comment by jdtsmith** [comment]
I took a look today, but it seems you've already fixed this by looking a bit deeper into the doc buffer for max pixel-width.   Seems to be working well here for my cases.
