### ISSUE TITLE
Possible bad interaction with eglot

### ISSUE THREAD

**Issue by psethwick** [minad/corfu#283]
There's an ongoing discussion here: https://github.com/joaotavora/eglot/discussions/1127

Corfu _seems_ like a common connection to people having problems (me included)

Any ideas how we can track this down or rule out corfu?

**Comment by minad** [comment]
I am not sure, but it could be that Eglot doesn't handle interrupts well. You can try:

~~~ elisp
(advice-add #'eglot-completion-at-point :around #'cape-wrap-noninterruptible)
~~~

This will have the unfortunate consequence that Corfu will be slower. Ideally Eglot should make sure that its Capf is robust with respect to interruption. Please let me know if you make progress on this issue.

cc @jdtsmith

**Comment by jdtsmith** [comment]
> it could be that Eglot doesn't handle interrupts well 

This sounds like a possible explanation. Making the CAPF non-interruptible for people who can reproduce the loss of sync quickly is a good quick test.  

The didChange events come only indirectly via completion and are generated by eglot's before+after-change-function; it's not clear interrupting the CAPF could do anything to those unless they are called from inside the CAPF.
