### ISSUE TITLE
Track font changes in parent window

### ISSUE THREAD

**Issue by ft** [minad/corfu#286]
I am using emacs with corfu on laptops, that change their screen setup commonly (stand-alone and on different docking stations as well as projectors). Because of that, I have some code that changes frame-font sizes on the fly. Basically, it's just something along the lines of:

```elisp
;; …where the 16 is calculated.
(modify-frame-parameters nil '((font . ""DejaVu Sans Mono-16")))
```

As it turns out, corfu uses an internal frame parameter (`corfu--frame`),  that — among other things — carries information inherited from the parent window. Including font selection. This causes the size calculation of the overlay to be off, when first using corfu with a certain font-setup and then changing the frame's fonts later.

I think a couple of pictures help to explain what I mean:

So here's my emacs just after it started. Everything looks perfect:

![corfu-popup-default](https://user-images.githubusercontent.com/128797/211064092-58a873eb-1879-4744-a47e-d1781d8c153f.png)

Then when reducing font size of the GUI frame, the corfu frame is still using the old (bigger font). Frame size is therefore wrong:

![corfu-popup-toobig](https://user-images.githubusercontent.com/128797/211064091-47ccd1a6-d046-4351-8581-d7fe7a07c1f7.png)

The reverse effect can also be observed when the GUI frame's font is increase beyond its initial font-size:

![corfu-popup-toosmall](https://user-images.githubusercontent.com/128797/211064090-6915fd42-44e0-4c93-9717-d7d74c646f07.png)

To fix the font sizes is fairly straight forward, just by copying the font-spec from the parent frame to `corfu--frame`:

![corfu-popup-fixed](https://user-images.githubusercontent.com/128797/211064083-9558a2c8-9f85-426d-8736-476ef36f3ee8.png)

I've looked at the code, and here's a patch that fixes the issue for me:

```udiff
diff --git a/corfu.el b/corfu.el
index 4a3579e..4cadc09 100644
--- a/corfu.el
+++ b/corfu.el
@@ -408,6 +408,10 @@ FRAME is the existing frame."
                      (internal-border-width
                       . ,(alist-get 'child-frame-border-width corfu--frame-parameters))
                      ,@corfu--frame-parameters))))
+    ;; Track parent font in case it changed (if only in size).
+    (let ((pfont (frame-parameter parent 'font)))
+      (unless (string= pfont (frame-parameter frame 'font))
+        (set-frame-parameter frame 'font pfont)))
     ;; XXX HACK Setting the same frame-parameter/face-background is not a nop.
     ;; Check before applying the setting. Without the check, the frame flickers
     ;; on Mac. We have to apply the face background before adjusting the frame
```

I don't know if it's worth it to check for differences first and then set the `font` parameter, or if it's just as fair to copy the parent's font spec in unconditionally. At any rate, something along these lines fixes the issue.

Also, thanks for another great emacs package! :)

**Comment by minad** [comment]
Thanks! I suggest we resolve the issue differently since changing the font on the fly seems a bit uncommon. Also you modify the font actively. At the place where you modify the font, add this code:

~~~ elisp
(ignore-errors (delete-frame corfu--frame))
(ignore-errors (delete-frame corfu-popupinfo--frame))
(setq corfu--frame nil corfu-popupinfo--frame nil)
~~~

I hope that's okay for you. Maybe there are even other frame parameters which could change under special circumstances and the benefits of checking all of them does not seem justified.

**Comment by ft** [comment]
Yeah, I have a workaround like that in my config at the moment. The thing is, that it feels wrong to muck about with internal parameters, that might be gone or completely changed in the future. I take it the double dash is  convention to mark non-API parameters.

Also, with the emergence of high DPI displays and other output media like (comparatively) low-resolution projectors, I don't think it's too uncommon to change frame fonts anymore.

**Comment by minad** [comment]
> Yeah, I have a workaround like that in my config at the moment. The thing is, that it feels wrong to muck about with internal parameters, that might be gone or completely changed in the future.

As far as I can tell corfu--frame is a unproblematic variable. In the unlikely case that this variable would go away or would be changed it would not be hard for you to adjust.

> Also, with the emergence of high DPI displays and other output media like (comparatively) low-resolution projectors, I don't think it's too uncommon to change frame fonts anymore.

Yes, but my point is that Emacs does not do this font size change out of the box. Right now we handle more common adjustments like text scaling, theme change, which are usually just a key press away. So far nobody had this particular font size changing issue, from which I can conclude that your setup is uncommon.

**Comment by minad** [comment]
Thanks. Another thing to consider is that I've never inspected the exhaustive list of frame parameters (and other things) which could modify how the Corfu popup behaves. This means I've just added checks on a case by case basis if issues popped up and if the issue seemed important enough. If font is indeed the last missing thing we should check, I think I wouldn't mind adding it. But if that's not the case and there are another ten parameters we should check eventually we would need to change the current approach and maybe loop over a list of parameters to check. It would be great to check all parameters and test how they affect or not affect Corfu.
