### ISSUE TITLE
Coexisting with company

### ISSUE THREAD

**Issue by haji-ali** [minad/corfu#287]
I am using corfu (with cape) for most of my needs, except for `notmuch-address` where an async seems indispensable to obtain the list of addresses. There's only one place in a new message where company is activated (when the line starts with "To:" or similar), otherwise company is not activated and I want to use corfu as usual.

The problem at the moment is that both company and corfu are activated (with corfu on top, hiding the list of addresses). Is there a way to disable corfu on specific lines where I know company will activate?

**Comment by minad** [comment]
You can try turning on Corfu and Company only locally per buffer (use the local modes). Using both in the same buffer at the same time is not possible.

**Comment by haji-ali** [comment]
I am not sure how good of a solution this is, but after some tinkering I came up with

```
(defun my/prefer-company-completion-at-point ()
  (when (my/company-will-run-p)
    (let ((bounds (bounds-of-thing-at-point 'word)))
      (when bounds
        (list (car bounds)
              (cdr bounds)
              nil)))))

(add-hook 'completion-at-point-functions
          #'my/prefer-company-completion-at-point
          nil t)
```

Where `my/company-will-run-p` is a function that return non-nil when company should be enabled in a specific context.

**Comment by agenbite** [comment]
@haji-ali, do you have your dotfiles available somewhere? I'm interested in your solution and would like to have a look at your`/company-will-run-p`. :)

EDIT: nevermind, I solved my issue with 
```
  (add-hook! 'notmuch-message-mode-hook #'company-mode)
  (add-hook! 'notmuch-message-mode-hook #'company-prescient-mode)
  (add-hook! 'notmuch-message-mode-hook (lambda () (corfu-mode -1)))
```
I don't need corfu when writing emails, so this is just fine.
