### ISSUE TITLE
Height of `corfu-popupinfo` face

### ISSUE THREAD

**Issue by protesilaos** [minad/corfu#288]
Hello Daniel,

In my config I change the `corfu-popupinfo` to `1.0` because my default font size is small (`:height 100`).  This is not a problem with this face, though I wonder what you think about applying this change at a theme level.  I am inclined to leave it as-is, since no one has ever complained about it.

**Comment by minad** [comment]
Actually I would have preferred if things just stay as is, but I wouldn't want themes to override this, since this leads to an overall incoherent appearance.

**Comment by protesilaos** [comment]
This is fine.  Thank you!
