### ISSUE TITLE
Fonts in corfu overlay don't match the frame font

### ISSUE THREAD

**Issue by roman-kashitsyn** [minad/corfu#296]
Fonts in Corfu suggestions do not match my main frame font:
<img width="567" alt="Screen Shot 2023-02-03 at 11 19 55" src="https://user-images.githubusercontent.com/847968/216576059-91346aae-d470-4e06-8175-cd9b20d102c1.png">

However, Corfu doesn't seem to override the default font family in its faces.

Configuration:
```lisp
(set-frame-font "Source Code Pro-12:weight=medium")

(use-package corfu
  :custom
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  (corfu-auto t)                 ;; Enable auto completion
  (corfu-separator ?\s)          ;; Orderless field separator
  :init
  (global-corfu-mode))

```

Platform: macOS
Corfu version: 0.34
Emacs version: 28.1

**Comment by minad** [comment]
You should probably set the font globally instead of only for the current frame. Then every frame will use the same font. See also the FRAMES argument of set-frame-font.

**Comment by roman-kashitsyn** [comment]
Thank you for the suggestion, @minad! Changing the font settings to the following fixed the issue:
```lisp
(set-frame-font "Source Code Pro-12:weight=medium" nil t)
```
