### ISSUE TITLE
Removing the space betwen the Corfu index and the kind icon

### ISSUE THREAD

**Issue by LemonBreezes** [minad/corfu#298]
![image](https://user-images.githubusercontent.com/29102529/218371950-402ab0ae-d482-4ac6-9ced-e794fa53c942.png)
Hi. Would it be possible to add an option to customize the display of the Corfu index? I would like to remove the space between the icon and the number.  The culprit is the `,(1+ width)` part of
![image](https://user-images.githubusercontent.com/29102529/218372198-8b24f98f-6d61-405d-8cb2-dafc27f608ae.png)
After replacing that sexp with just `width`, the new appearance of the completion window is this:
![image](https://user-images.githubusercontent.com/29102529/218372597-999ef1d4-096b-4e3f-8904-ca89b6660beb.png)

**Comment by minad** [comment]
> Would it be possible to add an option to customize the display of the Corfu index? I would like to remove the space between the icon and the number. The culprit is the ,(1+ width) part of

If we remove the 1+ the popup window will become misaligned with respect to the prompt. Therefore we cannot go with that simple solution. As an alternative we could swap index and icon. Do you prefer that? See https://github.com/minad/corfu/commit/5baad51b6c2b4a3f1eaddc9245fe761d62c5b2b9? If yes, I wouldn't mind to merge this.

**Comment by LemonBreezes** [comment]
> > Would it be possible to add an option to customize the display of the Corfu index? I would like to remove the space between the icon and the number. The culprit is the ,(1+ width) part of
> 
> If we remove the 1+ the popup window will become misaligned with respect to the prompt. Therefore we cannot go with that simple solution. As an alternative we could swap index and icon. Do you prefer that? See [5baad51](https://github.com/minad/corfu/commit/5baad51b6c2b4a3f1eaddc9245fe761d62c5b2b9). If yes, I wouldn't mind to merge this.

That looks pretty great to me! Now the indices are a bit easier to see.

**Comment by minad** [comment]
Thinking about it again - unfortunately this won't work since the icon is part of the prefix, but the prefix could also come directly from the original affixation-function, in which case we would want the index in front of the prefix. The solution for this problem will be more complicated it seems. I may have to refactor the treatment of icons. I will treat this as wontfix for now. Icons + indices looks too noisy for me anyway. But a proper fix for the problem would be welcome of course.
