### ISSUE TITLE
Does not work with selectrum?

### ISSUE THREAD

**Issue by danielpza** [minad/corfu#3]
Is there any way to make it work with selectrum? apparently doesn't work

```elisp
(setq tab-always-indent 'complete)

(use-package corfu
  :straight '(corfu :host github :repo "minad/corfu")
  :config
  (corfu-mode))

(use-package selectrum
  :straight t
  :config
  (selectrum-mode +1))
```

https://user-images.githubusercontent.com/17787042/114953624-c3736e80-9e26-11eb-88f4-ee932d2f2725.mp4

**Comment by minad** [comment]
Did you set `selectrum-complete-in-buffer=nil`?

**Comment by danielpza** [comment]
no I didn't... it works now thanks. :-D

**Comment by astoff** [comment]
So `completion-in-region-function` must be at the default value? This could be something that the minor mode takes care of setting, couldn't it?

**Comment by minad** [comment]
Yes, it could. Then you will run into order dependence problems if two modes make the same kind of adjustment. Therefore better not.

**Comment by astoff** [comment]
But this kind of cancels any advantage of `corfu-mode` being a non-global minor mode.  For instance, one can't use the completion in region from Consult or Selectrum by default, and enable Corfu in certain major modes. This is interesting in at least one case, namely when testing the package for the first time.

**Comment by minad** [comment]
Yes, but you can easily create a wrapper corfu-selectrum-mode which ensures that the two play nicely together. However I am still unsure about the best completion-in-region setup. 

I tried the following setups:

1. Originally I used company and selectrum-completion-in-region/consult-completion-in-region if company is not present (minibuffer etc)
2. Only use only selectrum-completion-in-region/consult-completion-in-region
3. Only use default completion-in-region
4. Now I try corfu and default completion-in-region where corfu is not present (minibuffer, ...)

Right now I tend to option 4. This explains why I didn't improve the current situation yet.
