### ISSUE TITLE
How to make CIDER work with Corfu

### ISSUE THREAD

**Issue by MicahElliott** [minad/corfu#30]
_(I don't want to hijack #8, so opening a new ticket here...)_

I realize that [Cider might not be behaving well](https://github.com/clojure-emacs/cider/issues/3006) with its completion functions. But it'd be nice to know if there are any workarounds yet. Documenting the start of a workaround here based on what I'm figuring out to be the problem.

Important settings to make plain old completion work (hopefully popping up `*Completions*` buffer sans Corfu):
```
(setq completion-styles '(basic)) ; or use orderless and cider to list (later)
(setq tab-always-indent 'complete)
(setq completion-styles-alist
  (cider cider-company-unfiltered-candidates cider-company-unfiltered-candidates "CIDER backend-driven completion style.")
  (orderless orderless-try-completion orderless-all-completions "Completion ...")
  (basic completion-basic-try-completion completion-basic-all-completions "Completion ...")
  ...))
```

As indicated in the alist above, Cider uses the following to call `cider-complete` to produce completions:
```
(defun cider-company-unfiltered-candidates (string &rest _)
  "Return CIDER completion candidates for STRING as is, unfiltered."
  (cider-complete string))
```

Seeing what that does:
```
Eval: (cider-complete "cond")
;=> (#("cond" 0 1 (type "macro" ns "clojure.core")) #("condp" 0 1 (type "macro" ns "clojure.core")) #("cond->" 0 1 (type "macro" ns "clojure.core")) #("cond->>" 0 1 (type "macro" ns "clojure.core")))
```

Cool! But I seem to be reading that only Company (not Corfu or other emacs completers) knows what to do with that format for results from the first "`try-completion`" function -- it's not standard.

So if I edit `completion-styles-alist`'s cider entry to have a "better" try-completion:
```
  ... (cider my-cider-try-completion cider-company-unfiltered-candidates "this doesn't really work.")

(setq completion-styles '(cider))
(defun my-cider-try-completion (a b c d) '("FOOBAR" . 3))
```

Then I can get a completion to work in a .clj file, as in:
```
(cond<TAB>
;; becomes=>
(FOOBAR
```

So is the right thing to do for now to just wrap `cider-complete` to produce a proper completion output? I'm trying to figure out what that output should look like. Something like:
```
(defun my-cider-try-completion (string table pred point &optional metadata)
   ;; call cider-complete and MASSAGE it into a pair???
  )
```

But I'm struggling to understand the interaction between the first and second functions to produce the MASSAGEd pair. I'll try reading some more about how those work together, but maybe it's clear to some here now that they could fill in the blank.

**Comment by MicahElliott** [comment]
Hi @minad. Hmm, I notice now that the Cider issue is still open. So don't feel compelled to solve this if it's not obvious to you; I can go push/help on the Cider issue if that's the better spot. Pleas lemme know if you prefer that.

**Comment by MicahElliott** [comment]
Well, I still can't understand why I don't get a `*Completions*` buffer popup with `corfu-mode` off, but when I turn `corfu-mode` on now, the dumb `my-cider-try-completion` is giving me some completions.

![image](https://user-images.githubusercontent.com/159047/122485606-3666a600-cf8c-11eb-9d8b-b8323c0652a8.png)

**Comment by minad** [comment]
Before discussing potential Corfu issues - the first thing which should work is the `*Completions*` buffer. If this does not work, I cannot say anything about Corfu.

**Comment by minad** [comment]
Closing. Please reopen if Cider provides a proper capf and it still doesn't work with Corfu.
