### ISSUE TITLE
User-customizable above/below frame positioning

### ISSUE THREAD

**Issue by tylerjl** [minad/corfu#303]
Thank you so much for your work and this package!

When I'm using both corfu and a package that adds large overlays (my case is copilot.el), I found that the corfu frame covers the overlay when placed below. Here's an example of what it looks like:

![image](https://user-images.githubusercontent.com/1733846/223953101-d574267e-1a48-4b5d-bc46-d0a010e314aa.png)

I'm still an elisp novice so my initial reaction was to try and see whether I could just tweak the placement of the child frame to _always_ appear _above_ the point. In some cases this would make candidates go outside the parent frame (I think?) but regardless, I think that a configurable setting that signaled "force appearance above or below point" would solve this. It might behave oddly in some cases (like if you set "force appearance below" and the point was at the bottom of the frame) but the point is that you _could_ alter it if you wanted to.

Is this capability something that would be worth adding or just extra cruft? Is there another approach here to both a) see the overlay and b) see completion candidates that I might not've considered that would be a better way to do it?

Thank you so much for the help!

**Comment by minad** [comment]
I am not enthusiastic about such a setting since it won't behave well if the point is at the top of the frame. My recommendation is to disable copilot or corfu temporarily if the other us active. It doesn't really make sense to show both at the same time.

**Comment by MarselScheer** [comment]
Just want to show how it is visualized in company-mode (using both company-pseudo-tooltip-frontend company-preview-frontend):
![image](https://github.com/minad/corfu/assets/8074083/309828fd-9d8f-4b02-bd88-d962d23257c9)
