### ISSUE TITLE
Unable to install corfu

### ISSUE THREAD

**Issue by Pklong** [minad/corfu#305]
Sorry for the issue, this is most likely local to my machine but I'm unable to install corfu (or vertico or vertico-prescient). 

My error comes from `package-generate-autoloads`, here is the debug message:

```
loaddefs-generate(".emacs.d/elpa/compat-29.1.4.0" ".emacs.d/elpa/compat-29.1.4.0/compat-autoloads.el" nil "(add-to-list 'load-path (or (and load-file-name (f...")
```

Apologies if this is an inappropriate forum but it does appear that my issue is related to my setup and https://elpa.gnu.org/packages/compat.html

**Comment by minad** [comment]
I am sorry, I cannot help you here given that limited amount of information. I suggest to remove Compat and the other packages and then reinstall them.
