### ISSUE TITLE
Undo not grouped anymore when corfu-mode is on

### ISSUE THREAD

**Issue by casouri** [minad/corfu#309]
Hi, when I'm writing Elisp I noticed something strange: when I type something and hit C-/ to undo, the undo only removes a single character rather than the whole word. Here's how I can reproduce it with corfu 0.35 and vanilla Emacs 29.0.60 with these configuration:

```emacs-lisp
(setq corfu-auto 
      corfu-auto-delay 0
      corfu-auto-prefix 2)
```

Open a buffer in `emacs-lisp-mode`, turn on `corfu-mode`, type anything, say `propertize`, and hit undo. I'd expect the whole word "propertize" to be removed, but what I see is that I can only undo a single character, sometimes two, at a time.

**Comment by minad** [comment]
The undo handling in Corfu is a bit problematic. Please check if it works better now.

**Comment by casouri** [comment]
That fixes it, thanks!
