### ISSUE TITLE
corfu-popupinfo and eglot doesn't work for me 

### ISSUE THREAD

**Issue by zikajk** [minad/corfu#310]

**Comment by minad** [comment]
More information is needed. See the wiki.

**Comment by zikajk** [comment]
It was a mistake, sorry ;)

**Comment by llllvvuu** [comment]
How did you make it work @zikajk ? I am getting "No documentation available for __" when I press <M-t>, but the ElDoc display on the bottom is working fine

**Comment by zikajk** [comment]
> How did you make it work @zikajk ? I am getting "No documentation available for __" when I press , but the ElDoc display on the bottom is working fine

I think I had to disable some Cider functionality. I am not sure, try this. 
But I do not have any special configuration for Corfu itself and I fixed it elsewhere.
`(add-hook 'cider-mode-hook (lambda () (remove-hook 'completion-at-point-functions #'cider-complete-at-point)))`

**Comment by zikajk** [comment]
But I suppose you don't use Cider.
Unfortunately, the original description of this ticket got lost somewhere (I must have accidentally deleted it before posting), so I don't remember what the exact problem (and the solution) was.
