### ISSUE TITLE
Emacs 30: Error running timer ‘corfu--auto-complete-deferred’: (void-function prefix)

### ISSUE THREAD

**Issue by magthe** [minad/corfu#319]
I recently decided to try building Emacs 30 and see how much of my config broke.

The only thing I've noticed so far is that corfu isn't working any longer:

```
Corfu completion error: Symbol’s function definition is void: prefix
Error running timer ‘corfu--auto-complete-deferred’: (void-function prefix)
```

**Comment by minad** [comment]
As far as I know people successfully use Corfu on Emacs 30. Please try to investigate this a bit more and let me know about the result. In particular try to reproduce your issue with `emacs -Q` and provide a full stack trace.

**Comment by magthe** [comment]
I have tried to investigate this a bit, but the errors aren't very descriptive and I'm not sure where to look further. I guess I'll just go back to 29 until 30 is a bit mature.

**Comment by mekeor** [comment]
I also run into this error on Emacs 30.

**Comment by minad** [comment]
This issue might be caused by a bytecompiler regression in Emacs 30. You could bisect the Emacs 30 commit log in order to locate the troublesome commit. Do you use the newest commit of Emacs 30? Maybe the issue has already been fixed in the meantime?

**Comment by minad** [comment]
See this upstream bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61917. You should update to a newer Emacs version and then clear your eln-cache.

**Comment by mekeor** [comment]
I'm using Emacs 30 without native compilation because of the bugs related to it.

Unfortunately, I did not yet have time to bisect the commit log to locate the troublesome commit; or to do any other debugging.

**Comment by mekeor** [comment]
It might possibly be related to these commits on the master-branch of Emacs, related to frames:

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=de81349bd898a2c26f9ae15ed967484c7475646f
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=cc29fab3a66c59e77d0ff67c0f3e2e34ec80a03c

But I'm just wildly guessing without a clue.

**Comment by minad** [comment]
That's unlikely. The error hints at a bytecompiler/miscompilation issue, since Corfu doesn't call a function prefix anywhere.

**Comment by mekeor** [comment]
Thanks. I think I have a different problem than reported here. I'll investigate further and come back with a new bug report if needed.

**Comment by tareefdev** [comment]
I still have this exact problem with GNU Emacs 29.1.50. I tried to eln-cache but this did not work too.

**Comment by minad** [comment]
@tareefdev One possibile reason for the problem is a miscompilation, either in the byte compiler or in the native compiler. In such cases I recommend resetting the configuration.

- Delete Compat and Corfu (or even better all packages)
- Delete the eln-cache
- Renstall the newest Emacs version 29.1 (by compiling it yourself or from binary archive)
- Reinstall Compat and Corfu (or even better all packages)

Another possibility is that your Capf is broken and somewhere calls `prefix`. The Capf backend could also be miscompiled. Which Capf do you use? Do you also observe the issue with emacs -Q?

**Comment by tareefdev** [comment]
Thanks for the detailed instructions, but it did not work. Here is what I did:
- I cloned Emacs again into a new directory.
I built it myself. Just in case, here is my config: `./configure --with-native-compilation=aot --with-x-toolkit=gtk3 --without-xaw3d --with-xinput2 --with-tree-sitter --with-json --without-compress-install CFLAGS='-march=native' --with-xml2 --with-lsystemd`
- Deleted the eln-cache and straight folders.
- Ran Emacs again so it cloned all packages and built them.

I ran emacs -q and tried to load the corfu and capf and some other packages, but did not manage to get corfu to work :D it neither shows that error message nor lists possible candidates.

Here are the relevant part of my config:

````
(use-package corfu
    :straight (:files (:defaults "extensions/*"))
    :custom
    ;; (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    (corfu-auto t)                 ;; Enable auto completion
    ;; (corfu-separator ?\s)          ;; Orderless field separator
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect-first nil)    ;; Disable candidate preselection
    ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
    ;; (corfu-echo-documentation nil) ;; Disable documentation in the echo area
    ;; (corfu-scroll-margin 5)        ;; Use scroll margin
    (corfu-history-mode 1)
    (savehist-mode 1)
    (add-to-list 'savehist-additional-variables 'corfu-history)
    ;; Recommended: Enable Corfu globally.
    ;; This is recommended since Dabbrev can be used globally (M-/).
    ;; See also `corfu-excluded-modes'.
    :init
    (global-corfu-mode))
    
    (use-package cape
    ;; Bind dedicated completion commands
    ;; Alternative prefix keys: C-c p, M-p, M-+, ...
    :bind (("C-c p p" . completion-at-point) ;; capf
	   ("C-c p t" . complete-tag)        ;; etags
	   ("C-c p d" . cape-dabbrev)        ;; or dabbrev-completion
	   ("C-c p h" . cape-history)
	   ("C-c p f" . cape-file)
	   ("C-c p k" . cape-keyword)
	   ("C-c p s" . cape-symbol)
	   ("C-c p a" . cape-abbrev)
	   ("C-c p i" . cape-ispell)
	   ("C-c p l" . cape-line)
	   ("C-c p w" . cape-dict)
	   ("C-c p \\" . cape-tex)
	   ("C-c p _" . cape-tex)
	   ("C-c p ^" . cape-tex)
	   ("C-c p &" . cape-sgml)
	   ("C-c p r" . cape-rfc1345))
    :init
    ;; Add `completion-at-point-functions', used by `completion-at-point'.
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file)
    ;;(add-to-list 'completion-at-point-functions #'cape-history)
    ;;(add-to-list 'completion-at-point-functions #'cape-keyword)
    ;;(add-to-list 'completion-at-point-functions #'cape-tex)
    ;;(add-to-list 'completion-at-point-functions #'cape-sgml)
    ;;(add-to-list 'completion-at-point-functions #'cape-rfc1345)
    (add-to-list 'completion-at-point-functions #'cape-abbrev)
    (add-to-list 'completion-at-point-functions #'cape-ispell)
    ;;(add-to-list 'completion-at-point-functions #'cape-dict)
    ;;(add-to-list 'completion-at-point-functions #'cape-symbol)
    ;;(add-to-list 'completion-at-point-functions #'cape-line)
    )
    ````

**Comment by minad** [comment]
If you press M-TAB or invoke one of the Cape commands via M-x do you see Corfu?

**Comment by tareefdev** [comment]
Oh, yes, I can. All Cape commands work if I invoke them directly via M-x

**Comment by minad** [comment]
@tareefdev Okay, so it seems that Corfu works correctly in most cases, e.g., with the Cape commands/Capfs? Can you obtain a stack trace for the void-function prefix problem and paste it here? See https://github.com/minad/corfu#debugging-corfu. This will help us to narrow down the location of the problem.

**Comment by tareefdev** [comment]
I had Corfu turned off in my config during the last couple of months, I turned it on again to debug the issue as you mentioned, however, it just worked! I waited for a week now, and it works flawlessly! Thanks for your time.

**Comment by shmul** [comment]
I also encountered this issue with an Emacs pre-build (see below). It was resolved by updating both corfu (a couple of commits past 1.3, `b7795523`) and cape (1.5).
```
GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.6.0, NS
 appkit-2299.70 Version 13.6.1 (Build 22G313)) of 2024-01-02
```

**Comment by philipnilsson** [comment]
I had a similar problem with corfu when upgrading to emacs30 that was resolved by just deleting the `.emacs.d/.cache` folder (just installing corfu didn't help), in case anyone comes looking here that could be worth a shot.
