### ISSUE TITLE
 Popup completion frame gets input focus if it appears at mouse cursor location

### ISSUE THREAD

**Issue by tsdh** [minad/corfu#32]
When the mouse cursor is at the location where the completion pos-frame will pop up, the pos-frame receives input focus and input will be inserted there.

Example where `|` is point and `^` is my mouse cursor:
```elisp
(de|
    ^
```
Now when I enter `f` so that `corfu-auto` will start suggesting `defun` and friends, the input focus is transferred to the pos-frame, see this screenshot.
![image](https://user-images.githubusercontent.com/103854/124419654-332a3300-dd5e-11eb-9495-bdf243442181.png)

This happens to me very frequently so I'm a bit surprised that this didn't seem to happen to others, too.  Maybe it's a specific to window manager `sway`?  If you can't reproduce the issue, I'll try to check if it also happens in Gnome.

**Comment by minad** [comment]
Yes, please check other wms. The popup is marked as no-accept-focus.

**Comment by tsdh** [comment]
@minad You are right, the popup frame cannot get input focus with Gnome so it is a sway issue.

**Comment by tsdh** [comment]
Ah, too bad, the sway issue got closed because `gtk_window_set_accept_focus` is a no-op on wayland.  But the issue does not appear with Gnome on Wayland, so there seems to be a way to prevent focus going to that child frame somehow.

By the way, I just found out that the issue doesn't happen with [posframe](https://github.com/tumashu/posframe) on sway.  It seems to make some effort to redirect focus of the posframe back to the parent frame, see https://github.com/tumashu/posframe/blob/master/posframe.el#L687 and also moves away the mouse pointer, see https://github.com/tumashu/posframe/blob/master/posframe.el#L48.

We'll see what happens on the sway issue but maybe the posframe workarounds aren't a bad idea.

**Comment by minad** [comment]
>  Ah, too bad, the sway issue got closed because gtk_window_set_accept_focus is a no-op on wayland. But the issue does not appear with Gnome on Wayland, so there seems to be a way to prevent focus going to that child frame somehow.

I think this should be fixed in sway. We could add the workaround here, but the child frame code is already horrible (as is posframe internally). I am very hesitant to add more hacks. Child frames should be implemented properly by the Emacs display engine. You could also ask on emacs-devel what their stance is one working around unreliable no-accept-focus in the Emacs display engine directly. It is simply not okay to push all the bugs upwards. Wayland does not support this, Sway ignores it, Emacs does not work around it, now I have to work around it on the topmost level?

**Comment by tsdh** [comment]
I didn't mean to sound demanding.  Sorry if I did!

You are correct that this should be fixed in emacs and not in each and every package spawning child frames.  I've just tested the pgtk emacs branch in the hope that this issue has been fixed there, but sadly it's not.  I'll ask on emacs-devel.

**Comment by minad** [comment]
> I didn't mean to sound demanding. Sorry if I did!

No, I didn't perceive it as such. I was just expressing my annoyance with how bad the child frame implementation of Emacs is. Maybe it is not even  the fault of Emacs but just of other programs in the stack. But in my opinion it is wrong to fix these issues on the package level, something like posframe should not be necessary.

Corfu contains two hacks:

https://github.com/minad/corfu/blob/33b37fdf364d5df4ee712a91cff7f1f01526674a/corfu.el#L250-L261

https://github.com/minad/corfu/blob/33b37fdf364d5df4ee712a91cff7f1f01526674a/corfu.el#L299-L302

But besides that, the popup code is not that bad.

**Comment by minad** [comment]
@tsdh I have to take a more pragmatic stance here it seems. I just discovered that the window manager I am using suffers from the same problem. :confused: 

I wonder why I didn't discover this before, but it seems I just started using the mouse a bit more while developing a more advanced mouse mode for Vertico (https://github.com/minad/vertico/blob/main/extensions/vertico-mouse.el), which is actually quite nice (I haven't pushed this yet to the Vertico repository, the current mouse support is rudimentary)

My mini-popup package is affected by this too. So I will implement the posframe hack :disappointed:

**Comment by minad** [comment]
I tried the posframe hack, it does not work. I would also like to disable clicks on the popup such that no events at all arrive at the popup. But nothing I tried works. :shrug:

**Comment by minad** [comment]
Please try https://github.com/minad/corfu/commit/4f426ab92665cdc622dd6bd7a45549c93362fae7. Maybe this helps.

**Comment by tsdh** [comment]
@minad Yes, it helps a lot.  I haven't been able to switch input focus to the popup frame anymore.

**Comment by minad** [comment]
I assume this can be closed then?

**Comment by tsdh** [comment]
@minad Yes.

BTW, I still think you are right in that packages shouldn't be responsible for handling those quirks.  I've written a mail but not sent it yet because it reads "look what hacks posframe and corfu need to include in order to handle several quirks in certain scenarios" which is doomed to result in an answer "yes, frame handling across different OS, toolkits, etc. is hell; patches welcome".

**Comment by minad** [comment]
Yes, I would still appreciate if you send the mail. Of course the foreseeable response will come and that's okay. On the other hand, the Emacs display code is really not good. So if the maintainers become more aware this may help, also with regards to pushing pgtk. The amount of settings required by child frames is astonishing for a thing which should be simple. And this does not even include the hacks needed like the one debated here. Of course I could also write an angry mail, I've so far didn't do this for two reasons: 1. I would have done so in a bad mood after trying to fix corfu/mini-popup, 2. I couldn't pinpoint a precise criticisim - the API is just bad overall. Maybe you could do better (more objective and neutral) given that you looked at posframe and corfu.
