### ISSUE TITLE
In-buffer completion for normal text/word with ispell + corfu + orderless.

### ISSUE THREAD

**Issue by hongyi-zhao** [minad/corfu#323]
I've made an [exhaustive word list](https://github.com/hongyi-zhao/english-wordlist/blob/master/american-english-exhaustive) for ispell. Now I would like to know if it's possible to use this word list in ispell and working with corfu and orderless.

The main consideration I consider is: For ordinary words, orderless will improve efficiency, but it will also return a lot of candidates, which also means an increase in latency and a decrease in efficiency. So what kind of matching/searching pattern should be used?

Any tips will be appreciated.

Regards,
Zhao

**Comment by minad** [comment]
See https://github.com/minad/cape.
