### ISSUE TITLE
Is there some way to customize the completions-common-part face just for corfu?

### ISSUE THREAD

**Issue by mohkale** [minad/corfu#326]
Hi,

I'm just experimenting with corfu instead of company atm. One thing I kind of miss from company was that a company had a lot of ways to customize the look and feel of the tooltip and completion candidates. So far I've managed to match corfu to company pretty well except I haven't found a substitute for `company-tooltip-common-selection`. My default completions-common-part face looks well for the minibuffer but not as well in corfu. I'm wondering if there's some way to advise or alter the face just for the tooltip :thinking:.

## In company

![Screenshot_20230505_215307](https://user-images.githubusercontent.com/23294780/236567227-85358767-dda2-4034-9460-617dccae153c.png)

## In corfu

![Screenshot_20230505_215625](https://user-images.githubusercontent.com/23294780/236567337-03fda6a8-aa7d-47a3-8cca-2b3566c8e94d.png)

**Comment by minad** [comment]
The face is attached to the candidates by the completion styles. There is no mechanism to override this further from the side of Corfu. You could install some face remapping in the Corfu child frame via advices or hooks, but this seems like unnecessary work. I recommend to just use a theme which takes more care about the details, like Prots Ef or Modus. You can of course also alter the faces manually.
