### ISSUE TITLE
Padding, margins in popup

### ISSUE THREAD

**Issue by samimb** [minad/corfu#327]
Hi,

I mainly have a question.
Is there an option in Corfu to get a similar look to LSP in vim?

I would assume you can reach similarities with the `corfu-border` face but that would remove the actual border with different colors.

![7DB9DF7B-77EF-4578-9714-F568B4AD4ED7_1_201_a](https://github.com/minad/corfu/assets/4834107/8df44adf-1aa5-46c3-81c7-6a33182cbd8e)

Apologies, I do not seem to have the option to add the label of Question

**Comment by minad** [comment]
You can adjust the left and right margin via customization options. There is no option for padding at the to and bottom, also no round borders.
