### ISSUE TITLE
Corfu will insert unexpected characters in Python's sys.stdin

### ISSUE THREAD

**Issue by Eason0210** [minad/corfu#330]
Hi @minad 

When I use `M-x run-python` and then run the below code snippet in Python's standard REPL, will get unexpected result as below:

```python
import sys
for line in sys.stdin:
    words = line.lower().split()
    print(words)
    if words[0] == 'q':
        break
```
with corfu-mode enabled, unexpected:
```
Python 3.11.3 (main, Apr  8 2023, 06:31:24) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> 
2 4
['2', '4']
3 2
['3', '\x08\x08\x08', '\x08\x08\x082', '\x08\x08\x08\x08\x083', '2']
```

disable corfu-mode, expected:
```
>>>
2 3
['2', '3']
2 4 5
['2', '4', '5']
1 2
['1', '2']
3 5
['3', '5']
```
minimal emacs config to reproduce issue:
```emacs-lisp
(setq package-user-dir
      (expand-file-name (format "elpa-%s.%s" emacs-major-version emacs-minor-version)
                        user-emacs-directory))

;; Standard package repositories
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "https://elpa.gnu.org/packages/")))

(require 'package)
(package-initialize)

(use-package corfu
  :ensure t
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-auto-prefix 1)
  (corfu-preselect 'prompt)
  :bind (:map corfu-map
              ([tab] . corfu-next)
              ([backtab] . corfu-previous)
              ("S-<return>" . corfu-insert)
              ("RET" . nil)
              ([remap move-end-of-line] . nil))
  :hook (eshell-mode . (lambda () (setq-local corfu-auto nil)))
  :init
  (global-corfu-mode)
  (corfu-popupinfo-mode))


(use-package python
  :ensure nil
  :defer t
  :custom (python-indent-guess-indent-offset-verbose nil))

```

I can confirm that this happens at Emacs 29 and Emacs 30.

GNU Emacs 30.0.50 (build 1, x86_64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (a) (Build 22E772610a), git sha1 a7dcc0d55c6) of 2023-05-14

**Comment by minad** [comment]
I am not entirely sure, but I suspect that reading from stdin like this interferes with auto completion. The Capf also has to communicate somehow with the process to obtain completion candidates and I assume that this happens via stdin/stdout. Please check first if this is the case.

**Comment by Eason0210** [comment]
Hi @minad 

You are right, Capf will communicate with the process.
With corfu disabled, after input 2, and trigger `complete-symbol` by <kbd>C-M-i</kbd>, will get the same result as below:

```
Python 3.11.3 (main, Apr  8 2023, 06:31:24) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
2 3
['2', '\x08\x08\x08', '\x08\x08\x083', '\x08\x08\x08\x08\x082', '3']
```

**Comment by Eason0210** [comment]
Meanwhile, with corfu enabled in python REPL, sometimes will get the dummy completion.
Is this an Emacs bug? or from Corfu? I am not sure about it. That's why I did the test above.
```
Python 3.11.3 (main, Apr  8 2023, 06:31:24) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 10 + 20
30
>>> print(80)
80
>>> pass
pow
print
property

0__dummy_completion__  1__dummy_completion__
```

**Comment by minad** [comment]
The problem could be that the python Capf does not handle interrupts gracefully. See cape-wrap-noninterruptible from my Cape package as workaround. Please check if that fixes the problem and let me know.

But overall it seems the Python repl Capf design is problematic. Communicating with the process via stdin/stdout while using the same channel for repl io is inheritly brittle, as long as the message types are not properly isolated.

**Comment by Eason0210** [comment]
> The problem could be that the python Capf does not handle interrupts gracefully. See cape-wrap-noninterruptible from my Cape package as workaround. Please check if that fixes the problem and let me know.

I have installed Cape, but I am not sure how to use `cape-wrap-noninterruptible`, I set this:
```
(advice-add 'python-shell-completion-at-point :around #'cape-wrap-noninterruptible)
```

After the above setting, will get this error when I input characters in a test.py buffer, bug no error in Python REPL buffer.
```
Error running timer ‘corfu--auto-complete-deferred’: (wrong-number-of-arguments (1 . 1) 2) [5 times]
```

**Comment by minad** [comment]
I don't observe such a wrong argument error with `cape-wrap-noninterruptible`. Can you debug this further and obtain a stack trace? Maybe something else from your config is interfering?

**Comment by guibor** [comment]
I have the same issue when I add `(advice-add 'python-shell-completion-at-point :around #'cape-wrap-noninterruptible)`, I get the same error @Eason0210 mentioned `Error running timer ‘corfu--auto-complete-deferred’.

**Comment by minad** [comment]
The problem is that `python-shell-completion-at-point` is called with an argument here:

~~~ elisp
(defun python-completion-at-point ()
  "Function for `completion-at-point-functions' in `python-mode'.
For this to work as best as possible you should call
`python-shell-send-buffer' from time to time so context in
inferior Python process is updated properly."
  (let ((process (python-shell-get-process)))
    (when (and process
               (python-shell-with-shell-buffer
                 (python-util-comint-end-of-output-p)))
      (python-shell-completion-at-point process))))
~~~

You can work around this with an indirection:

~~~ elisp
(advice-add 'python-shell-completion-at-point :around
            (lambda (fun &optional arg)
              (cape-wrap-noninterruptible (lambda () (funcall fun arg)))))
~~~

**Comment by guibor** [comment]
Thanks a lot @minad for the answer!
Unfortunately the solution doesn't seem to work


(defun auto-completion/init-corfu ()
  (use-package corfu
    :custom
    (corfu-cycle t)
    (corfu-auto t)
    :init
    (global-corfu-mode)
    (advice-add 'python-shell-completion-at-point :around #'cape-wrap-noninterruptible)
    (advice-add 'python-shell-completion-at-point :around
                (lambda (fun &optional arg)
                  (cape-wrap-noninterruptible (lambda () (funcall fun arg)))))

 
    (defun corfu-enable-in-minibuffer ()
      "Enable Corfu in the minibuffer."
      (when (local-variable-p 'completion-at-point-functions)
        (setq-local corfu-echo-delay nil ;; Disable automatic echo and popup
                    corfu-popupinfo-delay nil)
        (corfu-mode 1)))
    (add-hook 'minibuffer-setup-hook #'corfu-enable-in-minibuffer)))

**Comment by guibor** [comment]
I think I understood, you meant to put that /instead/ of `(advice-add 'python-shell-completion-at-point :around #'cape-wrap-noninterruptible)`.

This seems to work!
