### ISSUE TITLE
How to add documentation command for corfu-info-documentation when using corfu-dict completion?

### ISSUE THREAD

**Issue by bcmertz** [minad/corfu#333]
Hello,

I am trying to extend corfu-info to show documetation on corfu-dict word completions. My plan was to have `corfu-info-documentation` call a shell command such as `dict $candidate` to gather the definition of the candidate word as the info documentation when using `corfu-dict` completions. I can't see a way to do this as it seems `corfu-info` depends on `company-doc-buffer` or lsp definition information (can't see how the latter happens in the code but it seems to). Because of this there doesn't seem to be a way to add custom doc sources for a given completion. Any help would be greatly appreciated, thanks!

**Comment by minad** [comment]
Hi, documentation sources are provided by the backend via :company-doc-buffer. There is no functionality to plug-in additional documentation sources. You probably mean cape-dict? We could add :company-doc-buffer there. What do you want to use this for?

**Comment by bcmertz** [comment]
Hi, yes I meant `cape-dict`. I want `corfu-info` to show documentation for the `cape-dict` word completion. Perhaps this could just be the definition of the word via some outside utility like unix's `dict` command, or could be configurable to some other source. What would the process be for adding :comapny-doc-buffer?

**Comment by minad** [comment]
You can add a :company-doc-buffer to cape--dict-properties.

**Comment by bcmertz** [comment]
I see, thank you! If anyone stumbles across this I came up with:


```
(defun text--company-doc-buffer (word)
  (with-current-buffer (get-buffer-create "*word-definition*")
    (erase-buffer)
    (fundamental-mode)
    (when word
      (save-excursion
        (insert (shell-command-to-string (format "dict %s" word)))))
    (current-buffer)))

(defvar cape--dict-properties
  (list :annotation-function (lambda (_) " Dict")
        :company-kind (lambda (_) 'text)
        :company-doc-buffer 'text--company-doc-buffer
        :exclusive 'no)
  "Completion extra properties for `cape-dict'.")
```

**Comment by bcmertz** [comment]
Update: Here is the cape configuration I arrived at that avoids using advice or directly changing cape to achieve this. Hope it helps someone in the future:
```

(use-package cape
  :init
  (add-to-list 'completion-at-point-functions #'cape-dict)
  :config
  (defun text--company-doc-buffer (word)
    (with-current-buffer (get-buffer-create "*word-definition*")
      (erase-buffer)
      (fundamental-mode)
      (when word
        (save-excursion
          (insert (shell-command-to-string (format "dict %s" word)))))
      (current-buffer)))

  (setq cape--dict-properties (append cape--dict-properties
                                      (list :company-doc-buffer 'text--company-doc-buffer)))
  )

```

**Comment by danielfleischer** [comment]
Thanks @bcmertz; used your code successfully with the [osx-dictionary](https://github.com/xuchunyang/osx-dictionary.el) package, modifying it a bit:

```elisp
(defun text--company-doc-buffer (word)
    "Use osx-dictionary package compiled CLI to lookup words."
    (with-current-buffer (get-buffer-create "*word-definition*")
      (erase-buffer)
      (fundamental-mode)
      (let ((ans (shell-command-to-string (format "path/to/osx-dictionary-cli-tool %s" word))))
        (if (string-empty-p ans)
            (insert "No definition.")
          (insert ans)))
        (current-buffer)))
```
