### ISSUE TITLE
pop-up-frames to t and corfu-popupinfo weird behaviour

### ISSUE THREAD

**Issue by Cletip** [minad/corfu#335]
Hello,

Have you ever set pop-up-frames to t and used corfu-popupinfo ?
When this variable is set to t, corfu-popupinfo creates a new frame, which I don't think is normal.

**Comment by minad** [comment]
Indeed, I can reproduce this. It is a bug in `elisp--company-doc-buffer`. See the comments here: https://github.com/emacs-mirror/emacs/blob/e77e986a9b7d735c0e39198c8b80a34a29005fc5/lisp/progmodes/elisp-mode.el#L521-L526

You may want to report this problem upstream.

**Comment by minad** [comment]
I just noticed that `pop-up-frames` is deprecated according to its docstring. You should probably not set it to t and instead use `display-buffer-base-action`.
