### ISSUE TITLE
How to avoid number completion in SQL mode ?

### ISSUE THREAD

**Issue by zhangjie2012** [minad/corfu#337]
like this:
<img width="972" alt="image" src="https://github.com/minad/corfu/assets/2450412/4c2fe293-d1de-4687-9b18-0d6030fd9fad">

btw: **sql mode corfu very slow**. My config:

```
(use-package cape
  :ensure t
  :init
  (add-to-list 'completion-at-point-functions #'cape-file)
  (add-to-list 'completion-at-point-functions #'cape-history)
  (add-to-list 'completion-at-point-functions #'cape-dabbrev))

(use-package corfu
  :ensure t
  :hook (prog-mode . corfu-mode)
  :bind (:map corfu-map
              ("M-SPC" . corfu-insert-separator)
              ("C-n" . corfu-next)
              ("C-p" . corfu-previous))
  :config
  (setq corfu-auto t
        corfu-auto-prefix 1
        corfu-auto-delay 0.1
        corfu-quit-no-match t
        corfu-quit-at-boundary t)
  (add-hook 'multiple-cursors-mode-enabled-hook (lambda () (corfu-mode -1)))
  (add-hook 'multiple-cursors-mode-disabled-hook (lambda () (corfu-mode 1))))
```

**Comment by minad** [comment]
You could set a :predicate function in cape--dabbrev-properties which filters out numeric candidates. Alternatively you could modify cape-dabbrev (or wrap it) to return nil if the matching word is undesired.

**Comment by minad** [comment]
I added support for dabbrev-abbrev-char-regexp, see https://github.com/minad/cape/commit/e503d9a6f86b05962fe4b638f49d8d0110891570.
