### ISSUE TITLE
(eldoc-add-command #'corfu-complete)

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#339]
The configured eldoc functions are queried, but the resulting doc display is suppressed after `corfu-complete`.  This is because the `corfu-complete` command is not on `eldoc-message-commands`.  Placing it there with `eldoc-add-command` fixes this.  Unless corfu exit functions regularly echo to the minibuffer, this seems safe.

**Comment by minad** [comment]
Fixed
