### ISSUE TITLE
Corfu doesn't show completion for c-mode.

### ISSUE THREAD

**Issue by basicfunc** [minad/corfu#34]
Hey, there!
I don't know but it's pretty weird that Corfu shows me completion for Rust, JavaScript and for Golang while using Eglot as LSP client. But, it doesn't show me completion in C or C++ mode, I tried configuring LSP using clangd, ccls and irony-mode. Sadly, no success till now. Whereas Company Mode works fine in every buffer, it's weird as both Corfu and Company Mode use completion-at-point-functions(Capfs).

**Comment by neye-zhaw** [comment]
Works fine for me with eglot.

**Comment by basicfunc** [comment]
> Works fine for me with eglot.

Can you tell me how to debug it!?

**Comment by basicfunc** [comment]
![simplescreenrecorder-2021-07-14_21 00 18](https://user-images.githubusercontent.com/84739019/125650389-69c7e539-5c3f-4040-9bf1-7c9b74301a07.gif)
Well, here ccls is running but corfu doesn't show me any completions neither by pressing TAB nor by completion-at-point command
:(

**Comment by neye-zhaw** [comment]
I just replaced my company config with this:

```elisp
(use-package corfu
  :bind (:map corfu-map
         ("TAB" . corfu-next)
         ([tab] . corfu-next)
         ("S-TAB" . corfu-previous)
         ([backtab] . corfu-previous))
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-auto-prefix 1)
  :init
  (corfu-global-mode))
```

**Comment by basicfunc** [comment]
> I just replaced my company config with this:
> 
> ```elisp
> (use-package corfu
>   :bind (:map corfu-map
>          ("TAB" . corfu-next)
>          ([tab] . corfu-next)
>          ("S-TAB" . corfu-previous)
>          ([backtab] . corfu-previous))
>   :custom
>   (corfu-cycle t)
>   (corfu-auto t)
>   (corfu-auto-prefix 1)
>   :init
>   (corfu-global-mode))
> ```

I've configured my Corfu same way, just I'm using straight.el instead of use-package

**Comment by gagbo** [comment]
That's probably because eglot remapped `TAB` manually, or that your `corfu-auto` is taking over. Can you tell what is called when you hit `TAB` in your working setup, and on which keymap it's found ?

The crux of the issue is that c-mode ignores `tab-always-indent` (as its docstring says), and there's no way to set `c-tab-always-indent` to a value that can reach completion :/ Therefore TAB is always bound to `(c-indent-line-or-region &optional ARG REGION)` in c and cc-modes.

I think the solution would be to add a `corfu-mode-map`, even empty. This way I'd be able to bind `completion-at-point` in this map and hopefully I'll be able to override tab there. What do you think @minad ?

**Comment by minad** [comment]
In my opinion these offending modes should be fixed. Users can also add a keybinding themselves in the corfu-mode-hook.

What I think Corfu is missing is mostly testing - it needs to be tried with a large number of different modes, for each mode one should document if it works or requires workaround and then one draws conclusions. Like a big org table in the Corfu wiki.

**Comment by gagbo** [comment]
`corfu-mode-hook` is run on each buffer (as a minor mode) ? Because otherwise I don't think I can make `corfu-mode-hook` work properly (it'll trigger on the first buffer, and I don't think I want to add a global-map binding as it probably won't have priority). That's why I thought adding an empty, sparse, `corfu-mode-map` would be the best place for the binding

**Comment by minad** [comment]
> corfu-mode-hook is run on each buffer (as a minor mode) ?

corfu-mode is a minor local mode, so yes.

**Comment by basicfunc** [comment]
> That's probably because eglot remapped `TAB` manually, or that your `corfu-auto` is taking over. Can you tell what is called when you hit `TAB` in your working setup, and on which keymap it's found ?
> 
> The crux of the issue is that c-mode ignores `tab-always-indent` (as its docstring says), and there's no way to set `c-tab-always-indent` to a value that can reach completion :/ Therefore TAB is always bound to `(c-indent-line-or-region &optional ARG REGION)` in c and cc-modes (on `c-mode-base-map`)
> 
> I think the solution would be to add a `corfu-mode-map`, even empty. This way I'd be able to bind `completion-at-point` in this map and hopefully I'll be able to override tab there. What do you think @minad ?

I don't think so that's the case because M-x corfu-next/codu-complete isn't working too.

**Comment by basicfunc** [comment]
![image](https://user-images.githubusercontent.com/84739019/127181326-e7517d13-b005-4b36-b927-a05dfee7bcb6.png)

I taken that screenshot after pressing C-h k TAB
I guess, I done it right.

I think @gagbo was right!
@minad is there any workaround regarding that??

**Comment by basicfunc** [comment]
@minad if that's limitation of c-mode.
Will this work??

**Comment by gagbo** [comment]
I don't think it'll work either.

I ended up going with
```lisp
(when (equal tab-always-indent 'complete)
  (define-key c-mode-base-map [remap c-indent-line-or-region] #'completion-at-point))
```

**Comment by basicfunc** [comment]
> I don't think it'll work either.
> 
> I ended up going with
> 
> ```lisp
> (when (equal tab-always-indent 'complete)
>   (define-key c-mode-base-map [remap c-indent-line-or-region] #'completion-at-point))
> ```
> 
> (This is a "on the fly" translation of a snippet of Doom config, so it might not exactly work; but `(map! :map c-mode-base-map :i [remap c-indent-line-or-region] #'completion-at-point)` definitely did and was tested in Doom)

Thanks it worked. :)

**Comment by Hex4dec** [comment]
> I don't think it'll work either.
> 
> I ended up going with
> 
> (when (equal tab-always-indent 'complete)
>   (define-key c-mode-base-map [remap c-indent-line-or-region] #'completion-at-point))
> (This is a "on the fly" translation of a snippet of Doom config, so it might not exactly work; but `(map! :map c-mode-base-map :i [remap c-indent-line-or-region] #'completion-at-point)` definitely did and was tested in Doom)

This breaks indentation completely in C mode. (or at least breaks do-what-I-mean)
