### ISSUE TITLE
Recognizing if Corfu Completion is Open

### ISSUE THREAD

**Issue by john-d-murphy** [minad/corfu#343]
This may not be a bug, so feel free to close, but I wanted to make a note here on some behavior I'm seeing. 

I'm making a modification of the code here: https://gitlab.com/matsievskiysv/emacs-configs/-/blob/master/elisp/init-indent-or-complete.el

to support an overloaded TAB key with access to several functions in sequence. It's simple enough to run a "(check-expansion) (completion-at-point))" in the cond section of tab-indent-or-complete, but in *terminal* emacs, when TAB is is hit again, there is a branch somewhere that makes it hit tab-indent-or-complete again, while the GUI correctly looks at the corfu-map.

I'm not asking you to debug my specific setup, but from what I can tell, there is no helper utility to check to see if a corfu popup is currently active. I'm reasonably new to Emacs and lisp coding in general, so I may be missing something, but if there's a way to say "does a corfu popup currently exist in this buffer ?"  I can add that conditional to my tab-indent-or-complete method.

Does something like this exist ? And if not, what should I look at to write one ?

**Comment by minad** [comment]
You can use the following condition to check if the Corfu popup frame is visible:

~~~ elisp
(and (frame-live-p corfu--frame) (frame-visible-p corfu--frame))
~~~

Is this helpful for your use case? Note that `indent-for-tab-command` already either indents or completes if you set `tab-always-indent` to the symbol `complete`.

**Comment by john-d-murphy** [comment]
Thanks for the speedy response! There's some shenanigans with the tab-always-indent and evil-mode. It gets confused and then *no* indenting happens. It's one of those things that's a bit maddening and I've just decided to let it be.

It looks like when I'm calling the above snippet, it's always returning nil. I suspect there's something wonky with the namespace I'm in due to the evil-insert-state-map doing its own magic. I'll keep on hacking away at this - I'm sure there's something obvious that i'm missing and your answer is correct. 

Thank you!

**Comment by minad** [comment]
> It looks like when I'm calling the above snippet, it's always returning nil.

I assume that the Corfu popup is already closed at the time when you call the snippet from a non-Corfu command. See `corfu-continue-commands` if you want to keep Corfu alive.

**Comment by john-d-murphy** [comment]
Figured it out! I did my tab-overloading in corfu-next just to keep it moving and I'm in good shape. Now I just need to get cape to behave. :)

**Comment by minad** [comment]
If you come up with improvements which are generally useful please let me know. Then we can add them to Corfu/Cape directly.
