### ISSUE TITLE
Not getting highlighting with anything other than elisp

### ISSUE THREAD

**Issue by sethen** [minad/corfu#346]
Hello!

Love the package.  However I am having trouble getting highlighting to work on my matches when candidates come up with everything besides elisp.  For instance, whenever I type in elisp I get highlighted matches like so:
![Screenshot from 2023-07-08 15-55-00](https://github.com/minad/corfu/assets/1493530/d37ec7dd-a0c9-48be-a925-d0288a40a186)

But whenever I type something in a JavaScript file I do not get the highlighted matches:
![Screenshot from 2023-07-08 15-55-36](https://github.com/minad/corfu/assets/1493530/646c4894-211c-4256-b333-b78c9d6f99c3)

I am using orderless and not sure if that has anything to do with it.  Here is my current configuration for corfu:

```elisp
(require 'use-package)

(use-package corfu
  :config
  (setq corfu-auto t
        corfu-auto-delay 0
        corfu-auto-prefix 0)
  :custom
  (corfu-preselect 'prompt)
  :init
  (corfu-popupinfo-mode)
  (global-corfu-mode))

(provide 'sethen-corfu)
```

Might be a dumb question but I am coming from company where the matches were always highlighted.  For what it's worth I am using emacs lsp which also might have something to do with this?

**Comment by minad** [comment]
It depends on the lsp client. Eglot uses the `flex` completion style for highlighting and lsp-mode completely disables filtering. It uses a Company extension to provide highlighting which is not supported by Corfu. You can still use Orderless, see https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-clients.
