### ISSUE TITLE
corfu and `lsp-completion-show-detail`

### ISSUE THREAD

**Issue by sethen** [minad/corfu#347]
Looks like when I toggle on `lsp-completion-show-detail` for the emacs LSP, Corfu it does a good job of displaying additional information with some programming languages.  Rust, for example:

![Screenshot from 2023-07-09 23-22-47](https://github.com/minad/corfu/assets/1493530/ccda32cd-4370-47e5-8be6-bda117953b9d)

But it doesn't fair so well with JavaScript or TypeScript:

![Screenshot from 2023-07-09 23-23-20](https://github.com/minad/corfu/assets/1493530/a04d0ba3-e5fb-43cb-b098-39ad6c27cb54)

I know the language server has this information available since it works in completions in VSCode.  Curious why this information wouldn't be showing?

**Comment by minad** [comment]
I don't know. Maybe ask on some lsp-mode support channel?
