### ISSUE TITLE
Corfu completion window hangs with cider completion

### ISSUE THREAD

**Issue by TheKostins** [minad/corfu#348]
Steps to reproduce:
1. Install emacs with `brew install emacs-plus@28 --with-imagemagick --with-native-comp`
2. Use my configuration: https://github.com/TheKostins/dotemacs
3. Launch cider with babashka project `M-x cider-jack-in-clj`
4. Start typing in repl buffer `(require '[babaska.http-client :as http])`
5. See the window hang (the only option to make window disappear is to press C-g)

**Comment by minad** [comment]
Did you search the Corfu issue tracker for prior Cider-related issues and possible workarounds? Please report this problem on the Cider issue tracker, since the issue should be fixed there. Thanks!
