### ISSUE TITLE
How to disable arrow keys for corfu

### ISSUE THREAD

**Issue by ckruse** [minad/corfu#349]
Hi there,

how can I disable the arrow keys for corfu? I tried using this:

```
(use-package corfu
  :init (global-corfu-mode)
  :bind
  (:map corfu-map
        ([down] . nil)
        ([up] . nil)))
```

But up/down still cycles to the suggestions. I want up/down to move the mark, regardless if there is a corfu childframe open or not.

Is this possible?

Best regards,
 CK

**Comment by minad** [comment]
You can unbind the remappings too:

~~~ elisp
(define-key corfu-map [up] nil)
(define-key corfu-map [down] nil)
(define-key corfu-map [remap previous-line] nil)
(define-key corfu-map [remap next-line] nil)
~~~

**Comment by ckruse** [comment]
That works, thank you very much for your help! :-)
