### ISSUE TITLE
Completion list is incomplete on first try

### ISSUE THREAD

**Issue by pushqrdx** [minad/corfu#353]
### LSP Clients

Eglot, Emacs LSP, LSPCE

### Server

Clangd

### Current Behavior

When I type `std::` the completion list that appears is missing some items that should be there

![image](https://github.com/minad/corfu/assets/25884937/e0633ba8-aa92-426b-9b56-974c76f4a9b4)

Note the missing `std::format`

As a workaround, if I backspace _(without manually quitting the completion list)_ to the colon and start typing again, the new list correctly contains the items expected.

![image](https://github.com/minad/corfu/assets/25884937/733a6977-ce62-41c1-9545-142053d20bbf)

### Expected Behavior

Completion list should be populated correctly after the `::` trigger.

---

I have been trying to figure out why this happens for the past two days with no avail, I have read in [the wiki](https://github.com/minad/corfu/wiki#continuously-update-the-candidates) that it might be a caching issue, but this appears to only affect Eglot, so I tried with other LSP clients such as LSPCE and Emacs LSP, all of them exhibited the same behavior. This doesn't happen with `clangd` in other editors namely Sublime Text, Visual Studio Code, nor does it happen with Company, so I suspect the issue is Corfu specific.

**Comment by minad** [comment]
The lsp capfs don't update the completion table properly given more input after their initial invocation. See the documentation in the Corfu wiki regarding cape-capf-buster/cape-wrap-buster, which overrides this behavior.

**Comment by pushqrdx** [comment]
@minad so this happens with all emacs lsp clients, not only eglot? If so, why doesn't it happen with Company mode as well? Does company employ a similar cache invalidation to the one described in the wiki?

**Comment by minad** [comment]
Company uses a different calling convention to call Capfs. Basically it calls the Capf on every keypress, then calls the completion table and then throws the completion table away. In contrast, Corfu calls the Capf and retains the completion table for the duration of the completion session. This behavior can be created with cape-capf-buster.

**Comment by pushqrdx** [comment]
@minad What is strange is that I'd expect that to happen maybe in the middle of a completion where cache might interfere, but after `::` token, the server should respond with all candidates, so I am not sure what explain the fact that if I backspace to the colon and start typing again, the new list contains all the expected items. What I am trying to say is that both times the completion is supposedly triggered right after the `::` so the initial and new lists should be identical from the server, unless I am missing something.

**Comment by minad** [comment]
You are right. The backspacing confuses me as well. If you figure out the reason for that, please let me know. Another issue could be that the Capf in question doesn't handle interrupts gracefully. You can use cape-wrap-noninterruptible as a guard, but note that this will affect the responsiveness.
