### ISSUE TITLE
Child frame may flash downwards

### ISSUE THREAD

**Issue by HardGraphite** [minad/corfu#357]
Hi,

I find that the corfu child frame will "flash" downwards in a specific situation. I don't know how to accurately describe this, so I recorded a GIF. Note that the flashing duration is very short, so the GIF is recorded at 60 FPS and played in slow motion.

![child_frame_flashing_downwards](https://github.com/minad/corfu/assets/64914256/51c7f617-7f41-43a2-854d-a40fe1293898)

It only happens when the cursor is close to the bottom of the main frame (in which case **the corfu's child frame appears above the current line**). From the GIF, it can be seen that when typing, as the number of candidates decreases, **the child frame needs to resize**, and then it will **bounce downward** and then immediately return to the normal position.

I'm now using Emacs 29.1 on X11. I tried using `emacs -Q` and only loading corfu, but the problem still exists. Do you have any idea what is going wrong?

**Edit:** I found these codes. I don't know if they are related to this problem. It says "XXX HACK: Child frame popup behavior improved on Emacs 29. It seems we may not need the Emacs 27/28 hacks anymore.". I replaced `(< emacs-major-version 29)` with `t` to enable the hack for Emacs 29, but the problem still exists.

https://github.com/minad/corfu/blob/0de9193ae5c35abc209209caeddc82de55cf87df/corfu.el#L481-L499

**Comment by minad** [comment]
Yes. I don't see the problem as pronounced on my system, but flashing may occur when the frame is moved. The flash is caused by the Emacs display system, X or some other unfortunate interaction. Nothing we can fix in Corfu. Which X toolkit do you use? I use 29.1 with the Lucid toolkit on X11.

**Comment by minad** [comment]
I just tried Corfu with the hack code you mentioned above on Emacs 29. The hack makes the matter worse or even leads to the flicker in the first place. Could it be that you use an old version of Corfu compiled on Emacs 28, even after switching to Emacs 29? You can try recompiling all the packages via the command `package-recompile-all` (or delete your elpa and eln-cache directory).

**Comment by HardGraphite** [comment]
> Which X toolkit do you use? I use 29.1 with the Lucid toolkit on X11. 

I'm not using Lucid.

> Could it be that you still use an old version of Corfu compiled on Emacs 28, even after you switched to Emacs 29? 

I'm sure that the byte code file is generated by Emacs 29.1.



The code to resize and move a child frame without hack is:

```emacs-lisp
(set-frame-size frame width height t)
(unless (equal (frame-position frame) (cons x y))
  (set-frame-position frame x y))
```

Which resize first, and then move. But the GIF shows that, the child frame is somehow moved first and then resized.

```
+---------------+
| 1. ...        |
| 2. ...        |     
| 3. ...        |      ==>       +---------------+       ==>    +---------------+
| 4. ...        |                | 1. ...        |              | 1. ...        |
+---------------+                | 2. ...        |              +---------------+  
=== CURRENT LINE ===             | 3. ...        |===           === CURRENT LINE ===
                                 | 4. ...        |
                                 +---------------+ 
```

Besides, I don't understand why the two steps are displayed separately even if the code is wrapped with `(let ((inhibit-redisplay t)) ...)`.

**Comment by HardGraphite** [comment]
Yes, I can understand that. Anyway, thank you for your work!

**Comment by minad** [comment]
If you manage to create a minimal recipe (as reproducible as possible, including the rest of your setup) it may make sense to debug the Emacs child frame code and possibly optimize it.

**Comment by HardGraphite** [comment]
I've reported bug#65183.

**Comment by minad** [comment]
I don't see the issue with your `test-child-frame` function. This looks like a problem of your window manager, which also relates to what Eli wrote in https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-08/msg00675.html. I am not familiar with the X protocol so I am not sure if Emacs could do anything better here, like communicating to the window manager that the position and size should be changed at once. It seems as if Emacs is communicating the size and position change in two steps which may cause the flicker here.

**Comment by minad** [comment]
For reference, the upstream bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=65183
