### ISSUE TITLE
popupinfo messages are distracting

### ISSUE THREAD

**Issue by nehrbash** [minad/corfu#359]
I was playing around with `(corfu-popupinfo-delay 0)`  and found this [messages](https://github.com/minad/corfu/blob/416d7360e7a18ef8a7697e63a6fe75a437f4b145/extensions/corfu-popupinfo.el#L359)  distracting. I would greatly appreciate a variable to suppress messages or just outright remove this one.

**Comment by minad** [comment]
Popupinfo with a very short delay won't work well for performance reasons. The message is needed if the popup is triggered manually since otherwise you won't get feedback in this case at all.
