### ISSUE TITLE
Double return in eshell completion after tab to select the first occurence

### ISSUE THREAD

**Issue by arael** [minad/corfu#362]
Perhaps this is just a configuration problem, but I have an issue with eshell and corfu. I have corfu menu popping out when completing paths in eshell. The problem is that the when I need the first occurence I have to press return two times, the first time to select the completion and the second time to execute the command.

For example:

1. cd Dow >> press tab
2. cd Downloads >> the occurrence is completed and the corfu presents the popup
3. Return >> for accepting the proposed completion
4. Return >> for executing cd Downloads

This double Return is not very ergonomic, I would like to be able to execute the command when I press Return. Space should be enough for the cases where I have other parts of the command to complete and Ctrl-n Ctrl-p is enough for allowing me to add more completions.

Is this possible in corfu?

Thank you very much!

**Comment by minad** [comment]
See https://github.com/minad/corfu#completing-in-the-eshell-or-shell and https://github.com/minad/corfu#tab-only-completion.
