### ISSUE TITLE
Feature request/help: `corfu-info-documentation` will call a dictionary on `cape-dict` candidates

### ISSUE THREAD

**Issue by danielfleischer** [minad/corfu#368]
Hi! I would like to use the useful `corfu-info-documentation` function on `cape-dict` candidates to call the builtin `dictionary-search`. As the author of both packages, can you provide some directions to implement this?

**Comment by minad** [comment]
See #333. But I don't think we should add this here, since `cape-dict` can return words from arbitrary word lists. Also accessing a dictionary server is a bit costly for this purpose.
