### ISSUE TITLE
Corfu completion list have different result compared to M-x completion-at-point

### ISSUE THREAD

**Issue by syha6821** [minad/corfu#369]
This is when I just typed `strin`.

<img width="951" alt="Screenshot 2023-09-19 at 7 12 10 PM" src="https://github.com/minad/corfu/assets/83122197/73064bd8-6fc3-4928-8b48-7d65625ffb01">

This is when I typed `strin` and did `M-x completion-at-point` ( It completed strin to string )

<img width="795" alt="Screenshot 2023-09-19 at 7 12 57 PM" src="https://github.com/minad/corfu/assets/83122197/e5f74531-9ff8-4733-8a22-6e0d0b1a0171">

and this is my corfu configuration.

```
(use-package corfu
  :after (eglot)
  :hook (eglot-managed-mode . corfu-mode)
  :custom
  (corfu-cycle t)
  (corfu-auto t)
  (corfu-auto-prefix 1)
  (corfu-auto-delay 0.0))

```

Why Can't I see `string` in completion list without `M-x completion-at-point`?
I think it is related to corfu because without corfu I can see string in result of `M-x completion-at-point` and I use `Clangd`(c++ language server) and when I used `clangd` in vscode It works fine.

I don't know what causes this problem
So I added completion related settings in my `init.el`.
```
(fido-vertical-mode t)
(setq icomplete-compute-delay 0)

(setq completion-styles '(flex))
(define-key icomplete-minibuffer-map (kbd "TAB") 'icomplete-force-complete)

```

**Comment by minad** [comment]
See https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-clients
