### ISSUE TITLE
emacs-mac flickering (with solution)

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#37]
Very cool idea to make a child-frame popup with the default completion framework.  Works pretty well.  I encountered pretty substantial in-place frame flickering on emacs-mac v27.2, which I tracked down to it setting the `background-color` child-frame parameter every time the highlighted item is changed (e.g. with the arrow key).  

I solved this by moving the face setting expressions in `corfu--make-frame` _inside_ the `unless` which decides whether to make a new child frame at all, which seemed reasonable to me.  This eliminated all flicker and left things looking otherwise just as they had.   I.e., in `corfu--make-frame`:

```elisp
     (unless (and (frame-live-p corfu--frame)
                 (eq (frame-parent corfu--frame) (window-frame)))
      (when corfu--frame (delete-frame corfu--frame))
      (setq corfu--frame (make-frame
                          `((parent-frame . ,(window-frame))
                            (line-spacing . ,line-spacing)
                            ;; Set `internal-border-width' for Emacs 27
                            (internal-border-width
                             . ,(alist-get 'child-frame-border-width corfu--frame-parameters))
                            ,@corfu--frame-parameters)))
      (set-face-background
       (if (facep 'child-frame-border) 'child-frame-border 'internal-border)
       (face-attribute 'corfu-border :background) corfu--frame)
      (set-frame-parameter
       corfu--frame 'background-color
       (face-attribute 'corfu-background :background)))
```

As it eliminates the constant resetting of the face background, this completely solves the "flicker on arrow key" issue.  Not sure if it would interfere with anything else.

**Comment by minad** [comment]
Thanks.

This interferes with theme reloading. Therefore it is outside the frame initialization block. But tbh this sounds like an Emacs bug. Why does Emacs flicker if I change the face to *the same face*. The proper fix may be to check the face attribute first and set it only if it is different. Please try that. If this solves the problem too, we can add this. But the check must be outside the frame initialization code.

**Comment by jdtsmith** [comment]
I agree that setting to the same background color should be a no-op.  I think you are saying the issue is that you can change e.g. the `'corfu-background` face by loading a new theme (or directly altering the face), _after_ the frame is already in existence.   

Since that's such a rare case you could provide a function like `corfu-invalidate-frames` that removes all the existing child frames, and either asks the user to run this by hand upon theme load or via advice on `enable-theme`, or other theme-custom hook, or even in an `add-variable-watcher`.  

But this also works fine for me to avoid flicker (outside the `unless (and (frame-live-p`):

```elisp
    (let* ((border-face (if (facep 'child-frame-border) 'child-frame-border 'internal-border))
	   (frame-bg (frame-parameter corfu--frame 'background-color))
	   (border-bg (face-attribute border-face :background corfu--frame))
	   (corfu-bg (face-attribute 'corfu-background :background))
	   (corfu-border-bg (face-attribute 'corfu-border :background)))
      (unless (equal frame-bg corfu-bg)
	(set-frame-parameter corfu--frame 'background-color corfu-bg))
      (unless (equal border-bg corfu-bg)
	(set-face-background border-face corfu-border-bg corfu--frame)))
```

**Comment by minad** [comment]
There is another bug btw, with these checks the frame border does not get reloaded immediately after a theme change.

**Comment by jdtsmith** [comment]
Thanks for implementing!
