### ISSUE TITLE
Incorrect rendering in popup

### ISSUE THREAD

**Issue by stvpea** [minad/corfu#384]
As shown in the sequence of images below, I have encountered incorrect rendering of the popup. The behaviour is triggered by typing "dir" and then deleting "r", then "i". Re-typing and then deleting again will repeatably cycle through the states shown in the images.

Similar behaviour is seen with various completion candidates and major modes. 

I have not experienced this with emacs 28 but I am seeing it on emacs 29.1.90 (built from the emacs-29 branch). 

I am running emacs on WSL 1 (via VcXsrv). I suspect that this is a result of my environment; however, it is strange that it never occurred with emacs 28 but I have seen this with various builds of emacs 29.

This also occurs when running emacs -q and then evaluating code shown in the 4th image.

![bug_1](https://github.com/minad/corfu/assets/9432284/7b823f63-3ab2-4f23-9918-f66e2ec0cfea)
![bug_2](https://github.com/minad/corfu/assets/9432284/fe457d7f-d5ba-4b1e-b386-8ac8ce92dacc)
![bug_3](https://github.com/minad/corfu/assets/9432284/4af714d8-9de9-402e-badf-51d57417704a)

![bug_4](https://github.com/minad/corfu/assets/9432284/792ce544-4691-4055-9a75-1be201d17f69)

**Comment by minad** [comment]
Hi, thanks for the report. It is a while that I had observed child frame rendering issues on Linux/X11 (Emacs 27, 28, 29). As you suspect, this is likely related to your specific setup. We cannot do much about such display engine issues here.

**Comment by minad** [comment]
Hmm, it could be that child frames on Emacs 29 on your platform did not improve. I had added some artificial redisplays to work around rendering issues. You could try to enable these, see https://github.com/minad/corfu/blob/457042d486e7542b9a6a832e47e6833d217ffd47/corfu.el#L479-L481.

**Comment by stvpea** [comment]
Thanks for your quick response! I am away from the system until Monday, I will report back my findings.

**Comment by stvpea** [comment]
I have applied the fix by changing `(< emacs-major-version 29)` to "30". I then byte recompiled the files (and deleted the .eln from the cache) and it didn't seem to have any effect.

I then put some `(message "rd")` in the code to ensure that I was actually running the suggested fix (which I was).

I've attached the following image as it seems to clearly show the behaviour: the candidates are all there!

![bug_5](https://github.com/minad/corfu/assets/9432284/ad715961-e786-4641-92fd-ab38ff165862)

**Comment by minad** [comment]
Thanks for checking. Unfortunately such display issues cannot be fixed in Corfu, but should be fixed in Emacs itself. The problem is likely caused by your special X server (VcXsrv). The bug could even be there.

**Comment by stvpea** [comment]
> The problem is likely caused by your special X server (VcXsrv). The bug could even be there.

Yes, I thought it may be the case.

Thanks for your time looking at this (and a great piece of software!). I use corfu everywhere else, this machine will just have to live without it.
