### ISSUE TITLE
Error when typing part of a command

### ISSUE THREAD

**Issue by hankertrix** [minad/corfu#403]
![image](https://github.com/minad/corfu/assets/91734413/5349df96-fcb8-46c6-bfd8-3af42fa4cc83)

This happens when trying to type part of a command. It started happening after the commits on 23rd December.

**Comment by abougouffa** [comment]
@hankertrix I was about to open an issue related to this.

This behavior has been introduced after 9cebcfedca0ab165fcfc8a56acc2d2513a02b9e3. As a workaround, I'm using the commit before 8b5dbebea284a8b5b06bbd5dd20c3ce82c13cb1a, and it is working ok for me.

**Comment by minad** [comment]
Thanks for the report. Unfortunately I cannot reproduce this issue, so it may be caused by some other package, for example by evil-collection. Please create a minimal recipe based on emacs -Q.

**Comment by abougouffa** [comment]
Thank you for the quick response @minad

In my case, it was `evil-collection` who caused the problem.

@hankertrix: for info, this fixed the issue for me:

```elisp
;; Adapt `evil-collection-corfu' to the new `corfu--setup' signature (see github.com/minad/corfu/issues/403)
(with-eval-after-load 'evil-collection-corfu
  (advice-remove 'corfu--setup #'evil-normalize-keymaps)
  (advice-add 'corfu--setup :after (lambda (&rest _) (evil-normalize-keymaps))))
```

**Comment by hankertrix** [comment]
Thank you so much @abougouffa for the pull request to evil-collection and for the code to fix the issue!
