### ISSUE TITLE
persistent "no match" with corfu-auto

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#42]
With corfu-auto on, using orderless, I get a persistent "No match" popup often in the midst of typing, which doesn't clear itself.  The reason this occurs is if I type a part of a command that _does_ match something (according to orderless), and pause just long enough, now I'm in an uncommited completion, so that any more stuff I type on the entire line (including spaces) just leaves the flag up.  I never notice this process beginning, I only see "no match" boxes left behind.  For example in the following, as soon as corfu sees "wi" it begins a completion, which quickly gets expanded to contain no matches, throwing up the no match warning, which persists until I hit a Ret or C-g!  

![image](https://user-images.githubusercontent.com/93749/126560975-d21803a4-4f38-470b-a0c6-e2c280eec8ac.png)

I can turn on `corfu-quit-no-match`, but then any time I accidentally "over-specify" a search term, or if I'm adding on a regex which will _eventually_ match, the search abruptly ends.  So I like no-match during an actual completion search, but not when cruising along typing.  

I can't think of a great solution for this, other than figuring out a way to be stricter about when no-match can be shown.  Multiple "no match" events in a row is probably a good sign that the user is moving on and doesn't intend to find a match.  However regexps complicate that, since you may be composing a detailed regex that doesn't match until it is completed.   

Perhaps timing could help: throwing no-match within a fraction of a second of the original completion beginning is a sure sign that it wasn't wanted after all.   E.g. `(setq corfu-quit-no-match 0.5)` would say, quit if you get to no-match with 0.5s of the completion beginning.  Then you can just type right past such undesired matches and they'll usually disappear for you.

**Comment by minad** [comment]
I gave the timing idea a quick try and it does not seem to work that well. You may want to try instead increasing the `corfu-auto-delay`. 

Generally I think that `corfu-quit-no-match` and `corfu-auto` are incompatible. Maybe even `corfu-quit-at-boundary` should be enabled together with `corfu-auto`. 

Another idea is to terminate completion if you continue to type for *n* characters after the "No match" appeared. However this will probably be unsatisfactory too since the "No match" popup still appears and you have to type it away.

**Comment by jdtsmith** [comment]
Did you push a branch? I was thinking of trying this myself.  I'm pretty certain that almost all my "false positives" would be stamped out by putting a timer on auto-complete start, and just auto-exiting on "no match" until that timer elapses.  I did increase the delay some which helps.  Maybe even 1s would be fine.

**Comment by jdtsmith** [comment]
> Another idea is to terminate completion if you continue to type for _n_ characters after the "No match" appeared. However this will probably be unsatisfactory too since the "No match" popup still appears and you have to type it away.

And if you have an n+1 character regexp to enter, you'll be truly out of luck...  that's why I think timing is a better possibility. I could also switch the orderless field character to & or something.  But man that's painful.

**Comment by jdtsmith** [comment]
I gave it a go in [this branch](https://github.com/jdtsmith/corfu/tree/nomatch-quit-timer).  A setting of `corfu-quit-no-match 1.5` works very well for me, in my testing so far eliminating all the undesired "No match" trailers, and not really interfering with times I _want_ to refine the match.  I might even go 2s.  It's just an intermediate position between t or nil for this setting: before 2s: _quit on no match_, after 2s: _don't quit_.

**Comment by minad** [comment]
In my tests it felt a bit non-deterministic. Furthermore I rarely see an undesired popup when typing fast enough due to the debouncing. But you are probably right that this setting is reasonable compromise between nil and t. Do you have the FSF assignment for potential PRs btw?

**Comment by jdtsmith** [comment]
>  Do you have the FSF assignment for potential PRs btw? (EDIT: I assume yes, since your idlwave package is assigned to the FSF.)

Yes, I still do (despite IDLWAVE being on ice).  For me it works especially well when the "lookup space" is small (e.g. asking iPython for completions); I get to no match within 2s pretty much all the time if I'm just typing past it all.  Do you use orderless with space allowed?  That's the key difference (also a key feature so hard to give up).

**Comment by minad** [comment]
> I get to no match within 2s pretty much all the time if I'm just typing past it all. Do you use orderless with space allowed? That's the key difference (also a key feature so hard to give up).

Yes, for me the issue is rather that the "No match" may go away to quickly. But in this case I could just set the delay to a smaller value or disable it altogether.

I merged the patch here: https://github.com/minad/corfu/commit/497111211ed74d80de46c873fed06c1fbed9f997

**Comment by jdtsmith** [comment]
Great, thanks. We could also add a test of "did the user ever select any candidate?", if so, revert to `quit-no-match nil` independent of the time elapsed. Not sure if that would help you on your "undesired auto-quits".   I often start looking, then give up and enter more refinement (which works perfectly now with the "revert to refining on space").  

I also don't think any auto-quit non-`nil` setting makes sense unless auto is enabled; could be worth a mention in the docs.

**Comment by minad** [comment]
> We could also add a test of "did the user ever select any candidate?", if so, revert to quit-no-match nil independent of the time elapsed.

Good idea, added here https://github.com/minad/corfu/commit/de16e8499309965f146a72809114b06287c08a78.

> I also don't think any auto-quit non-nil setting makes sense unless auto is enabled; could be worth a mention in the docs.

A float is interpreted as nil for non-auto mode.
