### ISSUE TITLE
Show full list of candidates with Chinese lines

### ISSUE THREAD

**Issue by dwrz** [minad/corfu#420]
If the candidates are Chinese text, corfu doesn't seem to display all the candidates.

https://github.com/minad/corfu/assets/21134999/ab2d7306-df76-476a-99aa-1f6ae0e4beb7

**Comment by minad** [comment]
Hi! I suspect that this a font problem, see similar issues #148, #329 and #360. Can you make sure that your font has a consistent size? Maybe you use two different fonts which differ in size?
