### ISSUE TITLE
`C-n` in corfu-mode-map has low priority than `eshell-mode-map`

### ISSUE THREAD

**Issue by condy0919** [minad/corfu#44]
It can be reproduced by the following snippet.

``` elisp
(require 'corfu)
(require 'esh-mode)
(define-key eshell-mode-map (kbd "C-n") 'eshell-next-input)
```
In the following video, enable `corfu-mode` in eshell-mode.  `ls --` then `TAB` will complete, <kbd>C-n</kbd> should be `corfu-next` but it invokes `eshell-next-input` which is bound in `eshell-mode-map`. 

Since corfu-map is in `minor-mode-overriding-map-alist`, it should have high priority than major mode keymap.

https://user-images.githubusercontent.com/4024656/126713937-98931cb7-2837-4900-880c-21b8d69a7914.mp4

Test on Emacs 28.

**Comment by minad** [comment]
The problem is that you bind `C-n`, which will then take precedence over the `corfu-map`. The `corfu-map` uses remapping. If you use the following the problem will be solved:

~~~ elisp
(define-key eshell-mode-map [remap next-line] 'eshell-next-input)
~~~

**Comment by condy0919** [comment]
Thanks for the fast reply! it's resolved.
