### ISSUE TITLE
Corfu doesn't show the popup again, when I backspace

### ISSUE THREAD

**Issue by printfdebugging** [minad/corfu#449]
So in neovim, when I insert a space after a word, the nvim-cmp popup goes away, and when I press backspace to put the cursor next to the word, the popup shows up again, as if I was typing the word. I don't get corfu popup back like that. 

I would like it to quit when a space is inserted, and resume(sortof) when the space is removed.

**Comment by printfdebugging** [comment]
Also the popup should quit if (in evil mode) I exit the insert mode

**Comment by minad** [comment]
> So in neovim, when I insert a space after a word, the nvim-cmp popup goes away, and when I press backspace to put the cursor next to the word, the popup shows up again, as if I was typing the word. I don't get corfu popup back like that.

That's not a bad idea. I've added backward-delete-char to corfu-auto-commands to make this work by default. Let's see if the users like this, then we can keep it as default.

> Also the popup should quit if (in evil mode) I exit the insert mode

This is an Evil integration issue and as such out of scope here. Please take a look at evil-collection.

**Comment by printfdebugging** [comment]
I thought you were referring to some old commit of yours. :) thanks for the help

**Comment by printfdebugging** [comment]
Hi, I am not able to get these changes via package-install.... How long will it take to get the melpa version updated?

**Comment by nsemrau** [comment]
Additionally, compatability with smartparens-mode by adding `sp-backward-char-delete` to the `defcustom` would be great, please.

**Comment by minad** [comment]
@nsemrau That's out of scope, since smartparens is not a builtin Emacs package and I cannot maintain a command list for arbitrarily many packages here. But you can easily add this in your configuration. It is a defcustom after all. ;)

**Comment by nsemrau** [comment]
Oh, that policy makes sense, of course. Sorry for the noise, I was not aware of it.

Funnily enough, I came to the thought while changing my own defcustom, thinking that a broader array of people would be helpful in beta testing this feature.

Let me take this opportunity to say a huge Thank You! for Corfu and especially all your minibuffer-related packages, all of whom I use daily. :slightly_smiling_face:
