### ISSUE TITLE
spelling completion?

### ISSUE THREAD

**Issue by titaniumbones** [minad/corfu#46]
I'm trying to switch from company but, as I never really understood company very well, I keep running into features I hadn't realized I rely on. One is english-language word completion; or maybe actually it is just dabbrev-based completion, I'm not entirely certain. I am not really sure how I initially got this working (!!), but i use to get a completion pop-up buffer with word suggestions as I typed. Any idea what I need to do in corfu to get it back?

thanks!

**Comment by minad** [comment]
You can use dabbrev itself by C-M-/ or M-/, see the README.

If you want to auto-complete dabbrev, you can try to use a dabbrev capf backend, but this is work in progress and not really in the scope of Corfu, which concentrates on the UIs and not on the backends. See https://github.com/minad/corfu/issues/9#issuecomment-886006507 for a prototype backend. 

I close this issue in favor of #9. Feel free to comment there. It could also be that you rely on some alternative company backend. Please check if you have some company backends configured. Company configures a dabbrev backend by default.

**Comment by titaniumbones** [comment]
thanks @minad . I'll follow along in #9
