### ISSUE TITLE
Suggested orderless configuration differs between corfu and vertico repositories

### ISSUE THREAD

**Issue by doolio** [minad/corfu#47]
In the corfu README you suggest the following setting for the orderless package:

```
(setq completion-category-overrides '((file (styles . (partial-completion)))))
```

But in the vertico README you suggest the following:

```
(setq completion-category-overrides '((file (styles partial-completion))))
```

I think the form in the vertico README is correct as I use the customise interface to set this setting and the value has this form.

(Aside: I love the names you come up with your packages!)

**Comment by minad** [comment]
> (Aside: I love the names you come up with your packages!)

Thanks!

> I think the form in the vertico README is correct as I use the customise interface to set this setting and the value has this form.

This is just the same value, you can check it like this:

~~~ elisp
(equal '((file (styles . (partial-completion))))
       '((file (styles partial-completion))))
~~~

See also https://www.gnu.org/software/emacs/manual/html_node/elisp/Dotted-Pair-Notation.html.

I could align this, but there is also no point really. Call it a small inconsistency to find for the attentive reader ;)

**Comment by doolio** [comment]
> Call it a small inconsistency to find for the attentive reader ;)

Consider him found ;). Thanks for the quick response and the link. I'll eventually understand elisp.
