### ISSUE TITLE
corfu-auto: undo after corfu-complete deletes too much

### ISSUE THREAD

**Issue by daanturo** [minad/corfu#495]
After using `corfu-complete`, if we use `undo`, it may also delete text inserted before completing.

Reproduce from `emacs -Q`:

1. Install corfu
2. Minimal config:
```lisp
(progn
  (global-corfu-mode)
  (setq corfu-auto t))
```
3. Open an empty elisp file
4. Type `(def`|
5. Wait for the popup to show up, press `TAB` to complete `defun`
6. Undo

Observed: the whole `(defun` is deleted, leaving the buffer blank.

Expected: text comebacks to be `(def`.

**Comment by minad** [comment]
Thanks for the report. I am afraid that this is a wontfix. Originally Corfu inserted undo boundaries which would resolve this. Unfortunately the boundary led to other undesired side effects, in particular with auto completion.

**Comment by daanturo** [comment]
> Thanks for the report. I am afraid that this is a wontfix. Originally Corfu inserted undo boundaries which would resolve this. Unfortunately the boundary led to other undesired side effects, in particular with auto completion. Please search the commit history and the issue tracker.

Thank you, looks like #309 is the case? If I want to workaround this, let's say I write a wrapper around `corfu-complete`:

```elisp
(defun my-corfu-complete* ()
  (interactive)
  (undo-boundary) ;
  (corfu-complete))
(keymap-set corfu-map "TAB" #'my-corfu-complete*)  
```

The `undo-boundary` call here isn't effective, `undo` still deletes more than expected. Do I have to advise `corfu--setup`? But that would bring corfu back to the state before #309's fix.

Is there a recommended workaround? I hope it's mentioned in the README or wiki.

**Comment by minad** [comment]
I don't have a workaround readily available. If you figure something out, I'd appreciate if you update the wiki. We could also reconsider and trying to pull a fix. But my position right now is that it is reasonable to keep out of the undo machinery to avoid unexpected interactions. Less is more in some snese.

**Comment by daanturo** [comment]
By inspecting `buffer-undo-list` before and after `corfu-complete`, I came up with a workaround:


```lisp
(defun my-corfu-complete* ()
  (interactive)
  (let* (
         ;; make this element unique
         (boundary-marker (make-symbol "ignore (corfu undo)"))
         (marker-elem (list #'apply boundary-marker)))
    (defalias boundary-marker #'ignore)
    (undo-boundary)
    (push marker-elem buffer-undo-list)
    ;; `buffer-undo-list': ((apply symbol-above) nil ...old-history)
    (corfu-complete)
    ;; I don't know why undo boundaries (nil) elements are lost
    ;; `buffer-undo-list': (...new-history (apply symbol-above) ...old-history)
    ;;                                                         ^
    ;;                                                     no nil here
    (let* ((idx (-elem-index marker-elem buffer-undo-list)))
      ;; proceed to replace the placeholder element above with `undo-boundary'
      (setf (nth idx buffer-undo-list) nil))
    ;; `buffer-undo-list': (...new-history nil ...old-history)
    ))
```

It can be adapted into `corfu-complete`'s advice. Does this look OK to put on the wiki? Cause I think it touches a pretty low-level. I don't have much experience meddling with `buffer-undo-list` yet so any other side-effects are still unknown.
