### ISSUE TITLE
Completion-styles with prefix filtering

### ISSUE THREAD

**Issue by minad** [minad/corfu#5]
I think the lsp server must be called with a prefix; this requires the completion table to be called with a prefix. Maybe orderless could use the first word as prefix. I think there has some previous discussion on the orderless tracker. See also https://github.com/minad/consult/pull/175#issuecomment-821303555.

**Comment by minad** [comment]
See https://github.com/minad/consult/pull/175#issuecomment-821795539:

------

Okay, maybe there is something wrong with which string is used for the filtering. Does this also happen with Company? Both Corfu and Company use `completion-all-completions` to retrieve the completions. 

> Corfu shows all the 3 candidates.

In particular this is should not happen.

> If the completion prefix is foo and the candidates are afoo, fooa and bar (the latter being a fuzzy match, e.g. it's a bibitem whose authors contain bar), then the UI shows only afoo and fooa. It would probably remove fooa as well if I wasn't using orderless.

So this is a big problem with completion styles. I wonder how Company handles this problem, it should be affected as much as Corfu by the filtering. We probably need something to distinguish backend-filter-string and completion-sty-filter-string. You are using my Consult async commands, `consult-ripgrep` etc? I mean something like this, `#grep-regexp#completion-sty-filter`. The backend handles only the first part, the frontend handles the second part. In the context of LSP you wrote that there is not even the notion of a filter string passed to the backend, so one would actually only have `trigger-prefix#filter-string`, and `trigger-prefix#` is then ignored by the completion styles. The user has to enter this like `trigger-prefix TAB #filter-string`.

**Comment by minad** [comment]
~~~ elisp
(defun test-capf ()
  (list
   (save-excursion
     (backward-word)
     (point))
   (point)
   (lambda (str pred action)
     (message "CALLED %S %S" str action)
     (setq str "") ;; Ignore prefix!
     (complete-with-action action '("a1" "a2" "a3" "a4"
                                    "b1" "b2" "b3" "b4"
                                    "c1" "c2" "c3" "c4")
                           str pred))))

(add-to-list 'completion-at-point-functions #'test-capf)

(defun experiment-all-completions (str table pred _point)
  (let* ((parts (split-string str nil t))
         (completion-regexp-list (mapcar #'regexp-quote (cdr parts)))
         (completions (all-completions (or (car parts) "") table pred)))
    (and completions (nconc completions 0))))

(defun experiment-try-completion (str table pred _point)
  ;; (let* ((parts (split-string str nil t))
  ;;        (completion-regexp-list (mapcar #'regexp-quote (cdr parts)))
  ;;        (completion (try-completion (or (car parts) "") table pred)))
  ;;   (if (stringp completion)
  ;;       (cons completion (length completion))
  ;;     completion)))
  (car (split-string str nil t))
  )

(add-to-list 'completion-styles-alist
             '(experiment
               experiment-try-completion experiment-all-completions
               "Experimental completion."))

(setq completion-styles '(experiment))
~~~

**Comment by astoff** [comment]
Okay, I don't have anything coherent to say here but a bunch of random thoughts:

1. The Orderless issue you raised doesn't seem relevant to any LSP+Eglot discussion. Eglot overrides the completion style to `flex` (https://github.com/joaotavora/eglot/issues/575).
2. I like your analogy between `consult-grep`'s #-trick and the way things could work with LSP. But keep in mind that LSP is very vscode-centric, and in particular is mostly geared for "autocomplete". Different from the good old grep, calling the server for completions after each keypress is an expected usage. In fact, I'm pretty sure this is how things work in the Digestif+Eglot+Company combination from my GIF: Company never filters candidates, only the language server does.
3. I had forgotten about that `filterText` business, otherwise I wouldn't have let you discover it by yourself :-). But here is a summary of the situation:
        a. The LSP protocol provides no explicit way for the server to communicate that the completion list has been prefiltered on the server side. 
        b. Conversely, it's not really specified whether a server is allowed to send irrelevant candidates in the completion list, but the LSP people say this is allowed.
        c. To make things worse, the LSP completion response does not specify what the completion prefix is, so the editor-side filtering is necesssarily going to be somewhat heuristic!
Anyway, this at least explains that, in order to allow for the BibTeX fuzzy completions, the hacky `filterText` I use in Digestif is required for the time being.
4. Now returning to point 2, if we accept that, with LSP, the text before calling `completion-at-point` is like the `grep-regexp` and anything you type after that is like the `completion-sty-filter`, then wouldn't we conclude that the current behavior of Corfu (showing all candidates returned by the backend, without further filtering) is kind of correct? As a consequence, isn't https://github.com/oantolin/orderless/issues/49 exactly what you _don't_ want?
5. Suppose I type `\ci C-M-i t`. You seem to advocate that typing the `t` should use the completion style to filter, rather than calling the completion backend / language server. Is this correct? What if I type `\ci C-M-i DEL a`. Should I see the candidate `\cap`, which obviously isn't included in the candidate list returned after `\ci C-M-i`?
6. Note also the the LSP protocol allows the server to specify that a completion response is "incomplete", meaning that the completion for `\cit` may not be a subset of the completions for `\ci` (e.g., you may have 500 commands between `\ci` and `\cite` in alphabetic order, so the server returns only the first 50 to save bandwidth).

**Comment by minad** [comment]
1. Okay, I see. I am not using eglot right now, but I consider switching to it because I like its reduced scope. But using flex style does not sound good to me. I guess it is easy to fix this via some configuration or advices. As such the argument I made stays relevant and one could use eglot in combination with orderless assuming that orderless supports this prefix filtering (oantolin/orderless#49).
2. Sure, it is okay to call the server every time. It is still nice to filter afterwards via orderless as I proposed "prefix ord er less", where "prefix" is the trigger prefix and the rest is used for narrowing to the candidate. I think this would be better than the status quo and better to what company does. In the case of grep this feature is much more important though since we can avoid restarting the whole expensive search.
3. Thanks for the background info.
4. Corfu is correct as of now. But Corfu does filter using the completion style which happens in `completion-all-completions`. In order to allow for this "trigger prefix/filter" separation we need (oantolin/orderless#49). I don't understand why you think otherwise?
5. No I advocate something slightly different and very orderless specific. If you type `\ci TAB t`, then the server will still see `\cit`. But if you press `\ci TAB SPC t`, then orderless will send the first token `\cit` to the backend (prefix filtering) and use its own filtering only on the remaining tokens, in this case `t`.
6. That's okay. If you type `\ci TAB` you get only 50, maybe some irrelevant. And if you continue to type `t` (`\ci TAB t`) you will get the updated list from the server with Corfu doing live updates. As long as you don't type `SPC` the orderless filtering should be disabled as by my orderless proposal.

**Comment by minad** [comment]
Regarding 1.  one can disable the eglot override using `eglot-stay-out-of` and then I can adjust the completion style on the frontend by setting `corfu-completion-styles`.

**Comment by astoff** [comment]
Re 1: Then `(add-to-list 'eglot-stay-out-of 'completion-styles)` to your config (this is supposed to work for every "automagic" setting Eglot does for you). That said, Orderless and Eglot seem not play well together. If I type `\c C-M-i itt`, then after the second `t` the candidate list should become empty, but instead it goes back to the very first candidate list that I see after typing just `\c C-M-i`.

Re 5: Gotcha. That sounds pretty reasonable indeed.

**Comment by minad** [comment]
Okay, there is one problem though. Eglot sends the current document position and some trigger character. I think this explains why it does not work well with Orderless. When I wrote the above I assumed that it sends the beginning position and the string passed to the completion function. So I think there is no way to make this work with Orderless and oantolin/orderless#49 should be closed.

~~~ elisp
(defun eglot--CompletionParams ()
  (append
   (eglot--TextDocumentPositionParams)
   `(:context
     ,(if-let (trigger (and (characterp eglot--last-inserted-char)
                            (cl-find eglot--last-inserted-char
                                     (eglot--server-capable :completionProvider
                                                            :triggerCharacters)
                                     :key (lambda (str) (aref str 0))
                                     :test #'char-equal)))
          `(:triggerKind 2 :triggerCharacter ,trigger) `(:triggerKind 1)))))
~~~

One possibility to still make this work somehow is to perform the filtering in a two step process: 1. acquire the candidates using a non-filtering completion style (like calling `all-completions` with the empty string). After the user entered the first space, do not call the backend again. Filter the cached candidates list using a second completion style, e.g. orderless and pass it only the input after the first space.

**Comment by minad** [comment]
I wrote this small hack, a caching completion style. It should solve the problem we discussed.

~~~ elisp
;;; -*- lexical-binding: t -*-

(defun caching-completion-style-setup ()
  (let* ((candidates)
         (styles completion-styles)
         (all (lambda (str table pred point)
                (save-match-data
                  (if (and candidates (string-match "\\`\\([^ ]*\\) +\\(.*\\)" str))
                      (let ((completion-styles styles))
                        (message "CACHED ALL: input=%S filter=%S" (match-string 1 str) (match-string 2 str))
                        (completion-all-completions (match-string 2 str)
                                                    candidates pred
                                                    (max 0 (- point (match-beginning 2)))))
                    (let* ((completion-regexp-list)
                           (completions (all-completions str table pred)))
                      (message "BACKEND ALL: input=%S candidates=%S" str (length completions))
                      (setq candidates (mapcar #'substring completions))
                      (and completions (nconc completions 0)))))))
         (try (lambda (str table pred point)
                (save-match-data
                  (if (and candidates (string-match "\\`\\([^ ]*\\)\\(.*\\)" str))
                      (let ((completion-styles styles))
                        (message "CACHED TRY: input=%S filter=%S" (match-string 1 str) (match-string 2 str))
                        (completion-try-completion (match-string 2 str)
                                                   candidates pred
                                                   (max 0 (- point (match-beginning 2)))))
                    (let* ((completion-regexp-list)
                           (completion (try-completion str table pred)))
                      (message "BACKEND TRY: input=%S completion=%S" str completion)
                      (if (stringp completion)
                          (cons completion (length completion))
                        completion)))))))
    (setq-local completion-styles-alist (cons (list 'caching-style try all "") completion-styles-alist))
    (setq-local completion-styles '(caching-style))
    (setq-local completion-category-defaults nil)
    (setq-local completion-category-overrides nil)))

(defun caching-completion-style-kill ()
  (if completion-in-region-mode
      (add-hook 'completion-in-region-mode-hook #'caching-completion-style-kill 'local)
    (kill-local-variable 'completion-styles-alist)
    (kill-local-variable 'completion-styles)
    (kill-local-variable 'completion-category-defaults)
    (kill-local-variable 'completion-category-overrides)
    (remove-hook 'completion-in-region-mode-hook #'caching-completion-style-kill 'local)))

(defun caching-completion-style-advice (orig &rest args)
  (unwind-protect
      (progn
        (caching-completion-style-setup)
        (apply orig args))
    (caching-completion-style-kill)))

(advice-add #'corfu--completion-in-region :around #'caching-completion-style-advice)
~~~

**Comment by jdtsmith** [comment]
> Re 1: Then add `(add-to-list 'eglot-stay-out-of 'completion-styles)` to your config (this is supposed to work for every "automagic" setting Eglot does for you). That said, Orderless and Eglot seem not play well together. If I type `\c C-M-i itt`, then after the second `t` the candidate list should become empty, but instead it goes back to the very first candidate list – the one I see after typing just `\c C-M-i`.

BTW, this behavior was due to eglot not using `all-completions` and thus not correctly handling `completion-regexp-list`, which orderless employs for all its filtering magic.  Fixed in [this commit](https://github.com/joaotavora/eglot/commit/9b63f21e75dc8222b5dfc4006ce8559bb73532cb).
