### ISSUE TITLE
On every child-frame creation (on every `completion-at-point` call) there is a mem leak, emacs pgtk, wayland

### ISSUE THREAD

**Issue by Seme4eg** [minad/corfu#500]
This issue is not directly related to corfu, but maybe i can get some help with temporary fix here. 

Setup:
- doom emacs, up to date version (but even `emacs -Q` has same problem, so its definitely not doom's fault)
- emacs-wayland (arch repos) - 29.4-2
- Hyprland as compositor

Here are reference issues:
https://github.com/hyprwm/Hyprland/issues/7038
https://github.com/hyprwm/Hyprland/issues/7461

Even on latest version of gtk3 (arch repos) on every emacs frame resize its still 25-40mb leak, that goes into hyprland and being displayed as ram taken by hyprland in resource monitors. Caused me to hit oom many times already.

Disabling corfu-popupinfo-mode helped by just a bit, since less childframes is being created, but still on every completion invocation some memory is leaked. Any way to workaround that?

**Comment by minad** [comment]
This issue can probably not be fixed in Corfu. It must be fixed in Emacs or Gtk. Please report the problem on the relevant issue trackers (bug-gnu-emacs or the Gtk tracker).
