### ISSUE TITLE
`corfu-popupinfo-mode` change existing `*Help*` buffer

### ISSUE THREAD

**Issue by cyrus-and** [minad/corfu#514]
Not sure if expected, but it's quite annoying IMHO. So basically if you already have an existing `*Help*` buffer around, every time the popup information pops up, the `*Help*` buffer is changed to display the candidate.

Reproduce easily with `emacs -Q`, then in the `*scratch*` buffer evaluate (assuming you already have Corfu installed):

```lisp
(package-initialize)

(custom-set-variables
 '(corfu-auto t)
 '(global-corfu-mode t)
 '(corfu-popupinfo-mode t))
```

Then:

1. Spawn a `*Help*` buffer with, e.g., `C-h v emacs-version RET` (thus creating a split window);

2. In the original window (`*scratch*`) trigger Corfu, e.g., start typing `cor`, wait for the popup information to appear;

3. The `*Help*` buffer is changed accordingly, if you move to other candidates with `<down>`, the content keeps changing.

**Comment by minad** [comment]
See https://github.com/minad/corfu/discussions/504

**Comment by cyrus-and** [comment]
Thanks but #504 does not provide any solution or workaround to the issue.

**Comment by minad** [comment]
Yes, it is a backend issue (wontfix).

**Comment by cyrus-and** [comment]
Yes, but that's what's happening by default, I'm not saying you have to fix something in this repo. It's just that blaming the backend for something that happens by default, without providing some kind of solution/guidance/explanation doesn't really help with the adoption of this package.
