### ISSUE TITLE
`corfu-popupinfo--frame` needs the `BUFFER` argument

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#522]
16d5aef removed the `BUFFER` arg from `corfu--make-frame`, but it is needed by `popupinfo`.

**Comment by minad** [comment]
Are you sure? I've also modified `corfu-popupinfo` accordingly, see https://github.com/minad/corfu/commit/16d5aef839477ac54790fb797c1e85dfdbbd313f.
