### ISSUE TITLE
How to get corfu working in TTY child frames in Emacs 31?

### ISSUE THREAD

**Issue by DanZanzibar** [minad/corfu#536]
I understand that Emacs 31 now supports child frames in TTY and should work with Corfu. I expected it to just start working, but it seems I must need to configure something to make this take effect. I can't find any information on this.

Any help?

**Comment by DanZanzibar** [comment]
My apologies - I realised the issue was in connecting over ssh to a server and running emacs in terminal. It DOES work immediately on a local machine.

I wonder if it is possible to work over ssh...

**Comment by minad** [comment]
See also https://github.com/minad/corfu/discussions/531 regarding child frame support on TTY.
