### ISSUE TITLE
How to set corfu-auto for certain modes

### ISSUE THREAD

**Issue by ave-63** [minad/corfu#54]
I figured out a solution to the problem as I was writing this. It seems like other people might have the same issue so I'll go ahead and post the solution, but I'm happy to delete it if this is the wrong place.

Usually, I like `corfu-auto` to be `nil`. But in `ledger-mode`, where I want to auto-complete every dang thing, I want to make it `t`. 

If I simply eval `(setq corfu-auto t)` from a ledger buffer, it doesn't change the behavior in that buffer; it seems I have to set it to `t` *before* opening the buffer, and then it gets stuck that way. Apparently the `corfu-mode` function is what sets up the behavior for the buffer, and the value of `corfu-auto` at that time is what matters.

My solution is to use `ledger-mode-hook` as follows:

    (add-hook `ledger-mode-hook (lambda ()
                                  (setq corfu-auto t)
                                  (corfu-mode)
                                  (setq corfu-auto nil)))

**Comment by minad** [comment]
It is better to `setq-local corfu-auto` in the buffer where you want this behavior.
