### ISSUE TITLE
Default *Completions* instead of corfu pops up in slime buffers

### ISSUE THREAD

**Issue by hpdeifel** [minad/corfu#58]
In slime buffers, I get the standard `*Completions*` buffer on `M-TAB`, even though `corfu-global-mode` is on and `completion-in-region-function` is set to `corfu--completion-in-region`. I'm not sure if this is a configuration issue, a slime issue or a corfu issue and would appreciate pointers on how to debug this.

**Comment by minad** [comment]
Probably `M-TAB` is not bound to `completion-at-point` in slime buffers? I still wonder why the standard `*Completions*` buffer opens, probably slime does not use `completion-in-region`. `completion-in-region` is used internally by the `completion-at-point` command.

**Comment by minad** [comment]
Closing. This is probably a binding issue and should be fixed in Slime or the user configuration.
