### ISSUE TITLE
Confusion around `corfu-bar` and `corfu-border`

### ISSUE THREAD

**Issue by protesilaos** [minad/corfu#6]
Hello Daniel! I am now preparing to add Corfu to the Modus themes, but I got confused by the behaviour of `corfu-bar` and `corfu-border`.  When `line-spacing` is set to a number, I get this:

![Screenshot from 2021-04-17 06-49-25](https://user-images.githubusercontent.com/12828033/115101005-848a0980-9f49-11eb-8b8d-0ae82034c6ae.png)

Whereas `line-spacing nil` gives me this:

![Screenshot from 2021-04-17 06-49-39](https://user-images.githubusercontent.com/12828033/115101006-85bb3680-9f49-11eb-8085-fa166662b723.png)

Can we have separate faces for those cases? I would like the border in case 2 to be less prominent, without having to compromise on the scroll bar's looks (those are not final, by the way).

**Comment by minad** [comment]
There were some issues I just fixed. I added an explanation to the docstring.

Instead of using `:foreground/:background` to encode the thin/fallback border, I could use separate faces. Would that be significantly better? I am a bit unhappy that the thin borders don't work with line-spacing. Nevertheless we already need the fallback colors for text-mode.

**Comment by protesilaos** [comment]
Thanks for the clarification!  I think the new doc strings are enough to address my confusion.  Now I see something that was not present before with `(setq line-spacing 1)`: a border to the left of the candidates (using the default faces):

![Screenshot from 2021-04-17 15-55-44](https://user-images.githubusercontent.com/12828033/115113997-b032e100-9f95-11eb-8daa-dbc6e8b22d52.png)

![Screenshot from 2021-04-17 15-55-52](https://user-images.githubusercontent.com/12828033/115113999-b1640e00-9f95-11eb-8cda-120e619d81e7.png)

That does not exist in [the screenshot I shared earlier](https://user-images.githubusercontent.com/12828033/115101005-848a0980-9f49-11eb-8b8d-0ae82034c6ae.png).

> Nevertheless we already need the fallback colors for text-mode.

By `text-mode`, do you mean the major mode? Or TUI?

**Comment by minad** [comment]
> Now I see something that was not present before with (setq line-spacing 1): a border to the left of the candidates (using the default faces):

Yes, this is intentional. What do you think about it? Maybe it is better to not apply the border color on the left and only use the background color. That would be more consistent with the thin border look.

> By text-mode, do you mean the major mode? Or TUI?

I mean the terminal ui.

Btw do you use `line-spacing/=nil`, how common is that?

**Comment by protesilaos** [comment]
> Yes, this is intentional. What do you think about it? Maybe it is better to not apply the border color on the left and only use the background color. That would be more consistent with the thin border look.

I prefer the previous design. Unless this left border could be made thinner? Though this is not a particularly strong preference. I am fine either way. Just asking for the purposes of the themes.

> I mean the terminal ui.

I see. Maybe there is a better way to specify that? I am not sure actually.

> Btw do you use line-spacing/=nil, how common is that?

I normally I use 1. For videos or larger font heights I go with 2. I am not sure how common this is: I have not seen it in a lot of places (so don't worry about my particular case).

**Comment by minad** [comment]
> I prefer the previous design. Unless this left border could be made thinner? Though this is not a particularly strong preference. I am fine either way. Just asking for the purposes of the themes.

Unfortunately there is no way to make this thinner since it is a full character. But I can change it back to the old look.

> I normally I use 1. For videos or larger font heights I go with 2. I am not sure how common this is: I have not seen it in a lot of places (so don't worry about my particular case).

Okay, but this is a single pixel. This hardly makes a difference?

Is it okay to close the issue then?

**Comment by minad** [comment]
Btw, could you please push the newest Vertico and Corfu to ELPA? I just tagged new releases.

**Comment by protesilaos** [comment]
> Is it okay to close the issue then?

Yes, that is fine. If someone complains about the left border you can deal it.

> Okay, but this is a single pixel. This hardly makes a difference?

The difference is very small, but I notice it even at small point sizes. This happens, for example, with Source Code Pro when the overlays of matching parentheses are shown. The padding between the line height and the top of the parenthesis is larger than the bottom part. That one extra pixel makes it look more balanced.

**Comment by protesilaos** [comment]
> Btw, could you please push the newest Vertico and Corfu to ELPA? I just tagged new releases.

Yes, sure! I will do it in ~30 minutes though, because I was about to go for a brisk walk :)

**Comment by minad** [comment]
> Yes, that is fine. If someone complains about the left border you can deal it.

Oh, I changed it back now. The left border is not colorized separately.

> Yes, sure! I will do it in ~30 minutes though, because I was about to go for a brisk walk :)

A walk is a good idea. I was about to do the same. Thank you for your help!

**Comment by protesilaos** [comment]
Just updated both packages on elpa.git.

Also added corfu to the themes. Please let me know if the style is okay, otherwise we can tweak it. Will now finalise the release of the themes' version 1.3.0.

**Comment by minad** [comment]
Great, thank you! I like the colors you used for Corfu. There is one small issue though - the current line background takes precedence over the border/scrollbar. This is problematic when the scrollbar indicator extends across only two lines.

![screenshot4](https://user-images.githubusercontent.com/50754/115118559-13c40b00-9fa4-11eb-85ee-59f71da34dc4.png)

**Comment by protesilaos** [comment]
Thanks, I just fixed it!  Apparently setting a foreground would cause the issue.

**Comment by minad** [comment]
Thanks!
