### ISSUE TITLE
Corfu frame gets used by display-buffer

### ISSUE THREAD

**Issue by meedstrom** [minad/corfu#60]
Ok, I'm on emacs pgtk under the Sway WM, so Emacs is running as a pure Wayland app.  That or my config might be the culprit, so stop me if you can't reproduce the issue with these steps:

- 1. Make display-buffer use frames instead of windows:

``` emacs-lisp
(setq display-buffer-base-action '((display-buffer-use-some-frame
                                    display-buffer-pop-up-frame)
                                   ((reusable-frames . t))))
(setq display-buffer-alist nil)
```

If you have shackle-mode, popper-mode or some such, may have to disable them.

- 2. Trigger a corfu overlay by trying to complete something
- 3. Do something else
- 4. Trigger display-buffer by calling a command like `describe-function` or `magit-status`.

Expected result: The Help buffer from `describe-function` is displayed in a full-sized frame.

Actual result: The Help buffer from `describe-function` is displayed in a tiny corfu overlay frame.

**Comment by minad** [comment]
I can reproduce this. It seems to be an Emacs bug that `reusable-frames=t` also considers child frames. You may want to report this. Note that you can specify a `frame-predicate` which excludes child frames.

**Comment by meedstrom** [comment]
Wonderful.  Thanks for this package!  I never got around to learning how to use company, but using corfu was immediately obvious.

Before I report it upstream, do you really consider it a bug that it uses child frames?  I'm not sure what they're meant for, but it sounds feasible to have a setup of mostly child frames.
