### ISSUE TITLE
pcomplete capf fails to return valid data

### ISSUE THREAD

**Issue by meedstrom** [minad/corfu#61]
Reproduction in `emacs -Q` (Emacs 28):
- `M-x load-file RET ~/.emacs.d/straight/repos/corfu.el RET`
- `M-x corfu-global-mode RET`
- `M-x eshell RET`
- type a `"`(quote character)
- press TAB

Results in "Warning: pcomplete-completions-at-point failed to return valid completion data!" and a tab character is inserted.

I think this is two separate bugs, because it shouldn't insert a tab character when a capf fails, although a warning or message instead would be good.  It's thanks to the spurious tab characters that I tracked down this bug.

**Comment by minad** [comment]
This is not a Corfu bug, since you can reproduce it without `corfu-mode`. You may want to report this upstream.

**Comment by meedstrom** [comment]
Bug reported upstream.  https://debbugs.gnu.org/cgi/bugreport.cgi?bug=50675

**Comment by minad** [comment]
You can use the advices from my [Cape package](/minad/cape) to sanitize `pcomplete-completions-at-point`. See https://github.com/minad/corfu#completing-with-corfu-in-the-eshell-or-shell for details.

**Comment by meedstrom** [comment]
Heh, you saw me updating the debbug? Thanks a lot!

**Comment by minad** [comment]
Yes :)
