### ISSUE TITLE
corfu-auto-prefix uses entire symbol in some backends

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#62]
Certain completion systems do not know at the time of the CAPF call what portion of the buffer the completion backend will choose to complete.  Presently, corfu examines the `beg` and `end` returned from the CAPF to determine if enough characters are in place for auto-complete to commence (`(guard (>= (- end beg) corfu-auto-prefix)))`).

This is problematic for example when editing near the beginning of a symbol (e.g. `= [X]symbol`, where `[X]` is position of point).  In that case the completion system may mark the entire `symbol`, and, if asked, dutifully returns basically every symbol as completion.  

I'd suggest triggering corfu auto-completion only when the text between `beg` and `(point)` exceeds `corfu-auto-prefix` in length.  This will prevent this type of unintentional auto-complete, and seems to be the behavior of company as well.

**Comment by minad** [comment]
Makes sense. I've observed this behavior you described too.

**Comment by minad** [comment]
Probably additional sanity checking should be done, beg<=point<=end. And point-beg>=min.
