### ISSUE TITLE
(other-window 1 t) selects corfu frame

### ISSUE THREAD

**Issue by meedstrom** [minad/corfu#63]
Here is a neat little command:

``` emacs-lisp
(defun my-copy-region-or-rest-of-line-to-other-window ()
  (interactive)
  (save-mark-and-excursion
    (if (region-active-p)
        (kill-ring-save (region-beginning) (region-end))
      (kill-ring-save (point) (line-end-position)))
    (other-window 1 t)
    (yank)))
```

Using it from a single-window frame results in

    Buffer is read-only: #<buffer  *corfu*>

I can fix this by changing  `(other-window 1 t)` to `(other-window 1 'visible)`, but I believe the first form should not do anything surprising either.  What if there's an iconified/hidden frame and someone actually relies on auto-raise-mode to select it?  Maybe a niche issue, but reporting so it's documented.

If the programmer was calling `next-window-any-frame`, you'd leave it up to them to work around issues of picking inappropriate windows, but `other-window` already tries to be smart and skip minibuffers.  Perhaps it's `other-window` that should be patched to include cases like corfu?

This could probably be ameliorated if you move the corfu frame to the bottom of `frame-list`.  Is that possible?

**Comment by minad** [comment]
Thanks for the report. I hope the issue is fixed now. The child frame API is horrible. There are a bazillon parameters which must be set in order to prevent the child frame from misbehaving.

**Comment by meedstrom** [comment]
Confirmed fixed.
