### ISSUE TITLE
Show "documentation" (signatures) from TAGS file

### ISSUE THREAD

**Issue by rudolf-adamkovic** [minad/corfu#68]
I noticed that `README` mentions documentation, but I cannot figure out how to make it show something. Say, I have a `TAGS` file as follows:

```
r5rs.scm,2051
(define (make-list COUNT)         "list with COUNT elements") make-list 1,0
(define (make-list COUNT OBJECT)  "list with COUNT copies of OBJECT") make-list 2,62
...
```

(I removed the invisible separator characters from the example as GitHub does not like them.)

So, I load the file with `visit-tags-table` and `corfu` shows `make-list`, etc. Wonderful job! But then, could `corfu` display the signature, such as `(define (make-list COUNT) ...`, as documentation?

**Comment by salutis** [comment]
All right, after hours (and hours) of figuring out how everything works, I have a working solution for the Scheme programming language that I decided to learn! It correctly parses multi-line definitions and also includes the documentation comment above them, if present.

```emacs-lisp
(defun my-scheme-tag-doc (tag)
  "Return signature and surrounding documention for Scheme TAG."
  (when (or tags-file-name tags-table-list)
    (let ((inhibit-message t))          ; Inhibit "Mark set" messages.
      (save-mark-and-excursion
        (when-let ((source-buffer
                    (ignore-errors
                      (visit-tags-table-buffer)
                      (find-tag-in-order tag
                                         find-tag-search-function
                                         etags-xref-find-definitions-tag-order
                                         nil
                                         "exactly matching"
                                         t))))
          (with-current-buffer source-buffer
            (let ((end (save-excursion
                         (down-list)
                         (forward-sexp)   ; Skip "define" keyword.
                         (forward-sexp)   ; Skip name and arguments.
                         (line-end-position))))
              (when (> (line-number-at-pos) 1)
                (previous-line)
                (while (and (my-looking-at-comment)
                            (> (line-number-at-pos) 1))
                  (previous-line))
                (next-line))
              (let ((beginning (line-beginning-position)))
                (font-lock-ensure beginning end) ;; TODO Neccessary?
                (buffer-substring beginning end)))))))))
```

I plugged it in as follows:

```emacs-lisp
(defun my-scheme-tags-completion (completion)
  (when completion
    (append completion `(:company-docsig ,#'my-scheme-tag-doc))))
```

```emacs-lisp
(advice-add 'tags-completion-at-point-function :filter-return
            #'my-scheme-tags-completion)
```

Further, I plugged the same function to Eldoc and it works. Yay!

@minad Thank you again for your guidance!

P.S. The first "soft-selected" candidate (#45) does not have any documentation. Bummer!

**Comment by minad** [comment]
> P.S. The first "soft-selected" candidate (#45) does not have any documentation. Bummer!

It works as expected on my end. As soon as I select the first candidate, the documentation is shown. The point is that I only want to show the docstring as soon as you are explicitly scrolling through the candidate list in order to reduce the noise during typing.

**Comment by salutis** [comment]
@minad 

>  The point is that I only want to show the docstring as soon as you are explicitly scrolling through the candidate list in order to reduce the noise during typing.

Interesting. Dang, this soft-selection business in Corfu keeps breaking my brain. 😓
