### ISSUE TITLE
Auto trigger chars

### ISSUE THREAD

**Issue by minad** [minad/corfu#70]
Mentioned by @jdtsmith in https://github.com/minad/corfu/issues/41#issuecomment-961478689. I am not sure how this is implemented in Company, but maybe via the `:company-prefix-length` capf metadata extension? We could add support to `corfu--auto-complete`:

https://github.com/minad/corfu/blob/6647b7fc3dfdbc4b23740b3aea6c284576a82723/corfu.el#L938

Needs investigation. PR welcome!

**Comment by minad** [comment]
@dgutov The auto triggering feature of Company is something I wanted to ask you about. Corfu requires a certain number of prefix characters to be entered (3 by default), before the popup is opened. However @jdtsmith observed that Company opens the popup immediately after pressing "." for OOP languages like Python, which makes sense. Is there some special list of hard coded auto trigger characters in Company? I took a look at the Company source and the company-capf source but I didn't find anything.

**Comment by dgutov** [comment]
Any info about auto trigger characters resides in individual backends.

See the description of the possible return values of `prefix` in `company-backends` docstring. When it's a cons, it can override the "number of characters required".

`company-capf` uses the `:company-prefix-length` to pass that info. The whole thing feels a little hackish, but not too much.

**Comment by minad** [comment]
> company-capf uses the :company-prefix-length to pass that info. The whole thing feels a little hackish, but not too much.

Thanks! I suspected that `company-prefix-length` is the relevant function to implement this behavior. I think it is an acceptable design like this. Directly after invoking the capf, Corfu checks if the prefix length is sufficient. Currently Corfu checks against the value of the `corfu-auto-prefix` customizable variable. It could as well check against the value returned by `company-prefix-length`.

**Comment by minad** [comment]
But @dgutov is this documented somewhere? Which values are allowed?

https://github.com/company-mode/company-mode/commit/4cd4c3a7bf5ab0eb62e27be0d4c9fce7011c6d43

**Comment by dgutov** [comment]
A number or `t`. The documentation is in `company-backends`.

**Comment by minad** [comment]
Thank you! Why not only allow `t`? The backend knows the length of the prefix, so it would actually be sufficient to have an option `company-force-completion` which can just be nil or t.

**Comment by dgutov** [comment]
The backend doesn't know the value of `company-minimum-prefix-length`.

> Or alternatively only allow integers, since t=0 :)

`t` corresponds to the number "infinity".

**Comment by minad** [comment]
Ah I misunderstood this completely.

**Comment by jdtsmith** [comment]
This is working very well, thanks!
