### ISSUE TITLE
font size changes not respected

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#74]
On my system (Mac Emacs 27.2), `frame-char-width` (and height) are not updated when the buffer font is changed.  This leads to artifacts in the corfu popup frame size, which doesn't know that characters sizes have changed:

![image](https://user-images.githubusercontent.com/93749/141023614-aa95bfe9-f98e-4f13-ad81-c2be35a7240e.png)

A simple solution is to switch to `default-font-width` and `default-font-height`.  If there is a concern that the user may specify a different font size in the popup than in the buffer (not sure if that's even possible), `window-font-width` is also a possibility.  I have verified that `default-font-width|height` fixes this issue.

**Comment by minad** [comment]
No this doesn't work when the text size is adjusted as far as I know. Text size adjustment is more likely than font change?

**Comment by jdtsmith** [comment]
If I shift left-click, select "Change Buffer Font Size..." up pops my system's font selector.  I pick a new size in the same font (each _buffer_ is allowed to have its own font).  I select a much larger font, like 18 pt.  `frame-char-width` is unchanged at 7.  `default-font-width` does get updated (in this case to 11).  

For my `mlscroll` modeline scrollbar, since you can have a different font (inc. size) in the modeline and buffer, I had to use:

```elisp
(if (display-multi-font-p)
		  (aref (font-info (face-font 'mode-line)) 11)
		(default-font-width))
```

I notice that `svg-lib` uses `window-font-height` without any arguments (and also plucks slot 11 from font-info):

```elisp
         (txt-char-width  (window-font-width))
         (txt-char-height (window-font-height))
         (font-info       (font-info (format "%s-%d" font-family font-size)))
         (ascent          (aref font-info 8))
         (tag-char-width  (aref font-info 11))
```

**Comment by minad** [comment]
What about C-x C-+?

**Comment by jdtsmith** [comment]
Before:

- `(frame-char-width) = 7 (default-font-width) = 7` 

After `C-x C-+`:

- `(frame-char-width) = 7 (default-font-width) = 8` 

and another:

- `(frame-char-width) = 7 (default-font-width) = 10` 

This is:

`GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2021-03-27`

**Comment by jdtsmith** [comment]
Perhaps this difference is because there are still some 7-pixel-wide fonts on the frame (namely in the mode-line), even as the buffer font gets much larger.

**Comment by minad** [comment]
I don't see this issue with 0.14 on my system. I use default-font-width and default-line-height in corfu--popup-show.

**Comment by jdtsmith** [comment]
Oh great, I see, you changed that.  

Prefix offset working btw.  Stock is looking better and better...
