### ISSUE TITLE
Show "eldoc" documentation immediately after the user confirms a candidate with "corfu"

### ISSUE THREAD

**Issue by salutis** [minad/corfu#80]
**Reproduction steps:**

1. start typing some code
2. see some completion candidates
3. type `C-n` couple times to select some candidate
4. confirm the candidate with `RET`

**Expected:** 

See the `eldoc` documentation for the selected candidate in the echo area.

**Actual:**

The documentation shows after typing `SPC` or moving the cursor.

**Note:**

I write Scheme, and every time I select a candidate with `corfu`, I must go back and forward (`C-b` and `C-f`) to see the `eldoc` help in the echo area.

**Comment by minad** [comment]
Did you try corfu-echo-documentation=0? Please investigate first the available customization options before opening issues.

**Comment by minad** [comment]
It seems that the solution is this:

~~~ elisp
(eldoc-add-command-completions "corfu-")
~~~

See also https://github.com/company-mode/company-mode/issues/797, where I've got the solution.

**Comment by salutis** [comment]
@minad 

```
(eldoc-add-command #'corfu-insert)
```

OMG, this works! I would have never figured this one out. Thank you so much!
