### ISSUE TITLE
completion-at-point does not appear to work in SLIME

### ISSUE THREAD

**Issue by polaris64** [minad/corfu#84]
I'm using SLIME with the following configuration: -

```elisp
(use-package slime
  :config (setq inferior-lisp-program "sbcl")
  (slime-setup '(slime-fancy)))
```

When Corfu is enabled (either locally or globally), `completion-at-point` does nothing. For example, take the following, where `|` represents the point: -

```
(ro|)
```

Calling `completion-at-point` does nothing, no Corfu pop-up is displayed. When Corfu is disabled the following completions are displayed using the regular Emacs completion system: -

```
Click on a completion to select it.
In this buffer, type RET to select the completion near point.

Possible completions are:
room 	rotatef
round 	row-major-aref
```

I've tried to debug `completion-at-point` and I've noticed that after it evaluates the following form, `res` is `nil` when Corfu is active. However when Corfu is inactive, `res` is `(slime--completion-at-point . slime-complete-symbol*)`: -

```elisp
[...]
  (let ((res (run-hook-wrapped 'completion-at-point-functions
                               #'completion--capf-wrapper 'all)))
[...]
```

`completion-at-point-functions` is `(slime--completion-at-point t)` in both cases.

I'm using Emacs 29.0.50 (built from commit 90ac2db9ed9b2bab6f40508f6302996d5b8a725d).

**Comment by polaris64** [comment]
After some further testing, it looks like `corfu--capf-wrapper-advice` doesn't support `res` being a function in the same way as `completion--capf-wrapper` does. When the advice is active (i.e. when Corfu is active) then `res` being a function is not a case that is handled, therefore `nil` is returned.

It looks like SLIME's `slime-c-p-c` contrib package defines `slime-complete-symbol*`. If I remove this from `slime-completion-at-point-functions` (so that it is just `(slime-filename-completion slime-simple-completion-at-point)`) then Corfu completions work properly.

This is a workaround, but I think Corfu should perhaps support cases where `res` is a function too?

**Comment by minad** [comment]
Hi, thank you for the report! I was not aware that there are still packages in the wild using the outdated capf calling convention. You are right that Corfu bails out early if the capf result does not have the proper format. Basically Corfu currently only handles functions adhering to `completion--capf-safe-funs`. This completion format has been introduced over ten years ago.

~~~ elisp
(defvar completion--capf-safe-funs nil
  "List of well-behaved functions found on `completion-at-point-functions'.
These are functions which return proper completion data rather than
a completion function or god knows what else.")
~~~

Note that Company also bails out on "improper" completion data, see https://github.com/company-mode/company-mode/blob/eb9be0bff7c323c720198dcd539ee05fa2485cd3/company-capf.el#L71.

Can you please check which change would be necessary to make Corfu work properly with Slime, for example adjusting the corfu capf wrapper override accordingly? Furthermore it would be great if you can ask the Slime developers if they are interested in upgrading the completion function to adhere to the modern format. Is there something which prevents the upgrade?

**Comment by polaris64** [comment]
Hi @minad, thanks for your quick reply!

I don't know a huge amount about the capf framework, so I didn't realise this was an outdated convention. It seems like the best approach would be, as you suggested, to see if it could be changed by SLIME so I will see if I can raise an issue with them about it.

In the meantime, I'll be happy to see if I can figure out what changes would be necessary to support this. I'll let you know when I have something to share.

Thanks again!

**Comment by minad** [comment]
I forgot to answer to the last part of your comment:

> If I remove this from slime-completion-at-point-functions (so that it is just (slime-filename-completion slime-simple-completion-at-point)) then Corfu completions work properly. This is a workaround, but I think Corfu should perhaps support cases where res is a function too?

I wonder what the advantage of the `slime-complete-symbol*` function is? Maybe the slime-c-p-c contrib package should be updated?

**Comment by minad** [comment]
> I don't know a huge amount about the capf framework, so I didn't realise this was an outdated convention.

To be precise - I am not sure if the calling convention where the capf returns a function is indeed formally deprecated. It does not seem like it, since Emacs is quite conservative in preserving existing behavior. On the other hand Company not supporting it and the docstring of `completion--capf-safe-funs` clearly indicate that a function return value is not considered a "proper format" and that packages should ideally make the move.

**Comment by polaris64** [comment]
It looks like [the `slime-company` package](https://github.com/anwyn/slime-company) is required in order to allow completions to work with Company, so it does appear that workarounds are needed. I've just raised on issue on the SLIME repo (linked above) too.

**Comment by polaris64** [comment]
Reading through that package's code, [specifically here](https://github.com/anwyn/slime-company/blob/f20ecc4104d4c35052696e7e760109fb02060e72/slime-company.el#L188), it looks like this package allows only "simple" and "fuzzy" completions, so that indicates that they omit `slime-c-p-c` too.

The only reason that I was using `slime-c-p-c` is that it's included by default when you initialise SLIME with `slime-fancy` contributed packages, as suggested by their documentation. Without it though the completions still seem to work fine!

**Comment by polaris64** [comment]
> I wonder what the advantage of the `slime-complete-symbol*` function is? Maybe the `slime-c-p-c` contrib package should be updated?

```elisp
(defun slime-complete-symbol* ()
  "Expand abbreviations and complete the symbol at point."
  ;; NB: It is only the name part of the symbol that we actually want
  ;; to complete -- the package prefix, if given, is just context.
  (or (slime-maybe-complete-as-filename)
      (slime-expand-abbreviations-and-complete)))
```

**Comment by minad** [comment]
> It looks like the slime-company package is required in order to allow completions to work with Company, so it does appear that workarounds are needed.

Well, SLIME should work ootb with Company if it would provide a proper capf. This would make the slime-company package obsolete.

> The only reason that I was using slime-c-p-c is that it's included by default when you initialise SLIME with slime-fancy contributed packages, as suggested by their documentation. Without it though the completions still seem to work fine!

Since SLIME core works and since the offending capf belongs to a contrib package, I close the issue here. I would appreciate if you report back on how this issue develops. One could add a fix here or a ten-year-backward compatible advice to the wiki (if it is even possible), but generally I am not fond of making a move backward if an upgrade in SLIME is possible.

**Comment by polaris64** [comment]
> Since SLIME core works and since the offending capf belongs to a contrib package, I close the issue here.

I'm sorry to say that I think I spoke to soon. The "simple" completions (via `slime-simple-completion-at-point`) do indeed work, however as the name implies these are only basic completions, specifically just for Common Lisp built-ins it seems. They do not seem to include packages that have been loaded, such as Quicklisp.

I've yet to hear back from [the issue on the SLIME repository](https://github.com/slime/slime/issues/643) unfortunately.

**Comment by minad** [comment]
@polaris64 I looked at slime-complete-symbol*. It seems that the obsolete completion function works completely different. I performs the completion of the text and display of the completions itself. So there is no way we can support the old convention here. If you want slime to work with different UIs, a modern style capf is the requirement.

**Comment by polaris64** [comment]
OK, that's absolutely fine.

As a final note I tried [SLY](https://github.com/joaotavora/sly) which is a more up-to-date fork of SLIME and this seems to work perfectly with Corfu! So if anyone else needs Corfu completion support with SLIME, I'd recommend giving SLY a try instead.

**Comment by minad** [comment]
I also plan to write a company-corfu adapter, see https://github.com/minad/cape/issues/1.

**Comment by jgarte** [comment]
> OK, that's absolutely fine.
> 
> As a final note I tried [SLY](https://github.com/joaotavora/sly) which is a more up-to-date fork of SLIME and this seems to work perfectly with Corfu! So if anyone else needs Corfu completion support with SLIME, I'd recommend giving SLY a try instead.

@polaris64 Do you happen to have the corfu/sly config you used that you could share?

**Comment by polaris64** [comment]
Hi @jgarte,

I didn't do anything special to get it working with SLY, it just seemed to work OOTB.

Here are my configuration snippets though for reference: -

```elisp
(use-package corfu
  :custom
  (corfu-auto nil)             ;; Disable auto completion (complete with TAB)
  (corfu-quit-at-boundary nil) ;; Do not automatically quit at word boundary
  (corfu-quit-no-match t)      ;; Automatically quit if there is no match

  :init
  ;; Enable indentation+completion using the TAB key.
  ;; `completion-at-point' is often bound to M-TAB.
  (setq tab-always-indent 'complete)

  ;; Enable Corfu globally
  (corfu-global-mode)

  :config
  (use-package dabbrev
    ;; Swap M-/ and C-M-/
    :bind (("M-/" . dabbrev-completion)
           ("C-M-/" . dabbrev-expand)))

  ;; kind-icon: show icons next to completions
  (use-package kind-icon
    :custom
    (kind-icon-default-face 'corfu-default) ;; Compute blended background correctly
    :config
    (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter)))
```

```elisp
(use-package sly
  :commands (sly)
  :config (setq inferior-lisp-program "sbcl"))
```

**Comment by jgarte** [comment]
@polaris64 Thank you very much! It works for me now. Much appreciated!

**Comment by michael-776** [comment]
Those using SLY should note (from its README): "For consistency, SLY defaults to its own UI, sly-symbol-completion-mode, useful if you don't have or like any of those. You can turn it off."  That is, (setf sly-symbol-completion-mode nil)
