### ISSUE TITLE
error: (wrong-type-argument number-or-marker-p nil) when calling corfu-complete()

### ISSUE THREAD

**Issue by daanturo** [minad/corfu#85]
When we invoke `corfu-complete` via `M-x`, the above error will be raised

[corfu.el#L897](https://github.com/minad/corfu/blob/81453d987ebf2ef213998cba3c23545a4b41bedb/corfu.el#L897)

`completion-in-region--data` is nil.

Edit: so is `corfu-complete` not supposed to be called out of nowhere?

**Comment by minad** [comment]
`corfu-complete` is not supposed to be called when Corfu is not active. There are only three ways to invoke Corfu:

1. Invoke `completion-at-point`
2. Run a command which calls `completion-in-region` (`completion-at-point` belongs to this set of commands)
3. Set `corfu-auto=t` and wait until Corfu pops up

**Comment by minad** [comment]
Duplicate #24
