### ISSUE TITLE
Command to reset candidate selection or quit with initial input retained

### ISSUE THREAD

**Issue by iquiw** [minad/corfu#86]
I am using Corfu for a while and quite like it as well as your other packages, Vertico, Consult, Marginalia.
Thank you so much!

I found the following command useful when canceling candidate selection or clearing inputted filtering text.
Appreciated if Corfu would have this or similar command(s).
Thanks in advance.

```emacs-lisp
(defun corfu-reset-or-quit ()
  "Reset candidate selection or quit Corfu completion with the initial input retained."
  (interactive)
  (if (>= corfu--index 0)
      (corfu--goto -1)
    (corfu-quit)
    (unless (= corfu--start-point (point))
      (delete-region corfu--start-point (point)))))
```

with the following diff.

```diff
@@ -244,6 +244,9 @@ return a string, possibly an icon."
 (defvar-local corfu--echo-timer nil
   "Echo area message timer.")
 
+(defvar-local corfu--start-point nil
+  "Point where completion started.")
+
 (defvar corfu--frame nil
   "Popup frame.")
 
@@ -941,6 +944,7 @@ A scroll bar is displayed from LO to LO+BAR."
 (defun corfu--setup ()
   "Setup Corfu completion state."
   (when completion-in-region-mode
+    (setq corfu--start-point (point))
     (setq corfu--extra completion-extra-properties)
     (setcdr (assq #'completion-in-region-mode minor-mode-overriding-map-alist) corfu-map)
     (add-hook 'pre-command-hook #'corfu--pre-command nil 'local)
```

**Comment by minad** [comment]
Thanks! This is an interesting proposal! I would like to have a `corfu-reset` command here which quits and resets the input. The idea to move to the prompt first is also not a bad idea, but maybe a better fit for a custom command or the wiki.

It would be great if Corfu interacted more smoothly with undo, so I suggest the following:

1. Add a corfu-reset command which quits and deletes the input. Furthermore the undo list is reset to the state at the beginning.
2. When inserting the candidate finally and quitting, the completion related undo steps are amalgamated such that the completion can be undone as one.

I am not sure how to implement this exactly. My experience with buffer-undo-list is limited. Is it possible to add save points to the undo list such that one can go back there. Maybe you have an idea?

**Comment by minad** [comment]
See https://www.gnu.org/software/emacs/manual/html_node/elisp/Atomic-Changes.html

**Comment by minad** [comment]
I added a `corfu-reset` command which behaves similarly as your proposed variant. I bound it to ESC. Furthermore I improved the undo handling.

**Comment by minad** [comment]
The undo behavior was more problematic than expected, I had to rework this a few times. When testing, please ensure that you use the newest version: https://github.com/minad/corfu/commit/2f0dcbb5978d757d99bb343ed5440ffeba69cee1

**Comment by iquiw** [comment]
Ah, I was not aware of undo things.
It works great! Thank you!!
