### ISSUE TITLE
M-h (corfu-show-documentation) fails if company isn't installed

### ISSUE THREAD

**Issue by antifuchs** [minad/corfu#87]
I'm trying to ditch company entirely in favor of corfu, but this one thing is keeping it away: Hitting `M-h` to show a completion item's documentation results in this backtrace in my emacs (without company loaded):

```
Debugger entered--Lisp error: (void-function company-doc-buffer)
  company-doc-buffer(nil)
  #f(compiled-function (&rest args) #<bytecode -0xb6c74c414fddab3>)(#("atomic=" 0 7 (lsp-completion-resolved t lsp-completion-item #<hash-table equal 5/5 0x1ff0c67bcd93> lsp-sort-text "04.9999.atomic" lsp-completion-start-point 3304 lsp-completion-markers (3304 #<marker (moves after insertion) at 3307 in linkerd.py>) lsp-completion-prefix "ato" match-data (0 3 0 1 1 2 2 3))))
  corfu-show-documentation()
  funcall-interactively(corfu-show-documentation)
  command-execute(corfu-show-documentation)
```

I tried merely defining [that function](https://github.com/company-mode/company-mode/blob/6abb232acde15e1a7bf402a57f7bb982edf2de7d/company.el#L2737-L2745), but doing that pops up the `* company-documentation*` buffer and moves point, and then displays the completion overlay there. So, is it required to have company loaded to use this functionality?

**Comment by minad** [comment]
This is an issue of lsp-mode, which provides an invalid implementation of the `:company-doc-buffer` metadata extension. See https://github.com/emacs-lsp/lsp-mode/issues/3225. The issue can be fixed easily in lsp-mode. Lsp-mode should provide a proper implementation of `:company-doc-buffer`, which does not rely on Company functionality.
