### ISSUE TITLE
pop-up placement is slightly off

### ISSUE THREAD

**Issue by fgeller** [minad/corfu#89]
hi! thanks once more for a promising package! happy user of vertico and orderless here :)

the pop-up sometimes appears one level lower than expected
![Screenshot from 2021-11-25 06-35-57](https://user-images.githubusercontent.com/52790/143385679-82c3e238-2d57-4f16-b31d-44b1250964a1.png)

i can reproduce it with the example above (go-mode + lsp) if i type "slowly", ie wait for completion after i type `f` (placed correctly) and then type `m`.
i'm using a recent emacs 28 build:
```
GNU Emacs 28.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-11-15
```
i set some more custom values, but these are the ones i need to reproduce it for the above example:
```emacs-lisp
(setq corfu-auto t
      corfu-auto-prefix 1)
```
just noticed that the annotations are cut off a bit, that's probably because i set
```emacs-lisp
(setq corfu-max-width 60)
```
let me know if you need some more info or other help from my side - thanks!

**Comment by minad** [comment]
Ah I think this is an Emacs 28 bug due to the flymake/flycheck overlay. posn-at-point returns a wrong result. Can you reproduce with Emacs 27? If not it should he reported upstream.

**Comment by minad** [comment]
Reported here https://debbugs.gnu.org/cgi/bugreport.cgi?bug=52097

**Comment by minad** [comment]
Fixed upstream.

**Comment by fgeller** [comment]
can finally confirm :) thanks a lot for the fast turn-around time :)
