### ISSUE TITLE
Idea: do not overwrite prompt text

### ISSUE THREAD

**Issue by jdtsmith** [minad/corfu#91]
I've been using #88 pre-selection for a while, and have some further thoughts.  First, pre-selecting candidate 1 is a good idea.  It is just far more indicative of "what will happen if I commit actively or implicitly, via auto-commit".   

But I'm finding incongruous the fact that the 1st candidate selection is now "special" in the sense that it and it alone can reveal _what you've typed at the prompt_ .  I suspect it may put off some new users.  

I've recall that at least one user was already bothered that corfu is putting anything "at the prompt", (apparently, but not actually) overwriting what they wrote.  I understand that for complete-or-type-something-new situations, like for `mkdir`, you absolutely need to be able to specify a non-candidate.  But I've struggled to find the value of overwriting prompt text with the selected candidate (_except_ candidate #1, at present).  And quite often, while arrowing down to some candidates, I wonder "what orderless search terms do I already have up there, I wish I could see them so I knew how to refine them".    Yes, I can page-up or `M-S-v`, but that takes me out of the selection flow.  

My proposal is as follow: never overwrite the prompt text, until Tab/Ret/auto-commit.   First, I recognize that this is a pretty fundamental corfu interaction, and I suspect I must be missing some pro's which are obvious to you.  Here's what I see:

Advantages as I see them to no-prompt-overwrite:

1. Candidate 1 is "no longer a special case", other than being pre-selected on initial pop-up (sometimes). 
2. It will be clearer that you can continue editing prompt/adding search terms, wherever you are. 
3. You can see your prompt searches, which can be complex (like `co !-- [a-z]$`), at all times, with no need to "return to the 1st candidate".
4. It will be clear what completing commands can "take novel input" by the ability to "select the prompt". 

What do you lose?  Disadvantages:

1. Ability to 'select the prompt' and type something novel, except when "allowed".
2. Similarity to minibuffer-based completion/selection, like Vertico.
3. No "preview", so you have to "look down" the list to see what will be filled in when you hit Tab/Ret.  

For disadvantage 1, typing something novel that matches no candidates already leads to "No match" which will disappear (or you can C-g it).  And you've already fixed this case by optionally _not_ having the 1st candidate pre-selected, when you _expect_ novel input (e.g. for mkdir).  For the 2nd, vertico is just far more likely to encounter "select something or enter something new" scenario, like buffer selection.  In-buffer completion is far more commonly "pick a completion from this list".   For the 3rd, presumably since you selected, you know quite well it's selected. 

So what else is lost?

**Comment by minad** [comment]
Note that there is already the ~corfu-preview-current~ customization. Please let me know if this is sufficient! If you find time also take a look at the other configuration options, since I added a few recently. The feeling is growing on me that there is simply no perfect uniform way to do in-buffer completion with a Corfu/Company-style popup. For this reason I added these configurations.

**Comment by jdtsmith** [comment]
Oh my goodness, not sure how I missed that option!  Thanks, for pointing it out.  It seems to do what I hoped for.  I think it will also be the more familiar thing for people new to corfu, so you might consider making it nil by default. 

Does "auto-commit" == "type-away"?  That is an advantage, but one I never take advantage of, because it requires me to remember that once a (non-implicit) candidate is selected, typing does one thing, and before selection (or with implicit selection) another.  AKA: **if I [arrow], I [Ret]**. 

For specific thing where I DO want auto-committing, I can "opt in" with `corfu-commit-predicate`, so that it almost always works for me because I have special-cased things like ",", ".", etc. to do sensible auto-commit.   I just added a check to ignore "." for auto-commit if after a space so I can use it for regexps.

**Comment by minad** [comment]
> Oh my goodness, not sure how I missed that option! Thanks, for pointing it out. It seems to do what I hoped for. 

You could just watch the repo you know. Then you also won't miss when I make backwards incompatible changes to the margin formatter. ;)

> I think it will also be the more familiar thing for people new to corfu, so you might consider making it nil by default.

No, I will keep the default like this. My general policy is to have more features activated ootb. It is easier to discover something that way, and the natural Emacs user tendency is then to look for an option to turn off the annoyance!

> Does "auto-commit" == "type-away"? That is an advantage, but one I never take advantage of, because it requires me to remember that once a (non-implicit) candidate is selected, typing does one thing, and before selection (or with implicit selection) another.

Yes. This is mostly an advantage if you use manual completion triggering and TAB through the candidates. See https://github.com/minad/corfu#tab-and-go-completion.

> For specific thing where I DO want auto-committing, I can "opt in" with corfu-commit-predicate, so that it almost always works for me because I have special-cased things like ",", ".", etc. to do sensible auto-commit.

Yes, but this makes only sense for advanced users. If you find time please add this part of your config to the wiki. It can be helpful to showcase the purpose of the commit predicate.

**Comment by jdtsmith** [comment]
> > Oh my goodness, not sure how I missed that option! Thanks, for pointing it out. It seems to do what I hoped for.
> 
> You could just watch the repo you know. Then you also won't miss when I make backwards incompatible changes to the margin formatter. ;)

Hah!  That would be a full-time job with your commit rate... :). 

> this makes only sense for advanced users.

I haven't tried tab-and-go, which does look like an interesting approach.  I almost never reach for the arrow, preferring to orderless-select my way the candidate to the top and either "." or "Ret".  But maybe I'll try it and see if I like it.   Tab is actually a bit odd with partial completion, since it brings in the first full candidate to the prompt, which may or may not match other stuff.  And Tab never commits, nor does it cycle through remaining candidates.   Since one of my auto-committers is "if 1st candidate is an exact match, SPC auto-commits" I kind of get the best of all worlds. 

Will document the auto-committer.

**Comment by minad** [comment]
> Hah! That would be a full-time job with your commit rate... :). 

There is just a flurry activity right now thanks to the ideas and problems discovered due to my cape package. I hope that the package settles at some point. But there are probably still numerous issues. You probably read what I wrote about the interruptible capfs.

**Comment by jdtsmith** [comment]
It's a compliment.  Seriously not many people put this much energy into their packages.  The Wiki is locked BTW.

Cape really will be great for people who think "I like it, but it does XXXX wrong".  Just patch it up easy.  The cognitive overhead of learning the entire baroque functionally-composed CAPF system is too much, but Cape + rich examples should lower than barrier for people.

**Comment by minad** [comment]
> It's a compliment. Seriously not many people put this much energy into their packages. The Wiki is locked BTW.

Thanks! I unlocked the wiki.

> Cape really will be great for people who think "I like it, but it does XXXX wrong". Just patch it up easy. The cognitive overhead of learning the entire baroque functionally-composed CAPF system is too much, but Cape + rich examples should lower than barrier for people.

Yes, but in the long term the out of the box experience is important. I think it is not that bad actually - I've used Corfu for a while now without all the Cape trickery. Of course I had a few of the Cape capfs in my private config, e.g., the file capf and the dabbrev capf. For most users it should just be `corfu-global-mode+cape-dabbrev+cape-file`, if they even need that. Maybe `corfu-global-mode` is sufficient.

The cape combinators are only relevant if you really want to perfect the interplay of orderless with the underlying backend for example.

**Comment by jdtsmith** [comment]
> in the long term the out of the box experience is important. 

I mean if you take that thinking too far you end up in VS Code.  But yes.  

> The cape combinators are only relevant if you really want to perfect the interplay of orderless with the underlying backend for example.

For anyone who says company has the major advantage of compositing backends... this changes that.  And honestly makes it VERY easy to tweak in simple predicates, etc.  The significance of this is not to be underestimated, and is probably more important than any one of the particular capfs provided.

**Comment by minad** [comment]
> I mean if you take that thinking too far you end up in VS Code. But yes.

Nah. I mean activating `corfu-global-mode` or `vertico-mode` should give you a decent experience. That's all.

> For anyone who says company has the major advantage of compositing backends... this changes that. And honestly makes it VERY easy to tweak in simple predicates, etc. The significance of this is not to be underestimated, and is probably more important than any one of the particular capfs provided.

I don't think the advantage of composing multiple backends is that relevant. It simply does not work well enough due to the common prefix restriction and due to how these backends compute the candidates. As far as I know you cannot combine file+capf in Company for example. Maybe this changes in the future, but in the case of `cape-super-capf` it is very difficult to generally combine completion tables.

For the end user it seems more important to have `cape-file` and `cape-dabbrev` available. See also `cape-line` which is neat. Then I like `cape-symbol` since it allows me to complete elisp symbols everywhere.

**Comment by jdtsmith** [comment]
Are you really introducing bindings for all of these!?! That's a lot of additional bindings to remember for people used to completion being "wait for something to pop up , then choose something, or dismiss".   A nice C-u Tab transient pop-up comes to mind.... especially if you could "become" it from a normal auto-complete.

**Comment by minad** [comment]
> Are you really introducing bindings for all of these!?!

Yes, I have that in my config and documented in the readme. It is of course up to the user to bind those. I bind them under a mnemonic prefix map, so I don't find that particularly difficult since this is how all Emacs keybindings are organized anyways. `C-c p f` for files, `C-c p d` for dabbrev but there is also `M-/`. I've heard that in (neo)vim similar keybindings are used for completion. There is also a main completion key, but you can also start these special completions.

> A nice C-u Tab transient pop-up comes to mind.... especially if you could "become" it from a normal auto-complete.

Far too heavy. Just press `C-c p C-h`. I don't use which-key btw, I use `embark-prefix-help-command`.
