### ISSUE TITLE
[Feature Request] Can we select item by key?

### ISSUE THREAD

**Issue by cxa** [minad/corfu#94]
I like the idea of `vertico-quick`. Will be efficient and very appreciated if you could implement. Thanks.

**Comment by minad** [comment]
I don't have plans to add such extensions currently. Maybe in the long term. At least vertico-quick and vertico-indexed would transfer here.

**Comment by Luis-Henriquez-Perez** [comment]
I'd really like this feature and would be willing to work on such an extension. What do you mean by
`At least vertico-quick and vertico-indexed would transfer here.`?

**Comment by minad** [comment]
I meant - feel free to port vertico-quick and vertico-indexed to Corfu. We can add them as extensions here. The other Vertico extensions don't make sense in the context of Corfu.
