### ISSUE TITLE
Is there a plan to provide a documentation viewer like company-quickhelp?

### ISSUE THREAD

**Issue by galeo** [minad/corfu#98]
I've already switch from company to corfu for elisp code completion. I really hope corfu can provide a documentation viewer similar to `company-quickhelp`. I see the corresponding item in the [Caveats](https://github.com/minad/corfu#caveats). I want to know if there are any technical problems to implement it or that it is already on the TODO list.

Thanks.

**Comment by minad** [comment]
Thanks for your interest! No, I don't have plans to implement a corfu-quickhelp. There are multiple reasons why I haven't done that.

* I like that Corfu is small and unobtrusive. A documentation quickhelp window does really fit that picture. In my perspective it leads to an unnecessary information overload which is not justified for in-buffer completion. Note that you can already manually open the documentation in a separate window while Corfu is open.
* I intend to keep Corfu small. If you know my Vertico package, a feature like corfu-quickhelp makes only sense as an extension or an external package.
* Corfu uses its child frame popup code, which is tied to the completion popup. Ideally this code should be refactored such that a quick help popup could also rely on it.
* I would not say that there are other big technical problems, but a few issues still come to mind. From my experience the completion child frame popup is still not 100% robust. It occasionally flickers, which is a problem of the underlying Emacs display engine. If we add another large child frame for the documentation this will get worse. Another issue is the popup placement, such that the completion popup and the completion popup don't interfere.

**Comment by galeo** [comment]
> * Note that you can already manually open the documentation in a separate window while Corfu is open.

The experience is not very good. When the document buffer was opened, the completion popup disappeared immediately. The code completion of many editors will provide a similar documentation glance, which is generally placed next to the completion popup.

> * I intend to keep Corfu small. If you know my Vertico package, a feature like corfu-quickhelp makes only sense as an extension or an external package. Note that company-quickhelp is also an external package, separate from Company itself.

It can indeed be implemented as an extension.

> * Corfu uses its child frame popup code, which is tied to the completion popup. Ideally this code should be refactored such that a quick help popup could also rely on it.

Yes, if the child frame code can be separated from the completion popup, it can be reused.

> * Another issue is the popup placement, such that the completion popup and the help popup don't interfere with each other.

The child frame of the documentation can be calculated by the location and size of the completion child frame and the size of display, which should not be particularly difficult.

Thanks.

**Comment by minad** [comment]
> The experience is not very good. When the document buffer was opened, the completion popup disappeared immediately. The code completion of many editors will provide a similar documentation glance, which is generally placed next to the completion popup.

I don't see this. For me it works and I can even scroll the other window.

> The child frame of the documentation can be calculated by the location and size of the completion child frame and the size of display, which should not be particularly difficult.

Sure nothing here is particularly difficult. If you have interest you can create a separate corgu-quickhelp package.

**Comment by galeo** [comment]
> I don't see this. For me it works and I can even scroll the help window.

It tried again. It should be caused by popwin, but the help window still can't be scrolled. It will close immediately when trying to scroll with <kbd>C-M-v</kbd>.

> Sure nothing here is particularly difficult. If you have interest you can create a separate corfu-quickhelp package.

I will have a try.

**Comment by galeo** [comment]
> > I don't see this. For me it works and I can even scroll the help window.
> 
> Tried again. It should be caused by popwin, but the help window still can't be scrolled. It will close immediately when trying to scroll with C-M-v.

It can be scrolled when comment `(corfu--restore-on-next-command)` in `corfu-show-documentation`.

**Comment by minad** [comment]
Indeed, scrolling was broken. Fixed now.

**Comment by galeo** [comment]
> Fixed now.

Confirmed. Thanks.

**Comment by galeo** [comment]
> If you have interest you can create a separate corfu-quickhelp package.

I've tried to write a package called [`corfu-doc`](https://github.com/galeo/corfu-doc). You can have a look.

**Comment by minad** [comment]
This looks great! If you want to reuse some Corfu frame code I would accept a PR which generalizes the corfu--make-frame API such that it can be reused by your package. Maybe the basic blocker is to allow different frame variables, not only corfu--frame which would have to be passed explicitly?

**Comment by galeo** [comment]
> If you want to reuse some Corfu frame code I would accept a PR which generalizes the corfu--make-frame API such that it can be reused by your package.

It would be excellent if the code could be reused. The problem is I haven't signed the GNU assignment paper. 
So can you directly refactor the code? TIA.

> Maybe the basic blocker is to allow different frame handle variables (not only corfu--frame), which would have to be passed explicitly?

Yes. The frame can be passed explicitly.

Corfu-doc still has some problems to deal with. For example, when the completion item does not exist, Corfu will display "No match", and the doc frame is not hidden. Can Corfu hide the completion frame directly in this case?  I don't know how to implement the scroll bar. The doc frame can have a scroll bar and be scrolled with shortcut keys. And custom settings, such as inner margin (`child-frame-border` or `internal-border`), document font size, etc.

**Comment by minad** [comment]
> The problem is I haven't signed the GNU assignment paper.

Would you be interested in getting the papers? I am not sure if it is a good idea if we move the packages closer code wise if there is an unclear copyright situation since one cannot move code back and forth freely then. But we can keep this refactoring in mind for the long term. It is not high priority.

> Corfu-doc still has some problems to deal with. For example, when the completion item does not exist, Corfu will display "No match", and the doc frame is not hidden.

You can detect if there are no corfu candidates (`corfu--total=0`).

> I don't know how to implement the scroll bar. 

You can use the same technique as `corfu--show-popup`. Maybe the code could also be refactored to make this more reusable.

> The doc frame can have a scroll bar and be scrolled with shortcut keys. 

This is a good idea.

> And custom settings, such as inner margin (child-frame-border or internal-border), document font size, etc.

What is the problem here? There is one issue with Corfu currently: One cannot scale the popup font size independently of the parent frame font size. This should be fixed first in Corfu.
